GooFit: /home/travis/build/GooFit/GooFit/include/goofit/PDFs/DalitzPlotHelpers.h File Reference
DalitzPlotHelpers.h File Reference
#include "goofit/PDFs/GooPdf.h"
#include "goofit/PDFs/ResonancePdf.h"
#include "goofit/PDFs/LineshapesPdf.h"
Classes
struct DecayInfo
struct DecayInfo_DP
class strided_range< Iterator >
struct strided_range< Iterator >::stride_functor
Enumerations
enum DP4Pair {
M_12 = 0, M_34, M_13, M_14,
M_23, M_24, M_12_3, M_13_2,
M_23_1, M_12_4, M_14_2, M_24_1,
M_13_4, M_14_3, M_34_1, M_23_4,
M_24_3, M_34_2
}
enum DaughterPair { PAIR_12 = 0, PAIR_13, PAIR_23 }
Functions
template<typename E >
constexpr std::underlying_type< E >::type enum_to_underlying (E e)
EXEC_TARGET bool inDalitz (const fptype &m12, const fptype &m13, const fptype &bigM, const fptype &dm1, const fptype &dm2, const fptype &dm3)
EXEC_TARGET devcomplex< fptype > getResonanceAmplitude (fptype m12, fptype m13, fptype m23, unsigned int functionIdx, unsigned int pIndex)
EXEC_TARGET void get4Vecs (fptype *Vecs, const unsigned int &constants, const fptype &m12, const fptype &m34, const fptype &cos12, const fptype &cos34, const fptype &phi)
EXEC_TARGET fptype getmass (const unsigned int &pair, fptype &d1, fptype &d2, const fptype *vecs, const fptype &m1, const fptype &m2, const fptype &m3, const fptype &m4)
Variables
const int resonanceSize = 4
Enumeration Type Documentation
DaughterPair
enum DaughterPair
Enumerator
PAIR_12
PAIR_13
PAIR_23
Definition at line 36 of file DalitzPlotHelpers.h.
DP4Pair
enum DP4Pair
Enumerator
M_12
M_34
M_13
M_14
M_23
M_24
M_12_3
M_13_2
M_23_1
M_12_4
M_14_2
M_24_1
M_13_4
M_14_3
M_34_1
M_23_4
M_24_3
M_34_2
Definition at line 35 of file DalitzPlotHelpers.h.
Function Documentation
enum_to_underlying()
template<typename E > constexpr std::underlying_type<E>::type enum_to_underlying (E e)
Definition at line 17 of file DalitzPlotHelpers.h.
References get4Vecs(), getmass(), getResonanceAmplitude(), and inDalitz().
get4Vecs()
EXEC_TARGET void get4Vecs (fptype * Vecs, const unsigned int & constants, const fptype & m12, const fptype & m34, const fptype & cos12, const fptype & cos34, const fptype & phi)
Referenced by enum_to_underlying().
getmass()
EXEC_TARGET fptype getmass (const unsigned int & pair, fptype & d1, fptype & d2, const fptype * vecs, const fptype & m1, const fptype & m2, const fptype & m3, const fptype & m4)
Referenced by enum_to_underlying().
getResonanceAmplitude()
EXEC_TARGET devcomplex<fptype> getResonanceAmplitude (fptype m12, fptype m13, fptype m23, unsigned int functionIdx, unsigned int pIndex)
Referenced by enum_to_underlying().
inDalitz()
EXEC_TARGET bool inDalitz (const fptype & m12, const fptype & m13, const fptype & bigM, const fptype & dm1, const fptype & dm2, const fptype & dm3)
Referenced by enum_to_underlying().
Variable Documentation
resonanceSize
const int resonanceSize = 4
Definition at line 38 of file DalitzPlotHelpers.h.