GooFit: Faddeeva.cc File Reference
Faddeeva.cc File Reference
#include "Faddeeva.hh"
#include <complex>
#include <cassert>
#include <math.h>
Macros
#define M_2PI 6.28318530717958
Functions
std::complex< fptype > Faddeeva_2 (const std::complex< fptype > &z)
fptype cpuvoigtian (fptype x, fptype m, fptype w, fptype s)
Macro Definition Documentation
#define M_2PI 6.28318530717958
Definition at line 5 of file Faddeeva.cc.
Referenced by Faddeeva_2().
Function Documentation
fptype cpuvoigtian (fptype x, fptype m, fptype w, fptype s)
Definition at line 129 of file Faddeeva.cc.
Referenced by generateVoig().
std::complex<fptype> Faddeeva_2 (const std::complex< fptype > & z)
Definition at line 32 of file Faddeeva.cc.
References C, COS, D, e1, e2, EXP, exp(), FABS, FLOOR, M_2PI, n1, n2, norm(), and SIN.
Referenced by cpuvoigtian().