GooFit: Faddeeva.hh File Reference
Faddeeva.hh File Reference
#include "GlobalCudaDefines.hh"
Functions
fptype cpuvoigtian (fptype x, fptype m, fptype w, fptype s)
Function Documentation
fptype cpuvoigtian (fptype x, fptype m, fptype w, fptype s)
Definition at line 129 of file Faddeeva.cc.
References EXP, exp(), Faddeeva_2(), and rsqrtPi.
Referenced by generateVoig().