GooFit: /home/travis/build/GooFit/GooFit/include/goofit/Faddeeva.h File Reference
Faddeeva.h File Reference
#include "goofit/GlobalCudaDefines.h"
Functions
fptype cpuvoigtian (fptype x, fptype m, fptype w, fptype s)
Function Documentation
cpuvoigtian()
fptype cpuvoigtian (fptype x, fptype m, fptype w, fptype s)
Definition at line 140 of file Faddeeva.cc.
References EXP, exp(), and Faddeeva_2().
Referenced by generateVoig().
{
     // This calculation includes the normalisation - integral
     // over the reals is equal to one.
     // return constant for zero width and sigma
     if((0==s) && (0==w))
         return 1;
     assert(s > 0);
     assert(w > 0);
     fptype coef = -0.5/(s*s);
     fptype arg = x - m;
     // Breit-Wigner for zero sigma
     if(0==s)
         return (1/(arg*arg+0.25*w*w));
     // Gauss for zero width
     if(0==w)
         return EXP(coef*arg*arg);
     // actual Voigtian for non-trivial width and sigma
     fptype c = 1./(sqrt(2)*s);
     fptype a = 0.5*c*w;
     fptype u = c*arg;
     std::complex<fptype> z(u, a) ;
     //printf("Calling Faddeeva %f %f %f %f %f %f %f\n", x, m, s, w, c, a, u);
     std::complex<fptype> v = Faddeeva_2(z);
     static const fptype rsqrtPi = 0.5641895835477563;
     return c*rsqrtPi*v.real();
 }