GooFit: /home/travis/build/GooFit/GooFit/src/goofit/FitManagerMinuit1.cc File Reference
FitManagerMinuit1.cc File Reference
#include "goofit/PdfBase.h"
#include "goofit/fitting/FitManagerMinuit1.h"
#include "goofit/PDFs/GooPdf.h"
#include <cstdio>
#include <cassert>
#include <limits>
#include <typeinfo>
#include <set>
#include "goofit/Variable.h"
Namespaces
GooFit
Functions
void FitFun (int &npar, double *gin, double &fun, double *fp, int iflag)
Variables
PdfBase * pdfPointer
vector< Variable * > vars
int numPars = 0
Function Documentation
FitFun()
void FitFun (int & npar, double * gin, double & fun, double * fp, int iflag)
Definition at line 92 of file FitManagerMinuit1.cc.
References PdfBase::calculateNLL(), PdfBase::copyParams(), host_callnumber, numPars, and vars.
Referenced by GooFit::FitManagerMinuit1::setup().
{
     std::vector<double> pars;
     // Notice that npar is number of variable parameters, not total.
     pars.resize(numPars);
     int counter = 0;
     for(Variable* var : vars) {
         if(std::isnan(fp[counter]))
             cout << "Variable " << var->name << " " << var->index << " is NaN\n";
         pars.at(var->getIndex()) = fp[counter++] + var->blind;
     }
     pdfPointer->copyParams(pars);
     fun = pdfPointer->calculateNLL();
     host_callnumber++;
 }
Variable Documentation
numPars
int numPars = 0
Definition at line 12 of file FitManagerMinuit1.cc.
Referenced by FitFun(), and GooFit::FitManagerMinuit1::setup().
pdfPointer
PdfBase* pdfPointer
Definition at line 10 of file FitManagerMinuit1.cc.
vars
vector<Variable*> vars
Definition at line 11 of file FitManagerMinuit1.cc.
Referenced by FitFun(), GooFit::FitManagerMinuit1::getMinuitValues(), and GooFit::FitManagerMinuit1::setup().