GooFit: /home/travis/build/GooFit/GooFit/include/goofit/FitManagerMinuit1.h File Reference
FitManagerMinuit1.h File Reference
#include "goofit/GlobalCudaDefines.h"
#include "goofit/PDFs/GooPdf.h"
#include <TMinuit.h>
Classes
class GooFit::FitManagerMinuit1
Namespaces
GooFit
Functions
void FitFun (int &npar, double *gin, double &fun, double *fp, int iflag)
Variables
PdfBase * pdfPointer
int numPars
Function Documentation
FitFun()
void FitFun (int & npar, double * gin, double & fun, double * fp, int iflag)
Definition at line 114 of file FitManagerMinuit1.cc.
References PdfBase::calculateNLL(), PdfBase::copyParams(), GooFit::FitManagerMinuit1::getMinuitValues(), host_callnumber, numPars, specialTddpPrint(), and vars.
Referenced by GooFit::FitManagerMinuit1::setupMinuit().
{
     vector<double> pars;
     // Notice that npar is number of variable parameters, not total.
     pars.resize(numPars);
     int counter = 0;
     for(std::vector<Variable*>::iterator i = vars.begin(); i != vars.end(); ++i) {
         if(std::isnan(fp[counter]))
             cout << "Variable " << (*i)->name << " " << (*i)->index << " is NaN\n";
         pars[(*i)->getIndex()] = fp[counter++] + (*i)->blind;
     }
     pdfPointer->copyParams(pars);
     fun = pdfPointer->calculateNLL();
     host_callnumber++;
 #ifdef PRINTCALLS
     specialTddpPrint(fun);
 #endif
 }
Variable Documentation
numPars
int numPars
Definition at line 13 of file FitManagerMinuit1.cc.
Referenced by FitFun(), and GooFit::FitManagerMinuit1::setupMinuit().
pdfPointer
PdfBase* pdfPointer
Definition at line 11 of file FitManagerMinuit1.cc.