GooFit: PdfBuilder.cc File Reference
PdfBuilder.cc File Reference
#include "FunctorBase.hh"
#include "PdfBuilder.hh"
#include "ThrustPdfFunctor.hh"
#include <cstdio>
#include <cassert>
#include <limits>
#include <typeinfo>
#include <set>
#include "Variable.hh"
Functions
void specialTddpPrint (double fun)
void FitFun (int &npar, double *gin, double &fun, double *fp, int iflag)
Variables
char stringbuffer [100]
int numDummies = 0
FunctorBase * pdfPointer
PdfFunctor * currGlue = 0
int numPars = 0
set< Variable * > vars
Function Documentation
void FitFun (int & npar, double * gin, double & fun, double * fp, int iflag)
Definition at line 268 of file PdfBuilder.cc.
References FunctorBase::calculateNLL(), FunctorBase::copyParams(), host_callnumber, numPars, pdfPointer, and specialTddpPrint().
Referenced by PdfFunctor::setupMinuit().
void specialTddpPrint (double fun)
Definition at line 298 of file PdfBuilder.cc.
References currGlue, PdfFunctor::getMinuitValues(), and host_callnumber.
Referenced by FitFun().
Variable Documentation
PdfFunctor* currGlue = 0
Definition at line 32 of file PdfBuilder.cc.
Referenced by PdfFunctor::PdfFunctor(), and specialTddpPrint().
int numDummies = 0
Definition at line 14 of file PdfBuilder.cc.
int numPars = 0
Definition at line 33 of file PdfBuilder.cc.
Referenced by FitFun(), and PdfFunctor::setupMinuit().
FunctorBase* pdfPointer
Definition at line 31 of file PdfBuilder.cc.
Referenced by FitFun(), PdfFunctor::PdfFunctor(), and PdfFunctor::setupMinuit().
char stringbuffer[100]
Definition at line 13 of file PdfBuilder.cc.
set<Variable*> vars
Definition at line 181 of file PdfBuilder.cc.