GooFit: PdfBuilder.hh File Reference
PdfBuilder.hh File Reference
#include "GlobalCudaDefines.hh"
#include "ThrustPdfFunctor.hh"
#include "TMinuit.hh"
Classes
class PdfFunctor
Macros
#define MINUIT_VERSION 1
Functions
void FitFun (int &npar, double *gin, double &fun, double *fp, int iflag)
Variables
FunctorBase * pdfPointer
int numPars
Macro Definition Documentation
#define MINUIT_VERSION 1
Definition at line 9 of file PdfBuilder.hh.
Function Documentation
void FitFun (int & npar, double * gin, double & fun, double * fp, int iflag)
Definition at line 268 of file PdfBuilder.cc.
References FunctorBase::calculateNLL(), FunctorBase::copyParams(), host_callnumber, numPars, pdfPointer, and specialTddpPrint().
Referenced by PdfFunctor::setupMinuit().
Variable Documentation
int numPars
Definition at line 33 of file PdfBuilder.cc.
Referenced by FitFun(), and PdfFunctor::setupMinuit().
FunctorBase* pdfPointer
Definition at line 31 of file PdfBuilder.cc.
Referenced by FitFun(), PdfFunctor::PdfFunctor(), and PdfFunctor::setupMinuit().