GooFit: /home/travis/build/GooFit/GooFit/src/rootstuff/TMinuit.cc File Reference
TMinuit.cc File Reference
#include <stdlib.h>
#include <stdio.h>
#include <cstring>
#include <cmath>
#include "goofit/rootstuff/TMinuit.h"
#include "stdarg.h"
Functions
void toUpper (string &str)
bool contains (string &toLookIn, string toLookFor)
string local_Form (const char *va_fmt,...)
Variables
const char charal [29] = " .ABCDEFGHIJKLMNOPQRSTUVWXYZ"
Function Documentation
contains()
bool contains (string & toLookIn, string toLookFor)
Definition at line 332 of file TMinuit.cc.
Referenced by TMinuit::mnset().
{
     return (toLookIn.find(toLookFor) != string::npos);
 }
local_Form()
string local_Form (const char * va_fmt, ...)
Definition at line 338 of file TMinuit.cc.
Referenced by TMinuit::mnderi(), TMinuit::mnemat(), TMinuit::mnexcm(), TMinuit::mnhes1(), TMinuit::mnhess(), TMinuit::mnmatu(), TMinuit::mnparm(), TMinuit::mnpint(), TMinuit::mnprin(), and TMinuit::mnpsdf().
{
     static char strbuffer[10000];
     va_list ap;
     va_start(ap, va_fmt);
     vsnprintf(strbuffer, 10000, va_fmt, ap); // Use vsn, not sn, when we are passing a vararg list and not a strict vararg.
     va_end(ap);
     string ret(strbuffer);
     return ret;
 }
toUpper()
void toUpper (string & str)
Definition at line 326 of file TMinuit.cc.
Referenced by TMinuit::mncomd(), TMinuit::mnexcm(), and TMinuit::mnhelp().
{
     for(unsigned int i = 0; i < str.size(); ++i) {
         str[i] = toupper(str[i]);
     }
 }
Variable Documentation
charal
const char charal[29] = " .ABCDEFGHIJKLMNOPQRSTUVWXYZ"
Definition at line 323 of file TMinuit.cc.
Referenced by TMinuit::mncros(), and TMinuit::mnline().