GooFit: FPOINTER/TddpHelperFunctions.cxx File Reference
TddpHelperFunctions.cxx File Reference
Functions
__device__ fptype twoBodyCMmom (double rMassSq, fptype d1m, fptype d2m)
__device__ fptype dampingFactorSquare (fptype cmmom, int spin, fptype mRadius)
__device__ bool inDalitz (fptype m12, fptype m13, fptype bigM, fptype dm1, fptype dm2, fptype dm3)
__device__ fptype spinFactor (unsigned int spin, fptype motherMass, fptype daug1Mass, fptype daug2Mass, fptype daug3Mass, fptype m12, fptype m13, fptype m23, unsigned int cyclic_index)
__device__ devcomplex< fptype > plainBW (fptype m12, fptype m13, fptype m23, fptype resmass, fptype reswidth, fptype meson_radius, fptype motherMass, fptype daug1Mass, fptype daug2Mass, fptype daug3Mass, unsigned int spin, unsigned int cyclic_index)
__device__ devcomplex< fptype > gaussian (fptype m12, fptype m13, fptype m23, fptype resmass, fptype reswidth, unsigned int cyclic_index)
__device__ fptype hFun (double s, double daug2Mass, double daug3Mass)
__device__ fptype dh_dsFun (double s, double daug2Mass, double daug3Mass)
__device__ fptype dFun (double s, double daug2Mass, double daug3Mass)
__device__ fptype fsFun (double s, double m2, double gam, double daug2Mass, double daug3Mass)
__device__ devcomplex< fptype > gouSak (fptype m12, fptype m13, fptype m23, fptype resmass, fptype reswidth, fptype meson_radius, fptype motherMass, fptype daug1Mass, fptype daug2Mass, fptype daug3Mass, unsigned int spin, unsigned int cyclic_index)
__device__ devcomplex< fptype > getResonanceAmplitude (fptype m12, fptype m13, fptype resmass, fptype reswidth, unsigned int spin, unsigned int cyclic_index, unsigned int eval_type, unsigned int *indices)
__device__ void getAmplitudeCoefficients (devcomplex< fptype > a1, devcomplex< fptype > a2, fptype &a1sq, fptype &a2sq, fptype &a1a2real, fptype &a1a2imag)
Function Documentation
__device__ fptype dampingFactorSquare (fptype cmmom, int spin, fptype mRadius)
Definition at line 16 of file TddpHelperFunctions.cxx.
Referenced by gouSak(), and plainBW().
__device__ fptype dFun (double s, double daug2Mass, double daug3Mass)
Definition at line 164 of file TddpHelperFunctions.cxx.
References twoBodyCMmom().
Referenced by gouSak().
__device__ fptype dh_dsFun (double s, double daug2Mass, double daug3Mass)
Definition at line 154 of file TddpHelperFunctions.cxx.
References hFun(), and twoBodyCMmom().
Referenced by fsFun().
__device__ fptype fsFun (double s, double m2, double gam, double daug2Mass, double daug3Mass)
Definition at line 178 of file TddpHelperFunctions.cxx.
References dh_dsFun(), hFun(), POW, and twoBodyCMmom().
Referenced by gouSak().
__device__ devcomplex<fptype> gaussian (fptype m12, fptype m13, fptype m23, fptype resmass, fptype reswidth, unsigned int cyclic_index)
Definition at line 121 of file TddpHelperFunctions.cxx.
References EXP, PAIR_12, PAIR_13, and SQRT.
Referenced by device_threegauss_resolution(), and getResonanceAmplitude().
__device__ void getAmplitudeCoefficients (devcomplex< fptype > a1, devcomplex< fptype > a2, fptype & a1sq, fptype & a2sq, fptype & a1a2real, fptype & a1a2imag)
Definition at line 243 of file TddpHelperFunctions.cxx.
References devcomplex< T >::abs2(), conj(), devcomplex< T >::imag, and devcomplex< T >::real.
__device__ devcomplex<fptype> getResonanceAmplitude (fptype m12, fptype m13, fptype resmass, fptype reswidth, unsigned int spin, unsigned int cyclic_index, unsigned int eval_type, unsigned int * indices)
Definition at line 222 of file TddpHelperFunctions.cxx.
References functorConstants, GAUSSIAN, gaussian(), GOU_SAK, gouSak(), inDalitz(), NONRES, plainBW(), and RBW.
Referenced by device_Tddp_calcIntegrals(), SpecialIncoherentIntegrator::operator()(), SpecialIncoherentResonanceCalculator::operator()(), and SpecialWaveCalculator::operator()().
__device__ devcomplex<fptype> gouSak (fptype m12, fptype m13, fptype m23, fptype resmass, fptype reswidth, fptype meson_radius, fptype motherMass, fptype daug1Mass, fptype daug2Mass, fptype daug3Mass, unsigned int spin, unsigned int cyclic_index)
Definition at line 190 of file TddpHelperFunctions.cxx.
References D, dampingFactorSquare(), dFun(), fsFun(), PAIR_12, PAIR_13, PAIR_23, POW, spinFactor(), SQRT, and twoBodyCMmom().
Referenced by getResonanceAmplitude().
__device__ fptype hFun (double s, double daug2Mass, double daug3Mass)
Definition at line 141 of file TddpHelperFunctions.cxx.
References twoBodyCMmom().
Referenced by dh_dsFun(), and fsFun().
__device__ bool inDalitz (fptype m12, fptype m13, fptype bigM, fptype dm1, fptype dm2, fptype dm3)
Definition at line 25 of file TddpHelperFunctions.cxx.
References POW, and SQRT.
Referenced by device_DalitzVeto(), device_Tddp(), device_Tddp_calcIntegrals(), getResonanceAmplitude(), and SpecialWaveCalculator::operator()().
__device__ devcomplex<fptype> plainBW (fptype m12, fptype m13, fptype m23, fptype resmass, fptype reswidth, fptype meson_radius, fptype motherMass, fptype daug1Mass, fptype daug2Mass, fptype daug3Mass, unsigned int spin, unsigned int cyclic_index)
Definition at line 87 of file TddpHelperFunctions.cxx.
References C, dampingFactorSquare(), PAIR_12, PAIR_13, PAIR_23, POW, spinFactor(), SQRT, and twoBodyCMmom().
Referenced by getResonanceAmplitude().
__device__ fptype spinFactor (unsigned int spin, fptype motherMass, fptype daug1Mass, fptype daug2Mass, fptype daug3Mass, fptype m12, fptype m13, fptype m23, unsigned int cyclic_index)
Definition at line 42 of file TddpHelperFunctions.cxx.
References PAIR_12, and PAIR_13.
Referenced by gouSak(), and plainBW().
__device__ fptype twoBodyCMmom (double rMassSq, fptype d1m, fptype d2m)
Definition at line 1 of file TddpHelperFunctions.cxx.
References POW, and SQRT.
Referenced by dFun(), dh_dsFun(), fsFun(), gouSak(), hFun(), and plainBW().