GooFit: FPOINTER/TddpThrustFunctor.cu File Reference
TddpThrustFunctor.cu File Reference
#include "TddpThrustFunctor.hh"
#include <complex>
#include "TddpHelperFunctions.hh"
#include "TddpHelperFunctions.cxx"
Functions
__device__ int parIndexFromResIndex (int resIndex)
__device__ ThreeComplex device_Tddp_calcIntegrals (fptype m12, fptype m13, int res_i, int res_j, fptype *p, unsigned int *indices)
__device__ fptype device_Tddp (fptype *evt, fptype *p, unsigned int *indices)
Variables
const int resonanceSize = 8
const int resonanceOffset = 8
__device__ WaveHolder * cWaves [10]
__device__ device_function_ptr ptr_to_Tddp = device_Tddp
Function Documentation
__device__ fptype device_Tddp (fptype * evt, fptype * p, unsigned int * indices)
Definition at line 87 of file TddpThrustFunctor.cu.
References callFunction(), conj(), cWaves, device_function_table, FLOOR, functorConstants, devcomplex< T >::imag, inDalitz(), devcomplex< T >::multiply(), norm2(), parIndexFromResIndex(), and devcomplex< T >::real.
__device__ ThreeComplex device_Tddp_calcIntegrals (fptype m12, fptype m13, int res_i, int res_j, fptype * p, unsigned int * indices)
Definition at line 25 of file TddpThrustFunctor.cu.
References conj(), functorConstants, getResonanceAmplitude(), inDalitz(), and parIndexFromResIndex().
Referenced by SpecialDalitzIntegrator::operator()().
__device__ int parIndexFromResIndex (int resIndex) inline
Definition at line 21 of file TddpThrustFunctor.cu.
References resonanceOffset, and resonanceSize.
Referenced by device_Tddp(), device_Tddp_calcIntegrals(), SpecialDalitzIntegrator::operator()(), and SpecialWaveCalculator::operator()().
Variable Documentation
__device__ WaveHolder* cWaves[10]
Definition at line 19 of file TddpThrustFunctor.cu.
Referenced by device_Tddp(), and TddpThrustFunctor::setDataSize().
__device__ device_function_ptr ptr_to_Tddp = device_Tddp
Definition at line 234 of file TddpThrustFunctor.cu.
Referenced by TddpThrustFunctor::TddpThrustFunctor().
const int resonanceOffset = 8
Definition at line 9 of file TddpThrustFunctor.cu.
Referenced by TddpThrustFunctor::normalise(), and parIndexFromResIndex().
const int resonanceSize = 8
Definition at line 8 of file TddpThrustFunctor.cu.
Referenced by TddpThrustFunctor::normalise(), and parIndexFromResIndex().