GooFit: FPOINTER/TrigThresholdThrustFunctor.cu File Reference
TrigThresholdThrustFunctor.cu File Reference
#include "TrigThresholdThrustFunctor.hh"
Functions
__device__ fptype threshCalc (fptype distance, fptype linConst)
__device__ fptype device_TrigThresholdUpper (fptype *evt, fptype *p, unsigned int *indices)
__device__ fptype device_TrigThresholdLower (fptype *evt, fptype *p, unsigned int *indices)
__device__ fptype device_VerySpecialEpisodeTrigThresholdUpper (fptype *evt, fptype *p, unsigned int *indices)
__device__ fptype device_VerySpecialEpisodeTrigThresholdLower (fptype *evt, fptype *p, unsigned int *indices)
Variables
__device__ device_function_ptr ptr_to_TrigThresholdUpper = device_TrigThresholdUpper
__device__ device_function_ptr ptr_to_TrigThresholdLower = device_TrigThresholdLower
__device__ device_function_ptr ptr_to_VerySpecialEpisodeTrigThresholdUpper = device_VerySpecialEpisodeTrigThresholdUpper
__device__ device_function_ptr ptr_to_VerySpecialEpisodeTrigThresholdLower = device_VerySpecialEpisodeTrigThresholdLower
Function Documentation
__device__ fptype device_TrigThresholdLower (fptype * evt, fptype * p, unsigned int * indices)
Definition at line 18 of file TrigThresholdThrustFunctor.cu.
References threshCalc().
__device__ fptype device_TrigThresholdUpper (fptype * evt, fptype * p, unsigned int * indices)
Definition at line 8 of file TrigThresholdThrustFunctor.cu.
References threshCalc().
__device__ fptype device_VerySpecialEpisodeTrigThresholdLower (fptype * evt, fptype * p, unsigned int * indices)
Definition at line 43 of file TrigThresholdThrustFunctor.cu.
References threshCalc().
__device__ fptype device_VerySpecialEpisodeTrigThresholdUpper (fptype * evt, fptype * p, unsigned int * indices)
Definition at line 28 of file TrigThresholdThrustFunctor.cu.
References threshCalc().
__device__ fptype threshCalc (fptype distance, fptype linConst)
Definition at line 3 of file TrigThresholdThrustFunctor.cu.
References SIN.
Referenced by device_TrigThresholdLower(), device_TrigThresholdUpper(), device_VerySpecialEpisodeTrigThresholdLower(), and device_VerySpecialEpisodeTrigThresholdUpper().
Variable Documentation
__device__ device_function_ptr ptr_to_TrigThresholdLower = device_TrigThresholdLower
Definition at line 62 of file TrigThresholdThrustFunctor.cu.
Referenced by TrigThresholdThrustFunctor::TrigThresholdThrustFunctor().
__device__ device_function_ptr ptr_to_TrigThresholdUpper = device_TrigThresholdUpper
Definition at line 61 of file TrigThresholdThrustFunctor.cu.
Referenced by TrigThresholdThrustFunctor::TrigThresholdThrustFunctor().
__device__ device_function_ptr ptr_to_VerySpecialEpisodeTrigThresholdLower = device_VerySpecialEpisodeTrigThresholdLower
Definition at line 64 of file TrigThresholdThrustFunctor.cu.
Referenced by TrigThresholdThrustFunctor::TrigThresholdThrustFunctor().
__device__ device_function_ptr ptr_to_VerySpecialEpisodeTrigThresholdUpper = device_VerySpecialEpisodeTrigThresholdUpper
Definition at line 63 of file TrigThresholdThrustFunctor.cu.
Referenced by TrigThresholdThrustFunctor::TrigThresholdThrustFunctor().