GooFit: /home/travis/build/GooFit/GooFit/include/goofit/Variable.h File Reference
Variable.h File Reference
#include <string>
#include <map>
#include <iostream>
#include <cassert>
#include <algorithm>
#include "goofit/GlobalCudaDefines.h"
Classes
class Indexable
class Variable
class CountingVariable
class Constant
Functions
std::ostream & operator<< (std::ostream &o, const Variable &var)
int max_index (const std::vector< Variable *> &vars)
Get the max index of a variable from a list.
Function Documentation
max_index()
int max_index (const std::vector< Variable *> & vars) inline
Get the max index of a variable from a list.
Definition at line 135 of file Variable.h.
References Indexable::getIndex().
Referenced by GooFit::FCN::operator()().
{
     Variable* max_ind_ptr = *std::max_element(std::begin(vars),
                                               std::end(vars),
                                               [](const Variable *a, const Variable *b)
                                               {return a->getIndex() < b->getIndex();});
     return max_ind_ptr->getIndex();
 }
operator<<()
std::ostream& operator<< (std::ostream & o, const Variable & var) inline
Definition at line 121 of file Variable.h.
References Variable::error, Variable::fixed, Indexable::getFitterIndex(), Indexable::getIndex(), Variable::lowerlimit, Indexable::name, Variable::upperlimit, and Indexable::value.
{
     o << var.name << ": " << var.value << " +/- " << var.error;
     if(!var.fixed)
         o << " [" << var.lowerlimit << ", " << var.upperlimit << "]";
     if(var.getIndex() >= 0)
         o << " GooFit index: " << var.getIndex();
     if(var.getFitterIndex() >= 0)
         o << " Fitter index: " << var.getFitterIndex();
     return o;
 }