GooFit: GooFit::EventNumber Class Reference
GooFit::EventNumber Class Reference
#include <Variable.h>
Public Member Functions
EventNumber (std::string name, fptype min=0, fptype max=EventNumber::maxint)
~EventNumber () override=default
EventNumber & operator= (const EventNumber &)=delete
const EventNumber & operator= (const fptype &val)
Support var = 3.
Public Member Functions inherited from GooFit::Observable
Observable (std::string name, fptype lowerlimit, fptype upperlimit)
~Observable () override=default
Observable & operator= (const Observable &)=delete
void setNumBins (size_t num)
Set the number of bins.
size_t getNumBins () const
Get the number of bins.
fptype getBinSize () const
Get the bin size, (upper-lower) / bins.
bool isEventNumber () const
Check to see if this is an event number.
const Observable & operator= (const fptype &val)
Support var = 3.
Public Member Functions inherited from GooFit::Indexable
Indexable (std::string n, fptype val=0)
Indexable (std::string n, fptype val, fptype lowerlimit, fptype upperlimit)
Indexable & operator= (const Indexable &)=delete
virtual ~Indexable ()
int getIndex () const
Get the GooFit index.
void setIndex (int value)
Set the GooFit index.
const std::string & getName () const
Get the name.
fptype getValue () const
Get the value.
void setValue (fptype val)
Set the value.
fptype getUpperLimit () const
Get the upper limit.
void setUpperLimit (fptype val)
Set the upper limit.
fptype getLowerLimit () const
Get the lower limit.
void setLowerLimit (fptype val)
Set the lower limit.
const Indexable & operator= (const fptype &val)
Support var = 3.
operator fptype () const
Support fptype val = var.
bool operator< (const Indexable &other) const
Support for using as key in map - Notice this does NOT sort by index!
bool operator== (const Indexable &other) const
Support for comparison - only if really the same object, not just the same value.
bool operator!= (const Indexable &other) const
Support for comparison - only if really the same object, not just the same value.
operator bool () const
Check to see if in range.
Static Public Attributes
static constexpr fptype maxint {1L << std::numeric_limits<fptype>::digits}
Additional Inherited Members
Protected Attributes inherited from GooFit::Observable
std::shared_ptr< size_t > numbins {std::make_shared<size_t>(100)}
The number of bins (mostly for BinnedData, or plotting help)
bool is_event_number {false}
This identifies this as an EventNumber if copies are made.
Protected Attributes inherited from GooFit::Indexable
std::string name
The variable name. Should be unique.
std::shared_ptr< fptype > value
The value of the variable.
std::shared_ptr< fptype > lowerlimit {std::make_shared<fptype>(0)}
The lower limit.
std::shared_ptr< fptype > upperlimit {std::make_shared<fptype>(0)}
The upper limit.
std::shared_ptr< int > index {std::make_shared<int>(-1)}
The goofit index, -1 if unset.
Detailed Description
This is used to track event number for MPI versions. A cast is done to know whether the values need to be fixed. Ugly hack because this internally stores a floating point number!
Definition at line 242 of file Variable.h.
Constructor & Destructor Documentation
EventNumber()
GooFit::EventNumber::EventNumber (std::string name, fptype min = 0, fptype max = EventNumber::maxint) inline
Definition at line 246 of file Variable.h.
References GooFit::Indexable::operator=(), and GooFit::Indexable::value.
         : GooFit::Observable(name, min, max) {
         is_event_number = true;
         *value          = 0; // Start with 0 event number by default
     }
~EventNumber()
GooFit::EventNumber::~EventNumber () override default
Member Function Documentation
operator=() [1/2]
EventNumber& GooFit::EventNumber::operator= (const EventNumber &) delete
operator=() [2/2]
const EventNumber& GooFit::EventNumber::operator= (const fptype & val) inline
Support var = 3.
Definition at line 257 of file Variable.h.
References GooFit::max_fitter_index(), GooFit::max_index(), GooFit::operator<<(), GooFit::operator>>(), and GooFit::Indexable::setValue().
{
         setValue(val);
         return *this;
     }
Member Data Documentation
maxint
constexpr fptype GooFit::EventNumber::maxint {1L << std::numeric_limits<fptype>::digits} static
Definition at line 244 of file Variable.h.
The documentation for this class was generated from the following file:
/home/travis/build/GooFit/GooFit/include/goofit/Variable.h