GooFit: PdfBase Class Reference
PdfBase Class Reference abstract
#include <PdfBase.h>
Public Types
enum Specials { ForceSeparateNorm = 1, ForceCommonNorm = 2 }
typedef std::vector< Variable * > obsCont
typedef obsCont::iterator obsIter
typedef obsCont::const_iterator obsConstIter
typedef std::vector< Variable * > parCont
typedef parCont::iterator parIter
typedef parCont::const_iterator parConstIter
Public Member Functions
PdfBase (Variable *x, std::string n)
virtual __host__ double calculateNLL () const =0
virtual __host__ fptype normalise () const =0
__host__ void initialiseIndices (std::vector< unsigned int > pindices)
__host__ void addSpecialMask (int m)
__host__ void copyParams (const std::vector< double > &pars) const
__host__ void copyParams ()
__host__ void copyNormFactors () const
__host__ void generateNormRange ()
__host__ std::string getName () const
virtual __host__ void getObservables (obsCont &ret) const
virtual __host__ void getParameters (parCont &ret) const
__host__ Variable * getParameterByName (string n) const
__host__ int getSpecialMask () const
__host__ void setData (BinnedDataSet *data)
__host__ void setData (UnbinnedDataSet *data)
__host__ void setData (std::vector< std::map< Variable *, fptype >> &data)
virtual __host__ void setFitControl (FitControl *const fc, bool takeOwnerShip=true)=0
virtual __host__ bool hasAnalyticIntegral () const
__host__ unsigned int getFunctionIndex () const
__host__ unsigned int getParameterIndex () const
__host__ unsigned int registerParameter (Variable *var)
__host__ unsigned int registerConstants (unsigned int amount)
virtual __host__ void recursiveSetNormalisation (fptype norm=1) const
__host__ void unregisterParameter (Variable *var)
__host__ void registerObservable (Variable *obs)
__host__ void setIntegrationFineness (int i)
__host__ void printProfileInfo (bool topLevel=true)
__host__ bool parametersChanged () const
__host__ void storeParameters () const
__host__ obsIter obsBegin ()
__host__ obsIter obsEnd ()
__host__ obsConstIter obsCBegin () const
__host__ obsConstIter obsCEnd () const
__host__ void checkInitStatus (std::vector< std::string > &unInited) const
void clearCurrentFit ()
__host__ void SigGenSetIndices ()
Protected Member Functions
void setNumPerTask (PdfBase *p, const int &c)
Protected Attributes
fptype numEvents
unsigned int numEntries
fptype * normRanges
unsigned int parameters
unsigned int cIndex
obsCont observables
parCont parameterList
FitControl * fitControl
std::vector< PdfBase * > components
int integrationBins
int specialMask
fptype * cachedParams
bool properlyInitialised
unsigned int functionIdx
int m_iEventsPerTask
Detailed Description
Definition at line 29 of file PdfBase.h.
Member Typedef Documentation
obsConstIter
typedef obsCont::const_iterator PdfBase::obsConstIter
Definition at line 42 of file PdfBase.h.
obsCont
typedef std::vector<Variable*> PdfBase::obsCont
Definition at line 40 of file PdfBase.h.
obsIter
typedef obsCont::iterator PdfBase::obsIter
Definition at line 41 of file PdfBase.h.
parConstIter
typedef parCont::const_iterator PdfBase::parConstIter
Definition at line 45 of file PdfBase.h.
parCont
typedef std::vector<Variable*> PdfBase::parCont
Definition at line 43 of file PdfBase.h.
parIter
typedef parCont::iterator PdfBase::parIter
Definition at line 44 of file PdfBase.h.
Member Enumeration Documentation
Specials
enum PdfBase::Specials
Enumerator
ForceSeparateNorm
ForceCommonNorm
Definition at line 34 of file PdfBase.h.
 {ForceSeparateNorm = 1, ForceCommonNorm = 2};
Constructor & Destructor Documentation
PdfBase()
PdfBase::PdfBase (Variable * x, std::string n)
Definition at line 13 of file PdfBase.cc.
References registerObservable().
     : name(n)
     , numEvents(0)
     , numEntries(0)
     , normRanges(0)
     , fitControl(0)
     , integrationBins(-1)
     , specialMask(0)
     , cachedParams(0)
     , properlyInitialised(true) { // Special-case PDFs should set to false.
     if(x)
         registerObservable(x);
 }
Member Function Documentation
addSpecialMask()
__host__ void PdfBase::addSpecialMask (int m) inline
Definition at line 47 of file PdfBase.h.
References copyNormFactors(), copyParams(), generateNormRange(), and specialMask.
{
         specialMask |= m;
     }
calculateNLL()
virtual __host__ double PdfBase::calculateNLL () const pure virtual
Implemented in GooPdf.
Referenced by FitFun(), and GooFit::FitManagerMinuit2::operator()().
checkInitStatus()
__host__ void PdfBase::checkInitStatus (std::vector< std::string > & unInited) const
Definition at line 27 of file PdfBase.cc.
References components, getName(), and properlyInitialised.
Referenced by obsCEnd().
{
     if(!properlyInitialised)
         unInited.push_back(getName());
     for(unsigned int i = 0; i < components.size(); ++i) {
         components[i]->checkInitStatus(unInited);
     }
 }
clearCurrentFit()
void PdfBase::clearCurrentFit ()
Referenced by obsCEnd().
copyNormFactors()
__host__ void PdfBase::copyNormFactors () const
Referenced by addSpecialMask().
copyParams() [1/2]
__host__ void PdfBase::copyParams (const std::vector< double > & pars) const
Referenced by FitFun(), GooFit::FitManagerMinuit2::operator()(), and GooFit::FitManagerMinuit1::setupMinuit().
copyParams() [2/2]
__host__ void PdfBase::copyParams ()
Referenced by addSpecialMask().
generateNormRange()
__host__ void PdfBase::generateNormRange ()
Referenced by addSpecialMask(), and setIntegrationFineness().
getFunctionIndex()
__host__ unsigned int PdfBase::getFunctionIndex () const inline
Definition at line 70 of file PdfBase.h.
References functionIdx.
{
         return functionIdx;
     }
getName()
__host__ std::string PdfBase::getName () const inline
Definition at line 54 of file PdfBase.h.
References getObservables(), getParameterByName(), and getParameters().
Referenced by checkInitStatus(), SpinFactor::operator==(), Lineshape::operator==(), and registerParameter().
{
         return name;
     }
getObservables()
__host__ void PdfBase::getObservables (obsCont & ret) const virtual
Definition at line 133 of file PdfBase.cc.
References components, obsCBegin(), and obsCEnd().
Referenced by getName().
{
     for(obsConstIter p = obsCBegin(); p != obsCEnd(); ++p) {
         if(std::find(ret.begin(), ret.end(), *p) != ret.end())
             continue;
         ret.push_back(*p);
     }
     for(unsigned int i = 0; i < components.size(); ++i) {
         components[i]->getObservables(ret);
     }
 }
getParameterByName()
__host__ Variable * PdfBase::getParameterByName (string n) const
Definition at line 117 of file PdfBase.cc.
References components, and parameterList.
Referenced by getName().
{
     for(parConstIter p = parameterList.begin(); p != parameterList.end(); ++p) {
         if((*p)->name == n)
             return (*p);
     }
     for(unsigned int i = 0; i < components.size(); ++i) {
         Variable* cand = components[i]->getParameterByName(n);
         if(cand)
             return cand;
     }
     return 0;
 }
getParameterIndex()
__host__ unsigned int PdfBase::getParameterIndex () const inline
Definition at line 73 of file PdfBase.h.
References norm(), parameters, parametersChanged(), printProfileInfo(), recursiveSetNormalisation(), registerConstants(), registerObservable(), registerParameter(), setIntegrationFineness(), storeParameters(), and unregisterParameter().
{
         return parameters;
     }
getParameters()
__host__ void PdfBase::getParameters (parCont & ret) const virtual
Definition at line 104 of file PdfBase.cc.
References components, and parameterList.
Referenced by GooFit::FitManagerMinuit2::fit(), getName(), GooFit::FitManagerMinuit2::operator()(), parametersChanged(), readFromFile(), GooFit::FitManagerMinuit1::setupMinuit(), storeParameters(), and writeToFile().
{
     for(parConstIter p = parameterList.begin(); p != parameterList.end(); ++p) {
         if(std::find(ret.begin(), ret.end(), (*p)) != ret.end())
             continue;
         ret.push_back(*p);
     }
     for(unsigned int i = 0; i < components.size(); ++i) {
         components[i]->getParameters(ret);
     }
 }
getSpecialMask()
__host__ int PdfBase::getSpecialMask () const inline
Definition at line 60 of file PdfBase.h.
References setData(), setFitControl(), and specialMask.
{
         return specialMask;
     }
hasAnalyticIntegral()
virtual __host__ bool PdfBase::hasAnalyticIntegral () const inline virtual
Reimplemented in GooPdf, EventWeightedAddPdf, AddPdf, ExpPdf, ProdPdf, GaussianPdf, JohnsonSUPdf, KinLimitBWPdf, StepPdf, ArgusPdf, and ScaledGaussianPdf.
Definition at line 67 of file PdfBase.h.
{
         return false;
     }
initialiseIndices()
__host__ void PdfBase::initialiseIndices (std::vector< unsigned int > pindices)
normalise()
virtual __host__ fptype PdfBase::normalise () const pure virtual
Implemented in GooPdf, TddpPdf, DPPdf, TDDP4, IncoherentSumPdf, DalitzPlotPdf, CompositePdf, EventWeightedAddPdf, AddPdf, ConvolutionPdf, MappedPdf, ProdPdf, and SmoothHistogramPdf.
obsBegin()
__host__ obsIter PdfBase::obsBegin () inline
Definition at line 87 of file PdfBase.h.
References observables.
{
         return observables.begin();
     }
obsCBegin()
__host__ obsConstIter PdfBase::obsCBegin () const inline
Definition at line 93 of file PdfBase.h.
References observables.
Referenced by getObservables().
{
         return observables.begin();
     }
obsCEnd()
__host__ obsConstIter PdfBase::obsCEnd () const inline
Definition at line 96 of file PdfBase.h.
References checkInitStatus(), clearCurrentFit(), and observables.
Referenced by getObservables().
{
         return observables.end();
     }
obsEnd()
__host__ obsIter PdfBase::obsEnd () inline
Definition at line 90 of file PdfBase.h.
References observables.
{
         return observables.end();
     }
parametersChanged()
__host__ bool PdfBase::parametersChanged () const
Definition at line 168 of file PdfBase.cc.
References cachedParams, getParameters(), and host_params.
Referenced by getParameterIndex().
{
     if(!cachedParams)
         return true;
     parCont params;
     getParameters(params);
     int counter = 0;
     for(parIter v = params.begin(); v != params.end(); ++v) {
         if(cachedParams[counter++] != host_params[(*v)->index])
             return true;
     }
     return false;
 }
printProfileInfo()
__host__ void PdfBase::printProfileInfo (bool topLevel = true)
Referenced by getParameterIndex().
recursiveSetNormalisation()
__host__ void PdfBase::recursiveSetNormalisation (fptype norm = 1) const virtual
Definition at line 36 of file PdfBase.cc.
References components, host_normalisation, norm(), and parameters.
Referenced by getParameterIndex().
{
     host_normalisation[parameters] = norm;
     for(unsigned int i = 0; i < components.size(); ++i) {
         components[i]->recursiveSetNormalisation(norm);
     }
 }
registerConstants()
__host__ unsigned int PdfBase::registerConstants (unsigned int amount)
Definition at line 146 of file PdfBase.cc.
References cIndex, maxParams, and totalConstants.
Referenced by getParameterIndex().
{
     assert(totalConstants + amount < maxParams);
     cIndex = totalConstants;
     totalConstants += amount;
     return cIndex;
 }
registerObservable()
void PdfBase::registerObservable (Variable * obs)
Definition at line 153 of file PdfBase.cc.
References observables.
Referenced by getParameterIndex(), and PdfBase().
{
     if(!obs)
         return;
     if(find(observables.begin(), observables.end(), obs) != observables.end())
         return;
     observables.push_back(obs);
 }
registerParameter()
__host__ unsigned int PdfBase::registerParameter (Variable * var)
Definition at line 44 of file PdfBase.cc.
References Indexable::getIndex(), getName(), Indexable::index, parameterList, and variableRegistry.
Referenced by getParameterIndex().
{
     if(!var) {
         std::cout << "Error: Attempt to register null Variable with "
                   << getName()
                   << ", aborting.\n";
         assert(var);
         exit(1);
     }
     if(std::find(parameterList.begin(), parameterList.end(), var) != parameterList.end())
         return (unsigned int) var->getIndex();
     parameterList.push_back(var);
     variableRegistry[var].insert(this);
     if(0 > var->getIndex()) {
         unsigned int unusedIndex = 0;
         while(true) {
             bool canUse = true;
             for(std::map<Variable*, std::set<PdfBase*>>::iterator p = variableRegistry.begin(); p != variableRegistry.end(); ++p) {
                 if(unusedIndex != (*p).first->index)
                     continue;
                 canUse = false;
                 break;
             }
             if(canUse)
                 break;
             unusedIndex++;
         }
         var->index = unusedIndex;
     }
     return (unsigned int) var->getIndex();
 }
setData() [1/3]
__host__ void PdfBase::setData (BinnedDataSet * data)
Referenced by getSpecialMask().
setData() [2/3]
__host__ void PdfBase::setData (UnbinnedDataSet * data)
setData() [3/3]
__host__ void PdfBase::setData (std::vector< std::map< Variable *, fptype >> & data)
setFitControl()
virtual __host__ void PdfBase::setFitControl (FitControl *const fc, bool takeOwnerShip = true) pure virtual
Implemented in GooPdf.
Referenced by getSpecialMask().
setIntegrationFineness()
__host__ void PdfBase::setIntegrationFineness (int i)
Definition at line 163 of file PdfBase.cc.
References generateNormRange(), and integrationBins.
Referenced by getParameterIndex().
{
     integrationBins = i;
     generateNormRange();
 }
setNumPerTask()
__host__ void PdfBase::setNumPerTask (PdfBase * p, const int & c) protected
Definition at line 198 of file PdfBase.cc.
References m_iEventsPerTask.
{
     if(!p)
         return;
     m_iEventsPerTask = c;
 }
SigGenSetIndices()
__host__ void PdfBase::SigGenSetIndices () inline
Definition at line 102 of file PdfBase.h.
{
         setIndices();
     }
storeParameters()
__host__ void PdfBase::storeParameters () const
Definition at line 184 of file PdfBase.cc.
References cachedParams, getParameters(), and host_params.
Referenced by getParameterIndex().
{
     parCont params;
     getParameters(params);
     if(!cachedParams)
         cachedParams = new fptype[params.size()];
     int counter = 0;
     for(parIter v = params.begin(); v != params.end(); ++v) {
         cachedParams[counter++] = host_params[(*v)->index];
     }
 }
unregisterParameter()
__host__ void PdfBase::unregisterParameter (Variable * var)
Definition at line 85 of file PdfBase.cc.
References components, Indexable::index, parameterList, and variableRegistry.
Referenced by getParameterIndex().
{
     if(!var)
         return;
     parIter pos = std::find(parameterList.begin(), parameterList.end(), var);
     if(pos != parameterList.end())
         parameterList.erase(pos);
     variableRegistry[var].erase(this);
     if(0 == variableRegistry[var].size())
         var->index = -1;
     for(unsigned int i = 0; i < components.size(); ++i) {
         components[i]->unregisterParameter(var);
     }
 }
Member Data Documentation
cachedParams
fptype* PdfBase::cachedParams mutable protected
Definition at line 117 of file PdfBase.h.
Referenced by parametersChanged(), and storeParameters().
cIndex
unsigned int PdfBase::cIndex protected
Definition at line 110 of file PdfBase.h.
Referenced by registerConstants().
components
std::vector<PdfBase*> PdfBase::components protected
Definition at line 114 of file PdfBase.h.
Referenced by checkInitStatus(), getObservables(), getParameterByName(), getParameters(), recursiveSetNormalisation(), and unregisterParameter().
fitControl
FitControl* PdfBase::fitControl protected
Definition at line 113 of file PdfBase.h.
functionIdx
unsigned int PdfBase::functionIdx protected
Definition at line 120 of file PdfBase.h.
Referenced by getFunctionIndex().
integrationBins
int PdfBase::integrationBins protected
Definition at line 115 of file PdfBase.h.
Referenced by setIntegrationFineness().
m_iEventsPerTask
int PdfBase::m_iEventsPerTask protected
Definition at line 122 of file PdfBase.h.
Referenced by setNumPerTask().
normRanges
fptype* PdfBase::normRanges protected
Definition at line 108 of file PdfBase.h.
numEntries
unsigned int PdfBase::numEntries protected
Definition at line 107 of file PdfBase.h.
numEvents
fptype PdfBase::numEvents protected
Definition at line 106 of file PdfBase.h.
Referenced by TDDP4::setGenDecayTimeLimit(), and DPPdf::setGenerationOffset().
observables
obsCont PdfBase::observables protected
Definition at line 111 of file PdfBase.h.
Referenced by obsBegin(), obsCBegin(), obsCEnd(), obsEnd(), and registerObservable().
parameterList
parCont PdfBase::parameterList protected
Definition at line 112 of file PdfBase.h.
Referenced by getParameterByName(), getParameters(), registerParameter(), and unregisterParameter().
parameters
unsigned int PdfBase::parameters protected
Definition at line 109 of file PdfBase.h.
Referenced by getParameterIndex(), ExpPdf::hasAnalyticIntegral(), recursiveSetNormalisation(), SpinFactor::setConstantIndex(), and Lineshape::setConstantIndex().
properlyInitialised
bool PdfBase::properlyInitialised protected
Definition at line 118 of file PdfBase.h.
Referenced by checkInitStatus().
specialMask
int PdfBase::specialMask protected
Definition at line 116 of file PdfBase.h.
Referenced by addSpecialMask(), and getSpecialMask().
The documentation for this class was generated from the following files:
/home/travis/build/GooFit/GooFit/include/goofit/PdfBase.h
/home/travis/build/GooFit/GooFit/src/goofit/PdfBase.cc