GooFit: SymmLorentzMatrix Class Reference
SymmLorentzMatrix Class Reference
#include <SpinHelper.h>
Public Member Functions
EXEC_TARGET void makeGmunu ()
EXEC_TARGET const SymmLorentzMatrix & gmunu ()
EXEC_TARGET SymmLorentzMatrix ()
EXEC_TARGET SymmLorentzMatrix (const gpuLVec p[4])
EXEC_TARGET SymmLorentzMatrix (const gpuLVec p)
EXEC_TARGET SymmLorentzMatrix (const SymmLorentzMatrix &other)
EXEC_TARGET SymmLorentzMatrix & add (const SymmLorentzMatrix &other)
EXEC_TARGET SymmLorentzMatrix & subtract (const SymmLorentzMatrix &other)
EXEC_TARGET SymmLorentzMatrix & mult (fptype s)
EXEC_TARGET SymmLorentzMatrix & div (fptype s)
EXEC_TARGET gpuLVec Contract (const gpuLVec &vec)
EXEC_TARGET LorentzMatrix Contract_1 (const SymmLorentzMatrix &M)
EXEC_TARGET fptype Contract_2 (const SymmLorentzMatrix &M)
EXEC_TARGET SymmLorentzMatrix & operator+= (const SymmLorentzMatrix &rhs)
EXEC_TARGET SymmLorentzMatrix & operator*= (fptype rhs)
EXEC_TARGET SymmLorentzMatrix & operator-= (const SymmLorentzMatrix &rhs)
EXEC_TARGET SymmLorentzMatrix & operator/= (fptype rhs)
EXEC_TARGET SymmLorentzMatrix & operator= (const SymmLorentzMatrix &other)
EXEC_TARGET SymmLorentzMatrix operator+ (const SymmLorentzMatrix &rhs) const
EXEC_TARGET SymmLorentzMatrix operator- (const SymmLorentzMatrix &rhs) const
EXEC_TARGET SymmLorentzMatrix operator* (fptype rhs) const
EXEC_TARGET SymmLorentzMatrix operator/ (fptype rhs) const
Public Member Functions inherited from LorentzMatrix
EXEC_TARGET const gpuLVec & v (int i) const
EXEC_TARGET LorentzMatrix ()
EXEC_TARGET LorentzMatrix (const gpuLVec p[4])
EXEC_TARGET LorentzMatrix (const LorentzMatrix &other)
EXEC_TARGET const gpuLVec & X () const
EXEC_TARGET const gpuLVec & Y () const
EXEC_TARGET const gpuLVec & Z () const
EXEC_TARGET const gpuLVec & E () const
EXEC_TARGET gpuLVec & X ()
EXEC_TARGET gpuLVec & Y ()
EXEC_TARGET gpuLVec & Z ()
EXEC_TARGET gpuLVec & E ()
EXEC_TARGET const gpuLVec & operator[] (int i) const
EXEC_TARGET gpuLVec & operator[] (int i)
EXEC_TARGET LorentzMatrix & add (const LorentzMatrix &other)
EXEC_TARGET LorentzMatrix & subtract (const LorentzMatrix &other)
EXEC_TARGET LorentzMatrix & mult (fptype s)
EXEC_TARGET LorentzMatrix & div (fptype s)
EXEC_TARGET LorentzMatrix & operator+= (const LorentzMatrix &rhs)
EXEC_TARGET LorentzMatrix & operator*= (fptype rhs)
EXEC_TARGET LorentzMatrix & operator-= (const LorentzMatrix &rhs)
EXEC_TARGET LorentzMatrix & operator/= (fptype rhs)
EXEC_TARGET LorentzMatrix & operator= (const LorentzMatrix &other)
EXEC_TARGET LorentzMatrix operator+ (const LorentzMatrix &rhs) const
EXEC_TARGET LorentzMatrix operator- (const LorentzMatrix &rhs) const
EXEC_TARGET LorentzMatrix operator* (fptype rhs) const
EXEC_TARGET LorentzMatrix operator/ (fptype rhs) const
Protected Member Functions
EXEC_TARGET bool symmetrize ()
EXEC_TARGET bool makeZero ()
Protected Member Functions inherited from LorentzMatrix
EXEC_TARGET bool makeZero ()
Additional Inherited Members
Protected Attributes inherited from LorentzMatrix
gpuLVec _v [4]
Detailed Description
Definition at line 281 of file SpinHelper.h.
Constructor & Destructor Documentation
SymmLorentzMatrix() [1/4]
EXEC_TARGET SymmLorentzMatrix::SymmLorentzMatrix () inline
Definition at line 320 of file SpinHelper.h.
 : LorentzMatrix() {}
SymmLorentzMatrix() [2/4]
EXEC_TARGET SymmLorentzMatrix::SymmLorentzMatrix (const gpuLVec p[4]) inline
Definition at line 321 of file SpinHelper.h.
         :  LorentzMatrix(p) {};
SymmLorentzMatrix() [3/4]
EXEC_TARGET SymmLorentzMatrix::SymmLorentzMatrix (const gpuLVec p) inline
Definition at line 324 of file SpinHelper.h.
{
         X().SetX(p.GetX() * p.GetX());
         X().SetY(p.GetX() * p.GetY());
         X().SetZ(p.GetX() * p.GetZ());
         X().SetE(p.GetX() * p.GetE());
         Y().SetX(p.GetY() * p.GetX());
         Y().SetY(p.GetY() * p.GetY());
         Y().SetZ(p.GetY() * p.GetZ());
         Y().SetE(p.GetY() * p.GetE());
         Z().SetX(p.GetZ() * p.GetX());
         Z().SetY(p.GetZ() * p.GetY());
         Z().SetZ(p.GetZ() * p.GetZ());
         Z().SetE(p.GetZ() * p.GetE());
         E().SetX(p.GetE() * p.GetX());
         E().SetY(p.GetE() * p.GetY());
         E().SetZ(p.GetE() * p.GetZ());
         E().SetE(p.GetE() * p.GetE());
     }
SymmLorentzMatrix() [4/4]
EXEC_TARGET SymmLorentzMatrix::SymmLorentzMatrix (const SymmLorentzMatrix & other) inline
Definition at line 345 of file SpinHelper.h.
         : LorentzMatrix(other) {}
Member Function Documentation
add()
EXEC_TARGET SymmLorentzMatrix& SymmLorentzMatrix::add (const SymmLorentzMatrix & other) inline
Definition at line 348 of file SpinHelper.h.
References LorentzMatrix::_v.
{
         for(int i=0; i < 4; i++)
             _v[i] += other._v[i];
         return *this;
     }
Contract()
EXEC_TARGET gpuLVec SymmLorentzMatrix::Contract (const gpuLVec & vec) inline
Definition at line 372 of file SpinHelper.h.
{
         // M^{mu nu} g_{nu alpha} v^{alpha}
         // M^{mu nu} v_{alpha}
         return vec.GetE()*E() - vec.GetX()*X() - vec.GetY()*Y() -vec.GetZ()*Z();
     }
Contract_1()
EXEC_TARGET LorentzMatrix SymmLorentzMatrix::Contract_1 (const SymmLorentzMatrix & M) inline
Definition at line 377 of file SpinHelper.h.
References LorentzMatrix::E(), LorentzMatrix::X(), LorentzMatrix::Y(), and LorentzMatrix::Z().
{
         // One pair of indices gets contracted. Since
         // both matrices are symmetric, it doesnt matter which.
         //
         // O^{mu alpha} g_{alpha beta} M^{beta nu} = R^{mu nu}
         // O^{mu alpha} M_{beta}^{nu}
         LorentzMatrix R;
         R.X() =  this->Contract(M.X());
         R.Y() =  this->Contract(M.Y());
         R.Z() =  this->Contract(M.Z());
         R.E() =  this->Contract(M.E()); // signs?
         return R;
     }
Contract_2()
EXEC_TARGET fptype SymmLorentzMatrix::Contract_2 (const SymmLorentzMatrix & M) inline
Definition at line 391 of file SpinHelper.h.
References LorentzMatrix::E(), LorentzMatrix::X(), LorentzMatrix::Y(), and LorentzMatrix::Z().
{
         // Both pairs of indices are contracted.
         // since the matrices are symmetric, it does
         // not matter which index from this with which form M.
         //
         // O^{mu alpha} g_{alpha beta} M^{beta nu} g_{mu nu}
         LorentzMatrix R(Contract_1(M));
         // R^{mu nu} R_{mu nu}
         fptype xx =  R.X().GetX();//Dot(R.X());
         fptype yy =  R.Y().GetY();//Dot(R.Y());
         fptype zz =  R.Z().GetZ();//Dot(R.Z());
         fptype tt =  R.E().GetE();//Dot(R.E());
         return tt - xx - yy - zz; // signs?
     }
div()
EXEC_TARGET SymmLorentzMatrix& SymmLorentzMatrix::div (fptype s) inline
Definition at line 366 of file SpinHelper.h.
{
         for(int i=0; i < 4; i++)
             _v[i] *= (1./s);
         return *this;
     }
gmunu()
EXEC_TARGET const SymmLorentzMatrix& SymmLorentzMatrix::gmunu ()
makeGmunu()
EXEC_TARGET void SymmLorentzMatrix::makeGmunu () inline
Definition at line 313 of file SpinHelper.h.
{
         X().SetXYZE(-1, 0, 0, 0);
         Y().SetXYZE(0, -1, 0, 0);
         Z().SetXYZE(0, 0, -1, 0);
         E().SetXYZE(0, 0, 0, 1);
     }
makeZero()
EXEC_TARGET bool SymmLorentzMatrix::makeZero () inline protected
Definition at line 305 of file SpinHelper.h.
{
         X().SetXYZE(0, 0, 0, 0);
         Y().SetXYZE(0, 0, 0, 0);
         Z().SetXYZE(0, 0, 0, 0);
         E().SetXYZE(0, 0, 0, 0);
         return true;
     }
mult()
EXEC_TARGET SymmLorentzMatrix& SymmLorentzMatrix::mult (fptype s) inline
Definition at line 360 of file SpinHelper.h.
{
         for(int i=0; i < 4; i++)
             _v[i] *= s;
         return *this;
     }
operator*()
EXEC_TARGET SymmLorentzMatrix SymmLorentzMatrix::operator* (fptype rhs) const inline
Definition at line 435 of file SpinHelper.h.
{
         SymmLorentzMatrix returnVal(*this);
         returnVal *= rhs;
         return returnVal;
     }
operator*=()
EXEC_TARGET SymmLorentzMatrix& SymmLorentzMatrix::operator*= (fptype rhs) inline
Definition at line 410 of file SpinHelper.h.
{
         return mult(rhs);
     }
operator+()
EXEC_TARGET SymmLorentzMatrix SymmLorentzMatrix::operator+ (const SymmLorentzMatrix & rhs) const inline
Definition at line 425 of file SpinHelper.h.
{
         SymmLorentzMatrix returnVal(*this);
         returnVal += rhs;
         return returnVal;
     }
operator+=()
EXEC_TARGET SymmLorentzMatrix& SymmLorentzMatrix::operator+= (const SymmLorentzMatrix & rhs) inline
Definition at line 407 of file SpinHelper.h.
{
         return add(rhs);
     }
operator-()
EXEC_TARGET SymmLorentzMatrix SymmLorentzMatrix::operator- (const SymmLorentzMatrix & rhs) const inline
Definition at line 430 of file SpinHelper.h.
{
         SymmLorentzMatrix returnVal(*this);
         returnVal -= rhs;
         return returnVal;
     }
operator-=()
EXEC_TARGET SymmLorentzMatrix& SymmLorentzMatrix::operator-= (const SymmLorentzMatrix & rhs) inline
Definition at line 413 of file SpinHelper.h.
{
         return subtract(rhs);
     }
operator/()
EXEC_TARGET SymmLorentzMatrix SymmLorentzMatrix::operator/ (fptype rhs) const inline
Definition at line 440 of file SpinHelper.h.
{
         SymmLorentzMatrix returnVal(*this);
         returnVal /= rhs;
         return returnVal;
     }
operator/=()
EXEC_TARGET SymmLorentzMatrix& SymmLorentzMatrix::operator/= (fptype rhs) inline
Definition at line 416 of file SpinHelper.h.
{
         return div(rhs);
     }
operator=()
EXEC_TARGET SymmLorentzMatrix& SymmLorentzMatrix::operator= (const SymmLorentzMatrix & other) inline
Definition at line 419 of file SpinHelper.h.
References LorentzMatrix::_v.
{
         for(int i=0; i<4; i++)
             _v[i] = other._v[i];
         return *this;
     }
subtract()
EXEC_TARGET SymmLorentzMatrix& SymmLorentzMatrix::subtract (const SymmLorentzMatrix & other) inline
Definition at line 354 of file SpinHelper.h.
References LorentzMatrix::_v.
{
         for(int i=0; i < 4; i++)
             _v[i] -= other._v[i];
         return *this;
     }
symmetrize()
EXEC_TARGET bool SymmLorentzMatrix::symmetrize () inline protected
Definition at line 286 of file SpinHelper.h.
{
         // clumsy but save
         X().SetY(Y().GetX());
         X().SetZ(Z().GetX());
         X().SetE(E().GetX());
         Y().SetX(X().GetY());
         Y().SetZ(Z().GetY());
         Y().SetE(E().GetY());
         Z().SetX(X().GetZ());
         Z().SetY(Y().GetZ());
         Z().SetE(E().GetZ());
         E().SetX(X().GetE());
         E().SetY(Y().GetE());
         E().SetZ(Z().GetE());
         return true;
     }
The documentation for this class was generated from the following file:
/home/travis/build/GooFit/GooFit/include/goofit/PDFs/SpinHelper.h