GooFit: GooFit::Variable Class Reference
GooFit::Variable Class Reference
#include <Variable.h>
Public Member Functions
Variable (const Variable &)=delete
Variable & operator= (const Variable &)=delete
Variable (Variable &&)=default
void operator= (const fptype &val)
Support var = 3.
Variable (std::string n, fptype v)
This is a constant varaible.
Variable (std::string n, fptype dn, fptype up)
This is an independent variable.
Variable (std::string n, fptype v, fptype dn, fptype up)
This is a normal variable, with value and upper/lower limits.
Variable (std::string n, fptype v, fptype e, fptype dn, fptype up)
This is a full varaible with error scale as well.
~Variable () override=default
fptype getError () const
Get the error.
void setError (fptype val)
Set the error.
fptype getUpperLimit () const
Get the upper limit.
void setUpperLimit (fptype val)
Set the upper limit.
fptype getLowerLimit () const
Get the lower limit.
void setLowerLimit (fptype val)
Set the lower limit.
bool getChanged () const
Check to see if the value has changed this iteration (always true the first time)
void setNumBins (size_t num)
Set the number of bins.
size_t getNumBins () const
Get the number of bins.
bool IsFixed () const
Check to see if this is a constant.
void setFixed (bool fix)
Set the fixedness of a variable.
void setChanged (bool val=true)
Check to see if this has been changed since last iteration.
fptype getBinSize () const
Get the bin size, (upper-lower) / bins.
void setBlind (fptype val)
Hides the number; the real value is the result minus this value. Cannot be retreived once set.
operator bool () const
Check to see if in range.
Public Member Functions inherited from GooFit::Indexable
Indexable (std::string n, fptype val=0)
Indexable (const Indexable &)=delete
Indexable & operator= (const Indexable &)=delete
Indexable (Indexable &&)=default
virtual ~Indexable ()=default
int getIndex () const
Get the GooFit index.
void setIndex (int value)
Set the GooFit index.
int getFitterIndex () const
Get the index from the fitter.
void setFitterIndex (int value)
Set the index (should be done by the fitter)
const std::string & getName () const
Get the name.
void setName (const std::string &val)
Set the name.
fptype getValue () const
Get the value.
void setValue (fptype val)
Set the value.
fptype operator= (const fptype &val)
Support var = 3.
operator fptype () const
Support fptype val = var.
Protected Attributes
fptype error
The error.
fptype upperlimit
The upper limit.
fptype lowerlimit
The lower limit.
fptype blind {0}
A blinding value to add (disabled at the moment, TODO)
size_t numbins {100}
The number of bins (mostly for BinnedData, or plotting help)
bool changed_ {true}
True if the value was unchanged since the last iteration.
bool fixed {false}
This "fixes" the variable (constant)
Protected Attributes inherited from GooFit::Indexable
std::string name
Support for less than, etc.
fptype value
The value of the variable.
int index {-1}
The goofit index, -1 if unset.
int fitter_index {-1}
The fitter index, -1 if unset.
Friends
std::ostream & operator<< (std::ostream &o, const Variable &var)
Nice print of Variable.
std::istream & operator>> (std::istream &o, Variable &var)
Allow Variable to be read in.
Detailed Description
Contains information about a parameter allowed to vary in MINUIT, or an observable passed to a data set. The index can refer either to cudaArray or to an event.
Definition at line 81 of file Variable.h.
Constructor & Destructor Documentation
Variable() [1/6]
GooFit::Variable::Variable (const Variable &) delete
Variable() [2/6]
GooFit::Variable::Variable (Variable &&) default
Variable() [3/6]
GooFit::Variable::Variable (std::string n, fptype v) inline
This is a constant varaible.
Definition at line 97 of file Variable.h.
         : Indexable(n, v)
         , error(0.002)
         , upperlimit(v + 0.01)
         , lowerlimit(v - 0.01)
         , fixed(true) {}
Variable() [4/6]
GooFit::Variable::Variable (std::string n, fptype dn, fptype up) inline
This is an independent variable.
Definition at line 105 of file Variable.h.
         : Indexable(n)
         , upperlimit(up)
         , lowerlimit(dn) {}
Variable() [5/6]
GooFit::Variable::Variable (std::string n, fptype v, fptype dn, fptype up) inline
This is a normal variable, with value and upper/lower limits.
Definition at line 111 of file Variable.h.
         : Indexable(n, v)
         , error(0.1 * (up - dn))
         , upperlimit(up)
         , lowerlimit(dn) {}
Variable() [6/6]
GooFit::Variable::Variable (std::string n, fptype v, fptype e, fptype dn, fptype up) inline
This is a full varaible with error scale as well.
Definition at line 118 of file Variable.h.
         : Indexable(n, v)
         , error(e)
         , upperlimit(up)
         , lowerlimit(dn) {}
~Variable()
GooFit::Variable::~Variable () override default
Member Function Documentation
getBinSize()
fptype GooFit::Variable::getBinSize () const inline
Get the bin size, (upper-lower) / bins.
Definition at line 160 of file Variable.h.
 { return (getUpperLimit() - getLowerLimit()) / getNumBins(); }
getChanged()
bool GooFit::Variable::getChanged () const inline
Check to see if the value has changed this iteration (always true the first time)
Definition at line 142 of file Variable.h.
Referenced by GooFit::PdfBase::parametersChanged().
 { return changed_; }
getError()
fptype GooFit::Variable::getError () const inline
Get the error.
Definition at line 127 of file Variable.h.
Referenced by GooFit::operator<<().
 { return error; }
getLowerLimit()
fptype GooFit::Variable::getLowerLimit () const inline
Get the lower limit.
Definition at line 137 of file Variable.h.
Referenced by GooFit::operator<<().
 { return lowerlimit; }
getNumBins()
size_t GooFit::Variable::getNumBins () const inline
Get the number of bins.
Definition at line 148 of file Variable.h.
 { return numbins; }
getUpperLimit()
fptype GooFit::Variable::getUpperLimit () const inline
Get the upper limit.
Definition at line 132 of file Variable.h.
Referenced by GooFit::operator<<().
 { return upperlimit; }
IsFixed()
bool GooFit::Variable::IsFixed () const inline
Check to see if this is a constant.
Definition at line 151 of file Variable.h.
 { return fixed; }
operator bool()
GooFit::Variable::operator bool () const inline
Check to see if in range.
Definition at line 166 of file Variable.h.
References GooFit::Indexable::getValue().
 { return getValue() <= getUpperLimit() && getValue() >= getLowerLimit(); }
operator=() [1/2]
Variable& GooFit::Variable::operator= (const Variable &) delete
operator=() [2/2]
void GooFit::Variable::operator= (const fptype & val) inline
Support var = 3.
Definition at line 94 of file Variable.h.
References GooFit::Indexable::setValue().
 { setValue(val); }
setBlind()
void GooFit::Variable::setBlind (fptype val) inline
Hides the number; the real value is the result minus this value. Cannot be retreived once set.
Definition at line 163 of file Variable.h.
 { blind = val; }
setChanged()
void GooFit::Variable::setChanged (bool val = true) inline
Check to see if this has been changed since last iteration.
Definition at line 157 of file Variable.h.
Referenced by GooFit::FCN::FCN().
 { changed_ = val; }
setError()
void GooFit::Variable::setError (fptype val) inline
Set the error.
Definition at line 129 of file Variable.h.
Referenced by GooFit::readFromFile().
 { error = val; }
setFixed()
void GooFit::Variable::setFixed (bool fix) inline
Set the fixedness of a variable.
Definition at line 154 of file Variable.h.
 { fixed = fix; }
setLowerLimit()
void GooFit::Variable::setLowerLimit (fptype val) inline
Set the lower limit.
Definition at line 139 of file Variable.h.
Referenced by GooFit::readFromFile().
 { lowerlimit = val; }
setNumBins()
void GooFit::Variable::setNumBins (size_t num) inline
Set the number of bins.
Definition at line 145 of file Variable.h.
Referenced by GooFit::readFromFile().
 { numbins = num; }
setUpperLimit()
void GooFit::Variable::setUpperLimit (fptype val) inline
Set the upper limit.
Definition at line 134 of file Variable.h.
Referenced by GooFit::readFromFile().
 { upperlimit = val; }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & o, const Variable & var) friend
Nice print of Variable.
Definition at line 24 of file Variable.cc.
{
     o << var.getName() << ": " << var.getValue() << " +/- " << var.getError();
     if(!var.fixed)
         o << " [" << var.getLowerLimit() << ", " << var.getUpperLimit() << "]";
     if(var.getIndex() >= 0)
         o << " GooFit index: " << var.getIndex();
     if(var.getFitterIndex() >= 0)
         o << " Fitter index: " << var.getFitterIndex();
     if(var.blind != 0)
         o << " Blinded";
     return o;
 }
operator>>
std::istream& operator>> (std::istream & o, GooFit::Variable & var) friend
Allow Variable to be read in.
Definition at line 38 of file Variable.cc.
 { return i >> var.value; }
Member Data Documentation
blind
fptype GooFit::Variable::blind {0} protected
A blinding value to add (disabled at the moment, TODO)
Definition at line 179 of file Variable.h.
Referenced by GooFit::operator<<().
changed_
bool GooFit::Variable::changed_ {true} protected
True if the value was unchanged since the last iteration.
Definition at line 185 of file Variable.h.
error
fptype GooFit::Variable::error protected
The error.
Definition at line 170 of file Variable.h.
fixed
bool GooFit::Variable::fixed {false} protected
This "fixes" the variable (constant)
Definition at line 188 of file Variable.h.
Referenced by GooFit::operator<<().
lowerlimit
fptype GooFit::Variable::lowerlimit protected
The lower limit.
Definition at line 176 of file Variable.h.
numbins
size_t GooFit::Variable::numbins {100} protected
The number of bins (mostly for BinnedData, or plotting help)
Definition at line 182 of file Variable.h.
upperlimit
fptype GooFit::Variable::upperlimit protected
The upper limit.
Definition at line 173 of file Variable.h.
The documentation for this class was generated from the following file:
/home/travis/build/GooFit/GooFit/include/goofit/Variable.h