GooFit: FitManager Class Reference
FitManager Class Reference
#include <FitManagerMinuit1.h>
Public Member Functions
FitManager (PdfBase *dat)
~FitManager ()
void setMaxCalls (double mxc)
void useHesseBefore (bool use=true)
void useHesse (bool use=true)
void useMinos (bool use=true)
void useImprove (bool use=true)
void setupMinuit ()
void runMigrad ()
void fit ()
TMinuit * getMinuitObject ()
void getMinuitValues () const
void getMinuitStatus (double &fmin, double &fedm, double &errdef, int &npari, int &nparx, int &istat) const
FitManager (PdfBase *dat)
virtual double Up () const
double operator() (const std::vector< double > &pars) const
ROOT::Minuit2::FunctionMinimum * fit ()
void getMinuitValues () const
FitManager (PdfBase *dat)
void fit ()
void getMinuitValues () const
Public Attributes
TMinuit * minuit
Protected Attributes
PdfBase * pdfPointer
ROOT::Minuit2::MnUserParameters * params
ROOT::Minuit2::MnMigrad * migrad
std::vector< Variable * > vars
int numPars
Friends
class FitManager
Detailed Description
Definition at line 11 of file FitManagerMinuit1.h.
Constructor & Destructor Documentation
FitManager() [1/3]
FitManager::FitManager (PdfBase * dat)
Definition at line 8 of file FitManagerMinuit1.cc.
     : minuit(0)
     , overrideCallLimit(-1)
     , _useHesseBefore(true)
     , _useHesse(true)
     , _useMinos(false)
     , _useImprove(false) {
     pdfPointer = dat;
     currGlue = this;
 }
~FitManager()
FitManager::~FitManager ()
Definition at line 19 of file FitManagerMinuit1.cc.
References minuit.
{
     if(minuit)
         delete minuit;
 }
FitManager() [2/3]
FitManager::FitManager (PdfBase * dat) inline
Definition at line 17 of file FitManagerMinuit2.h.
References pdfPointer.
{
         pdfPointer = dat;
     }
FitManager() [3/3]
FitManager::FitManager (PdfBase * dat)
Member Function Documentation
fit() [1/3]
void FitManager::fit ()
fit() [2/3]
ROOT::Minuit2::FunctionMinimum* FitManager::fit ()
fit() [3/3]
void FitManager::fit ()
Definition at line 54 of file FitManagerMinuit1.cc.
References runMigrad(), and setupMinuit().
Referenced by Up(), and useImprove().
                      {
     setupMinuit();
     runMigrad();
 }
getMinuitObject()
TMinuit* FitManager::getMinuitObject () inline
Definition at line 33 of file FitManagerMinuit1.h.
References getMinuitStatus(), getMinuitValues(), and minuit.
{
         return minuit;
     }
getMinuitStatus()
void FitManager::getMinuitStatus (double & fmin, double & fedm, double & errdef, int & npari, int & nparx, int & istat) const
Definition at line 94 of file FitManagerMinuit1.cc.
References minuit, and TMinuit::mnstat().
Referenced by getMinuitObject().
{
     minuit->mnstat(fmin, fedm, errdef, npari, nparx, istat);
     std::cout << "mnstat(fmin = " << fmin << ", fedm = " << fedm << ", errdef = " << errdef
               << ", npari = " << npari << ", nparx = " << nparx << ", istat = " << istat << ")" << std::endl;
 }
getMinuitValues() [1/3]
void FitManager::getMinuitValues () const
getMinuitValues() [2/3]
void FitManager::getMinuitValues () const
getMinuitValues() [3/3]
void FitManager::getMinuitValues () const
Definition at line 86 of file FitManagerMinuit1.cc.
References TMinuit::GetParameter(), minuit, and vars.
Referenced by FitFun(), getMinuitObject(), and Up().
{
     int counter = 0;
     for(std::vector<Variable*>::iterator i = vars.begin(); i != vars.end(); ++i) {
         minuit->GetParameter(counter++, (*i)->value, (*i)->error);
     }
 }
operator()()
double FitManager::operator() (const std::vector< double > & pars) const
Definition at line 30 of file FitManagerMinuit2.cc.
References PdfBase::calculateNLL(), PdfBase::copyParams(), PdfBase::getParameters(), host_callnumber, migrad, numPars, pdfPointer, and vars.
Referenced by Up().
{
     vector<double> gooPars; // Translates from Minuit indexing to GooFit indexing
     gooPars.resize(numPars);
     int counter = 0;
     for(std::vector<Variable*>::iterator i = vars.begin(); i != vars.end(); ++i) {
         gooPars[(*i)->index] = pars[counter++];
     }
     pdfPointer->copyParams(gooPars);
     double nll = pdfPointer->calculateNLL();
     host_callnumber++;
 #ifdef PRINTCALLS
     double edm = migrad->State().Edm();
     cout.precision(8);
     cout << "State at call "
          << host_callnumber << " : "
          << nll << " "
          << edm << " Pars: ";
     std::vector<Variable*> vars;
     pdfPointer->getParameters(vars);
     for(std::vector<Variable*>::iterator i = vars.begin(); i != vars.end(); ++i) {
         if(0 > (*i)->getIndex())
             continue;
         if((*i)->fixed)
             continue;
         cout << "(" << (*i)->name << " " << pars[(*i)->getIndex()] << ") "; // migrad->Value((*i)->getIndex()) << ") ";
     }
     cout << endl;
 #endif
     return nll;
 }
runMigrad()
void FitManager::runMigrad ()
Definition at line 59 of file FitManagerMinuit1.cc.
References host_callnumber, TMinuit::Migrad(), minuit, and TMinuit::mnexcm().
Referenced by fit(), and useImprove().
{
     assert(minuit);
     host_callnumber = 0;
     if(0 < overrideCallLimit) {
         std::cout << "Calling MIGRAD with call limit " << overrideCallLimit << std::endl;
         double plist[1];
         plist[0] = overrideCallLimit;
         int err = 0;
         if(_useHesseBefore)
             minuit->mnexcm("HESSE", plist, 1, err);
         minuit->mnexcm("MIGRAD", plist, 1, err);
         if(_useHesse)
             minuit->mnexcm("HESSE", plist, 1, err);
         if(_useMinos)
             minuit->mnexcm("MINOS", plist, 1, err);
         if(_useImprove)
             minuit->mnexcm("IMPROVE", plist, 1, err);
     } else
         minuit->Migrad();
 }
setMaxCalls()
void FitManager::setMaxCalls (double mxc) inline
Definition at line 15 of file FitManagerMinuit1.h.
{
         overrideCallLimit = mxc;
     }
setupMinuit()
void FitManager::setupMinuit ()
Definition at line 24 of file FitManagerMinuit1.cc.
References PdfBase::copyParams(), TMinuit::DefineParameter(), FitFun(), TMinuit::FixParameter(), PdfBase::getParameters(), minuit, numPars, TMinuit::SetFCN(), and vars.
Referenced by fit(), and useImprove().
{
     vars.clear();
     pdfPointer->getParameters(vars);
     numPars = vars.size();
     if(minuit)
         delete minuit;
     minuit = new TMinuit(numPars);
     int maxIndex = 0;
     int counter = 0;
     for(std::vector<Variable*>::iterator i = vars.begin(); i != vars.end(); ++i) {
         minuit->DefineParameter(counter, (*i)->name.c_str(), (*i)->value, (*i)->error, (*i)->lowerlimit, (*i)->upperlimit);
         if((*i)->fixed)
             minuit->FixParameter(counter);
         counter++;
         if(maxIndex < (*i)->getIndex())
             maxIndex = (*i)->getIndex();
     }
     numPars = maxIndex+1;
     pdfPointer->copyParams();
     minuit->SetFCN(FitFun);
 }
Up()
virtual double FitManager::Up () const inline virtual
Definition at line 20 of file FitManagerMinuit2.h.
References fit(), getMinuitValues(), and operator()().
{
         return 1.0;
     }
useHesse()
void FitManager::useHesse (bool use = true) inline
Definition at line 21 of file FitManagerMinuit1.h.
{
         _useHesse = use;
     }
useHesseBefore()
void FitManager::useHesseBefore (bool use = true) inline
Definition at line 18 of file FitManagerMinuit1.h.
{
         _useHesseBefore = use;
     }
useImprove()
void FitManager::useImprove (bool use = true) inline
Definition at line 27 of file FitManagerMinuit1.h.
References fit(), runMigrad(), and setupMinuit().
{
         _useImprove = use;
     }
useMinos()
void FitManager::useMinos (bool use = true) inline
Definition at line 24 of file FitManagerMinuit1.h.
{
         _useMinos = use;
     }
Friends And Related Function Documentation
FitManager
FitManager friend
Definition at line 15 of file FitManagerMinuit2.h.
Member Data Documentation
migrad
ROOT::Minuit2::MnMigrad* FitManager::migrad protected
Definition at line 30 of file FitManagerMinuit2.h.
Referenced by operator()().
minuit
TMinuit* FitManager::minuit
Definition at line 38 of file FitManagerMinuit1.h.
Referenced by getMinuitObject(), getMinuitStatus(), getMinuitValues(), runMigrad(), setupMinuit(), and ~FitManager().
numPars
int FitManager::numPars protected
Definition at line 33 of file FitManagerMinuit2.h.
Referenced by FitFun(), operator()(), and setupMinuit().
params
ROOT::Minuit2::MnUserParameters* FitManager::params protected
Definition at line 29 of file FitManagerMinuit2.h.
pdfPointer
PdfBase* FitManager::pdfPointer protected
Definition at line 28 of file FitManagerMinuit2.h.
Referenced by FitManager(), and operator()().
vars
std::vector<Variable*> FitManager::vars protected
Definition at line 32 of file FitManagerMinuit2.h.
Referenced by FitFun(), getMinuitValues(), operator()(), and setupMinuit().
The documentation for this class was generated from the following files:
/home/travis/build/GooFit/GooFit/include/goofit/FitManagerMinuit1.h
/home/travis/build/GooFit/GooFit/include/goofit/FitManagerMinuit2.h
/home/travis/build/GooFit/GooFit/include/goofit/FitManagerMinuit3.h
/home/travis/build/GooFit/GooFit/src/goofit/FitManagerMinuit1.cc
/home/travis/build/GooFit/GooFit/src/goofit/FitManagerMinuit2.cc
/home/travis/build/GooFit/GooFit/src/goofit/FitManagerMinuit3.cc