GooFit: SpecialIncoherentIntegrator Class Reference
SpecialIncoherentIntegrator Class Reference
#include <IncoherentSumThrustFunctor.hh>
Public Member Functions
SpecialIncoherentIntegrator (int pIdx, unsigned int ri)
__device__ fptype operator() (thrust::tuple< int, fptype * > t) const
Detailed Description
Definition at line 53 of file IncoherentSumThrustFunctor.hh.
Constructor & Destructor Documentation
SpecialIncoherentIntegrator::SpecialIncoherentIntegrator (int pIdx, unsigned int ri)
Definition at line 226 of file IncoherentSumThrustFunctor.cu.
Member Function Documentation
__device__ fptype SpecialIncoherentIntegrator::operator() (thrust::tuple< int, fptype * > t) const
Definition at line 231 of file IncoherentSumThrustFunctor.cu.
References devcomplex< T >::abs2(), callFunction(), cudaArray, FLOOR, getResonanceAmplitude(), paramIndices, and parIndexFromResIndex_incoherent().
The documentation for this class was generated from the following files:
FPOINTER/IncoherentSumThrustFunctor.hh
FPOINTER/IncoherentSumThrustFunctor.cu