GooFit: BinnedDataSet Class Reference
BinnedDataSet Class Reference
#include <BinnedDataSet.h>
Public Member Functions
BinnedDataSet (Variable *var, string n="")
BinnedDataSet (std::vector< Variable *> &vars, string n="")
BinnedDataSet (std::set< Variable *> &vars, string n="")
~BinnedDataSet ()
virtual void addEventVector (std::vector< fptype > &vals, fptype weight=1)
fptype getBinContent (unsigned int bin) const
fptype getBinCenter (Variable *var, unsigned int bin) const
unsigned int getBinNumber () const
fptype getBinVolume (unsigned int bin) const
fptype getBinError (unsigned int bin) const
unsigned int getNumBins () const
fptype getNumEvents () const
void setBinContent (unsigned int bin, fptype value)
void setBinError (unsigned int bin, fptype error)
Public Member Functions inherited from DataSet
DataSet (Variable *var, string n="")
DataSet (std::vector< Variable *> &vars, string n="")
DataSet (std::set< Variable *> &vars, string n="")
~DataSet ()
void addEvent ()
void addEvent (fptype val)
void addWeightedEvent (fptype weight)
varConstIt varsBegin () const
varConstIt varsEnd () const
void getVariables (std::vector< Variable *> &vars)
varConstRIt varsRBegin () const
varConstRIt varsREnd () const
int numVariables () const
int numEvents () const
string getName () const
Additional Inherited Members
Protected Member Functions inherited from DataSet
vector< fptype > getCurrentValues () const
unsigned int indexOfVariable (Variable *var) const
Protected Attributes inherited from DataSet
int numEventsAdded
Detailed Description
Definition at line 6 of file BinnedDataSet.h.
Constructor & Destructor Documentation
BinnedDataSet() [1/3]
BinnedDataSet::BinnedDataSet (Variable * var, string n = "")
Definition at line 4 of file BinnedDataSet.cc.
References getNumBins().
     : DataSet(var, n) {
     cacheNumBins();
     binvalues.resize(getNumBins());
 }
BinnedDataSet() [2/3]
BinnedDataSet::BinnedDataSet (std::vector< Variable *> & vars, string n = "")
Definition at line 10 of file BinnedDataSet.cc.
References getNumBins().
     : DataSet(vars, n) {
     cacheNumBins();
     binvalues.resize(getNumBins());
 }
BinnedDataSet() [3/3]
BinnedDataSet::BinnedDataSet (std::set< Variable *> & vars, string n = "")
Definition at line 16 of file BinnedDataSet.cc.
References getNumBins().
     : DataSet(vars, n) {
     cacheNumBins();
     binvalues.resize(getNumBins());
 }
~BinnedDataSet()
BinnedDataSet::~BinnedDataSet ()
Definition at line 22 of file BinnedDataSet.cc.
 {}
Member Function Documentation
addEventVector()
void BinnedDataSet::addEventVector (std::vector< fptype > & vals, fptype weight = 1) virtual
Implements DataSet.
Definition at line 24 of file BinnedDataSet.cc.
References DataSet::numEventsAdded, DataSet::varsBegin(), and DataSet::varsEnd().
{
     numEventsAdded++;
     std::vector<unsigned int> localBins = convertValuesToBins(vals);
     unsigned int bin = localToGlobal(localBins);
     if(bin >= binvalues.size()) {
         std::cout << "Bad bin number "
                   << bin << " / "
                   << binvalues.size()
                   << " from input values ";
         for(unsigned int i = 0; i < vals.size(); ++i) {
             std::cout << vals[i] << " ";
         }
         std::cout << "\n";
         assert(bin < binvalues.size());
     }
     binvalues[bin] += weight;
 }
getBinCenter()
fptype BinnedDataSet::getBinCenter (Variable * var, unsigned int bin) const
Definition at line 85 of file BinnedDataSet.cc.
References DataSet::indexOfVariable(), Variable::lowerlimit, and Variable::upperlimit.
Referenced by getBinContent().
{
     std::vector<unsigned int> locals;
     globalToLocal(locals, bin);
     unsigned int varIndex = indexOfVariable(var);
     unsigned int localBin = locals[varIndex];
     fptype ret = var->upperlimit;
     ret       -= var->lowerlimit;
     ret       /= cachedNumBins.at(var);
     ret       *= (localBin + 0.5);
     ret       += var->lowerlimit;
     return ret;
 }
getBinContent()
fptype BinnedDataSet::getBinContent (unsigned int bin) const inline
Definition at line 17 of file BinnedDataSet.h.
References getBinCenter(), getBinError(), getBinNumber(), getBinVolume(), getNumBins(), and getNumEvents().
{
         return binvalues[bin];
     }
getBinError()
fptype BinnedDataSet::getBinError (unsigned int bin) const
Definition at line 111 of file BinnedDataSet.cc.
References SQRT.
Referenced by getBinContent().
{
     if(0 == binerrors.size())
         return SQRT(binvalues[bin]);
     assert(bin < binerrors.size());
     return binerrors[bin];
 }
getBinNumber()
unsigned int BinnedDataSet::getBinNumber () const
Definition at line 52 of file BinnedDataSet.cc.
References DataSet::getCurrentValues(), DataSet::indexOfVariable(), DataSet::varsBegin(), and DataSet::varsEnd().
Referenced by getBinContent().
{
     vector<fptype> vals = getCurrentValues();
     vector<unsigned int> locals = convertValuesToBins(vals);
     return localToGlobal(locals);
 }
getBinVolume()
fptype BinnedDataSet::getBinVolume (unsigned int bin) const
Definition at line 98 of file BinnedDataSet.cc.
References DataSet::varsBegin(), and DataSet::varsEnd().
Referenced by getBinContent().
{
     fptype ret = 1;
     for(varConstIt v = varsBegin(); v != varsEnd(); ++v) {
         fptype step = (*v)->upperlimit;
         step       -= (*v)->lowerlimit;
         step       /= cachedNumBins.at(*v);
         ret *= step;
     }
     return ret;
 }
getNumBins()
unsigned int BinnedDataSet::getNumBins () const
Definition at line 127 of file BinnedDataSet.cc.
References DataSet::varsBegin(), and DataSet::varsEnd().
Referenced by BinnedDataSet(), and getBinContent().
{
     unsigned int ret = 1;
     for(varConstIt v = varsBegin(); v != varsEnd(); ++v) {
         ret *= cachedNumBins.at(*v);
     }
     return ret;
 }
getNumEvents()
fptype BinnedDataSet::getNumEvents () const
Definition at line 137 of file BinnedDataSet.cc.
References DataSet::varsBegin(), and DataSet::varsEnd().
Referenced by getBinContent().
{
     fptype ret = 0;
     for(std::vector<fptype>::const_iterator bin = binvalues.begin(); bin != binvalues.end(); ++bin)
         ret += (*bin);
     return ret;
 }
setBinContent()
void BinnedDataSet::setBinContent (unsigned int bin, fptype value) inline
Definition at line 27 of file BinnedDataSet.h.
References setBinError().
{
         binvalues[bin] = value;
     }
setBinError()
void BinnedDataSet::setBinError (unsigned int bin, fptype error)
Definition at line 119 of file BinnedDataSet.cc.
Referenced by setBinContent().
{
     if(0 == binerrors.size())
         binerrors.resize(binvalues.size());
     assert(bin < binerrors.size());
     binerrors[bin] = error;
 }
The documentation for this class was generated from the following files:
/home/travis/build/GooFit/GooFit/include/goofit/BinnedDataSet.h
/home/travis/build/GooFit/GooFit/src/goofit/BinnedDataSet.cc