GooFit: GooFit::Uncertain Class Reference
GooFit::Uncertain Class Reference
#include <Uncertain.h>
Public Member Functions
Uncertain (fptype value, fptype uncertainty=0)
Uncertain (const Variable &val)
fptype get_value () const
fptype get_uncertainty () const
fptype get_relative_uncertainty () const
bool operator== (const Uncertain &other) const
bool operator!= (const Uncertain &other) const
Uncertain operator+ (const Uncertain &other) const
Uncertain operator- (const Uncertain &other) const
Uncertain operator* (const Uncertain &other) const
Uncertain operator* (fptype other) const
Allow int and float multiplies.
Uncertain operator/ (const Uncertain &other) const
Uncertain operator/ (const fptype &other) const
Detailed Description
Definition at line 36 of file Uncertain.h.
Constructor & Destructor Documentation
Uncertain() [1/2]
GooFit::Uncertain::Uncertain (fptype value, fptype uncertainty = 0) inline
Definition at line 43 of file Uncertain.h.
Referenced by operator*(), GooFit::operator*(), operator+(), operator-(), and operator/().
         : m_value(value)
         , m_uncertainty(uncertainty) {
         if(m_uncertainty < 0)
             throw std::invalid_argument("Uncertainty can not be negative.");
     }
Uncertain() [2/2]
GooFit::Uncertain::Uncertain (const Variable & val) inline
Definition at line 50 of file Uncertain.h.
         : Uncertain(val.getValue(), val.getError()) {}
Member Function Documentation
get_relative_uncertainty()
fptype GooFit::Uncertain::get_relative_uncertainty () const inline
Definition at line 58 of file Uncertain.h.
Referenced by operator*(), and operator/().
 { return m_uncertainty / m_value; }
get_uncertainty()
fptype GooFit::Uncertain::get_uncertainty () const inline
Definition at line 56 of file Uncertain.h.
Referenced by GooFit::format_arg(), GooFit::operator*(), and GooFit::operator<<().
 { return m_uncertainty; }
get_value()
fptype GooFit::Uncertain::get_value () const inline
Definition at line 54 of file Uncertain.h.
Referenced by GooFit::format_arg(), GooFit::operator*(), and GooFit::operator<<().
 { return m_value; }
operator!=()
bool GooFit::Uncertain::operator!= (const Uncertain & other) const inline
Definition at line 65 of file Uncertain.h.
References operator==().
 { return !operator==(other); }
operator*() [1/2]
Uncertain GooFit::Uncertain::operator* (const Uncertain & other) const inline
Definition at line 76 of file Uncertain.h.
References get_relative_uncertainty(), and Uncertain().
{
         return Uncertain(m_value * other.m_value, get_relative_uncertainty() + other.get_relative_uncertainty());
     }
operator*() [2/2]
Uncertain GooFit::Uncertain::operator* (fptype other) const inline
Allow int and float multiplies.
Definition at line 81 of file Uncertain.h.
References Uncertain().
 { return Uncertain(m_value * other, m_uncertainty * other); }
operator+()
Uncertain GooFit::Uncertain::operator+ (const Uncertain & other) const inline
Definition at line 68 of file Uncertain.h.
References Uncertain().
{
         return Uncertain(m_value + other.m_value, m_uncertainty + other.m_uncertainty);
     }
operator-()
Uncertain GooFit::Uncertain::operator- (const Uncertain & other) const inline
Definition at line 72 of file Uncertain.h.
References Uncertain().
{
         return Uncertain(m_value - other.m_value, m_uncertainty + other.m_uncertainty);
     }
operator/() [1/2]
Uncertain GooFit::Uncertain::operator/ (const Uncertain & other) const inline
Definition at line 83 of file Uncertain.h.
References get_relative_uncertainty(), and Uncertain().
{
         return Uncertain(m_value / other.m_value, get_relative_uncertainty() + other.get_relative_uncertainty());
     }
operator/() [2/2]
Uncertain GooFit::Uncertain::operator/ (const fptype & other) const inline
Definition at line 87 of file Uncertain.h.
References Uncertain().
 { return Uncertain(m_value / other, m_uncertainty / other); }
operator==()
bool GooFit::Uncertain::operator== (const Uncertain & other) const inline
Definition at line 61 of file Uncertain.h.
Referenced by operator!=().
{
         return (m_value == other.m_value) && (m_uncertainty == other.m_uncertainty);
     }
The documentation for this class was generated from the following file:
/home/travis/build/GooFit/GooFit/include/goofit/detail/Uncertain.h