GooFit: SpecialWaveCalculator Class Reference
SpecialWaveCalculator Class Reference
#include <TddpThrustFunctor.hh>
Public Member Functions
SpecialWaveCalculator (int pIdx, unsigned int res_idx)
__device__ WaveHolder operator() (thrust::tuple< int, fptype *, int > t) const
Detailed Description
Definition at line 151 of file TddpThrustFunctor.hh.
Constructor & Destructor Documentation
SpecialWaveCalculator::SpecialWaveCalculator (int pIdx, unsigned int res_idx)
Definition at line 568 of file TddpThrustFunctor.cu.
Member Function Documentation
__device__ WaveHolder SpecialWaveCalculator::operator() (thrust::tuple< int, fptype *, int > t) const
Definition at line 573 of file TddpThrustFunctor.cu.
References cudaArray, functorConstants, getResonanceAmplitude(), devcomplex< T >::imag, inDalitz(), paramIndices, parIndexFromResIndex(), and devcomplex< T >::real.
The documentation for this class was generated from the following files:
FPOINTER/TddpThrustFunctor.hh
FPOINTER/TddpThrustFunctor.cu