GooFit: GooFit::PdfBase Class Reference
GooFit::PdfBase Class Reference abstract
#include <PdfBase.h>
Public Types
enum Specials { ForceSeparateNorm = 1, ForceCommonNorm = 2 }
Public Member Functions
PdfBase (Variable *x, std::string n)
virtual ~PdfBase ()=default
virtual __host__ double calculateNLL () const =0
virtual __host__ fptype normalize () const =0
__host__ void initializeIndices (std::vector< unsigned int > pindices)
__host__ void addSpecialMask (int m)
__host__ void copyParams (const std::vector< double > &pars) const
__host__ void copyParams ()
__host__ void copyNormFactors () const
__host__ void generateNormRange ()
__host__ std::string getName () const
virtual __host__ std::vector< Variable * > getObservables () const
virtual __host__ std::vector< Variable * > getParameters () const
__host__ Variable * getParameterByName (std::string n) const
__host__ int getSpecialMask () const
__host__ void setData (DataSet *data)
__host__ DataSet * getData ()
virtual __host__ void setFitControl (FitControl *const fc, bool takeOwnerShip=true)=0
virtual __host__ bool hasAnalyticIntegral () const
__host__ ROOT::Minuit2::FunctionMinimum fitTo (DataSet *data, int verbosity=3)
RooFit style fitting shortcut.
__host__ unsigned int getFunctionIndex () const
__host__ unsigned int getParameterIndex () const
__host__ unsigned int registerParameter (Variable *var)
__host__ unsigned int registerConstants (unsigned int amount)
virtual __host__ void recursiveSetNormalisation (fptype norm=1) const
__host__ void unregisterParameter (Variable *var)
__host__ void registerObservable (Variable *obs)
__host__ void setIntegrationFineness (int i)
__host__ void printProfileInfo (bool topLevel=true)
__host__ bool parametersChanged () const
__host__ void checkInitStatus (std::vector< std::string > &unInited) const
void clearCurrentFit ()
__host__ void SigGenSetIndices ()
Protected Member Functions
void setNumPerTask (PdfBase *p, const int &c)
This needs to be set before a call to setData.
Protected Attributes
DataSet * data_ = nullptr
fptype numEvents {0}
unsigned int numEntries {0}
fptype * normRanges
unsigned int parameters {0}
unsigned int cIndex {1}
std::vector< Variable * > observables
std::vector< Variable * > parameterList
FitControl * fitControl {nullptr}
std::vector< PdfBase * > components
int integrationBins {-1}
int specialMask {0}
bool properlyInitialised {true}
unsigned int functionIdx
int m_iEventsPerTask
Detailed Description
Definition at line 51 of file PdfBase.h.
Member Enumeration Documentation
Specials
enum GooFit::PdfBase::Specials
Enumerator
ForceSeparateNorm
ForceCommonNorm
Definition at line 56 of file PdfBase.h.
 { ForceSeparateNorm = 1, ForceCommonNorm = 2 };
Constructor & Destructor Documentation
PdfBase()
GooFit::PdfBase::PdfBase (Variable * x, std::string n)
Definition at line 30 of file PdfBase.cc.
References registerObservable().
     : name(std::move(n)) { // Special-case PDFs should set to false.
     if(x)
         registerObservable(x);
 }
~PdfBase()
virtual GooFit::PdfBase::~PdfBase () virtual default
Member Function Documentation
addSpecialMask()
__host__ void GooFit::PdfBase::addSpecialMask (int m) inline
Definition at line 62 of file PdfBase.h.
 { specialMask |= m; }
calculateNLL()
virtual __host__ double GooFit::PdfBase::calculateNLL () const pure virtual
Implemented in GooFit::GooPdf.
Referenced by GooFit::Minuit1::Eval(), and GooFit::FCN::operator()().
checkInitStatus()
__host__ void GooFit::PdfBase::checkInitStatus (std::vector< std::string > & unInited) const
Definition at line 36 of file PdfBase.cc.
References components, getName(), and properlyInitialised.
{
     if(!properlyInitialised)
         unInited.push_back(getName());
     for(auto component : components) {
         component->checkInitStatus(unInited);
     }
 }
clearCurrentFit()
void GooFit::PdfBase::clearCurrentFit ()
copyNormFactors()
__host__ void GooFit::PdfBase::copyNormFactors () const
copyParams() [1/2]
__host__ void GooFit::PdfBase::copyParams (const std::vector< double > & pars) const
Referenced by GooFit::Minuit1::Eval(), GooFit::Params::from_minuit_vector(), and GooFit::Minuit1::Minuit1().
copyParams() [2/2]
__host__ void GooFit::PdfBase::copyParams ()
fitTo()
__host__ ROOT::Minuit2::FunctionMinimum GooFit::PdfBase::fitTo (DataSet * data, int verbosity = 3)
RooFit style fitting shortcut.
Definition at line 187 of file PdfBase.cc.
References setData(), and GooFit::FitManagerMinuit2::setVerbosity().
{
     setData(data);
     FitManager fitter{this};
     fitter.setVerbosity(verbosity);
     return fitter.fit();
 }
generateNormRange()
__host__ void GooFit::PdfBase::generateNormRange ()
Referenced by setIntegrationFineness().
getData()
__host__ DataSet* GooFit::PdfBase::getData ()
getFunctionIndex()
__host__ unsigned int GooFit::PdfBase::getFunctionIndex () const inline
Definition at line 83 of file PdfBase.h.
 { return functionIdx; }
getName()
__host__ std::string GooFit::PdfBase::getName () const inline
Definition at line 67 of file PdfBase.h.
Referenced by GooFit::abort(), checkInitStatus(), GooFit::Lineshape::operator==(), GooFit::SpinFactor::operator==(), registerObservable(), registerParameter(), and unregisterParameter().
 { return name; }
getObservables()
__host__ std::vector< Variable * > GooFit::PdfBase::getObservables () const virtual
Definition at line 139 of file PdfBase.cc.
References components, and observables.
{
     std::vector<Variable *> ret = observables;
     for(const PdfBase *comp : components) {
         for(Variable *sub_comp : comp->getObservables())
             if(std::find(std::begin(ret), std::end(ret), sub_comp) == std::end(ret))
                 ret.push_back(sub_comp);
     }
     return ret;
 }
getParameterByName()
__host__ Variable * GooFit::PdfBase::getParameterByName (std::string n) const
Definition at line 123 of file PdfBase.cc.
References components, and parameterList.
{
     for(Variable *p : parameterList) {
         if(p->getName() == n)
             return p;
     }
     for(auto component : components) {
         Variable *cand = component->getParameterByName(n);
         if(cand)
             return cand;
     }
     return nullptr;
 }
getParameterIndex()
__host__ unsigned int GooFit::PdfBase::getParameterIndex () const inline
Definition at line 84 of file PdfBase.h.
 { return parameters; }
getParameters()
__host__ std::vector< Variable * > GooFit::PdfBase::getParameters () const virtual
Definition at line 111 of file PdfBase.cc.
References components, and parameterList.
Referenced by GooFit::abort(), GooFit::Params::Params(), GooFit::readFromFile(), and GooFit::writeToFile().
{
     std::vector<Variable *> ret = parameterList;
     for(const PdfBase *comp : components) {
         for(Variable *sub_comp : comp->getParameters())
             if(std::find(std::begin(ret), std::end(ret), sub_comp) == std::end(ret))
                 ret.push_back(sub_comp);
     }
     return ret;
 }
getSpecialMask()
__host__ int GooFit::PdfBase::getSpecialMask () const inline
Definition at line 72 of file PdfBase.h.
 { return specialMask; }
hasAnalyticIntegral()
virtual __host__ bool GooFit::PdfBase::hasAnalyticIntegral () const inline virtual
Reimplemented in GooFit::GooPdf, GooFit::EventWeightedAddPdf, GooFit::ExpPdf, GooFit::AddPdf, GooFit::GaussianPdf, GooFit::JohnsonSUPdf, GooFit::StepPdf, GooFit::ProdPdf, GooFit::ArgusPdf, GooFit::KinLimitBWPdf, and GooFit::ScaledGaussianPdf.
Definition at line 78 of file PdfBase.h.
 { return false; }
initializeIndices()
__host__ void GooFit::PdfBase::initializeIndices (std::vector< unsigned int > pindices)
normalize()
virtual __host__ fptype GooFit::PdfBase::normalize () const pure virtual
Implemented in GooFit::TddpPdf, GooFit::GooPdf, GooFit::DPPdf, GooFit::TDDP4, GooFit::IncoherentSumPdf, GooFit::DalitzPlotPdf, GooFit::CompositePdf, GooFit::SmoothHistogramPdf, GooFit::EventWeightedAddPdf, GooFit::ConvolutionPdf, GooFit::AddPdf, GooFit::MappedPdf, and GooFit::ProdPdf.
parametersChanged()
__host__ bool GooFit::PdfBase::parametersChanged () const
Definition at line 176 of file PdfBase.cc.
References GooFit::Variable::getChanged(), and parameterList.
{
     return std::any_of(std::begin(parameterList), std::end(parameterList), [](Variable *v) { return v->getChanged(); });
 }
printProfileInfo()
__host__ void GooFit::PdfBase::printProfileInfo (bool topLevel = true)
recursiveSetNormalisation()
__host__ void GooFit::PdfBase::recursiveSetNormalisation (fptype norm = 1) const virtual
Definition at line 45 of file PdfBase.cc.
References components, and parameters.
{
     host_normalisation[parameters] = norm;
     for(auto component : components) {
         component->recursiveSetNormalisation(norm);
     }
 }
registerConstants()
__host__ unsigned int GooFit::PdfBase::registerConstants (unsigned int amount)
Definition at line 151 of file PdfBase.cc.
References cIndex, GooFit::maxParams, and GooFit::totalConstants.
{
     if(totalConstants + amount >= maxParams)
         throw GooFit::GeneralError(
             "totalConstants {} + amount {} can not be more than {}", totalConstants, amount, maxParams);
     cIndex = totalConstants;
     totalConstants += amount;
     return cIndex;
 }
registerObservable()
void GooFit::PdfBase::registerObservable (Variable * obs)
Definition at line 160 of file PdfBase.cc.
References GooFit::Indexable::getName(), getName(), GOOFIT_DEBUG, and observables.
Referenced by PdfBase().
{
     if(!obs)
         return;
     if(find(observables.begin(), observables.end(), obs) != observables.end())
         return;
     GOOFIT_DEBUG("{}: Registering o:{} for {}", getName(), observables.size(), obs->getName());
     observables.push_back(obs);
 }
registerParameter()
__host__ unsigned int GooFit::PdfBase::registerParameter (Variable * var)
Definition at line 53 of file PdfBase.cc.
References GooFit::Indexable::getIndex(), GooFit::Indexable::getName(), getName(), GOOFIT_DEBUG, parameterList, and GooFit::Indexable::setIndex().
{
     if(var == nullptr)
         throw GooFit::GeneralError("{}: Can not register a nullptr", getName());
     if(std::find(parameterList.begin(), parameterList.end(), var) != parameterList.end())
         return static_cast<unsigned int>(var->getIndex());
     parameterList.push_back(var);
     variableRegistry[var].insert(this);
     if(0 > var->getIndex()) {
         unsigned int unusedIndex = 0;
         while(true) {
             bool canUse = true;
             for(auto &p : variableRegistry) {
                 if(unusedIndex != p.first->getIndex())
                     continue;
                 canUse = false;
                 break;
             }
             if(canUse)
                 break;
             unusedIndex++;
         }
         GOOFIT_DEBUG("{}: Registering p:{} for {}", getName(), unusedIndex, var->getName());
         var->setIndex(unusedIndex);
     }
     return static_cast<unsigned int>(var->getIndex());
 }
setData()
__host__ void GooFit::PdfBase::setData (DataSet * data)
Referenced by fitTo().
setFitControl()
virtual __host__ void GooFit::PdfBase::setFitControl (FitControl *const fc, bool takeOwnerShip = true) pure virtual
Implemented in GooFit::GooPdf.
setIntegrationFineness()
__host__ void GooFit::PdfBase::setIntegrationFineness (int i)
Definition at line 171 of file PdfBase.cc.
References generateNormRange(), and integrationBins.
{
     integrationBins = i;
     generateNormRange();
 }
setNumPerTask()
__host__ void GooFit::PdfBase::setNumPerTask (PdfBase * p, const int & c) protected
This needs to be set before a call to setData.
Definition at line 180 of file PdfBase.cc.
References m_iEventsPerTask.
{
     if(!p)
         return;
     m_iEventsPerTask = c;
 }
SigGenSetIndices()
__host__ void GooFit::PdfBase::SigGenSetIndices () inline
Definition at line 97 of file PdfBase.h.
 { setIndices(); }
unregisterParameter()
__host__ void GooFit::PdfBase::unregisterParameter (Variable * var)
Definition at line 90 of file PdfBase.cc.
References components, GooFit::Indexable::getName(), getName(), GOOFIT_DEBUG, parameterList, and GooFit::Indexable::setIndex().
{
     if(var == nullptr)
         return;
     GOOFIT_DEBUG("{}: Removing {}", getName(), var->getName());
     auto pos = std::find(parameterList.begin(), parameterList.end(), var);
     if(pos != parameterList.end())
         parameterList.erase(pos);
     variableRegistry[var].erase(this);
     if(0 == variableRegistry[var].size())
         var->setIndex(-1);
     for(PdfBase *comp : components) {
         comp->unregisterParameter(var);
     }
 }
Member Data Documentation
cIndex
unsigned int GooFit::PdfBase::cIndex {1} protected
Definition at line 106 of file PdfBase.h.
Referenced by registerConstants().
components
std::vector<PdfBase *> GooFit::PdfBase::components protected
Definition at line 110 of file PdfBase.h.
Referenced by checkInitStatus(), getObservables(), getParameterByName(), getParameters(), recursiveSetNormalisation(), and unregisterParameter().
data_
DataSet* GooFit::PdfBase::data_ = nullptr protected
Definition at line 100 of file PdfBase.h.
fitControl
FitControl* GooFit::PdfBase::fitControl {nullptr} protected
Definition at line 109 of file PdfBase.h.
functionIdx
unsigned int GooFit::PdfBase::functionIdx protected
Definition at line 115 of file PdfBase.h.
integrationBins
int GooFit::PdfBase::integrationBins {-1} protected
Definition at line 111 of file PdfBase.h.
Referenced by setIntegrationFineness().
m_iEventsPerTask
int GooFit::PdfBase::m_iEventsPerTask protected
Definition at line 117 of file PdfBase.h.
Referenced by setNumPerTask().
normRanges
fptype* GooFit::PdfBase::normRanges protected
Initial value:
{
        nullptr}
Definition at line 103 of file PdfBase.h.
numEntries
unsigned int GooFit::PdfBase::numEntries {0} protected
Definition at line 102 of file PdfBase.h.
numEvents
fptype GooFit::PdfBase::numEvents {0} protected
Definition at line 101 of file PdfBase.h.
Referenced by GooFit::DPPdf::setGenerationOffset(), and GooFit::TDDP4::setMaxWeight().
observables
std::vector<Variable *> GooFit::PdfBase::observables protected
Definition at line 107 of file PdfBase.h.
Referenced by getObservables(), and registerObservable().
parameterList
std::vector<Variable *> GooFit::PdfBase::parameterList protected
Definition at line 108 of file PdfBase.h.
Referenced by getParameterByName(), getParameters(), parametersChanged(), registerParameter(), and unregisterParameter().
parameters
unsigned int GooFit::PdfBase::parameters {0} protected
Definition at line 105 of file PdfBase.h.
Referenced by GooFit::ExpPdf::hasAnalyticIntegral(), recursiveSetNormalisation(), and GooFit::ResonancePdf::setConstantIndex().
properlyInitialised
bool GooFit::PdfBase::properlyInitialised {true} protected
Definition at line 113 of file PdfBase.h.
Referenced by checkInitStatus().
specialMask
int GooFit::PdfBase::specialMask {0} protected
Definition at line 112 of file PdfBase.h.
The documentation for this class was generated from the following files:
/home/travis/build/GooFit/GooFit/include/goofit/PdfBase.h
/home/travis/build/GooFit/GooFit/src/goofit/PdfBase.cc