GooFit: FitControl Class Reference
FitControl Class Reference
#include <FitControl.hh>
Public Member Functions
FitControl (bool bin, std::string mn)
~FitControl ()
bool binnedFit () const
bool binErrors () const
bool metricIsPdf () const
std::string getMetric () const
FunctorBase * getOwner () const
void setOwner (FunctorBase *dat)
Protected Attributes
bool errorsOnBins
Detailed Description
Definition at line 11 of file FitControl.hh.
Constructor & Destructor Documentation
FitControl::FitControl (bool bin, std::string mn)
Definition at line 4 of file FitControl.cc.
FitControl::~FitControl ()
Definition at line 11 of file FitControl.cc.
Member Function Documentation
bool FitControl::binErrors () const inline
Definition at line 17 of file FitControl.hh.
References errorsOnBins.
Referenced by FunctorBase::setData().
bool FitControl::binnedFit () const inline
Definition at line 16 of file FitControl.hh.
Referenced by ThrustPdfFunctor::calculateNLL(), ThrustPdfFunctor::getCompProbsAtDataPoints(), and FunctorBase::setData().
std::string FitControl::getMetric () const inline
Definition at line 19 of file FitControl.hh.
Referenced by ThrustPdfFunctor::setMetrics().
FunctorBase* FitControl::getOwner () const inline
Definition at line 20 of file FitControl.hh.
Referenced by ThrustPdfFunctor::setFitControl().
bool FitControl::metricIsPdf () const inline
Definition at line 18 of file FitControl.hh.
References errorsOnBins.
Referenced by ThrustPdfFunctor::normalise().
void FitControl::setOwner (FunctorBase * dat)
Definition at line 13 of file FitControl.cc.
Referenced by ThrustPdfFunctor::setFitControl().
Member Data Documentation
bool FitControl::errorsOnBins protected
Definition at line 24 of file FitControl.hh.
Referenced by binErrors(), BinnedErrorFit::BinnedErrorFit(), and metricIsPdf().
The documentation for this class was generated from the following files:
FitControl.hh
FitControl.cc