GooFit: GooFit::Application Class Reference
GooFit::Application Class Reference
#include <Application.h>
Public Member Functions
Application (std::string discription, int argc, char **argv)
Make a new Application.
Application (int argc, char **argv)
Shortcut for the lazy.
int get_device () const
Get the set GPU device.
void run ()
simple run since argc and argv are stored
void pre_callback () override
Gets called in parse.
int exit (const CLI::Error &e)
void set_device () const
~Application ()
Cleanup MPI.
std::string get_filename (const std::string &input_str, std::string base="") const
Protected Attributes
int gpuDev_ = 0
bool show_gpus_
bool quiet_
bool splash_
int argc_
char ** argv_
struct sigaction sigIntHandler
Handle control-c codes.
Detailed Description
Definition at line 95 of file Application.h.
Constructor & Destructor Documentation
Application() [1/2]
GooFit::Application::Application (std::string discription, int argc, char ** argv) inline
Make a new Application.
Definition at line 109 of file Application.h.
References GooFit::reset, sigIntHandler, and GooFit::signal_handler().
         : App(discription)
         , argc_(argc)
         , argv_(argv) {
 #ifdef GOOFIT_MPI
         MPI_Init(&argc_, &argv_);
         int myId, numProcs;
         MPI_Comm_size(MPI_COMM_WORLD, &numProcs);
         MPI_Comm_rank(MPI_COMM_WORLD, &myId);
 #if THRUST_DEVICE_SYSTEM == THRUST_DEVICE_SYSTEM_CUDA
         int deviceCount;
         cudaGetDeviceCount(&deviceCount);
         // Get Batch system number of nodes if possible
         auto PBS_NUM_NODES = getenv("PBS_NUM_NODES");
         int nodes = PBS_NUM_NODES == nullptr ? 1 : atoi(PBS_NUM_NODES);
         if(nodes == 0)
             nodes = 1;
         int procsPerNode = numProcs / nodes;
         int localRank    = myId % procsPerNode;
         // Note, this will (probably) be overwritten by gpu-set-device calls...
         if(deviceCount == 1 && localRank > 1) {
             // Multi-process to one GPU!
             gpuDev_ = 0;
         } else if(procsPerNode > 1 && deviceCount > 1) {
             if(localRank <= deviceCount) {
                 // setting multiple processes to multiple GPU's
                 gpuDev_ = localRank;
             } else {
                 // More multiple processes than GPU's, distribute sort of evenly!
                 gpuDev_ = localRank % deviceCount;
             }
         } else {
             // multiple GPU's, using one process
             gpuDev_ = 0;
         }
         std::cout << "MPI using CUDA device: " << gpuDev_ << std::endl;
         cudaSetDevice(gpuDev_);
 #endif
 #endif
         // Fallthrough is useful for most models of GooFit subcommands
         fallthrough();
 #if THRUST_DEVICE_SYSTEM == THRUST_DEVICE_SYSTEM_CUDA
 #ifndef GOOFIT_MPI
         add_option("--gpu-dev", gpuDev_, "GPU device to use", true)->group("GooFit");
 #endif
         add_flag("--show-gpus", show_gpus_, "Show the available GPU devices and exit")->group("GooFit");
 #endif
         auto quiet = add_flag("-q,--quiet", quiet_, "Reduce the verbosity of the Application")->group("GooFit");
         add_flag("--nosplash", splash_, "Do not print a splash")->group("GooFit")->excludes(quiet);
         set_config("--config", "config.ini", "An ini file with command line options in it")->group("GooFit");
         // Reset color on exit (but not control-c)
         std::atexit([]() { std::cout << GooFit::reset; });
         sigIntHandler.sa_handler = signal_handler;
         sigemptyset(&sigIntHandler.sa_mask);
         sigIntHandler.sa_flags = 0;
         sigaction(SIGINT, &sigIntHandler, nullptr);
     }
Application() [2/2]
GooFit::Application::Application (int argc, char ** argv) inline
Shortcut for the lazy.
Definition at line 182 of file Application.h.
         : Application("", argc, argv) {}
~Application()
GooFit::Application::~Application () inline
Cleanup MPI.
Definition at line 284 of file Application.h.
                    {
 // Intentionally empty, comment needed to avoid clang warning about = default
 #ifdef GOOFIT_MPI
         MPI_Finalize();
 #endif
     }
Member Function Documentation
exit()
int GooFit::Application::exit (const CLI::Error & e) inline
Definition at line 256 of file Application.h.
References GooFit::blue, GooFit::red, and GooFit::reset.
{
 #ifdef GOOFIT_MPI
         int myId;
         MPI_Comm_rank(MPI_COMM_WORLD, &myId);
         if(myId > 0)
             return e.get_exit_code();
 #endif
         std::cout << (e.get_exit_code() == 0 ? blue : red);
         int rval = CLI::App::exit(e);
         std::cout << GooFit::reset;
         return rval;
     }
get_device()
int GooFit::Application::get_device () const inline
Get the set GPU device.
Definition at line 186 of file Application.h.
References gpuDev_.
Referenced by pre_callback().
 { return gpuDev_; }
get_filename()
std::string GooFit::Application::get_filename (const std::string & input_str, std::string base = "") const inline
Get a file from the current directory, looks up one and in the true current directory Base gives a relative path from the source directory
Definition at line 293 of file Application.h.
{
         // Run from current directory
         if(CLI::ExistingFile(input_str).empty())
             return input_str;
         // Run from a different directory
         std::string prog_name{argv_[0]};
         size_t loc = prog_name.rfind("/");
         if(loc != std::string::npos) {
             std::string cdir = prog_name.substr(0, loc);
             std::string new_input{cdir + "/" + input_str};
             if(CLI::ExistingFile(new_input).empty()) {
                 std::cout << "Found file at " << new_input << std::endl;
                 return new_input;
             }
         }
         // If all else fails, try to get file from source directory (if base is specified)
         if(base.size() > 0) {
             std::string new_input = std::string(GOOFIT_SOURCE_DIR) + "/" + base + "/" + input_str;
             if(CLI::ExistingFile(new_input).empty()) {
                 std::cout << "Found file at " << new_input << std::endl;
                 return new_input;
             }
         }
         // Could not find file
         throw GooFit::FileError(input_str);
     }
pre_callback()
void GooFit::Application::pre_callback () inline override
Gets called in parse.
Definition at line 192 of file Application.h.
References get_device(), GOOFIT_DEBUG, GOOFIT_INFO, GooFit::print_splash(), GooFit::red, GooFit::reset, and set_device().
{
         set_device();
         if(!quiet_) {
             if(!splash_)
                 print_splash();
             GOOFIT_INFO("GooFit: Version {} ({}) Commit: {}", GOOFIT_VERSION, GOOFIT_TAG, GOOFIT_GIT_VERSION);
 #if THRUST_DEVICE_SYSTEM == THRUST_DEVICE_SYSTEM_CUDA
             cudaDeviceProp devProp;
             cudaGetDeviceProperties(&devProp, gpuDev_);
             GOOFIT_INFO("CUDA: Device {}: {}", get_device(), devProp.name);
             GOOFIT_INFO("CUDA: Compute {}.{}", devProp.major, devProp.minor);
             GOOFIT_INFO("CUDA: Total global memory: {} GB", devProp.totalGlobalMem / 1.0e9);
             GOOFIT_INFO("CUDA: Multiprocessors: {}", devProp.multiProcessorCount);
             GOOFIT_DEBUG("CUDA: Total amount of shared memory per block: {}", devProp.sharedMemPerBlock);
             GOOFIT_DEBUG("CUDA: Total registers per block: {}", devProp.regsPerBlock);
             GOOFIT_DEBUG("CUDA: Warp size: {}", devProp.warpSize);
             GOOFIT_DEBUG("CUDA: Maximum memory pitch: {}", devProp.memPitch);
             GOOFIT_DEBUG("CUDA: Total amount of constant memory: {}", devProp.totalConstMem);
 #elif THRUST_DEVICE_SYSTEM == THRUST_DEVICE_SYSTEM_OMP
             GOOFIT_INFO("OMP: Number of threads: {}", omp_get_max_threads());
 #elif THRUST_DEVICE_SYSTEM == THRUST_DEVICE_SYSTEM_TBB
             GOOFIT_INFO("TBB: Backend selected");
 #elif THRUST_DEVICE_SYSTEM == THRUST_DEVICE_SYSTEM_CPP
             GOOFIT_INFO("CPP: Single threaded mode");
 #endif
 #if GOOFIT_ROOT_FOUND
             GOOFIT_INFO("ROOT: Found");
 #else
             GOOFIT_INFO("ROOT: Not found");
 #endif
             // Print out warnings if not fully optimized
             std::cout << red;
             FeatureDetector::cpu_x86::print_warnings();
             std::cout << GooFit::reset << std::flush;
         }
 #if THRUST_DEVICE_SYSTEM == THRUST_DEVICE_SYSTEM_CUDA
         if(show_gpus_) {
             int deviceCount;
             cudaGetDeviceCount(&deviceCount);
             for(int i = 0; i < deviceCount; i++) {
                 cudaDeviceProp deviceProp;
                 cudaGetDeviceProperties(&deviceProp, i);
                 std::cout << "CUDA: Device " << i << " has compute capability " << deviceProp.major << "."
                           << deviceProp.minor << std::endl;
             }
             throw GooFit::Success();
         }
 #endif
     }
run()
void GooFit::Application::run () inline
simple run since argc and argv are stored
Definition at line 189 of file Application.h.
 { parse(argc_, argv_); }
set_device()
void GooFit::Application::set_device () const inline
Call if the application might fork, otherwise automatic For example, if explicitly using omp
Definition at line 273 of file Application.h.
Referenced by pre_callback().
{
 #if THRUST_DEVICE_SYSTEM == THRUST_DEVICE_SYSTEM_CUDA
         if(gpuDev_ != 0) {
             cudaSetDevice(gpuDev_);
         }
 #endif
     }
Member Data Documentation
argc_
int GooFit::Application::argc_ protected
Definition at line 101 of file Application.h.
argv_
char** GooFit::Application::argv_ protected
Definition at line 102 of file Application.h.
gpuDev_
int GooFit::Application::gpuDev_ = 0 protected
Definition at line 97 of file Application.h.
Referenced by get_device().
quiet_
bool GooFit::Application::quiet_ protected
Definition at line 99 of file Application.h.
show_gpus_
bool GooFit::Application::show_gpus_ protected
Definition at line 98 of file Application.h.
sigIntHandler
struct sigaction GooFit::Application::sigIntHandler protected
Handle control-c codes.
Definition at line 105 of file Application.h.
Referenced by Application().
splash_
bool GooFit::Application::splash_ protected
Definition at line 100 of file Application.h.
The documentation for this class was generated from the following file:
/home/travis/build/GooFit/GooFit/include/goofit/Application.h