GooFit: PdfFunctor Class Reference
PdfFunctor Class Reference
#include <PdfBuilder.hh>
Public Member Functions
PdfFunctor (FunctorBase *dat)
~PdfFunctor ()
void setMaxCalls (double mxc)
void setupMinuit ()
void runMigrad ()
void fit ()
TMinuit * getMinuitObject ()
void getMinuitValues () const
Detailed Description
Definition at line 70 of file PdfBuilder.hh.
Constructor & Destructor Documentation
PdfFunctor::PdfFunctor (FunctorBase * dat)
Definition at line 184 of file PdfBuilder.cc.
References currGlue, and pdfPointer.
PdfFunctor::~PdfFunctor ()
Definition at line 192 of file PdfBuilder.cc.
Member Function Documentation
void PdfFunctor::fit ()
Definition at line 234 of file PdfBuilder.cc.
References runMigrad(), and setupMinuit().
Referenced by fitAndPlot().
TMinuit* PdfFunctor::getMinuitObject () inline
Definition at line 78 of file PdfBuilder.hh.
void PdfFunctor::getMinuitValues () const
Definition at line 252 of file PdfBuilder.cc.
References TMinuit::GetParameter().
Referenced by fitAndPlot(), and specialTddpPrint().
void PdfFunctor::runMigrad ()
Definition at line 239 of file PdfBuilder.cc.
References host_callnumber, TMinuit::Migrad(), and TMinuit::mnexcm().
Referenced by fit().
void PdfFunctor::setMaxCalls (double mxc) inline
Definition at line 74 of file PdfBuilder.hh.
void PdfFunctor::setupMinuit ()
Definition at line 196 of file PdfBuilder.cc.
References FunctorBase::copyParams(), TMinuit::DefineParameter(), FitFun(), TMinuit::FixParameter(), FunctorBase::getParameters(), numPars, pdfPointer, and TMinuit::SetFCN().
Referenced by fit().
The documentation for this class was generated from the following files:
PdfBuilder.hh
PdfBuilder.cc