GooFit: GooFit::Indexable Class Reference
GooFit::Indexable Class Reference
#include <Variable.h>
Public Member Functions
Indexable (std::string n, fptype val=0)
Indexable (std::string n, fptype val, fptype lowerlimit, fptype upperlimit)
Indexable & operator= (const Indexable &)=delete
virtual ~Indexable ()
int getIndex () const
Get the GooFit index.
void setIndex (int value)
Set the GooFit index.
const std::string & getName () const
Get the name.
fptype getValue () const
Get the value.
void setValue (fptype val)
Set the value.
fptype getUpperLimit () const
Get the upper limit.
void setUpperLimit (fptype val)
Set the upper limit.
fptype getLowerLimit () const
Get the lower limit.
void setLowerLimit (fptype val)
Set the lower limit.
const Indexable & operator= (const fptype &val)
Support var = 3.
operator fptype () const
Support fptype val = var.
bool operator< (const Indexable &other) const
Support for using as key in map - Notice this does NOT sort by index!
bool operator== (const Indexable &other) const
Support for comparison - only if really the same object, not just the same value.
bool operator!= (const Indexable &other) const
Support for comparison - only if really the same object, not just the same value.
operator bool () const
Check to see if in range.
Protected Attributes
std::string name
The variable name. Should be unique.
std::shared_ptr< fptype > value
The value of the variable.
std::shared_ptr< fptype > lowerlimit {std::make_shared<fptype>(0)}
The lower limit.
std::shared_ptr< fptype > upperlimit {std::make_shared<fptype>(0)}
The upper limit.
std::shared_ptr< int > index {std::make_shared<int>(-1)}
The goofit index, -1 if unset.
Detailed Description
This class is specifically for any indexable quanity: Observables or Variables. It contains the idea of a limited quanity (min==max means no limit). It can also take a value.
Definition at line 22 of file Variable.h.
Constructor & Destructor Documentation
Indexable() [1/2]
GooFit::Indexable::Indexable (std::string n, fptype val = 0) inline
Definition at line 40 of file Variable.h.
         : name(n)
         , value(std::make_shared<fptype>(val)) {}
Indexable() [2/2]
GooFit::Indexable::Indexable (std::string n, fptype val, fptype lowerlimit, fptype upperlimit) inline
Definition at line 44 of file Variable.h.
References operator=().
         : name(n)
         , value(std::make_shared<fptype>(val))
         , lowerlimit(std::make_shared<fptype>(lowerlimit))
         , upperlimit(std::make_shared<fptype>(upperlimit)) {}
~Indexable()
virtual GooFit::Indexable::~Indexable () inline virtual
Definition at line 52 of file Variable.h.
References GOOFIT_DEBUG.
{
         if(value.use_count() == 1)
             GOOFIT_DEBUG("Destroying Indexable: {}", name);
     }
Member Function Documentation
getIndex()
int GooFit::Indexable::getIndex () const inline
Get the GooFit index.
Definition at line 58 of file Variable.h.
References index.
Referenced by GooFit::max_index(), GooFit::operator<<(), and GooFit::PdfBase::registerParameter().
 { return *index; }
getLowerLimit()
fptype GooFit::Indexable::getLowerLimit () const inline
Get the lower limit.
Definition at line 78 of file Variable.h.
References lowerlimit.
Referenced by GooFit::DalitzPlotter::DalitzPlotter(), GooFit::Observable::getBinSize(), GooFit::DalitzPlotter::getM13(), GooFit::make_a_grid(), operator bool(), and GooFit::operator<<().
 { return *lowerlimit; }
getName()
const std::string& GooFit::Indexable::getName () const inline
Get the name.
Definition at line 63 of file Variable.h.
References name.
Referenced by GooFit::UnbinnedDataSet::getValue(), GooFit::operator<<(), GooFit::PdfBase::registerObservable(), GooFit::PdfBase::registerParameter(), and GooFit::PdfBase::unregisterParameter().
 { return name; }
getUpperLimit()
fptype GooFit::Indexable::getUpperLimit () const inline
Get the upper limit.
Definition at line 73 of file Variable.h.
References upperlimit.
Referenced by GooFit::Observable::getBinSize(), GooFit::DalitzPlotter::getM13(), GooFit::make_a_grid(), operator bool(), and GooFit::operator<<().
 { return *upperlimit; }
getValue()
fptype GooFit::Indexable::getValue () const inline
Get the value.
Definition at line 68 of file Variable.h.
References value.
Referenced by GooFit::DalitzPlotter::DalitzPlotter(), GooFit::make_a_grid(), operator bool(), operator fptype(), GooFit::operator<<(), and GooFit::UnbinnedDataSet::setValueForAllEvents().
 { return *value; }
operator bool()
GooFit::Indexable::operator bool () const inline
Check to see if in range.
Definition at line 103 of file Variable.h.
References getLowerLimit(), getUpperLimit(), and getValue().
{
         return getUpperLimit() == getLowerLimit() || (getValue() <= getUpperLimit() && getValue() >= getLowerLimit());
     }
operator fptype()
GooFit::Indexable::operator fptype () const inline
Support fptype val = var.
Definition at line 91 of file Variable.h.
References getValue().
 { return getValue(); }
operator!=()
bool GooFit::Indexable::operator!= (const Indexable & other) const inline
Support for comparison - only if really the same object, not just the same value.
Definition at line 100 of file Variable.h.
References value.
 { return value.get() != other.value.get(); }
operator<()
bool GooFit::Indexable::operator< (const Indexable & other) const inline
Support for using as key in map - Notice this does NOT sort by index!
Definition at line 94 of file Variable.h.
References value.
 { return value.get() < other.value.get(); }
operator=() [1/2]
Indexable& GooFit::Indexable::operator= (const Indexable &) delete
Referenced by GooFit::EventNumber::EventNumber(), Indexable(), GooFit::Observable::Observable(), and GooFit::Variable::Variable().
operator=() [2/2]
const Indexable& GooFit::Indexable::operator= (const fptype & val) inline
Support var = 3.
Definition at line 83 of file Variable.h.
References setValue().
{
         setValue(val);
         return *this;
     }
operator==()
bool GooFit::Indexable::operator== (const Indexable & other) const inline
Support for comparison - only if really the same object, not just the same value.
Definition at line 97 of file Variable.h.
References value.
 { return value.get() == other.value.get(); }
setIndex()
void GooFit::Indexable::setIndex (int value) inline
Set the GooFit index.
Definition at line 60 of file Variable.h.
References index, and value.
Referenced by GooFit::PdfBase::registerParameter(), and GooFit::PdfBase::unregisterParameter().
 { *index = value; }
setLowerLimit()
void GooFit::Indexable::setLowerLimit (fptype val) inline
Set the lower limit.
Definition at line 80 of file Variable.h.
References lowerlimit.
Referenced by GooFit::readFromFile().
 { *lowerlimit = val; }
setUpperLimit()
void GooFit::Indexable::setUpperLimit (fptype val) inline
Set the upper limit.
Definition at line 75 of file Variable.h.
References upperlimit.
Referenced by GooFit::readFromFile().
 { *upperlimit = val; }
setValue()
void GooFit::Indexable::setValue (fptype val) inline
Set the value.
Definition at line 70 of file Variable.h.
Referenced by GooFit::DalitzPlotter::DalitzPlotter(), GooFit::DalitzPlotter::fillDataSetMC(), GooFit::make_a_grid(), operator=(), GooFit::Observable::operator=(), GooFit::Variable::operator=(), GooFit::EventNumber::operator=(), and GooFit::readFromFile().
 { *value = val; }
Member Data Documentation
index
std::shared_ptr<int> GooFit::Indexable::index {std::make_shared<int>(-1)} protected
The goofit index, -1 if unset.
Definition at line 37 of file Variable.h.
Referenced by getIndex(), and setIndex().
lowerlimit
std::shared_ptr<fptype> GooFit::Indexable::lowerlimit {std::make_shared<fptype>(0)} protected
The lower limit.
Definition at line 31 of file Variable.h.
Referenced by getLowerLimit(), and setLowerLimit().
name
std::string GooFit::Indexable::name protected
The variable name. Should be unique.
Definition at line 25 of file Variable.h.
Referenced by getName().
upperlimit
std::shared_ptr<fptype> GooFit::Indexable::upperlimit {std::make_shared<fptype>(0)} protected
The upper limit.
Definition at line 34 of file Variable.h.
Referenced by getUpperLimit(), and setUpperLimit().
value
std::shared_ptr<fptype> GooFit::Indexable::value protected
The value of the variable.
Definition at line 28 of file Variable.h.
Referenced by GooFit::EventNumber::EventNumber(), getValue(), operator!=(), operator<(), operator==(), GooFit::operator>>(), GooFit::Variable::setFitterIndex(), and setIndex().
The documentation for this class was generated from the following file:
/home/travis/build/GooFit/GooFit/include/goofit/Variable.h