GooFit: GooFit::Observable Class Reference
GooFit::Observable Class Reference
Special class for observables. Used in DataSets.
#include <Variable.h>
Public Member Functions
Observable (std::string name, fptype lowerlimit, fptype upperlimit)
~Observable () override=default
void setNumBins (size_t num)
Set the number of bins.
size_t getNumBins () const
Get the number of bins.
fptype getBinSize () const
Get the bin size, (upper-lower) / bins.
const Observable & operator= (const fptype &val)
Support var = 3.
Public Member Functions inherited from GooFit::Indexable
Indexable (std::string n, fptype val=0)
Indexable (std::string n, fptype val, fptype lowerlimit, fptype upperlimit)
virtual ~Indexable ()
int getIndex () const
Get the GooFit index.
void setIndex (int value)
Set the GooFit index.
const std::string & getName () const
Get the name.
fptype getValue () const
Get the value.
void setValue (fptype val)
Set the value.
fptype getUpperLimit () const
Get the upper limit.
void setUpperLimit (fptype val)
Set the upper limit.
fptype getLowerLimit () const
Get the lower limit.
void setLowerLimit (fptype val)
Set the lower limit.
const Indexable & operator= (const fptype &val)
Support var = 3.
operator fptype () const
Support fptype val = var.
bool operator< (const Indexable &other) const
Support for using as key in map - Notice this does NOT sort by index!
bool operator== (const Indexable &other) const
Support for comparison - only if really the same object, not just the same value.
bool operator!= (const Indexable &other) const
Support for comparison - only if really the same object, not just the same value.
operator bool () const
Check to see if in range.
Protected Attributes
std::shared_ptr< size_t > numbins {std::make_shared<size_t>(100)}
The number of bins (mostly for BinnedData, or plotting help)
Protected Attributes inherited from GooFit::Indexable
std::string name
The variable name. Should be unique.
std::shared_ptr< fptype > value
The value of the variable.
std::shared_ptr< fptype > lowerlimit {std::make_shared<fptype>(0)}
The lower limit.
std::shared_ptr< fptype > upperlimit {std::make_shared<fptype>(0)}
The upper limit.
std::shared_ptr< int > index {std::make_shared<int>(-1)}
The goofit index, -1 if unset.
Friends
std::istream & operator>> (std::istream &o, Observable &var)
Allow Observable to be read in.
Detailed Description
Special class for observables. Used in DataSets.
Definition at line 107 of file Variable.h.
Constructor & Destructor Documentation
Observable()
GooFit::Observable::Observable (std::string name, fptype lowerlimit, fptype upperlimit) inline
Definition at line 115 of file Variable.h.
         : GooFit::Indexable(name, 0, lowerlimit, upperlimit) {}
~Observable()
GooFit::Observable::~Observable () override default
Member Function Documentation
getBinSize()
fptype GooFit::Observable::getBinSize () const inline
Get the bin size, (upper-lower) / bins.
Definition at line 126 of file Variable.h.
References GooFit::Indexable::getLowerLimit(), and GooFit::Indexable::getUpperLimit().
 { return (getUpperLimit() - getLowerLimit()) / getNumBins(); }
getNumBins()
size_t GooFit::Observable::getNumBins () const inline
Get the number of bins.
Definition at line 123 of file Variable.h.
Referenced by GooFit::operator<<().
 { return *numbins; }
operator=()
const Observable& GooFit::Observable::operator= (const fptype & val) inline
Support var = 3.
Definition at line 129 of file Variable.h.
References GooFit::Indexable::setValue().
{
         setValue(val);
         return *this;
     }
setNumBins()
void GooFit::Observable::setNumBins (size_t num) inline
Set the number of bins.
Definition at line 121 of file Variable.h.
 { *numbins = num; }
Friends And Related Function Documentation
operator>>
std::istream& operator>> (std::istream & o, GooFit::Observable & var) friend
Allow Observable to be read in.
Definition at line 59 of file Variable.cpp.
 { return i >> *var.value; }
Member Data Documentation
numbins
std::shared_ptr<size_t> GooFit::Observable::numbins {std::make_shared<size_t>(100)} protected
The number of bins (mostly for BinnedData, or plotting help)
Definition at line 112 of file Variable.h.
The documentation for this class was generated from the following file:
/home/travis/build/GooFit/GooFit/include/goofit/Variable.h