GooFit: ThrustPdfFunctor Class Reference
ThrustPdfFunctor Class Reference
#include <ThrustPdfFunctor.hh>
Public Member Functions
ThrustPdfFunctor (Variable *x, std::string n)
virtual __host__ double calculateNLL () const
__host__ void evaluateAtPoints (std::vector< fptype > &points) const
__host__ void evaluateAtPoints (Variable *var, std::vector< fptype > &res)
virtual __host__ fptype normalise () const
virtual __host__ fptype integrate (fptype lo, fptype hi) const
virtual __host__ bool hasAnalyticIntegral () const
__host__ fptype getValue ()
__host__ void getCompProbsAtDataPoints (std::vector< std::vector< fptype > > &values)
__host__ void initialise (std::vector< unsigned int > pindices, void *dev_functionPtr=host_fcn_ptr)
__host__ void scan (Variable *var, std::vector< fptype > &values)
virtual __host__ void setFitControl (FitControl *const fc, bool takeOwnerShip=true)
virtual __host__ void setMetrics ()
__host__ void setParameterConstantness (bool constant=true)
virtual __host__ void transformGrid (fptype *host_output)
__host__ void setDebugMask (int mask, bool setSpecific=true) const
Public Member Functions inherited from FunctorBase
FunctorBase (Variable *x, std::string n)
__host__ void initialiseIndices (std::vector< unsigned int > pindices)
__host__ void addSpecialMask (int m)
__host__ void copyParams (const std::vector< double > &pars) const
__host__ void copyParams ()
__host__ void copyNormFactors () const
__host__ void generateNormRange ()
__host__ std::string getName () const
virtual __host__ void getObservables (obsCont &ret) const
virtual __host__ void getParameters (parCont &ret) const
__host__ int getSpecialMask () const
__host__ void setData (BinnedDataSet *data)
__host__ void setData (UnbinnedDataSet *data)
__host__ void setData (std::vector< std::map< Variable *, fptype > > &data)
__host__ unsigned int getFunctionIndex () const
__host__ unsigned int getParameterIndex () const
__host__ unsigned int registerParameter (Variable *var)
__host__ unsigned int registerConstants (unsigned int amount)
virtual __host__ void recursiveSetNormalisation (fptype norm=1) const
__host__ void unregisterParameter (Variable *var)
__host__ void registerObservable (Variable *obs)
__host__ void setIntegrationFineness (int i)
__host__ void printProfileInfo (bool topLevel=true)
__host__ bool parametersChanged () const
__host__ void storeParameters () const
__host__ obsIter obsBegin ()
__host__ obsIter obsEnd ()
__host__ obsConstIter obsCBegin () const
__host__ obsConstIter obsCEnd () const
__host__ void checkInitStatus (std::vector< std::string > &unInited) const
void clearCurrentFit ()
Static Public Member Functions
static __host__ int findFunctionIdx (void *dev_functionPtr)
Protected Member Functions
virtual __host__ double sumOfNll (int numVars) const
Protected Attributes
MetricTaker * logger
Protected Attributes inherited from FunctorBase
fptype numEvents
unsigned int numEntries
fptype * normRanges
unsigned int parameters
unsigned int cIndex
obsCont observables
parCont parameterList
FitControl * fitControl
std::vector< FunctorBase * > components
int integrationBins
int specialMask
fptype * cachedParams
bool properlyInitialised
unsigned int functionIdx
Additional Inherited Members
Public Types inherited from FunctorBase
enum Specials { ForceSeparateNorm = 1, ForceCommonNorm = 2 }
typedef std::vector< Variable * > obsCont
typedef obsCont::iterator obsIter
typedef obsCont::const_iterator obsConstIter
typedef std::set< Variable * > parCont
typedef parCont::iterator parIter
Detailed Description
Definition at line 28 of file ThrustPdfFunctor.hh.
Constructor & Destructor Documentation
ThrustPdfFunctor::ThrustPdfFunctor (Variable * x, std::string n)
Definition at line 179 of file ThrustPdfFunctor.cu.
Member Function Documentation
__host__ double ThrustPdfFunctor::calculateNLL () const virtual
Implements FunctorBase.
Definition at line 285 of file ThrustPdfFunctor.cu.
References abortWithCudaPrintFlush(), FitControl::binnedFit(), FunctorBase::fitControl, FunctorBase::getName(), host_normalisation, normalisationFactors, normalise(), FunctorBase::observables, sumOfNll(), and totalParams.
Referenced by scan().
__host__ void ThrustPdfFunctor::evaluateAtPoints (std::vector< fptype > & points) const
Definition at line 379 of file ThrustPdfFunctor.cu.
__host__ void ThrustPdfFunctor::evaluateAtPoints (Variable * var, std::vector< fptype > & res)
Definition at line 322 of file ThrustPdfFunctor.cu.
References DataSet::addEvent(), FunctorBase::copyParams(), cudaDataArray, getMetricPointer(), host_normalisation, Variable::lowerlimit, normalisationFactors, normalise(), Variable::numbins, FunctorBase::numEntries, FunctorBase::observables, FunctorBase::parameters, FunctorBase::setData(), totalParams, Variable::upperlimit, and Variable::value.
__host__ int ThrustPdfFunctor::findFunctionIdx (void * dev_functionPtr) static
Definition at line 186 of file ThrustPdfFunctor.cu.
References cutilSafeCall, device_function_table, functionAddressToDeviceIndexMap, host_function_table, and num_device_functions.
Referenced by initialise(), and MixingTimeResolution::initIndex().
__host__ void ThrustPdfFunctor::getCompProbsAtDataPoints (std::vector< std::vector< fptype > > & values)
Definition at line 626 of file ThrustPdfFunctor.cu.
References FitControl::binnedFit(), FunctorBase::components, FunctorBase::copyParams(), cudaDataArray, FunctorBase::fitControl, getMetricPointer(), host_normalisation, normalisationFactors, normalise(), FunctorBase::numEntries, FunctorBase::observables, and totalParams.
Referenced by fitAndPlot().
__host__ fptype ThrustPdfFunctor::getValue ()
Definition at line 426 of file ThrustPdfFunctor.cu.
References DataSet::addEvent(), FunctorBase::copyParams(), cudaDataArray, getMetricPointer(), host_normalisation, normalisationFactors, normalise(), FunctorBase::observables, FunctorBase::setData(), and totalParams.
virtual __host__ bool ThrustPdfFunctor::hasAnalyticIntegral () const inline virtual
Reimplemented from FunctorBase.
Reimplemented in EventWeightedAddThrustFunctor, AddThrustFunctor, ExpThrustFunctor, ProdThrustFunctor, GaussianThrustFunctor, JohnsonSUThrustFunctor, KinLimitBWThrustFunctor, StepThrustFunctor, ArgusThrustFunctor, and ScaledGaussianThrustFunctor.
Definition at line 37 of file ThrustPdfFunctor.hh.
Referenced by normalise().
__host__ void ThrustPdfFunctor::initialise (std::vector< unsigned int > pindices, void * dev_functionPtr = host_fcn_ptr)
Definition at line 220 of file ThrustPdfFunctor.cu.
References findFunctionIdx(), FunctorBase::fitControl, FunctorBase::functionIdx, FunctorBase::initialiseIndices(), setFitControl(), and setMetrics().
Referenced by AddThrustFunctor::AddThrustFunctor(), ArgusThrustFunctor::ArgusThrustFunctor(), BifurGaussThrustFunctor::BifurGaussThrustFunctor(), BinTransformThrustFunctor::BinTransformThrustFunctor(), CompositeThrustFunctor::CompositeThrustFunctor(), ConvolutionThrustFunctor::ConvolutionThrustFunctor(), CorrGaussianThrustFunctor::CorrGaussianThrustFunctor(), CrystalBallThrustFunctor::CrystalBallThrustFunctor(), DalitzVetoThrustFunctor::DalitzVetoThrustFunctor(), EventWeightedAddThrustFunctor::EventWeightedAddThrustFunctor(), ExpGausThrustFunctor::ExpGausThrustFunctor(), ExpThrustFunctor::ExpThrustFunctor(), GaussianThrustFunctor::GaussianThrustFunctor(), IncoherentSumThrustFunctor::IncoherentSumThrustFunctor(), InterHistThrustFunctor::InterHistThrustFunctor(), JohnsonSUThrustFunctor::JohnsonSUThrustFunctor(), KinLimitBWThrustFunctor::KinLimitBWThrustFunctor(), LandauThrustFunctor::LandauThrustFunctor(), MappedThrustFunctor::MappedThrustFunctor(), NovosibirskThrustFunctor::NovosibirskThrustFunctor(), PolynomialThrustFunctor::PolynomialThrustFunctor(), ProdThrustFunctor::ProdThrustFunctor(), ScaledGaussianThrustFunctor::ScaledGaussianThrustFunctor(), SmoothHistogramThrustFunctor::SmoothHistogramThrustFunctor(), StepThrustFunctor::StepThrustFunctor(), TddpThrustFunctor::TddpThrustFunctor(), TrigThresholdThrustFunctor::TrigThresholdThrustFunctor(), and VoigtianThrustFunctor::VoigtianThrustFunctor().
virtual __host__ fptype ThrustPdfFunctor::integrate (fptype lo, fptype hi) const inline virtual
Reimplemented in ArgusThrustFunctor, ExpThrustFunctor, PolynomialThrustFunctor, BifurGaussThrustFunctor, CrystalBallThrustFunctor, GaussianThrustFunctor, JohnsonSUThrustFunctor, and StepThrustFunctor.
Definition at line 36 of file ThrustPdfFunctor.hh.
Referenced by normalise().
__host__ fptype ThrustPdfFunctor::normalise () const virtual
Implements FunctorBase.
Reimplemented in TddpThrustFunctor, IncoherentSumThrustFunctor, CompositeThrustFunctor, EventWeightedAddThrustFunctor, AddThrustFunctor, ConvolutionThrustFunctor, MappedThrustFunctor, ProdThrustFunctor, and SmoothHistogramThrustFunctor.
Definition at line 450 of file ThrustPdfFunctor.cu.
References abortWithCudaPrintFlush(), FunctorBase::fitControl, FunctorBase::getName(), hasAnalyticIntegral(), host_normalisation, integrate(), FunctorBase::integrationBins, logger, FitControl::metricIsPdf(), FunctorBase::normRanges, FunctorBase::obsCBegin(), FunctorBase::obsCEnd(), FunctorBase::observables, and FunctorBase::parameters.
Referenced by calculateNLL(), evaluateAtPoints(), PolynomialThrustFunctor::getCoefficient(), getCompProbsAtDataPoints(), getValue(), ProdThrustFunctor::normalise(), ConvolutionThrustFunctor::normalise(), and CompositeThrustFunctor::normalise().
__host__ void ThrustPdfFunctor::scan (Variable * var, std::vector< fptype > & values)
Definition at line 405 of file ThrustPdfFunctor.cu.
References calculateNLL(), FunctorBase::copyParams(), Variable::lowerlimit, Variable::numbins, Variable::upperlimit, and Variable::value.
__host__ void ThrustPdfFunctor::setDebugMask (int mask, bool setSpecific = true) const
Definition at line 230 of file ThrustPdfFunctor.cu.
References cpuDebug, debugParamIndex, gpuDebug, and FunctorBase::parameters.
__host__ void ThrustPdfFunctor::setFitControl (FitControl *const fc, bool takeOwnerShip = true) virtual
Implements FunctorBase.
Definition at line 737 of file ThrustPdfFunctor.cu.
References FunctorBase::components, FunctorBase::fitControl, FitControl::getOwner(), setMetrics(), and FitControl::setOwner().
Referenced by initialise().
__host__ void ThrustPdfFunctor::setMetrics () virtual
Definition at line 236 of file ThrustPdfFunctor.cu.
References FunctorBase::fitControl, FitControl::getMetric(), getMetricPointer(), and logger.
Referenced by initialise(), and setFitControl().
__host__ void ThrustPdfFunctor::setParameterConstantness (bool constant = true)
Definition at line 418 of file ThrustPdfFunctor.cu.
References FunctorBase::getParameters().
__host__ double ThrustPdfFunctor::sumOfNll (int numVars) const protected virtual
Reimplemented in AddThrustFunctor.
Definition at line 241 of file ThrustPdfFunctor.cu.
References cudaDataArray, logger, and FunctorBase::numEntries.
Referenced by calculateNLL().
__host__ void ThrustPdfFunctor::transformGrid (fptype * host_output) virtual
Definition at line 674 of file ThrustPdfFunctor.cu.
References FunctorBase::generateNormRange(), logger, FunctorBase::normRanges, FunctorBase::obsCBegin(), FunctorBase::obsCEnd(), and FunctorBase::observables.
Member Data Documentation
MetricTaker* ThrustPdfFunctor::logger protected
Definition at line 52 of file ThrustPdfFunctor.hh.
Referenced by normalise(), setMetrics(), AddThrustFunctor::sumOfNll(), sumOfNll(), and transformGrid().
The documentation for this class was generated from the following files:
FPOINTER/ThrustPdfFunctor.hh
FPOINTER/ThrustPdfFunctor.cu