GooFit: CLI::App Class Reference
CLI::App Class Reference
Creates a command line program, with very few defaults.
#include <CLI11.hpp>
Public Member Functions
Basic
App (std::string description_="", bool help=true)
Create a new program. Pass in the same arguments as main(), along with a help string.
App * set_callback (std::function< void()> callback)
App * allow_extras (bool allow=true)
Remove the error when extras are left over on the command line.
App * ignore_case (bool value=true)
Ignore case. Subcommand inherit value.
App * require_subcommand (int value=-1)
App * fallthrough (bool value=true)
Adding options
Option * add_option (std::string name, callback_t callback, std::string description="", bool defaulted=false)
template<typename T , enable_if_t<!is_vector< T >::value, detail::enabler > = detail::dummy>
Option * add_option (std::string name, T &variable, std::string description="", bool defaulted=false)
Add option for non-vectors.
template<typename T >
Option * add_option (std::string name, std::vector< T > &variable, std::string description="", bool defaulted=false)
Add option for vectors.
Option * add_flag (std::string name, std::string description="")
Add option for flag.
template<typename T , enable_if_t< std::is_integral< T >::value &&!is_bool< T >::value, detail::enabler > = detail::dummy>
Option * add_flag (std::string name, T &count, std::string description="")
Add option for flag integer.
template<typename T , enable_if_t< is_bool< T >::value, detail::enabler > = detail::dummy>
Option * add_flag (std::string name, T &count, std::string description="")
Bool version only allows the flag once.
template<typename T >
Option * add_set (std::string name, T &member, std::set< T > options, std::string description="", bool defaulted=false)
Add set of options.
Option * add_set_ignore_case (std::string name, std::string &member, std::set< std::string > options, std::string description="", bool defaulted=false)
Add set of options, string only, ignore case.
Option * add_config (std::string name="--config", std::string default_filename="", std::string help="Read an ini file", bool required=false)
Add a configuration ini file option.
bool remove_option (Option *opt)
Removes an option from the App. Takes an option pointer. Returns true if found and removed.
Subcommmands
App * add_subcommand (std::string name, std::string description="", bool help=true)
Add a subcommand. Like the constructor, you can override the help message addition by setting help=false.
Extras for subclassing
virtual void pre_callback ()
Post parsing
int count (std::string name) const
Counts the number of times the given option was passed.
std::vector< App * > get_subcommands ()
Get a subcommand pointer list to the currently selected subcommands (after parsing)
bool got_subcommand (App *subcom) const
Check to see if selected subcommand in list.
bool got_subcommand (std::string name) const
Check with name instead of pointer.
std::string config_to_str (bool default_also=false, std::string prefix="") const
Produce a string that could be read in as a config of the current values of the App. Set default_also to include default arguments. Prefix will add a string to the beginning of each option.
std::string help (size_t wid=30, std::string prev="") const
Makes a help message, with a column wid for column 1.
Getters
Option * get_help_ptr ()
Get a pointer to the help flag.
Option * get_config_ptr ()
Get a pointer to the config option.
std::string get_name () const
Get the name of the current app.
bool check_name (std::string name_to_check) const
Check the name, case insensitive if set.
Protected Member Functions
App (std::string description_, bool help, detail::enabler)
Special private constructor for subcommand.
void _validate () const
missing_t * missing ()
Return missing from the master.
void run_callback ()
Internal function to run (App) callback, top down.
bool _valid_subcommand (const std::string &current) const
detail::Classifer _recognize (const std::string &current) const
Selects a Classifer enum based on the type of the current argument.
void _parse (std::vector< std::string > &args)
Internal parse function.
bool _parse_ini (std::vector< detail::ini_ret_t > &args)
void _parse_single (std::vector< std::string > &args, bool &positional_only)
Parse "one" argument (some may eat more than one), delegate to parent if fails, add to missing if missing from master.
void _parse_positional (std::vector< std::string > &args)
Parse a positional, go up the tree to check.
void _parse_subcommand (std::vector< std::string > &args)
void _parse_short (std::vector< std::string > &args)
Parse a short argument, must be at the top of the list.
void _parse_long (std::vector< std::string > &args)
Parse a long argument, must be at the top of the list.
Protected Attributes
Basics
std::string name_ {"program"}
Subcommand name or program name (from parser)
std::string description_
Description of the current program/subcommand.
bool allow_extras_ {false}
If true, allow extra arguments (ie, don't throw an error).
std::function< void()> callback_
This is a function that runs when complete. Great for subcommands. Can throw.
Options
std::vector< Option_p > options_
The list of options, stored locally.
Option * help_ptr_ {nullptr}
A pointer to the help flag if there is one.
Subcommands
std::vector< App_p > subcommands_
Storage for subcommand list.
bool ignore_case_ {false}
If true, the program name is not case sensitive.
bool fallthrough_ {false}
Allow subcommand fallthrough, so that parent commands can collect commands after subcommand.
App * parent_ {nullptr}
A pointer to the parent if this is a subcommand.
std::vector< App * > selected_subcommands_
A list of all the subcommand pointers that have been collected on the command line.
int require_subcommand_ = 0
-1 for 1 or more, 0 for not required, # for exact number required
Config
std::string config_name_
The name of the connected config file.
bool config_required_ {false}
True if ini is required (throws if not present), if false simply keep going.
Option * config_ptr_ {nullptr}
Pointer to the config option.
Parsing
typedef std::vector< std::pair< detail::Classifer, std::string > > missing_t
missing_t missing_
std::vector< std::string > parse (int argc, char **argv)
std::vector< std::string > & parse (std::vector< std::string > &args)
int exit (const Error &e) const
Print a nice error message and return the exit code.
void reset ()
Reset the parsed data.
Detailed Description
Creates a command line program, with very few defaults.
To use, create a new Program() instance with argc, argv, and a help description. The templated add_option methods make it easy to prepare options. Remember to call .start before starting your program, so that the options can be evaluated and the help option doesn't accidentally run your program.
Definition at line 1282 of file CLI11.hpp.
Member Typedef Documentation
missing_t
typedef std::vector<std::pair<detail::Classifer, std::string> > CLI::App::missing_t protected
Definition at line 1318 of file CLI11.hpp.
Constructor & Destructor Documentation
App() [1/2]
CLI::App::App (std::string description_, bool help, detail::enabler) inline protected
Special private constructor for subcommand.
Definition at line 1364 of file CLI11.hpp.
         :  description_(description_) {
         if(help)
             help_ptr_ = add_flag("-h,--help", "Print this help message and exit");
     }
App() [2/2]
CLI::App::App (std::string description_ = "", bool help = true) inline
Create a new program. Pass in the same arguments as main(), along with a help string.
Definition at line 1377 of file CLI11.hpp.
         : App(description_, help, detail::dummy) {
     }
Member Function Documentation
_parse()
void CLI::App::_parse (std::vector< std::string > & args) inline protected
Internal parse function.
Definition at line 2004 of file CLI11.hpp.
References CLI::Option::count(), CLI::Option::excludes_, CLI::Option::get_name(), CLI::detail::parse_ini(), CLI::detail::POSITIONAL_MARK, CLI::Option::requires_, and CLI::detail::rjoin().
{
         bool positional_only = false;
         while(args.size()>0) {
             _parse_single(args, positional_only);
         }
         if (help_ptr_ != nullptr && help_ptr_->count() > 0) {
             throw CallForHelp();
         }
         // Process an INI file
         if (config_ptr_ != nullptr && config_name_ != "") {
             try {
                 std::vector<detail::ini_ret_t> values = detail::parse_ini(config_name_);
                 while(values.size() > 0) {
                     if(!_parse_ini(values)) {
                         throw ExtrasINIError(values.back().fullname);
                     }
                 }
             } catch (const FileError &) {
                 if(config_required_)
                     throw;
             }
         }
         // Get envname options if not yet passed
         for(const Option_p& opt : options_) {
             if (opt->count() == 0 && opt->envname_ != "") {
                 char *ename = std::getenv(opt->envname_.c_str());
                 if(ename != nullptr) {
                     opt->add_result(std::string(ename));
                 }
             }
         }
         // Process callbacks
         for(const Option_p& opt : options_) {
             if (opt->count() > 0 && !opt->get_callback_run()) {
                 opt->run_callback();
             }
         }
         // Verify required options
         for(const Option_p& opt : options_) {
             // Required
             if (opt->get_required()
                     && (opt->count() < opt->get_expected() || opt->count() == 0))
                 throw RequiredError(opt->get_name());
             // Requires
             for (const Option* opt_req : opt->requires_)
                 if (opt->count() > 0 && opt_req->count() == 0)
                     throw RequiresError(opt->get_name(), opt_req->get_name());
             // Excludes
             for (const Option* opt_ex : opt->excludes_)
                 if (opt->count() > 0 && opt_ex->count() != 0)
                     throw ExcludesError(opt->get_name(), opt_ex->get_name());
         }
         if(require_subcommand_ < 0 && selected_subcommands_.size() == 0)
             throw RequiredError("Subcommand required");
         else if(require_subcommand_ > 0 && (int) selected_subcommands_.size() != require_subcommand_)
             throw RequiredError(std::to_string(require_subcommand_) + " subcommand(s) required");
         // Convert missing (pairs) to extras (string only)
         if(parent_ == nullptr) {
             args.resize(missing()->size());
             std::transform(std::begin(*missing()), std::end(*missing()), std::begin(args),
                     [](const std::pair<detail::Classifer, std::string>& val){return val.second;});
             std::reverse(std::begin(args), std::end(args));
             size_t num_left_over = std::count_if(std::begin(*missing()), std::end(*missing()),
                     [](std::pair<detail::Classifer, std::string>& val){return val.first != detail::Classifer::POSITIONAL_MARK;});
             if(num_left_over>0 && !allow_extras_)
                 throw ExtrasError("[" + detail::rjoin(args, " ") + "]");
         }
     }
_parse_ini()
bool CLI::App::_parse_ini (std::vector< detail::ini_ret_t > & args) inline protected
Parse one ini param, return false if not found in any subcommand, remove if it is
If this has more than one dot.separated.name, go into the subcommand matching it Returns true if it managed to find the option, if false you'll need to remove the arg manully.
Definition at line 2089 of file CLI11.hpp.
References CLI::detail::ini_ret_t::fullname, CLI::detail::ini_ret_t::inputs, CLI::detail::ini_ret_t::level, CLI::detail::ini_ret_t::name(), CLI::detail::ini_ret_t::parent(), and CLI::detail::to_lower().
{
         detail::ini_ret_t& current = args.back();
         std::string parent = current.parent(); // respects curent.level
         std::string name = current.name();
         // If a parent is listed, go to a subcommand
         if(parent != "") {
             current.level++;
             for(const App_p &com : subcommands_)
                 if(com->check_name(parent))
                     return com->_parse_ini(args);
             return false;
         }
         auto op_ptr = std::find_if(std::begin(options_), std::end(options_),
                 [name](const Option_p &v){return v->check_lname(name);});
         if(op_ptr == std::end(options_))
             return false;
         // Let's not go crazy with pointer syntax
         Option_p& op = *op_ptr;
         if(op->results_.empty()) {
             // Flag parsing
             if(op->get_expected() == 0) {
                 if(current.inputs.size() == 1) {
                     std::string val = current.inputs.at(0);
                     val = detail::to_lower(val);
                     if(val == "true" || val == "on" || val == "yes")
                         op->results_ = {""};
                     else if(val == "false" || val == "off" || val == "no")
                         ;
                     else
                         try {
                             size_t ui = std::stoul(val);
                             for (size_t i=0; i<ui; i++)
                                 op->results_.push_back("");
                         } catch (const std::invalid_argument &) {
                             throw ConversionError(current.fullname + ": Should be true/false or a number");
                         }
                 } else
                     throw ConversionError(current.fullname + ": too many inputs for a flag");
             } else {
                 op->results_ = current.inputs;
                 op->run_callback();
             }
         }
         args.pop_back();
         return true;
     }
_parse_long()
void CLI::App::_parse_long (std::vector< std::string > & args) inline protected
Parse a long argument, must be at the top of the list.
Definition at line 2277 of file CLI11.hpp.
References _parse_long(), CLI::detail::LONG, CLI::detail::NONE, and CLI::detail::split_long().
Referenced by _parse_long().
{
         std::string current = args.back();
         std::string name;
         std::string value;
         if(!detail::split_long(current, name, value))
             throw HorribleError("Long:" + args.back());
         auto op_ptr = std::find_if(std::begin(options_), std::end(options_), [name](const Option_p &v){return v->check_lname(name);});
         // Option not found
         if(op_ptr == std::end(options_)) {
             // If a subcommand, try the master command
             if(parent_ != nullptr && fallthrough_)
                 return parent_->_parse_long(args);
             // Otherwise, add to missing
             else {
                 args.pop_back();
                 missing()->emplace_back(detail::Classifer::LONG, current);
                 return;
             }
         }
         args.pop_back();
         // Get a reference to the pointer to make syntax bearable
         Option_p& op = *op_ptr;
         int num = op->get_expected();
         if(value != "") {
             if(num!=-1) num--;
             op->add_result(value);
         } else if (num == 0) {
             op->add_result("");
         }
         if(num == -1) {
             while(args.size() > 0 && _recognize(args.back()) == detail::Classifer::NONE) {
                 op->add_result(args.back());
                 args.pop_back();
             }
         } else while(num>0 && args.size()>0) {
             num--;
             op->add_result(args.back());
             args.pop_back();
         }
         return;
     }
_parse_positional()
void CLI::App::_parse_positional (std::vector< std::string > & args) inline protected
Parse a positional, go up the tree to check.
Definition at line 2173 of file CLI11.hpp.
References _parse_positional(), and CLI::detail::NONE.
Referenced by _parse_positional().
{
         std::string positional = args.back();
         for(const Option_p& opt : options_) {
             // Eat options, one by one, until done
             if (    opt->get_positional()
                     && (opt->count() < opt->get_expected()
                         || opt->get_expected() < 0)
                     ) {
                 opt->add_result(positional);
                 args.pop_back();
                 return;
             }
         }
         if(parent_ != nullptr && fallthrough_)
             return parent_->_parse_positional(args);
         else {
             args.pop_back();
             missing()->emplace_back(detail::Classifer::NONE, positional);
         }
     }
_parse_short()
void CLI::App::_parse_short (std::vector< std::string > & args) inline protected
Parse a short argument, must be at the top of the list.
Definition at line 2216 of file CLI11.hpp.
References _parse_short(), CLI::detail::NONE, CLI::detail::SHORT, and CLI::detail::split_short().
Referenced by _parse_short().
{
         std::string current = args.back();
         std::string name;
         std::string rest;
         if(!detail::split_short(current, name, rest))
             throw HorribleError("Short");
         auto op_ptr = std::find_if(std::begin(options_), std::end(options_), [name](const Option_p &opt){return opt->check_sname(name);});
         // Option not found
         if(op_ptr == std::end(options_)) {
             // If a subcommand, try the master command
             if(parent_ != nullptr && fallthrough_)
                 return parent_->_parse_short(args);
             // Otherwise, add to missing
             else {
                 args.pop_back();
                 missing()->emplace_back(detail::Classifer::SHORT, current);
                 return;
             }
         }
         args.pop_back();
         // Get a reference to the pointer to make syntax bearable
         Option_p& op = *op_ptr;
         int num = op->get_expected();
         if(num == 0)
             op->add_result("");
         else if(rest!="") {
             if (num > 0)
                 num--;
             op->add_result(rest);
             rest = "";
         }
         if(num == -1) {
             while(args.size()>0 && _recognize(args.back()) == detail::Classifer::NONE) {
                 op->add_result(args.back());
                 args.pop_back();
             }
         } else while(num>0 && args.size() > 0) {
             num--;
             std::string current_ = args.back();
             args.pop_back();
             op->add_result(current_);
         }
         if(rest != "") {
             rest = "-" + rest;
             args.push_back(rest);
         }
     }
_parse_single()
void CLI::App::_parse_single (std::vector< std::string > & args, bool & positional_only) inline protected
Parse "one" argument (some may eat more than one), delegate to parent if fails, add to missing if missing from master.
Definition at line 2144 of file CLI11.hpp.
References CLI::detail::LONG, CLI::detail::NONE, CLI::detail::POSITIONAL_MARK, CLI::detail::SHORT, and CLI::detail::SUBCOMMAND.
{
         detail::Classifer classifer = positional_only ? detail::Classifer::NONE : _recognize(args.back());
         switch(classifer) {
         case detail::Classifer::POSITIONAL_MARK:
             missing()->emplace_back(classifer, args.back());
             args.pop_back();
             positional_only = true;
             break;
         case detail::Classifer::SUBCOMMAND:
             _parse_subcommand(args);
             break;
         case detail::Classifer::LONG:
             // If already parsed a subcommand, don't accept options_
             _parse_long(args);
             break;
         case detail::Classifer::SHORT:
             // If already parsed a subcommand, don't accept options_
             _parse_short(args);
             break;
         case detail::Classifer::NONE:
             // Probably a positional or something for a parent (sub)command
             _parse_positional(args);
         }
     }
_parse_subcommand()
void CLI::App::_parse_subcommand (std::vector< std::string > & args) inline protected
Parse a subcommand, modify args and continue
Unlike the others, this one will always allow fallthrough
Definition at line 2200 of file CLI11.hpp.
References _parse_subcommand().
Referenced by _parse_subcommand().
{
         for(const App_p &com : subcommands_) {
             if(com->check_name(args.back())){
                 args.pop_back();
                 selected_subcommands_.push_back(com.get());
                 com->_parse(args);
                 return;
             }
         }
         if(parent_ != nullptr)
             return parent_->_parse_subcommand(args);
         else
             throw HorribleError("Subcommand " + args.back() + " missing");
     }
_recognize()
detail::Classifer CLI::App::_recognize (const std::string & current) const inline protected
Selects a Classifer enum based on the type of the current argument.
Definition at line 1988 of file CLI11.hpp.
References CLI::detail::LONG, CLI::detail::NONE, CLI::detail::POSITIONAL_MARK, CLI::detail::SHORT, CLI::detail::split_long(), CLI::detail::split_short(), and CLI::detail::SUBCOMMAND.
{
         std::string dummy1, dummy2;
         if(current == "--")
             return detail::Classifer::POSITIONAL_MARK;
         if(_valid_subcommand(current))
             return detail::Classifer::SUBCOMMAND;
         if(detail::split_long(current, dummy1, dummy2))
             return detail::Classifer::LONG;
         if(detail::split_short(current, dummy1, dummy2))
             return detail::Classifer::SHORT;
         return detail::Classifer::NONE;
     }
_valid_subcommand()
bool CLI::App::_valid_subcommand (const std::string & current) const inline protected
Definition at line 1976 of file CLI11.hpp.
References _valid_subcommand().
Referenced by _valid_subcommand().
{
         for(const App_p &com : subcommands_)
             if(com->check_name(current))
                 return true;
         if(parent_ != nullptr)
             return parent_->_valid_subcommand(current);
         else
             return false;
     }
_validate()
void CLI::App::_validate () const inline protected
Check the options to make sure there are no conficts.
Currenly checks to see if mutiple positionals exist with -1 args
Definition at line 1949 of file CLI11.hpp.
{
         auto count = std::count_if(std::begin(options_), std::end(options_),
                 [](const Option_p& opt){return opt->get_expected() == -1 && opt->get_positional();});
         if(count > 1)
             throw InvalidError(name_ + ": Too many positional arguments with unlimited expected args");
         for(const App_p& app : subcommands_)
             app->_validate();
     }
add_config()
Option* CLI::App::add_config (std::string name = "--config", std::string default_filename = "", std::string help = "Read an ini file", bool required = false) inline
Add a configuration ini file option.
Definition at line 1644 of file CLI11.hpp.
{
         // Remove existing config if present
         if(config_ptr_ != nullptr)
             remove_option(config_ptr_);
         config_name_ = default_filename;
         config_required_ = required;
         config_ptr_ = add_option(name, config_name_, help, default_filename!="");
         return config_ptr_;
     }
add_flag() [1/3]
Option* CLI::App::add_flag (std::string name, std::string description = "") inline
Add option for flag.
Definition at line 1516 of file CLI11.hpp.
References CLI::detail::dummy, CLI::Option::get_positional(), CLI::IncorrectConstruction, and CLI::Option::set_custom_option().
               {
         CLI::callback_t fun = [](CLI::results_t){
             return true;
         };
         Option* opt = add_option(name, fun, description, false);
         if(opt->get_positional())
             throw IncorrectConstruction("Flags cannot be positional");
         opt->set_custom_option("", 0);
         return opt;
     }
add_flag() [2/3]
template<typename T , enable_if_t< std::is_integral< T >::value &&!is_bool< T >::value, detail::enabler > = detail::dummy> Option* CLI::App::add_flag (std::string name, T & count, std::string description = "") inline
Add option for flag integer.
Parameters
count A varaible holding the count
Definition at line 1534 of file CLI11.hpp.
References CLI::detail::dummy, CLI::Option::get_positional(), CLI::IncorrectConstruction, and CLI::Option::set_custom_option().
               {
         count = 0;
         CLI::callback_t fun = [&count](CLI::results_t res){
             count = (T) res.size();
             return true;
         };
         Option* opt = add_option(name, fun, description, false);
         if(opt->get_positional())
             throw IncorrectConstruction("Flags cannot be positional");
         opt->set_custom_option("", 0);
         return opt;
     }
add_flag() [3/3]
template<typename T , enable_if_t< is_bool< T >::value, detail::enabler > = detail::dummy> Option* CLI::App::add_flag (std::string name, T & count, std::string description = "") inline
Bool version only allows the flag once.
Parameters
count A varaible holding true if passed
Definition at line 1556 of file CLI11.hpp.
References CLI::Option::get_positional(), CLI::IncorrectConstruction, and CLI::Option::set_custom_option().
               {
         count = false;
         CLI::callback_t fun = [&count](CLI::results_t res){
             count = true;
             return res.size() == 1;
         };
         Option* opt = add_option(name, fun, description, false);
         if(opt->get_positional())
             throw IncorrectConstruction("Flags cannot be positional");
         opt->set_custom_option("", 0);
         return opt;
     }
add_option() [1/3]
Option* CLI::App::add_option (std::string name, callback_t callback, std::string description = "", bool defaulted = false) inline
Add an option, will automatically understand the type for common types.
To use, create a variable with the expected type, and pass it in after the name. After start is called, you can use count to see if the value was passed, and the value will be initialized properly. Numbers, vectors, and strings are supported.
->required(), ->default, and the validators are options, The positional options take an optional number of arguments.
For example,
std::string filename;
program.add_option("filename", filename, "description of filename");
Definition at line 1444 of file CLI11.hpp.
References CLI::detail::dummy, and CLI::OptionAlreadyAdded.
               {
         Option myopt{name, description, callback, defaulted, this};
         if(std::find_if(std::begin(options_), std::end(options_),
                     [&myopt](const Option_p &v){return *v == myopt;}) == std::end(options_)) {
             options_.emplace_back();
             Option_p& option = options_.back();
             option.reset(new Option(name, description, callback, defaulted, this));
             return option.get();
         } else
             throw OptionAlreadyAdded(myopt.get_name());
     }
add_option() [2/3]
template<typename T , enable_if_t<!is_vector< T >::value, detail::enabler > = detail::dummy> Option* CLI::App::add_option (std::string name, T & variable, std::string description = "", bool defaulted = false) inline
Add option for non-vectors.
Parameters
variable The variable to set
Definition at line 1465 of file CLI11.hpp.
References CLI::detail::lexical_cast(), CLI::Option::set_custom_option(), and CLI::Option::set_default_val().
               {
         CLI::callback_t fun = [&variable](CLI::results_t res){
             if(res.size()!=1)
                 return false;
             return detail::lexical_cast(res[0], variable);
         };
         Option* opt = add_option(name, fun, description, defaulted);
         opt->set_custom_option(detail::type_name<T>());
         if(defaulted) {
             std::stringstream out;
             out << variable;
             opt->set_default_val(out.str());
         }
         return opt;
     }
add_option() [3/3]
template<typename T > Option* CLI::App::add_option (std::string name, std::vector< T > & variable, std::string description = "", bool defaulted = false) inline
Add option for vectors.
Parameters
variable The variable vector to set
Definition at line 1491 of file CLI11.hpp.
References CLI::Option::clear(), CLI::detail::join(), CLI::detail::lexical_cast(), CLI::Option::set_custom_option(), and CLI::Option::set_default_val().
               {
         CLI::callback_t fun = [&variable](CLI::results_t res){
             bool retval = true;
             variable.clear();
             for(const auto &a : res) {
                 variable.emplace_back();
                 retval &= detail::lexical_cast(a, variable.back());
             }
             return variable.size() > 0 && retval;
         };
         Option* opt =  add_option(name, fun, description, defaulted);
         opt->set_custom_option(detail::type_name<T>(), -1, true);
         if(defaulted)
             opt->set_default_val("[" + detail::join(variable) + "]");
         return opt;
     }
add_set()
template<typename T > Option* CLI::App::add_set (std::string name, T & member, std::set< T > options, std::string description = "", bool defaulted = false) inline
Add set of options.
Parameters
member The selected member of the set
options The set of posibilities
Definition at line 1578 of file CLI11.hpp.
References CLI::detail::join(), CLI::detail::lexical_cast(), CLI::Option::set_custom_option(), and CLI::Option::set_default_val().
               {
         CLI::callback_t fun = [&member, options](CLI::results_t res){
             if(res.size()!=1) {
                 return false;
             }
             bool retval = detail::lexical_cast(res[0], member);
             if(!retval)
                 return false;
             return std::find(std::begin(options), std::end(options), member) != std::end(options);
         };
         Option* opt = add_option(name, fun, description, defaulted);
         std::string typeval = detail::type_name<T>();
         typeval += " in {" + detail::join(options) + "}";
         opt->set_custom_option(typeval);
         if(defaulted) {
             std::stringstream out;
             out << member;
             opt->set_default_val(out.str());
         }
         return opt;
     }
add_set_ignore_case()
Option* CLI::App::add_set_ignore_case (std::string name, std::string & member, std::set< std::string > options, std::string description = "", bool defaulted = false) inline
Add set of options, string only, ignore case.
Parameters
member The selected member of the set
options The set of posibilities
Definition at line 1609 of file CLI11.hpp.
References CLI::detail::join(), CLI::Option::set_custom_option(), CLI::Option::set_default_val(), and CLI::detail::to_lower().
               {
         CLI::callback_t fun = [&member, options](CLI::results_t res){
             if(res.size()!=1) {
                 return false;
             }
             member = detail::to_lower(res[0]);
             auto iter = std::find_if(std::begin(options), std::end(options),
                     [&member](std::string val){return detail::to_lower(val) == member;});
             if(iter == std::end(options))
                 return false;
             else {
                 member = *iter;
                 return true;
             }
         };
         Option* opt = add_option(name, fun, description, defaulted);
         std::string typeval = detail::type_name<std::string>();
         typeval += " in {" + detail::join(options) + "}";
         opt->set_custom_option(typeval);
         if(defaulted) {
             opt->set_default_val(member);
         }
         return opt;
     }
add_subcommand()
App* CLI::App::add_subcommand (std::string name, std::string description = "", bool help = true) inline
Add a subcommand. Like the constructor, you can override the help message addition by setting help=false.
Definition at line 1674 of file CLI11.hpp.
References CLI::detail::dummy, name_, and CLI::OptionAlreadyAdded.
{
         subcommands_.emplace_back(new App(description, help, detail::dummy));
         subcommands_.back()->name_ = name;
         subcommands_.back()->allow_extras();
         subcommands_.back()->parent_ = this;
         subcommands_.back()->ignore_case_ = ignore_case_;
         subcommands_.back()->fallthrough_ = fallthrough_;
         for(const auto& subc : subcommands_)
             if(subc.get() != subcommands_.back().get())
                 if(subc->check_name(subcommands_.back()->name_) || subcommands_.back()->check_name(subc->name_))
                     throw OptionAlreadyAdded(subc->name_);
         return subcommands_.back().get();
     }
allow_extras()
App* CLI::App::allow_extras (bool allow = true) inline
Remove the error when extras are left over on the command line.
Definition at line 1394 of file CLI11.hpp.
{
         allow_extras_ = allow;
         return this;
     }
check_name()
bool CLI::App::check_name (std::string name_to_check) const inline
Check the name, case insensitive if set.
Definition at line 1931 of file CLI11.hpp.
References CLI::detail::to_lower().
{
         std::string local_name = name_;
         if(ignore_case_) {
             local_name = detail::to_lower(name_);
             name_to_check = detail::to_lower(name_to_check);
         }
         return local_name == name_to_check;
     }
config_to_str()
std::string CLI::App::config_to_str (bool default_also = false, std::string prefix = "") const inline
Produce a string that could be read in as a config of the current values of the App. Set default_also to include default arguments. Prefix will add a string to the beginning of each option.
Definition at line 1791 of file CLI11.hpp.
References CLI::detail::inijoin().
{
         std::stringstream out;
         for(const Option_p &opt : options_) {
             // Only process option with a long-name
             if(opt->lnames_.size() > 0) {
                 std::string name = prefix + opt->lnames_[0];
                 // Non-flags
                 if(opt->get_expected() != 0) {
                     // If the option was found on command line
                     if(opt->count() > 0)
                         out << name << "=" << detail::inijoin(opt->results()) << std::endl;
                     // If the option has a default and is requested by optional argument
                     else if(default_also && opt->defaultval_ != "")
                         out << name << "=" << opt->defaultval_ << std::endl;
                 // Flag, one passed
                 } else if(opt->count() == 1) {
                     out << name << "=true" << std::endl;
                 // Flag, multiple passed
                 } else if(opt->count() > 1) {
                     out << name << "=" << opt->count() << std::endl;
                 }
             }
         }
         for(const App_p &subcom : subcommands_)
             out << subcom->config_to_str(default_also, prefix + subcom->name_ + ".");
         return out.str();
     }
count()
int CLI::App::count (std::string name) const inline
Counts the number of times the given option was passed.
Definition at line 1756 of file CLI11.hpp.
References CLI::OptionNotFound.
{
         for(const Option_p &opt : options_) {
             if(opt->check_name(name)) {
                 return opt->count();
             }
         }
         throw OptionNotFound(name);
     }
exit()
int CLI::App::exit (const Error & e) const inline
Print a nice error message and return the exit code.
Definition at line 1724 of file CLI11.hpp.
References CLI::Error::exit_code, CLI::Error::get_exit_code(), CLI::Error::print_help, and CLI::Success.
Referenced by GooFit::Application::exit().
{
         if(e.exit_code != ExitCodes::Success) {
             std::cerr << "ERROR: ";
             std::cerr << e.what() << std::endl;
             if(e.print_help)
                 std::cerr << help();
         } else {
             if(e.print_help)
                 std::cout << help();
         }
         return e.get_exit_code();
     }
fallthrough()
App* CLI::App::fallthrough (bool value = true) inline
Stop subcommand fallthrough, so that parent commands cannot collect commands after subcommand. Default from parent, usually set on parent.
Definition at line 1420 of file CLI11.hpp.
{
         fallthrough_ = value;
         return this;
     }
get_config_ptr()
Option* CLI::App::get_config_ptr () inline
Get a pointer to the config option.
Definition at line 1921 of file CLI11.hpp.
{
         return config_ptr_;
     }
get_help_ptr()
Option* CLI::App::get_help_ptr () inline
Get a pointer to the help flag.
Definition at line 1916 of file CLI11.hpp.
{
         return help_ptr_;
     }
get_name()
std::string CLI::App::get_name () const inline
Get the name of the current app.
Definition at line 1926 of file CLI11.hpp.
{
         return name_;
     }
get_subcommands()
std::vector<App*> CLI::App::get_subcommands () inline
Get a subcommand pointer list to the currently selected subcommands (after parsing)
Definition at line 1766 of file CLI11.hpp.
{
         return selected_subcommands_;
     }
got_subcommand() [1/2]
bool CLI::App::got_subcommand (App * subcom) const inline
Check to see if selected subcommand in list.
Definition at line 1772 of file CLI11.hpp.
{
         return std::find(std::begin(selected_subcommands_),
                          std::end(selected_subcommands_), subcom)
                            != std::end(selected_subcommands_);
     }
got_subcommand() [2/2]
bool CLI::App::got_subcommand (std::string name) const inline
Check with name instead of pointer.
Definition at line 1779 of file CLI11.hpp.
References CLI::OptionNotFound.
{
         for(const App_p &subcomptr : subcommands_)
             if(subcomptr->check_name(name))
                 return got_subcommand(subcomptr.get());
         throw CLI::OptionNotFound(name);
     }
help()
std::string CLI::App::help (size_t wid = 30, std::string prev = "") const inline
Makes a help message, with a column wid for column 1.
Definition at line 1825 of file CLI11.hpp.
References CLI::detail::format_help(), and CLI::detail::to_lower().
{
         // Delegate to subcommand if needed
         if(prev == "")
             prev = name_;
         else
             prev += " " + name_;
         if(selected_subcommands_.size() > 0)
             return selected_subcommands_.at(0)->help(wid, prev);
         std::stringstream out;
         out << description_ << std::endl;
         out << "Usage: " << prev;
         // Check for options_
         bool npos = false;
         std::set<std::string> groups;
         for(const Option_p &opt : options_) {
             if(opt->nonpositional()) {
                 npos = true;
                 groups.insert(opt->get_group());
             }
         }
         if(npos)
             out << " [OPTIONS]";
         // Positionals
         bool pos=false;
         for(const Option_p &opt : options_)
             if(opt->get_positional()) {
                 // A hidden positional should still show up in the usage statement
                 //if(detail::to_lower(opt->get_group()) == "hidden")
                 //    continue;
                 out << " " << opt->help_positional();
                 if(opt->_has_help_positional())
                     pos=true;
             }
         if(subcommands_.size() > 0) {
             if(require_subcommand_ != 0)
                 out << " SUBCOMMAND";
             else
                 out << " [SUBCOMMAND]";
         }
         out << std::endl << std::endl;
         // Positional descriptions
         if(pos) {
             out << "Positionals:" << std::endl;
             for(const Option_p &opt : options_) {
                 if(detail::to_lower(opt->get_group()) == "hidden")
                     continue;
                 if(opt->_has_help_positional())
                     detail::format_help(out, opt->help_pname(), opt->get_description(), wid);
             }
             out << std::endl;
         }
         // Options
         if(npos) {
             for (const std::string& group : groups) {
                 if(detail::to_lower(group) == "hidden")
                     continue;
                 out << group << ":" << std::endl;
                 for(const Option_p &opt : options_) {
                     if(opt->nonpositional() && opt->get_group() == group)
                         detail::format_help(out, opt->help_name(), opt->get_description(), wid);
                 }
                 out << std::endl;
             }
         }
         // Subcommands
         if(subcommands_.size()> 0) {
             out << "Subcommands:" << std::endl;
             for(const App_p &com : subcommands_)
                 detail::format_help(out, com->get_name(), com->description_, wid);
         }
         return out.str();
     }
ignore_case()
App* CLI::App::ignore_case (bool value = true) inline
Ignore case. Subcommand inherit value.
Definition at line 1400 of file CLI11.hpp.
References CLI::OptionAlreadyAdded, and subcommands_.
{
         ignore_case_ = value;
         if(parent_ != nullptr) {
             for(const auto &subc : parent_->subcommands_) {
                 if(subc.get() != this && (this->check_name(subc->name_) || subc->check_name(this->name_)))
                     throw OptionAlreadyAdded(subc->name_);
             }
         }
         return this;
     }
missing()
missing_t* CLI::App::missing () inline protected
Return missing from the master.
Definition at line 1960 of file CLI11.hpp.
References missing().
Referenced by missing().
{
         if(parent_ != nullptr)
             return parent_->missing();
         return &missing_;
     }
parse() [1/2]
std::vector<std::string> CLI::App::parse (int argc, char ** argv) inline
Parses the command line - throws errors This must be called after the options are in but before the rest of the program.
Definition at line 1705 of file CLI11.hpp.
{
         name_ = argv[0];
         std::vector<std::string> args;
         for(int i=argc-1; i>0; i--)
             args.push_back(argv[i]);
         return parse(args);
     }
parse() [2/2]
std::vector<std::string>& CLI::App::parse (std::vector< std::string > & args) inline
The real work is done here. Expects a reversed vector. Changes the vector to the remaining options.
Definition at line 1716 of file CLI11.hpp.
{
         _validate();
         _parse(args);
         run_callback();
         return args;
     }
pre_callback()
virtual void CLI::App::pre_callback () inline virtual
This allows subclasses to inject code before callbacks but after parse.
This does not run if any errors or help is thrown.
Reimplemented in GooFit::Application.
Definition at line 1697 of file CLI11.hpp.
 {}
remove_option()
bool CLI::App::remove_option (Option * opt) inline
Removes an option from the App. Takes an option pointer. Returns true if found and removed.
Definition at line 1659 of file CLI11.hpp.
{
         auto iterator = std::find_if(std::begin(options_), std::end(options_),
                 [opt](const Option_p &v){return v.get() == opt;});
         if (iterator != std::end(options_)) {
             options_.erase(iterator);
             return true;
         }
         return false;
     }
require_subcommand()
App* CLI::App::require_subcommand (int value = -1) inline
Require a subcommand to be given (does not affect help call) Does not return a pointer since it is supposed to be called on the main App.
Definition at line 1413 of file CLI11.hpp.
{
         require_subcommand_ = value;
         return this;
     }
reset()
void CLI::App::reset () inline
Reset the parsed data.
Definition at line 1738 of file CLI11.hpp.
                  {
         selected_subcommands_.clear();
         missing_.clear();
         for(const Option_p &opt : options_) {
             opt->clear();
         }
         for(const App_p &app : subcommands_) {
             app->reset();
         }
     }
run_callback()
void CLI::App::run_callback () inline protected
Internal function to run (App) callback, top down.
Definition at line 1967 of file CLI11.hpp.
{
         pre_callback();
         if(callback_)
             callback_();
         for(App* subc : selected_subcommands_) {
             subc->run_callback();
         }
     }
set_callback()
App* CLI::App::set_callback (std::function< void()> callback) inline
Set a callback for the end of parsing.
Due to a bug in c++11, it is not possible to overload on std::function (fixed in c++14 and backported to c++11 on newer compilers). Use capture by reference to get a pointer to App if needed.
Definition at line 1388 of file CLI11.hpp.
{
         callback_ = callback;
         return this;
     }
Member Data Documentation
allow_extras_
bool CLI::App::allow_extras_ {false} protected
If true, allow extra arguments (ie, don't throw an error).
Definition at line 1299 of file CLI11.hpp.
callback_
std::function<void()> CLI::App::callback_ protected
This is a function that runs when complete. Great for subcommands. Can throw.
Definition at line 1302 of file CLI11.hpp.
config_name_
std::string CLI::App::config_name_ protected
The name of the connected config file.
Definition at line 1352 of file CLI11.hpp.
config_ptr_
Option* CLI::App::config_ptr_ {nullptr} protected
Pointer to the config option.
Definition at line 1358 of file CLI11.hpp.
config_required_
bool CLI::App::config_required_ {false} protected
True if ini is required (throws if not present), if false simply keep going.
Definition at line 1355 of file CLI11.hpp.
description_
std::string CLI::App::description_ protected
Description of the current program/subcommand.
Definition at line 1296 of file CLI11.hpp.
fallthrough_
bool CLI::App::fallthrough_ {false} protected
Allow subcommand fallthrough, so that parent commands can collect commands after subcommand.
Definition at line 1336 of file CLI11.hpp.
help_ptr_
Option* CLI::App::help_ptr_ {nullptr} protected
A pointer to the help flag if there is one.
Definition at line 1312 of file CLI11.hpp.
ignore_case_
bool CLI::App::ignore_case_ {false} protected
If true, the program name is not case sensitive.
Definition at line 1333 of file CLI11.hpp.
missing_
missing_t CLI::App::missing_ protected
Pair of classifier, string for missing options. (extra detail is removed on returning from parse)
This is faster and cleaner than storing just a list of strings and reparsing. This may contain the – separator.
Definition at line 1323 of file CLI11.hpp.
name_
std::string CLI::App::name_ {"program"} protected
Subcommand name or program name (from parser)
Definition at line 1293 of file CLI11.hpp.
Referenced by add_subcommand().
options_
std::vector<Option_p> CLI::App::options_ protected
The list of options, stored locally.
Definition at line 1309 of file CLI11.hpp.
parent_
App* CLI::App::parent_ {nullptr} protected
A pointer to the parent if this is a subcommand.
Definition at line 1339 of file CLI11.hpp.
require_subcommand_
int CLI::App::require_subcommand_ = 0 protected
-1 for 1 or more, 0 for not required, # for exact number required
Definition at line 1345 of file CLI11.hpp.
selected_subcommands_
std::vector<App*> CLI::App::selected_subcommands_ protected
A list of all the subcommand pointers that have been collected on the command line.
Definition at line 1342 of file CLI11.hpp.
subcommands_
std::vector<App_p> CLI::App::subcommands_ protected
Storage for subcommand list.
Definition at line 1330 of file CLI11.hpp.
Referenced by ignore_case().
The documentation for this class was generated from the following file:
/home/travis/build/GooFit/GooFit/include/goofit/detail/CLI11.hpp