GooFit: TRandom3 Class Reference
TRandom3 Class Reference
#include <TRandom3.h>
Public Member Functions
TRandom3 (unsigned int seed=4357)
virtual ~TRandom3 ()
virtual unsigned int GetSeed () const
virtual double Rndm (int i=0)
virtual void RndmArray (int n, float *array)
virtual void RndmArray (int n, double *array)
virtual void SetSeed (unsigned int seed=0)
Public Member Functions inherited from TRandom
TRandom (unsigned int seed=65539)
virtual ~TRandom ()
virtual int Binomial (int ntot, double prob)
virtual double BreitWigner (double mean=0, double gamma=1)
virtual void Circle (double &x, double &y, double r)
virtual double Exp (double tau)
virtual double Gaus (double mean=0, double sigma=1)
virtual unsigned int Integer (unsigned int imax)
virtual double Landau (double mean=0, double sigma=1)
virtual int Poisson (double mean)
virtual double PoissonD (double mean)
virtual void Rannor (float &a, float &b)
virtual void Rannor (double &a, double &b)
virtual void Sphere (double &x, double &y, double &z, double r)
virtual double Uniform (double x1=1)
virtual double Uniform (double x1, double x2)
double landau_quantile (double, double)
Additional Inherited Members
Static Public Attributes inherited from TRandom
static TRandom * gRandom = new TRandom3()
Protected Attributes inherited from TRandom
unsigned int fSeed
Detailed Description
Definition at line 30 of file TRandom3.h.
Constructor & Destructor Documentation
TRandom3()
TRandom3::TRandom3 (unsigned int seed = 4357)
Definition at line 52 of file TRandom3.cc.
References SetSeed().
{
 //*-*-*-*-*-*-*-*-*-*-*default constructor*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
 // If seed is 0, the seed is automatically computed via a TUUID object.
 // In this case the seed is guaranteed to be unique in space and time.
     SetSeed(seed);
 }
~TRandom3()
TRandom3::~TRandom3 () virtual
Definition at line 60 of file TRandom3.cc.
                     {
 //*-*-*-*-*-*-*-*-*-*-*default destructor*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
 //*-*                  ==================
 }
Member Function Documentation
GetSeed()
virtual unsigned int TRandom3::GetSeed () const inline virtual
Reimplemented from TRandom.
Definition at line 40 of file TRandom3.h.
References Rndm(), RndmArray(), and SetSeed().
{
         return fMt[0];
     }
Rndm()
double TRandom3::Rndm (int i = 0) virtual
Reimplemented from TRandom.
Definition at line 66 of file TRandom3.cc.
Referenced by GetSeed(), and RndmArray().
{
 //  Machine independent random number generator.
 //  Produces uniformly-distributed floating points in ]0,1]
 //  Method: Mersenne Twistor
     unsigned int y;
     const int  kM = 397;
     const int  kN = 624;
     const unsigned int kTemperingMaskB =  0x9d2c5680;
     const unsigned int kTemperingMaskC =  0xefc60000;
     const unsigned int kUpperMask =       0x80000000;
     const unsigned int kLowerMask =       0x7fffffff;
     const unsigned int kMatrixA =         0x9908b0df;
     if(fCount624 >= kN) {
         register int i;
         for(i=0; i < kN-kM; i++) {
             y = (fMt[i] & kUpperMask) | (fMt[i+1] & kLowerMask);
             fMt[i] = fMt[i+kM] ^ (y >> 1) ^ ((y & 0x1) ? kMatrixA : 0x0);
         }
         for(; i < kN-1    ; i++) {
             y = (fMt[i] & kUpperMask) | (fMt[i+1] & kLowerMask);
             fMt[i] = fMt[i+kM-kN] ^ (y >> 1) ^ ((y & 0x1) ? kMatrixA : 0x0);
         }
         y = (fMt[kN-1] & kUpperMask) | (fMt[0] & kLowerMask);
         fMt[kN-1] = fMt[kM-1] ^ (y >> 1) ^ ((y & 0x1) ? kMatrixA : 0x0);
         fCount624 = 0;
     }
     y = fMt[fCount624++];
     y ^= (y >> 11);
     y ^= ((y << 7) & kTemperingMaskB);
     y ^= ((y << 15) & kTemperingMaskC);
     y ^= (y >> 18);
     if(y)
         return ((double) y * 2.3283064365386963e-10);  // * Power(2,-32)
     return Rndm();
 }
RndmArray() [1/2]
void TRandom3::RndmArray (int n, float * array) virtual
Reimplemented from TRandom.
Definition at line 112 of file TRandom3.cc.
References Rndm().
Referenced by GetSeed().
{
     // Return an array of n random numbers uniformly distributed in ]0,1]
     for(int i=0; i<n; i++)
         array[i]=(float)Rndm();
 }
RndmArray() [2/2]
void TRandom3::RndmArray (int n, double * array) virtual
Reimplemented from TRandom.
Definition at line 120 of file TRandom3.cc.
{
     // Return an array of n random numbers uniformly distributed in ]0,1]
     int k = 0;
     unsigned int y;
     const int  kM = 397;
     const int  kN = 624;
     const unsigned int kTemperingMaskB =  0x9d2c5680;
     const unsigned int kTemperingMaskC =  0xefc60000;
     const unsigned int kUpperMask =       0x80000000;
     const unsigned int kLowerMask =       0x7fffffff;
     const unsigned int kMatrixA =         0x9908b0df;
     while(k < n) {
         if(fCount624 >= kN) {
             register int i;
             for(i=0; i < kN-kM; i++) {
                 y = (fMt[i] & kUpperMask) | (fMt[i+1] & kLowerMask);
                 fMt[i] = fMt[i+kM] ^ (y >> 1) ^ ((y & 0x1) ? kMatrixA : 0x0);
             }
             for(; i < kN-1    ; i++) {
                 y = (fMt[i] & kUpperMask) | (fMt[i+1] & kLowerMask);
                 fMt[i] = fMt[i+kM-kN] ^ (y >> 1) ^ ((y & 0x1) ? kMatrixA : 0x0);
             }
             y = (fMt[kN-1] & kUpperMask) | (fMt[0] & kLowerMask);
             fMt[kN-1] = fMt[kM-1] ^ (y >> 1) ^ ((y & 0x1) ? kMatrixA : 0x0);
             fCount624 = 0;
         }
         y = fMt[fCount624++];
         y ^= (y >> 11);
         y ^= ((y << 7) & kTemperingMaskB);
         y ^= ((y << 15) & kTemperingMaskC);
         y ^= (y >> 18);
         if(y) {
             array[k] = double(y * 2.3283064365386963e-10);  // * Power(2,-32)
             k++;
         }
     }
 }
SetSeed()
void TRandom3::SetSeed (unsigned int seed = 0) virtual
Reimplemented from TRandom.
Definition at line 168 of file TRandom3.cc.
References TRandom::fSeed, and TRandom::SetSeed().
Referenced by GetSeed(), and TRandom3().
{
     //  Set the random generator sequence
     TRandom::SetSeed(seed);
     fCount624 = 624;
     int i, j;
     fMt[0] = fSeed;
     j = 1;
     // use multipliers from  Knuth's "Art of Computer Programming" Vol. 2, 3rd Ed. p.106
     for(i=j; i<624; i++) {
         fMt[i] = (1812433253 * (fMt[i-1]  ^ (fMt[i-1] >> 30)) + i);
     }
 }
The documentation for this class was generated from the following files:
/home/travis/build/GooFit/GooFit/include/goofit/rootstuff/TRandom3.h
/home/travis/build/GooFit/GooFit/src/rootstuff/TRandom3.cc