GooFit: GooFit::DataSet Class Reference
GooFit::DataSet Class Reference abstract
#include <DataSet.h>
Public Member Functions
DataSet (const Observable &var, std::string n="")
DataSet (const std::vector< Observable > &vars, std::string n="")
DataSet (const std::set< Observable > &vars, std::string n="")
DataSet (std::initializer_list< Observable > vars, std::string n="")
virtual ~DataSet ()=default
virtual void addEvent ()=0
virtual void addWeightedEvent (fptype weight)
template<typename... Args>
void addEvent (fptype value, Args... args)
This is a helper that allows multiple values to be passed in instead of relying on the content of the Variables.
const std::vector< Observable > & getObservables () const
size_t numVariables () const
size_t getNumEvents () const
std::string getName () const
Protected Member Functions
std::vector< fptype > getCurrentValues () const
size_t indexOfVariable (const Observable &var) const
void checkAllVars () const
Throw an error if any variables are out of range, call in addEvent.
Protected Attributes
size_t numEventsAdded {0}
std::vector< Observable > observables
Detailed Description
Definition at line 15 of file DataSet.h.
Constructor & Destructor Documentation
DataSet() [1/4]
GooFit::DataSet::DataSet (const Observable & var, std::string n = "")
Definition at line 11 of file DataSet.cpp.
     : name(std::move(n))
     , observables({var}) {
     generateName();
 }
DataSet() [2/4]
GooFit::DataSet::DataSet (const std::vector< Observable > & vars, std::string n = "")
Definition at line 17 of file DataSet.cpp.
     : name(std::move(n))
     , observables(vars) {
     generateName();
 }
DataSet() [3/4]
GooFit::DataSet::DataSet (const std::set< Observable > & vars, std::string n = "")
Definition at line 23 of file DataSet.cpp.
     : name(std::move(n))
     , observables(std::begin(vars), std::end(vars)) {
     generateName();
 }
DataSet() [4/4]
GooFit::DataSet::DataSet (std::initializer_list< Observable > vars, std::string n = "")
Definition at line 29 of file DataSet.cpp.
     : name(std::move(n))
     , observables(vars) {
     generateName();
 }
~DataSet()
virtual GooFit::DataSet::~DataSet () virtual default
Member Function Documentation
addEvent() [1/2]
virtual void GooFit::DataSet::addEvent () pure virtual
Implemented in GooFit::UnbinnedDataSet, and GooFit::BinnedDataSet.
Referenced by addEvent().
addEvent() [2/2]
template<typename... Args> void GooFit::DataSet::addEvent (fptype value, Args... args) inline
This is a helper that allows multiple values to be passed in instead of relying on the content of the Variables.
Definition at line 31 of file DataSet.h.
References addEvent(), getObservables(), and observables.
{
         std::vector<fptype> values{value, static_cast<fptype>(args)...};
         if(values.size() != observables.size())
             throw GooFit::GeneralError("You must pass the correct number of values ({}) to addEvent",
                                        observables.size());
         for(size_t i = 0; i < values.size(); i++)
             observables[i].setValue(values[i]);
         addEvent();
     }
addWeightedEvent()
void GooFit::DataSet::addWeightedEvent (fptype weight) virtual
Reimplemented in GooFit::BinnedDataSet.
Definition at line 35 of file DataSet.cpp.
{
     throw GooFit::GeneralError("AddWeightedEvent not implemented for this type of DataSet");
 }
checkAllVars()
void GooFit::DataSet::checkAllVars () const protected
Throw an error if any variables are out of range, call in addEvent.
Definition at line 71 of file DataSet.cpp.
References observables.
Referenced by GooFit::BinnedDataSet::addEvent(), GooFit::UnbinnedDataSet::addEvent(), and GooFit::BinnedDataSet::addWeightedEvent().
{
     for(const Observable &v : observables) {
         if(!v)
             throw GooFit::OutOfRange(v.getName(), v.getValue(), v.getLowerLimit(), v.getUpperLimit());
     }
 }
getCurrentValues()
std::vector< fptype > GooFit::DataSet::getCurrentValues () const protected
Definition at line 39 of file DataSet.cpp.
References observables.
Referenced by GooFit::BinnedDataSet::getBinNumber(), and getName().
{
     std::vector<fptype> values;
     for(const Observable &v : observables) {
         values.push_back(v.getValue());
     }
     return values;
 }
getName()
std::string GooFit::DataSet::getName () const inline
Definition at line 49 of file DataSet.h.
References getCurrentValues(), and indexOfVariable().
Referenced by GooFit::BinnedDataSet::getNumWeightedEvents().
 { return name; }
getNumEvents()
size_t GooFit::DataSet::getNumEvents () const inline
Definition at line 47 of file DataSet.h.
References numEventsAdded.
Referenced by GooFit::UnbinnedDataSet::from_matrix(), GooFit::UnbinnedDataSet::getValue(), and GooFit::UnbinnedDataSet::setValueForAllEvents().
 { return numEventsAdded; }
getObservables()
const std::vector< Observable > & GooFit::DataSet::getObservables () const
Definition at line 49 of file DataSet.cpp.
References observables.
Referenced by addEvent().
 { return observables; }
indexOfVariable()
size_t GooFit::DataSet::indexOfVariable (const Observable & var) const protected
Definition at line 51 of file DataSet.cpp.
References observables.
Referenced by GooFit::BinnedDataSet::getBinCenter(), getName(), GooFit::UnbinnedDataSet::getValue(), and GooFit::UnbinnedDataSet::setValueForAllEvents().
{
     for(size_t i = 0; i < observables.size(); ++i)
         if(var == observables[i])
             return i;
     throw GooFit::GeneralError("Invalid variable access into dataset!");
 }
numVariables()
size_t GooFit::DataSet::numVariables () const inline
Definition at line 45 of file DataSet.h.
References observables.
 { return observables.size(); }
Member Data Documentation
numEventsAdded
size_t GooFit::DataSet::numEventsAdded {0} protected
Definition at line 54 of file DataSet.h.
Referenced by GooFit::BinnedDataSet::addEvent(), GooFit::UnbinnedDataSet::addEvent(), GooFit::BinnedDataSet::addWeightedEvent(), and getNumEvents().
observables
std::vector<Observable> GooFit::DataSet::observables protected
Definition at line 66 of file DataSet.h.
Referenced by GooFit::UnbinnedDataSet::addEvent(), addEvent(), GooFit::BinnedDataSet::addWeightedEvent(), checkAllVars(), GooFit::UnbinnedDataSet::from_matrix(), GooFit::BinnedDataSet::getBinCenter(), GooFit::BinnedDataSet::getBinNumber(), GooFit::BinnedDataSet::getBinSize(), GooFit::BinnedDataSet::getBinVolume(), getCurrentValues(), GooFit::BinnedDataSet::getNumWeightedEvents(), getObservables(), indexOfVariable(), GooFit::UnbinnedDataSet::loadEvent(), and numVariables().
The documentation for this class was generated from the following files:
/home/travis/build/GooFit/GooFit/include/goofit/DataSet.h
/home/travis/build/GooFit/GooFit/src/goofit/DataSet.cpp