GooFit: GooPdf Class Reference
GooPdf Class Reference
#include <GooPdf.h>
Public Member Functions
GooPdf (Variable *x, std::string n)
virtual __host__ double calculateNLL () const
__host__ void evaluateAtPoints (std::vector< fptype > &points) const
__host__ void evaluateAtPoints (Variable *var, std::vector< fptype > &res)
virtual __host__ fptype normalise () const
A normalize function. This fills in the host_normalize.
virtual __host__ fptype integrate (fptype lo, fptype hi) const
virtual __host__ bool hasAnalyticIntegral () const
__host__ fptype getValue ()
__host__ void getCompProbsAtDataPoints (std::vector< std::vector< fptype >> &values)
__host__ void initialise (std::vector< unsigned int > pindices, void *dev_functionPtr=host_fcn_ptr)
__host__ void scan (Variable *var, std::vector< fptype > &values)
virtual __host__ void setFitControl (FitControl *const fc, bool takeOwnerShip=true)
virtual __host__ void setMetrics ()
__host__ void setParameterConstantness (bool constant=true)
virtual __host__ void transformGrid (fptype *host_output)
__host__ void setDebugMask (int mask, bool setSpecific=true) const
Public Member Functions inherited from PdfBase
PdfBase (Variable *x, std::string n)
__host__ void initialiseIndices (std::vector< unsigned int > pindices)
__host__ void addSpecialMask (int m)
__host__ void copyParams (const std::vector< double > &pars) const
__host__ void copyParams ()
__host__ void copyNormFactors () const
__host__ void generateNormRange ()
__host__ std::string getName () const
virtual __host__ void getObservables (obsCont &ret) const
virtual __host__ void getParameters (parCont &ret) const
__host__ Variable * getParameterByName (string n) const
__host__ int getSpecialMask () const
__host__ void setData (BinnedDataSet *data)
__host__ void setData (UnbinnedDataSet *data)
__host__ void setData (std::vector< std::map< Variable *, fptype >> &data)
__host__ unsigned int getFunctionIndex () const
__host__ unsigned int getParameterIndex () const
__host__ unsigned int registerParameter (Variable *var)
__host__ unsigned int registerConstants (unsigned int amount)
virtual __host__ void recursiveSetNormalisation (fptype norm=1) const
__host__ void unregisterParameter (Variable *var)
__host__ void registerObservable (Variable *obs)
__host__ void setIntegrationFineness (int i)
__host__ void printProfileInfo (bool topLevel=true)
__host__ bool parametersChanged () const
__host__ void storeParameters () const
__host__ obsIter obsBegin ()
__host__ obsIter obsEnd ()
__host__ obsConstIter obsCBegin () const
__host__ obsConstIter obsCEnd () const
__host__ void checkInitStatus (std::vector< std::string > &unInited) const
void clearCurrentFit ()
__host__ void SigGenSetIndices ()
Static Public Member Functions
static __host__ int findFunctionIdx (void *dev_functionPtr)
Protected Member Functions
virtual __host__ double sumOfNll (int numVars) const
Protected Member Functions inherited from PdfBase
void setNumPerTask (PdfBase *p, const int &c)
Protected Attributes
MetricTaker * logger
Protected Attributes inherited from PdfBase
fptype numEvents
unsigned int numEntries
fptype * normRanges
unsigned int parameters
unsigned int cIndex
obsCont observables
parCont parameterList
FitControl * fitControl
std::vector< PdfBase * > components
int integrationBins
int specialMask
fptype * cachedParams
bool properlyInitialised
unsigned int functionIdx
int m_iEventsPerTask
Additional Inherited Members
Public Types inherited from PdfBase
enum Specials { ForceSeparateNorm = 1, ForceCommonNorm = 2 }
typedef std::vector< Variable * > obsCont
typedef obsCont::iterator obsIter
typedef obsCont::const_iterator obsConstIter
typedef std::vector< Variable * > parCont
typedef parCont::iterator parIter
typedef parCont::const_iterator parConstIter
Detailed Description
Definition at line 51 of file GooPdf.h.
Constructor & Destructor Documentation
GooPdf()
GooPdf::GooPdf (Variable * x, std::string n)
Member Function Documentation
calculateNLL()
virtual __host__ double GooPdf::calculateNLL () const virtual
Implements PdfBase.
evaluateAtPoints() [1/2]
__host__ void GooPdf::evaluateAtPoints (std::vector< fptype > & points) const
evaluateAtPoints() [2/2]
__host__ void GooPdf::evaluateAtPoints (Variable * var, std::vector< fptype > & res)
findFunctionIdx()
static __host__ int GooPdf::findFunctionIdx (void * dev_functionPtr) static
Referenced by hasAnalyticIntegral().
getCompProbsAtDataPoints()
__host__ void GooPdf::getCompProbsAtDataPoints (std::vector< std::vector< fptype >> & values)
Referenced by hasAnalyticIntegral().
getValue()
__host__ fptype GooPdf::getValue ()
Referenced by hasAnalyticIntegral().
hasAnalyticIntegral()
virtual __host__ bool GooPdf::hasAnalyticIntegral () const inline virtual
Reimplemented from PdfBase.
Reimplemented in EventWeightedAddPdf, AddPdf, ExpPdf, ProdPdf, GaussianPdf, JohnsonSUPdf, KinLimitBWPdf, StepPdf, ArgusPdf, and ScaledGaussianPdf.
Definition at line 64 of file GooPdf.h.
References findFunctionIdx(), getCompProbsAtDataPoints(), getValue(), host_fcn_ptr, initialise(), scan(), setDebugMask(), setFitControl(), setMetrics(), setParameterConstantness(), sumOfNll(), and transformGrid().
{
         return false;
     }
initialise()
__host__ void GooPdf::initialise (std::vector< unsigned int > pindices, void * dev_functionPtr = host_fcn_ptr)
Referenced by hasAnalyticIntegral().
integrate()
virtual __host__ fptype GooPdf::integrate (fptype lo, fptype hi) const inline virtual
Reimplemented in ArgusPdf, PolynomialPdf, ExpPdf, BifurGaussPdf, CrystalBallPdf, GaussianPdf, JohnsonSUPdf, and StepPdf.
Definition at line 61 of file GooPdf.h.
{
         return 0;
     }
normalise()
virtual __host__ fptype GooPdf::normalise () const virtual
A normalize function. This fills in the host_normalize.
Implements PdfBase.
Reimplemented in TddpPdf, DPPdf, TDDP4, IncoherentSumPdf, DalitzPlotPdf, CompositePdf, EventWeightedAddPdf, AddPdf, ConvolutionPdf, MappedPdf, ProdPdf, and SmoothHistogramPdf.
scan()
__host__ void GooPdf::scan (Variable * var, std::vector< fptype > & values)
Referenced by hasAnalyticIntegral().
setDebugMask()
__host__ void GooPdf::setDebugMask (int mask, bool setSpecific = true) const
Referenced by hasAnalyticIntegral().
setFitControl()
virtual __host__ void GooPdf::setFitControl (FitControl *const fc, bool takeOwnerShip = true) virtual
Implements PdfBase.
Referenced by hasAnalyticIntegral().
setMetrics()
virtual __host__ void GooPdf::setMetrics () virtual
Referenced by hasAnalyticIntegral().
setParameterConstantness()
__host__ void GooPdf::setParameterConstantness (bool constant = true)
Referenced by hasAnalyticIntegral().
sumOfNll()
virtual __host__ double GooPdf::sumOfNll (int numVars) const protected virtual
Reimplemented in AddPdf.
Referenced by hasAnalyticIntegral().
transformGrid()
virtual __host__ void GooPdf::transformGrid (fptype * host_output) virtual
Referenced by hasAnalyticIntegral().
Member Data Documentation
logger
MetricTaker* GooPdf::logger protected
Definition at line 81 of file GooPdf.h.
The documentation for this class was generated from the following file:
/home/travis/build/GooFit/GooFit/include/goofit/PDFs/GooPdf.h