GooFit: CLI::Option Class Reference
CLI::Option Class Reference
#include <CLI11.hpp>
Public Member Functions
Basic
int count () const
Count the total number of times an option was passed.
operator bool () const
This class is true if option is passed.
void clear ()
Clear the parsed results (mostly for testing)
Setting options
Option * required (bool value=true)
Set the option as required.
Option * mandatory (bool value=true)
Support Plubmum term.
Option * expected (int value)
Set the number of expected arguments (Flags bypass this)
Option * check (std::function< bool(std::string)> validator)
Adds a validator.
Option * group (std::string name)
Changes the group membership.
Option * requires (Option *opt)
Sets required options.
template<typename T = App>
Option * requires (std::string opt_name)
Can find a string if needed.
template<typename A , typename B , typename... ARG>
Option * requires (A opt, B opt1, ARG... args)
Any number supported, any mix of string and Opt.
Option * excludes (Option *opt)
Sets excluded options.
template<typename T = App>
Option * excludes (std::string opt_name)
Can find a string if needed.
template<typename A , typename B , typename... ARG>
Option * excludes (A opt, B opt1, ARG... args)
Any number supported, any mix of string and Opt.
Option * envname (std::string name)
Sets environment variable to read if no option given.
template<typename T = App>
Option * ignore_case (bool value=true)
Accessors
bool get_required () const
True if this is a required option.
int get_expected () const
The number of arguments the option expects.
int get_default () const
True if this has a default value.
bool get_positional () const
True if the argument can be given directly.
bool nonpositional () const
True if option has at least one non-positional name.
bool has_description () const
True if option has description.
const std::string & get_group () const
Get the group of this option.
const std::string & get_description () const
Get the description.
std::string get_pname () const
Help tools
std::string get_name (bool opt_only=false) const
Gets a , sep list of names. Does not include the positional name if opt_only=true.
std::string help_positional () const
The name and any extras needed for positionals.
std::string help_name () const
The first half of the help print, name plus default, etc.
std::string help_pname () const
pname with type info
std::string help_aftername () const
This is the part after the name is printed but before the description.
Parser tools
void run_callback () const
Process the callback.
bool operator== (const Option &other) const
If options share any of the same names, they are equal (not counting positional)
bool check_name (std::string name) const
Check a name. Requires "-" or "--" for short / long, supports positional name.
bool check_sname (std::string name) const
Requires "-" to be removed from string.
bool check_lname (std::string name) const
Requires "--" to be removed from string.
void add_result (std::string s)
Puts a result at position r.
std::vector< std::string > results () const
Get a copy of the results.
bool get_callback_run () const
See if the callback has been run already.
Custom options
void set_custom_option (std::string typeval, int expected=1, bool changeable=false)
Set a custom option, typestring, expected, and changeable.
void set_default_val (std::string val)
Set the default value string representation.
Protected Member Functions
Option (std::string name, std::string description="", std::function< bool(results_t)> callback=[](results_t){return true;}, bool default_=true, App *parent=nullptr)
Making an option by hand is not defined, it must be made by the App class.
App Helpers
Can print positional name detailed option if true
bool _has_help_positional () const
Protected Attributes
Names
std::vector< std::string > snames_
A list of the short names (-a) without the leading dashes.
std::vector< std::string > lnames_
A list of the long names (--a) without the leading dashes.
std::string pname_
A positional name.
std::string envname_
If given, check the environment for this option.
std::string description_
The description for help strings.
std::string defaultval_
A human readable default value, usually only set if default is true in creation.
std::string typeval_
A human readable type value, set when App creates this.
std::string group_ {"Options"}
The group membership.
bool default_ {false}
True if this option has a default.
Configuration
bool required_ {false}
True if this is a required option.
int expected_ {1}
The number of expected values, 0 for flag, -1 for unlimited vector.
bool changeable_ {false}
A private setting to allow args to not be able to accept incorrect expected values.
bool ignore_case_ {false}
Ignore the case when matching (option, not value)
std::vector< std::function< bool(std::string)> > validators_
A list of validators to run on each value parsed.
std::set< Option * > requires_
A list of options that are required with this option.
std::set< Option * > excludes_
A list of options that are excluded with this option.
Other
App * parent_
Remember the parent app.
callback_t callback_
Options store a callback to do all the work.
Parsing results
results_t results_
Results of parsing.
bool callback_run_ {false}
Whether the callback has run (needed for INI parsing)
Detailed Description
Definition at line 796 of file CLI11.hpp.
Constructor & Destructor Documentation
Option()
CLI::Option::Option (std::string name, std::string description = "", std::function< bool(results_t)> callback = [](results_t){return true;}, bool default_ = true, App * parent = nullptr) inline protected
Making an option by hand is not defined, it must be made by the App class.
Definition at line 882 of file CLI11.hpp.
References CLI::detail::get_names(), and CLI::detail::split_names().
                                                                                                           {return true;}, bool default_=true, App* parent = nullptr) :
       description_(description), callback_(callback), default_(default_), parent_(parent) {
         std::tie(snames_, lnames_, pname_) = detail::get_names(detail::split_names(name));
     }
Member Function Documentation
_has_help_positional()
bool CLI::Option::_has_help_positional () const inline protected
Definition at line 1254 of file CLI11.hpp.
{
         return get_positional() && (has_description() || requires_.size()>0 || excludes_.size()>0 );
     }
add_result()
void CLI::Option::add_result (std::string s) inline
Puts a result at position r.
Definition at line 1213 of file CLI11.hpp.
{
         results_.push_back(s);
         callback_run_ = false;
     }
check()
Option* CLI::Option::check (std::function< bool(std::string)> validator) inline
Adds a validator.
Definition at line 936 of file CLI11.hpp.
{
         validators_.push_back(validator);
         return this;
     }
check_lname()
bool CLI::Option::check_lname (std::string name) const inline
Requires "--" to be removed from string.
Definition at line 1201 of file CLI11.hpp.
References CLI::detail::to_lower().
Referenced by operator==().
{
          if(ignore_case_) {
              name = detail::to_lower(name);
             return std::find_if(std::begin(lnames_), std::end(lnames_),
                         [&name](std::string local_sname){return detail::to_lower(local_sname) == name;})
                 != std::end(lnames_);
         } else
             return std::find(std::begin(lnames_), std::end(lnames_), name) != std::end(lnames_);
     }
check_name()
bool CLI::Option::check_name (std::string name) const inline
Check a name. Requires "-" or "--" for short / long, supports positional name.
Definition at line 1173 of file CLI11.hpp.
References CLI::detail::to_lower().
{
         if(name.length()>2 && name.substr(0,2) == "--")
             return check_lname(name.substr(2));
         else if (name.length()>1 && name.substr(0,1) == "-")
             return check_sname(name.substr(1));
         else {
             std::string local_pname = pname_;
             if(ignore_case_) {
                 local_pname = detail::to_lower(local_pname);
                 name = detail::to_lower(name);
             }
             return name == local_pname;
         }
     }
check_sname()
bool CLI::Option::check_sname (std::string name) const inline
Requires "-" to be removed from string.
Definition at line 1190 of file CLI11.hpp.
References CLI::detail::to_lower().
Referenced by operator==().
{
         if(ignore_case_) {
             name = detail::to_lower(name);
             return std::find_if(std::begin(snames_), std::end(snames_),
                         [&name](std::string local_sname){return detail::to_lower(local_sname) == name;})
                 != std::end(snames_);
         } else
             return std::find(std::begin(snames_), std::end(snames_), name) != std::end(snames_);
     }
clear()
void CLI::Option::clear () inline
Clear the parsed results (mostly for testing)
Definition at line 904 of file CLI11.hpp.
Referenced by CLI::App::add_option().
                  {
         results_.clear();
     }
count()
int CLI::Option::count () const inline
Count the total number of times an option was passed.
Definition at line 893 of file CLI11.hpp.
Referenced by CLI::App::_parse().
                       {
         return results_.size();
     }
envname()
Option* CLI::Option::envname (std::string name) inline
Sets environment variable to read if no option given.
Definition at line 999 of file CLI11.hpp.
{
         envname_ = name;
         return this;
     }
excludes() [1/3]
Option* CLI::Option::excludes (Option * opt) inline
Sets excluded options.
Definition at line 975 of file CLI11.hpp.
References get_name(), and CLI::OptionAlreadyAdded.
{
         auto tup = excludes_.insert(opt);
         if(!tup.second)
             throw OptionAlreadyAdded(get_name() + " excludes " + opt->get_name());
         return this;
     }
excludes() [2/3]
template<typename T = App> Option* CLI::Option::excludes (std::string opt_name) inline
Can find a string if needed.
Definition at line 984 of file CLI11.hpp.
References CLI::IncorrectConstruction.
{
         for(const Option_p& opt : dynamic_cast<T*>(parent_)->options_)
             if(opt.get() != this && opt->check_name(opt_name))
                 return excludes(opt.get());
         throw IncorrectConstruction("Option " + opt_name + " is not defined");
     }
excludes() [3/3]
template<typename A , typename B , typename... ARG> Option* CLI::Option::excludes (A opt, B opt1, ARG... args) inline
Any number supported, any mix of string and Opt.
Definition at line 993 of file CLI11.hpp.
{
         excludes(opt);
         return excludes(opt1, args...);
     }
expected()
Option* CLI::Option::expected (int value) inline
Set the number of expected arguments (Flags bypass this)
Definition at line 924 of file CLI11.hpp.
References CLI::IncorrectConstruction.
{
         if(value == 0)
             throw IncorrectConstruction("Cannot set 0 expected, use a flag instead");
         else if(expected_ == 0)
             throw IncorrectConstruction("Cannot make a flag take arguments!");
         else if(!changeable_)
             throw IncorrectConstruction("You can only change the expected arguments for vectors");
         expected_ = value;
         return this;
     }
get_callback_run()
bool CLI::Option::get_callback_run () const inline
See if the callback has been run already.
Definition at line 1225 of file CLI11.hpp.
{
         return callback_run_;
     }
get_default()
int CLI::Option::get_default () const inline
True if this has a default value.
Definition at line 1032 of file CLI11.hpp.
{
         return default_;
     }
get_description()
const std::string& CLI::Option::get_description () const inline
Get the description.
Definition at line 1057 of file CLI11.hpp.
{
         return description_;
     }
get_expected()
int CLI::Option::get_expected () const inline
The number of arguments the option expects.
Definition at line 1027 of file CLI11.hpp.
{
         return expected_;
     }
get_group()
const std::string& CLI::Option::get_group () const inline
Get the group of this option.
Definition at line 1052 of file CLI11.hpp.
{
         return group_;
     }
get_name()
std::string CLI::Option::get_name (bool opt_only = false) const inline
Gets a , sep list of names. Does not include the positional name if opt_only=true.
Definition at line 1071 of file CLI11.hpp.
References CLI::detail::join().
Referenced by CLI::App::_parse(), excludes(), and requires().
{
         std::vector<std::string> name_list;
         if(!opt_only && pname_.length() > 0)
             name_list.push_back(pname_);
         for(const std::string& sname : snames_)
             name_list.push_back("-"+sname);
         for(const std::string& lname : lnames_)
             name_list.push_back("--"+lname);
         return detail::join(name_list);
     }
get_pname()
std::string CLI::Option::get_pname () const inline
Definition at line 1062 of file CLI11.hpp.
{
         return pname_;
     }
get_positional()
bool CLI::Option::get_positional () const inline
True if the argument can be given directly.
Definition at line 1037 of file CLI11.hpp.
Referenced by CLI::App::add_flag().
{
         return pname_.length() > 0;
     }
get_required()
bool CLI::Option::get_required () const inline
True if this is a required option.
Definition at line 1022 of file CLI11.hpp.
{
         return required_;
     }
group()
Option* CLI::Option::group (std::string name) inline
Changes the group membership.
Definition at line 943 of file CLI11.hpp.
{
         group_ = name;
         return this;
     }
has_description()
bool CLI::Option::has_description () const inline
True if option has description.
Definition at line 1047 of file CLI11.hpp.
{
         return description_.length() > 0;
     }
help_aftername()
std::string CLI::Option::help_aftername () const inline
This is the part after the name is printed but before the description.
Definition at line 1108 of file CLI11.hpp.
{
         std::stringstream out;
         if(get_expected() != 0) {
             if(typeval_ != "")
                 out << " " << typeval_;
             if(defaultval_ != "")
                 out << "=" << defaultval_;
             if(get_expected() > 1)
                 out << " x " << get_expected();
             if(get_expected() == -1)
                 out << " ...";
         }
         if(envname_ != "")
             out << " (env:" << envname_ << ")";
         if(requires_.size() > 0) {
             out << " Requires:";
             for(const Option* opt : requires_)
                 out << " " << opt->get_name();
         }
         if(excludes_.size() > 0) {
             out << " Excludes:";
             for(const Option* opt : excludes_)
                 out << " " << opt->get_name();
         }
         return out.str();
     }
help_name()
std::string CLI::Option::help_name () const inline
The first half of the help print, name plus default, etc.
Definition at line 1094 of file CLI11.hpp.
{
         std::stringstream out;
         out << get_name(true) << help_aftername();
         return out.str();
     }
help_pname()
std::string CLI::Option::help_pname () const inline
pname with type info
Definition at line 1101 of file CLI11.hpp.
{
         std::stringstream out;
         out << get_pname() << help_aftername();
         return out.str();
     }
help_positional()
std::string CLI::Option::help_positional () const inline
The name and any extras needed for positionals.
Definition at line 1083 of file CLI11.hpp.
{
         std::string out = pname_;
         if(get_expected()>1)
             out = out + "(" + std::to_string(get_expected()) + "x)";
         else if(get_expected()==-1)
             out = out + "...";
         out = get_required() ? out : "["+out+"]";
         return out;
     }
ignore_case()
template<typename T = App> Option* CLI::Option::ignore_case (bool value = true) inline
Ignore case
The template hides the fact that we don't have the definition of App yet. You are never expected to add an argument to the template here.
Definition at line 1009 of file CLI11.hpp.
References CLI::OptionAlreadyAdded.
{
         ignore_case_ = value;
         for(const Option_p& opt : dynamic_cast<T*>(parent_)->options_)
             if(opt.get() != this && *opt == *this)
                 throw OptionAlreadyAdded(opt->get_name());
         return this;
     }
mandatory()
Option* CLI::Option::mandatory (bool value = true) inline
Support Plubmum term.
Definition at line 919 of file CLI11.hpp.
{
         return required(value);
     }
nonpositional()
bool CLI::Option::nonpositional () const inline
True if option has at least one non-positional name.
Definition at line 1042 of file CLI11.hpp.
{
         return (snames_.size() + lnames_.size()) > 0;
     }
operator bool()
CLI::Option::operator bool () const inline
This class is true if option is passed.
Definition at line 899 of file CLI11.hpp.
{
         return count() > 0;
     }
operator==()
bool CLI::Option::operator== (const Option & other) const inline
If options share any of the same names, they are equal (not counting positional)
Definition at line 1155 of file CLI11.hpp.
References check_lname(), check_sname(), lnames_, and snames_.
{
         for(const std::string &sname : snames_)
             if(other.check_sname(sname))
                 return true;
         for(const std::string &lname : lnames_)
             if(other.check_lname(lname))
                 return true;
         // We need to do the inverse, just in case we are ignore_case
         for(const std::string &sname : other.snames_)
             if(check_sname(sname))
                 return true;
         for(const std::string &lname : other.lnames_)
             if(check_lname(lname))
                 return true;
         return false;
     }
required()
Option* CLI::Option::required (bool value = true) inline
Set the option as required.
Definition at line 913 of file CLI11.hpp.
{
         required_ = value;
         return this;
     }
requires() [1/3]
Option* CLI::Option::requires (Option * opt) inline
Sets required options.
Definition at line 950 of file CLI11.hpp.
References get_name(), and CLI::OptionAlreadyAdded.
{
         auto tup = requires_.insert(opt);
         if(!tup.second)
             throw OptionAlreadyAdded(get_name() + " requires " + opt->get_name());
         return this;
     }
requires() [2/3]
template<typename T = App> Option* CLI::Option::requires (std::string opt_name) inline
Can find a string if needed.
Definition at line 959 of file CLI11.hpp.
References CLI::IncorrectConstruction.
{
         for(const Option_p& opt : dynamic_cast<T*>(parent_)->options_)
             if(opt.get() != this && opt->check_name(opt_name))
                 return requires(opt.get());
         throw IncorrectConstruction("Option " + opt_name + " is not defined");
     }
requires() [3/3]
template<typename A , typename B , typename... ARG> Option* CLI::Option::requires (A opt, B opt1, ARG... args) inline
Any number supported, any mix of string and Opt.
Definition at line 969 of file CLI11.hpp.
{
         requires(opt);
         return requires(opt1, args...);
     }
results()
std::vector<std::string> CLI::Option::results () const inline
Get a copy of the results.
Definition at line 1220 of file CLI11.hpp.
{
         return results_;
     }
run_callback()
void CLI::Option::run_callback () const inline
Process the callback.
Definition at line 1143 of file CLI11.hpp.
References CLI::detail::join().
{
         if(!callback_(results_))
             throw ConversionError(get_name() + "=" + detail::join(results_));
         if(validators_.size()>0) {
             for(const std::string & result : results_)
                 for(const std::function<bool(std::string)> &vali : validators_)
                     if(!vali(result))
                         throw ValidationError(get_name() + "=" + result);
         }
     }
set_custom_option()
void CLI::Option::set_custom_option (std::string typeval, int expected = 1, bool changeable = false) inline
Set a custom option, typestring, expected, and changeable.
Definition at line 1234 of file CLI11.hpp.
Referenced by CLI::App::add_flag(), CLI::App::add_option(), CLI::App::add_set(), and CLI::App::add_set_ignore_case().
{
         typeval_ = typeval;
         expected_ = expected;
         changeable_ = changeable;
     }
set_default_val()
void CLI::Option::set_default_val (std::string val) inline
Set the default value string representation.
Definition at line 1241 of file CLI11.hpp.
Referenced by CLI::App::add_option(), CLI::App::add_set(), and CLI::App::add_set_ignore_case().
{
         defaultval_ = val;
     }
Member Data Documentation
callback_
callback_t CLI::Option::callback_ protected
Options store a callback to do all the work.
Definition at line 866 of file CLI11.hpp.
callback_run_
bool CLI::Option::callback_run_ {false} protected
Whether the callback has run (needed for INI parsing)
Definition at line 877 of file CLI11.hpp.
changeable_
bool CLI::Option::changeable_ {false} protected
A private setting to allow args to not be able to accept incorrect expected values.
Definition at line 844 of file CLI11.hpp.
default_
bool CLI::Option::default_ {false} protected
True if this option has a default.
Definition at line 831 of file CLI11.hpp.
defaultval_
std::string CLI::Option::defaultval_ protected
A human readable default value, usually only set if default is true in creation.
Definition at line 822 of file CLI11.hpp.
description_
std::string CLI::Option::description_ protected
The description for help strings.
Definition at line 819 of file CLI11.hpp.
envname_
std::string CLI::Option::envname_ protected
If given, check the environment for this option.
Definition at line 812 of file CLI11.hpp.
excludes_
std::set<Option*> CLI::Option::excludes_ protected
A list of options that are excluded with this option.
Definition at line 856 of file CLI11.hpp.
Referenced by CLI::App::_parse().
expected_
int CLI::Option::expected_ {1} protected
The number of expected values, 0 for flag, -1 for unlimited vector.
Definition at line 841 of file CLI11.hpp.
group_
std::string CLI::Option::group_ {"Options"} protected
The group membership.
Definition at line 828 of file CLI11.hpp.
ignore_case_
bool CLI::Option::ignore_case_ {false} protected
Ignore the case when matching (option, not value)
Definition at line 847 of file CLI11.hpp.
lnames_
std::vector<std::string> CLI::Option::lnames_ protected
A list of the long names (--a) without the leading dashes.
Definition at line 806 of file CLI11.hpp.
Referenced by operator==().
parent_
App* CLI::Option::parent_ protected
Remember the parent app.
Definition at line 863 of file CLI11.hpp.
pname_
std::string CLI::Option::pname_ protected
A positional name.
Definition at line 809 of file CLI11.hpp.
required_
bool CLI::Option::required_ {false} protected
True if this is a required option.
Definition at line 838 of file CLI11.hpp.
requires_
std::set<Option*> CLI::Option::requires_ protected
A list of options that are required with this option.
Definition at line 853 of file CLI11.hpp.
Referenced by CLI::App::_parse().
results_
results_t CLI::Option::results_ protected
Results of parsing.
Definition at line 874 of file CLI11.hpp.
snames_
std::vector<std::string> CLI::Option::snames_ protected
A list of the short names (-a) without the leading dashes.
Definition at line 803 of file CLI11.hpp.
Referenced by operator==().
typeval_
std::string CLI::Option::typeval_ protected
A human readable type value, set when App creates this.
Definition at line 825 of file CLI11.hpp.
validators_
std::vector<std::function<bool(std::string)> > CLI::Option::validators_ protected
A list of validators to run on each value parsed.
Definition at line 850 of file CLI11.hpp.
The documentation for this class was generated from the following file:
/home/travis/build/GooFit/GooFit/include/goofit/detail/CLI11.hpp