GooFit: FunctorBase Class Reference
FunctorBase Class Reference abstract
#include <FunctorBase.hh>
Public Types
enum Specials { ForceSeparateNorm = 1, ForceCommonNorm = 2 }
typedef std::vector< Variable * > obsCont
typedef obsCont::iterator obsIter
typedef obsCont::const_iterator obsConstIter
typedef std::set< Variable * > parCont
typedef parCont::iterator parIter
Public Member Functions
FunctorBase (Variable *x, std::string n)
virtual __host__ double calculateNLL () const =0
virtual __host__ fptype normalise () const =0
__host__ void initialiseIndices (std::vector< unsigned int > pindices)
__host__ void addSpecialMask (int m)
__host__ void copyParams (const std::vector< double > &pars) const
__host__ void copyParams ()
__host__ void copyNormFactors () const
__host__ void generateNormRange ()
__host__ std::string getName () const
virtual __host__ void getObservables (obsCont &ret) const
virtual __host__ void getParameters (parCont &ret) const
__host__ int getSpecialMask () const
__host__ void setData (BinnedDataSet *data)
__host__ void setData (UnbinnedDataSet *data)
__host__ void setData (std::vector< std::map< Variable *, fptype > > &data)
virtual __host__ void setFitControl (FitControl *const fc, bool takeOwnerShip=true)=0
virtual __host__ bool hasAnalyticIntegral () const
__host__ unsigned int getFunctionIndex () const
__host__ unsigned int getParameterIndex () const
__host__ unsigned int registerParameter (Variable *var)
__host__ unsigned int registerConstants (unsigned int amount)
virtual __host__ void recursiveSetNormalisation (fptype norm=1) const
__host__ void unregisterParameter (Variable *var)
__host__ void registerObservable (Variable *obs)
__host__ void setIntegrationFineness (int i)
__host__ void printProfileInfo (bool topLevel=true)
__host__ bool parametersChanged () const
__host__ void storeParameters () const
__host__ obsIter obsBegin ()
__host__ obsIter obsEnd ()
__host__ obsConstIter obsCBegin () const
__host__ obsConstIter obsCEnd () const
__host__ void checkInitStatus (std::vector< std::string > &unInited) const
void clearCurrentFit ()
Protected Attributes
fptype numEvents
unsigned int numEntries
fptype * normRanges
unsigned int parameters
unsigned int cIndex
obsCont observables
parCont parameterList
FitControl * fitControl
std::vector< FunctorBase * > components
int integrationBins
int specialMask
fptype * cachedParams
bool properlyInitialised
unsigned int functionIdx
Detailed Description
Definition at line 33 of file FunctorBase.hh.
Member Typedef Documentation
typedef obsCont::const_iterator FunctorBase::obsConstIter
Definition at line 46 of file FunctorBase.hh.
typedef std::vector<Variable*> FunctorBase::obsCont
Definition at line 44 of file FunctorBase.hh.
typedef obsCont::iterator FunctorBase::obsIter
Definition at line 45 of file FunctorBase.hh.
typedef std::set<Variable*> FunctorBase::parCont
Definition at line 47 of file FunctorBase.hh.
typedef parCont::iterator FunctorBase::parIter
Definition at line 48 of file FunctorBase.hh.
Member Enumeration Documentation
enum FunctorBase::Specials
Enumerator
ForceSeparateNorm
ForceCommonNorm
Definition at line 38 of file FunctorBase.hh.
Constructor & Destructor Documentation
FunctorBase::FunctorBase (Variable * x, std::string n)
Definition at line 22 of file FunctorBase.cc.
References registerObservable().
Member Function Documentation
__host__ void FunctorBase::addSpecialMask (int m) inline
Definition at line 50 of file FunctorBase.hh.
References specialMask.
Referenced by IncoherentSumThrustFunctor::IncoherentSumThrustFunctor(), and TddpThrustFunctor::TddpThrustFunctor().
virtual __host__ double FunctorBase::calculateNLL () const pure virtual
Implemented in ThrustPdfFunctor.
Referenced by FitFun().
__host__ void FunctorBase::checkInitStatus (std::vector< std::string > & unInited) const
Definition at line 36 of file FunctorBase.cc.
References components, getName(), and properlyInitialised.
void FunctorBase::clearCurrentFit ()
Definition at line 291 of file FunctorBase.cu.
References cudaDataArray, and totalParams.
__host__ void FunctorBase::copyNormFactors () const
Definition at line 65 of file FunctorBase.cu.
References host_normalisation, normalisationFactors, and totalParams.
__host__ void FunctorBase::copyParams (const std::vector< double > & pars) const
Definition at line 34 of file FunctorBase.cu.
References abortWithCudaPrintFlush(), cudaArray, and host_params.
Referenced by FitFun(), and PdfFunctor::setupMinuit().
__host__ void FunctorBase::copyParams ()
Definition at line 48 of file FunctorBase.cu.
References getParameters().
Referenced by ThrustPdfFunctor::evaluateAtPoints(), ThrustPdfFunctor::getCompProbsAtDataPoints(), ThrustPdfFunctor::getValue(), and ThrustPdfFunctor::scan().
__host__ void FunctorBase::generateNormRange ()
Definition at line 266 of file FunctorBase.cu.
References integrationBins, normRanges, obsBegin(), obsEnd(), and observables.
Referenced by setIntegrationFineness(), and ThrustPdfFunctor::transformGrid().
__host__ unsigned int FunctorBase::getFunctionIndex () const inline
Definition at line 64 of file FunctorBase.hh.
References functionIdx.
Referenced by AddThrustFunctor::AddThrustFunctor(), CompositeThrustFunctor::CompositeThrustFunctor(), ConvolutionThrustFunctor::ConvolutionThrustFunctor(), EventWeightedAddThrustFunctor::EventWeightedAddThrustFunctor(), IncoherentSumThrustFunctor::IncoherentSumThrustFunctor(), MappedThrustFunctor::MappedThrustFunctor(), printProfileInfo(), and TddpThrustFunctor::TddpThrustFunctor().
__host__ std::string FunctorBase::getName () const inline
Definition at line 55 of file FunctorBase.hh.
Referenced by ThrustPdfFunctor::calculateNLL(), checkInitStatus(), SmoothHistogramThrustFunctor::copyHistogramToDevice(), MappedThrustFunctor::MappedThrustFunctor(), ThrustPdfFunctor::normalise(), PolynomialThrustFunctor::PolynomialThrustFunctor(), printProfileInfo(), ConvolutionThrustFunctor::registerOthers(), registerParameter(), and SmoothHistogramThrustFunctor::SmoothHistogramThrustFunctor().
__host__ void FunctorBase::getObservables (obsCont & ret) const virtual
Definition at line 113 of file FunctorBase.cc.
References components, obsCBegin(), and obsCEnd().
Referenced by AddThrustFunctor::AddThrustFunctor(), EventWeightedAddThrustFunctor::EventWeightedAddThrustFunctor(), MappedThrustFunctor::MappedThrustFunctor(), and ProdThrustFunctor::ProdThrustFunctor().
__host__ unsigned int FunctorBase::getParameterIndex () const inline
Definition at line 65 of file FunctorBase.hh.
References parameters.
Referenced by AddThrustFunctor::AddThrustFunctor(), CompositeThrustFunctor::CompositeThrustFunctor(), ConvolutionThrustFunctor::ConvolutionThrustFunctor(), EventWeightedAddThrustFunctor::EventWeightedAddThrustFunctor(), IncoherentSumThrustFunctor::IncoherentSumThrustFunctor(), MappedThrustFunctor::MappedThrustFunctor(), printProfileInfo(), and TddpThrustFunctor::TddpThrustFunctor().
__host__ void FunctorBase::getParameters (parCont & ret) const virtual
Definition at line 106 of file FunctorBase.cc.
References components, and parameterList.
Referenced by copyParams(), parametersChanged(), readFromFile(), ThrustPdfFunctor::setParameterConstantness(), PdfFunctor::setupMinuit(), storeParameters(), and writeToFile().
__host__ int FunctorBase::getSpecialMask () const inline
Definition at line 58 of file FunctorBase.hh.
References specialMask.
Referenced by AddThrustFunctor::normalise().
virtual __host__ bool FunctorBase::hasAnalyticIntegral () const inline virtual
Reimplemented in ThrustPdfFunctor, EventWeightedAddThrustFunctor, AddThrustFunctor, ExpThrustFunctor, ProdThrustFunctor, GaussianThrustFunctor, JohnsonSUThrustFunctor, KinLimitBWThrustFunctor, StepThrustFunctor, ArgusThrustFunctor, and ScaledGaussianThrustFunctor.
Definition at line 63 of file FunctorBase.hh.
__host__ void FunctorBase::initialiseIndices (std::vector< unsigned int > pindices)
Definition at line 70 of file FunctorBase.cu.
References host_indices, maxParams, observables, parameters, paramIndices, and totalParams.
Referenced by ThrustPdfFunctor::initialise().
virtual __host__ fptype FunctorBase::normalise () const pure virtual
Implemented in TddpThrustFunctor, ThrustPdfFunctor, IncoherentSumThrustFunctor, CompositeThrustFunctor, EventWeightedAddThrustFunctor, AddThrustFunctor, ConvolutionThrustFunctor, MappedThrustFunctor, ProdThrustFunctor, and SmoothHistogramThrustFunctor.
__host__ obsIter FunctorBase::obsBegin () inline
Definition at line 77 of file FunctorBase.hh.
References observables.
Referenced by generateNormRange(), and setData().
__host__ obsConstIter FunctorBase::obsCBegin () const inline
Definition at line 79 of file FunctorBase.hh.
References observables.
Referenced by getObservables(), ThrustPdfFunctor::normalise(), and ThrustPdfFunctor::transformGrid().
__host__ obsConstIter FunctorBase::obsCEnd () const inline
Definition at line 80 of file FunctorBase.hh.
References observables.
Referenced by getObservables(), ThrustPdfFunctor::normalise(), and ThrustPdfFunctor::transformGrid().
__host__ obsIter FunctorBase::obsEnd () inline
Definition at line 78 of file FunctorBase.hh.
References observables.
Referenced by generateNormRange(), and setData().
__host__ bool FunctorBase::parametersChanged () const
Definition at line 141 of file FunctorBase.cc.
References cachedParams, getParameters(), and host_params.
Referenced by ConvolutionThrustFunctor::normalise(), and IncoherentSumThrustFunctor::normalise().
__host__ void FunctorBase::printProfileInfo (bool topLevel = true)
Definition at line 297 of file FunctorBase.cu.
References components, getFunctionIndex(), getName(), and getParameterIndex().
__host__ void FunctorBase::recursiveSetNormalisation (fptype norm = 1) const virtual
Definition at line 43 of file FunctorBase.cc.
References components, host_normalisation, norm(), and parameters.
Referenced by ProdThrustFunctor::normalise(), ConvolutionThrustFunctor::normalise(), CompositeThrustFunctor::normalise(), IncoherentSumThrustFunctor::normalise(), and TddpThrustFunctor::normalise().
__host__ unsigned int FunctorBase::registerConstants (unsigned int amount)
Definition at line 123 of file FunctorBase.cc.
References cIndex, maxParams, and totalConstants.
Referenced by BinTransformThrustFunctor::BinTransformThrustFunctor(), ConvolutionThrustFunctor::ConvolutionThrustFunctor(), IncoherentSumThrustFunctor::IncoherentSumThrustFunctor(), InterHistThrustFunctor::InterHistThrustFunctor(), KinLimitBWThrustFunctor::KinLimitBWThrustFunctor(), SmoothHistogramThrustFunctor::SmoothHistogramThrustFunctor(), and TddpThrustFunctor::TddpThrustFunctor().
void FunctorBase::registerObservable (Variable * obs)
Definition at line 130 of file FunctorBase.cc.
References observables.
Referenced by BinTransformThrustFunctor::BinTransformThrustFunctor(), CorrGaussianThrustFunctor::CorrGaussianThrustFunctor(), DalitzVetoThrustFunctor::DalitzVetoThrustFunctor(), EventWeightedAddThrustFunctor::EventWeightedAddThrustFunctor(), FunctorBase(), IncoherentSumThrustFunctor::IncoherentSumThrustFunctor(), InterHistThrustFunctor::InterHistThrustFunctor(), PolynomialThrustFunctor::PolynomialThrustFunctor(), SmoothHistogramThrustFunctor::SmoothHistogramThrustFunctor(), TddpThrustFunctor::TddpThrustFunctor(), and TrigThresholdThrustFunctor::TrigThresholdThrustFunctor().
__host__ unsigned int FunctorBase::registerParameter (Variable * var)
Definition at line 50 of file FunctorBase.cc.
References Variable::getIndex(), getName(), Variable::index, parameterList, and variableRegistry.
Referenced by AddThrustFunctor::AddThrustFunctor(), ArgusThrustFunctor::ArgusThrustFunctor(), BifurGaussThrustFunctor::BifurGaussThrustFunctor(), CorrGaussianThrustFunctor::CorrGaussianThrustFunctor(), ThreeGaussResolution::createParameters(), CrystalBallThrustFunctor::CrystalBallThrustFunctor(), DalitzVetoThrustFunctor::DalitzVetoThrustFunctor(), ExpGausThrustFunctor::ExpGausThrustFunctor(), ExpThrustFunctor::ExpThrustFunctor(), GaussianThrustFunctor::GaussianThrustFunctor(), IncoherentSumThrustFunctor::IncoherentSumThrustFunctor(), InterHistThrustFunctor::InterHistThrustFunctor(), JohnsonSUThrustFunctor::JohnsonSUThrustFunctor(), KinLimitBWThrustFunctor::KinLimitBWThrustFunctor(), LandauThrustFunctor::LandauThrustFunctor(), NovosibirskThrustFunctor::NovosibirskThrustFunctor(), PolynomialThrustFunctor::PolynomialThrustFunctor(), ScaledGaussianThrustFunctor::ScaledGaussianThrustFunctor(), SmoothHistogramThrustFunctor::SmoothHistogramThrustFunctor(), StepThrustFunctor::StepThrustFunctor(), TddpThrustFunctor::TddpThrustFunctor(), TrigThresholdThrustFunctor::TrigThresholdThrustFunctor(), and VoigtianThrustFunctor::VoigtianThrustFunctor().
__host__ void FunctorBase::setData (BinnedDataSet * data)
Definition at line 196 of file FunctorBase.cu.
References FitControl::binErrors(), FitControl::binnedFit(), cudaDataArray, fitControl, functorConstants, BinnedDataSet::getBinCenter(), BinnedDataSet::getBinContent(), BinnedDataSet::getBinError(), BinnedDataSet::getBinVolume(), BinnedDataSet::getNumBins(), numEntries, numEvents, obsBegin(), obsEnd(), observables, and setFitControl().
Referenced by ThrustPdfFunctor::evaluateAtPoints(), fitAndPlot(), and ThrustPdfFunctor::getValue().
__host__ void FunctorBase::setData (UnbinnedDataSet * data)
Definition at line 166 of file FunctorBase.cu.
References cudaDataArray, functorConstants, UnbinnedDataSet::getNumEvents(), UnbinnedDataSet::getValue(), numEntries, numEvents, obsBegin(), obsEnd(), and observables.
__host__ void FunctorBase::setData (std::vector< std::map< Variable *, fptype > > & data)
Definition at line 108 of file FunctorBase.cu.
References cudaDataArray, functorConstants, numEntries, numEvents, obsBegin(), obsEnd(), and observables.
virtual __host__ void FunctorBase::setFitControl (FitControl *const fc, bool takeOwnerShip = true) pure virtual
Implemented in ThrustPdfFunctor.
Referenced by setData().
__host__ void FunctorBase::setIntegrationFineness (int i)
Definition at line 136 of file FunctorBase.cc.
References generateNormRange(), and integrationBins.
__host__ void FunctorBase::storeParameters () const
Definition at line 154 of file FunctorBase.cc.
References cachedParams, getParameters(), and host_params.
Referenced by ConvolutionThrustFunctor::normalise(), and IncoherentSumThrustFunctor::normalise().
__host__ void FunctorBase::unregisterParameter (Variable * var)
Definition at line 90 of file FunctorBase.cc.
References components, Variable::index, parameterList, and variableRegistry.
Member Data Documentation
fptype* FunctorBase::cachedParams mutable protected
Definition at line 97 of file FunctorBase.hh.
Referenced by parametersChanged(), and storeParameters().
unsigned int FunctorBase::cIndex protected
Definition at line 90 of file FunctorBase.hh.
Referenced by BinTransformThrustFunctor::BinTransformThrustFunctor(), IncoherentSumThrustFunctor::IncoherentSumThrustFunctor(), InterHistThrustFunctor::InterHistThrustFunctor(), registerConstants(), ConvolutionThrustFunctor::setIntegrationConstants(), KinLimitBWThrustFunctor::setMasses(), SmoothHistogramThrustFunctor::SmoothHistogramThrustFunctor(), and TddpThrustFunctor::TddpThrustFunctor().
std::vector<FunctorBase*> FunctorBase::components protected
Definition at line 94 of file FunctorBase.hh.
Referenced by AddThrustFunctor::AddThrustFunctor(), checkInitStatus(), CompositeThrustFunctor::CompositeThrustFunctor(), ConvolutionThrustFunctor::ConvolutionThrustFunctor(), EventWeightedAddThrustFunctor::EventWeightedAddThrustFunctor(), ThrustPdfFunctor::getCompProbsAtDataPoints(), getObservables(), getParameters(), IncoherentSumThrustFunctor::IncoherentSumThrustFunctor(), MappedThrustFunctor::MappedThrustFunctor(), MappedThrustFunctor::normalise(), ProdThrustFunctor::normalise(), AddThrustFunctor::normalise(), EventWeightedAddThrustFunctor::normalise(), CompositeThrustFunctor::normalise(), printProfileInfo(), ProdThrustFunctor::ProdThrustFunctor(), recursiveSetNormalisation(), ThrustPdfFunctor::setFitControl(), AddThrustFunctor::sumOfNll(), TddpThrustFunctor::TddpThrustFunctor(), and unregisterParameter().
FitControl* FunctorBase::fitControl protected
Definition at line 93 of file FunctorBase.hh.
Referenced by ThrustPdfFunctor::calculateNLL(), ThrustPdfFunctor::getCompProbsAtDataPoints(), ThrustPdfFunctor::initialise(), ThrustPdfFunctor::normalise(), setData(), ThrustPdfFunctor::setFitControl(), and ThrustPdfFunctor::setMetrics().
unsigned int FunctorBase::functionIdx protected
Definition at line 100 of file FunctorBase.hh.
Referenced by getFunctionIndex(), and ThrustPdfFunctor::initialise().
int FunctorBase::integrationBins protected
Definition at line 95 of file FunctorBase.hh.
Referenced by generateNormRange(), ArgusThrustFunctor::integrate(), ThrustPdfFunctor::normalise(), and setIntegrationFineness().
fptype* FunctorBase::normRanges protected
Definition at line 88 of file FunctorBase.hh.
Referenced by generateNormRange(), ThrustPdfFunctor::normalise(), and ThrustPdfFunctor::transformGrid().
unsigned int FunctorBase::numEntries protected
Definition at line 87 of file FunctorBase.hh.
Referenced by ThrustPdfFunctor::evaluateAtPoints(), ThrustPdfFunctor::getCompProbsAtDataPoints(), IncoherentSumThrustFunctor::normalise(), TddpThrustFunctor::normalise(), setData(), IncoherentSumThrustFunctor::setDataSize(), TddpThrustFunctor::setDataSize(), AddThrustFunctor::sumOfNll(), and ThrustPdfFunctor::sumOfNll().
fptype FunctorBase::numEvents protected
Definition at line 86 of file FunctorBase.hh.
Referenced by setData(), and AddThrustFunctor::sumOfNll().
obsCont FunctorBase::observables protected
Definition at line 91 of file FunctorBase.hh.
Referenced by AddThrustFunctor::AddThrustFunctor(), ThrustPdfFunctor::calculateNLL(), SmoothHistogramThrustFunctor::copyHistogramToDevice(), ThrustPdfFunctor::evaluateAtPoints(), EventWeightedAddThrustFunctor::EventWeightedAddThrustFunctor(), generateNormRange(), PolynomialThrustFunctor::getCoefficient(), ThrustPdfFunctor::getCompProbsAtDataPoints(), ThrustPdfFunctor::getValue(), initialiseIndices(), MappedThrustFunctor::MappedThrustFunctor(), SmoothHistogramThrustFunctor::normalise(), ThrustPdfFunctor::normalise(), obsBegin(), obsCBegin(), obsCEnd(), obsEnd(), PolynomialThrustFunctor::PolynomialThrustFunctor(), ProdThrustFunctor::ProdThrustFunctor(), registerObservable(), setData(), ConvolutionThrustFunctor::setIntegrationConstants(), and ThrustPdfFunctor::transformGrid().
parCont FunctorBase::parameterList protected
Definition at line 92 of file FunctorBase.hh.
Referenced by getParameters(), registerParameter(), and unregisterParameter().
unsigned int FunctorBase::parameters protected
Definition at line 89 of file FunctorBase.hh.
Referenced by ThrustPdfFunctor::evaluateAtPoints(), PolynomialThrustFunctor::getCoefficient(), getParameterIndex(), ExpThrustFunctor::hasAnalyticIntegral(), IncoherentSumThrustFunctor::IncoherentSumThrustFunctor(), initialiseIndices(), StepThrustFunctor::integrate(), BifurGaussThrustFunctor::integrate(), GaussianThrustFunctor::integrate(), CrystalBallThrustFunctor::integrate(), ArgusThrustFunctor::integrate(), ExpThrustFunctor::integrate(), PolynomialThrustFunctor::integrate(), SmoothHistogramThrustFunctor::normalise(), ProdThrustFunctor::normalise(), MappedThrustFunctor::normalise(), AddThrustFunctor::normalise(), EventWeightedAddThrustFunctor::normalise(), IncoherentSumThrustFunctor::normalise(), ThrustPdfFunctor::normalise(), TddpThrustFunctor::normalise(), recursiveSetNormalisation(), ConvolutionThrustFunctor::registerOthers(), ThrustPdfFunctor::setDebugMask(), AddThrustFunctor::sumOfNll(), and TddpThrustFunctor::TddpThrustFunctor().
bool FunctorBase::properlyInitialised protected
Definition at line 98 of file FunctorBase.hh.
Referenced by checkInitStatus(), ConvolutionThrustFunctor::ConvolutionThrustFunctor(), and ConvolutionThrustFunctor::registerOthers().
int FunctorBase::specialMask protected
Definition at line 96 of file FunctorBase.hh.
Referenced by addSpecialMask(), and getSpecialMask().
The documentation for this class was generated from the following files:
FunctorBase.hh
FunctorBase.cc
FunctorBase.cu