GooFit: GooFit::Minuit1 Class Reference
GooFit::Minuit1 Class Reference
#include <FitManagerMinuit1.h>
Public Member Functions
Minuit1 (PdfBase *pdfPointer)
Int_t Eval (Int_t npar, Double_t *grad, Double_t &fval, Double_t *par, Int_t flag) override
Fit function for Minuit.
std::vector< Variable > getVaraibles () const
Detailed Description
Definition at line 11 of file FitManagerMinuit1.h.
Constructor & Destructor Documentation
Minuit1()
GooFit::Minuit1::Minuit1 (PdfBase * pdfPointer)
Definition at line 13 of file FitManagerMinuit1.cpp.
References GooFit::PdfBase::copyParams().
     : TMinuit(max_index(pdfPointer->getParameters()) + 1)
     , pdfPointer(pdfPointer)
     , vars(pdfPointer->getParameters()) {
     int counter = 0;
     for(Variable &var : vars) {
         var.setFitterIndex(counter);
         Int_t err = DefineParameter(
             counter, var.getName().c_str(), var.getValue(), var.getError(), var.getLowerLimit(), var.getUpperLimit());
         if(GetNumPars() != counter + 1)
             throw GooFit::GeneralError(
                 "Error when implementing param {} (possibly invalid error/lowerlimit/upperlimit values)!",
                 var.getName());
         if(err != 0)
             throw GooFit::GeneralError("Was not able to implement param {} (error {})", var.getName(), err);
         if(var.IsFixed())
             FixParameter(counter);
         counter++;
     }
     pdfPointer->copyParams();
 }
Member Function Documentation
Eval()
Int_t GooFit::Minuit1::Eval (Int_t npar, Double_t * grad, Double_t & fval, Double_t * par, Int_t flag) override
Fit function for Minuit.
Definition at line 42 of file FitManagerMinuit1.cpp.
References GooFit::PdfBase::calculateNLL(), GooFit::PdfBase::copyParams(), GOOFIT_TRACE, GOOFIT_WARN, GooFit::host_callnumber, and GooFit::max_index().
{
     std::vector<double> pars{fp, fp + GetNumPars()};
     std::vector<double> gooPars;
     gooPars.resize(max_index(vars) + 1);
     for(Variable &var : vars) {
         if(std::isnan(pars.at(var.getFitterIndex())))
             GOOFIT_WARN("Variable {} at {} is NaN", var.getName(), var.getIndex());
         var.setChanged(var.getValue() != pars.at(var.getFitterIndex()));
         var.setValue(pars.at(var.getFitterIndex()));
         gooPars.at(var.getIndex()) = var.getValue() - var.getBlind(Variable::Key());
     }
     pdfPointer->copyParams(gooPars);
     GOOFIT_TRACE("Calculating NLL");
     fun = pdfPointer->calculateNLL();
     host_callnumber++;
     return 0;
 }
getVaraibles()
std::vector<Variable> GooFit::Minuit1::getVaraibles () const inline
Definition at line 27 of file FitManagerMinuit1.h.
 { return vars; };
The documentation for this class was generated from the following files:
/home/travis/build/GooFit/GooFit/include/goofit/fitting/FitManagerMinuit1.h
/home/travis/build/GooFit/GooFit/src/goofit/FitManagerMinuit1.cpp