GooFit: GooFit::BinnedDataSet Class Reference
GooFit::BinnedDataSet Class Reference
#include <BinnedDataSet.h>
Public Member Functions
BinnedDataSet (const Observable &var, std::string n="")
BinnedDataSet (const std::vector< Observable > &vars, std::string n="")
BinnedDataSet (const std::set< Observable > &vars, std::string n="")
BinnedDataSet (std::initializer_list< Observable > vars, std::string n="")
~BinnedDataSet () override=default
void addEvent () override
void addWeightedEvent (double weight) override
fptype getBinContent (size_t bin) const
fptype getBinCenter (size_t ivar, size_t bin) const
fptype getBinCenter (const Observable &var, size_t bin) const
fptype getBinSize (size_t ivar) const
size_t getBinNumber () const
fptype getBinVolume (size_t bin) const
fptype getBinError (size_t bin) const
size_t getNumBins () const
fptype getNumWeightedEvents () const
This includes weights.
void setBinContent (unsigned int bin, fptype value)
void setBinError (unsigned int bin, fptype error)
Public Member Functions inherited from GooFit::DataSet
DataSet (const Observable &var, std::string n="")
DataSet (const std::vector< Observable > &vars, std::string n="")
DataSet (const std::set< Observable > &vars, std::string n="")
DataSet (std::initializer_list< Observable > vars, std::string n="")
virtual ~DataSet ()=default
template<typename... Args>
void addEvent (fptype value, Args... args)
This is a helper that allows multiple values to be passed in instead of relying on the content of the Variables.
const std::vector< Observable > & getObservables () const
size_t numVariables () const
size_t getNumEvents () const
std::string getName () const
Additional Inherited Members
Protected Member Functions inherited from GooFit::DataSet
std::vector< fptype > getCurrentValues () const
size_t indexOfVariable (const Observable &var) const
void checkAllVars () const
Throw an error if any variables are out of range, call in addEvent.
Protected Attributes inherited from GooFit::DataSet
size_t numEventsAdded {0}
std::vector< Observable > observables
Detailed Description
Definition at line 10 of file BinnedDataSet.h.
Constructor & Destructor Documentation
BinnedDataSet() [1/4]
GooFit::BinnedDataSet::BinnedDataSet (const Observable & var, std::string n = "")
Definition at line 12 of file BinnedDataSet.cpp.
References getNumBins().
     : DataSet(var, n) {
     collectBins();
     binvalues.resize(getNumBins());
 }
BinnedDataSet() [2/4]
GooFit::BinnedDataSet::BinnedDataSet (const std::vector< Observable > & vars, std::string n = "")
Definition at line 18 of file BinnedDataSet.cpp.
References getNumBins().
     : DataSet(vars, n) {
     collectBins();
     binvalues.resize(getNumBins());
 }
BinnedDataSet() [3/4]
GooFit::BinnedDataSet::BinnedDataSet (const std::set< Observable > & vars, std::string n = "")
Definition at line 24 of file BinnedDataSet.cpp.
References getNumBins().
     : DataSet(vars, n) {
     collectBins();
     binvalues.resize(getNumBins());
 }
BinnedDataSet() [4/4]
GooFit::BinnedDataSet::BinnedDataSet (std::initializer_list< Observable > vars, std::string n = "")
Definition at line 30 of file BinnedDataSet.cpp.
References getNumBins().
     : DataSet(vars, n) {
     collectBins();
     binvalues.resize(getNumBins());
 }
~BinnedDataSet()
GooFit::BinnedDataSet::~BinnedDataSet () override default
Member Function Documentation
addEvent()
void GooFit::BinnedDataSet::addEvent () override virtual
Implements GooFit::DataSet.
Definition at line 36 of file BinnedDataSet.cpp.
References GooFit::DataSet::checkAllVars(), getBinNumber(), and GooFit::DataSet::numEventsAdded.
{
     checkAllVars();
     size_t ibin = getBinNumber();
     binvalues.at(ibin) += 1;
     numEventsAdded++;
 }
addWeightedEvent()
void GooFit::BinnedDataSet::addWeightedEvent (double weight) override virtual
Reimplemented from GooFit::DataSet.
Definition at line 43 of file BinnedDataSet.cpp.
References GooFit::DataSet::checkAllVars(), getBinNumber(), GooFit::DataSet::numEventsAdded, and GooFit::DataSet::observables.
{
     checkAllVars();
     size_t ibin = getBinNumber();
     binvalues.at(ibin) += weight;
     numEventsAdded++;
 }
getBinCenter() [1/2]
fptype GooFit::BinnedDataSet::getBinCenter (size_t ivar, size_t bin) const
Definition at line 92 of file BinnedDataSet.cpp.
References getBinSize(), and GooFit::DataSet::observables.
Referenced by getBinCenter(), and getBinContent().
{
     std::vector<size_t> locals = globalToLocal(bin);
     size_t localBin            = locals.at(ivar);
     fptype ret = getBinSize(ivar);
     ret *= (localBin + 0.5);
     ret += observables[ivar].getLowerLimit();
     return ret;
 }
getBinCenter() [2/2]
fptype GooFit::BinnedDataSet::getBinCenter (const Observable & var, size_t bin) const
Definition at line 102 of file BinnedDataSet.cpp.
References getBinCenter(), and GooFit::DataSet::indexOfVariable().
{
     size_t ivar = indexOfVariable(var);
     return getBinCenter(ivar, bin);
 }
getBinContent()
fptype GooFit::BinnedDataSet::getBinContent (size_t bin) const inline
Definition at line 25 of file BinnedDataSet.h.
References getBinCenter(), getBinError(), getBinNumber(), getBinSize(), getBinVolume(), getNumBins(), and getNumWeightedEvents().
 { return binvalues.at(bin); }
getBinError()
fptype GooFit::BinnedDataSet::getBinError (size_t bin) const
Definition at line 121 of file BinnedDataSet.cpp.
Referenced by getBinContent().
{
     if(0 == binerrors.size())
         return sqrt(binvalues.at(bin));
     return binerrors.at(bin);
 }
getBinNumber()
size_t GooFit::BinnedDataSet::getBinNumber () const
Definition at line 58 of file BinnedDataSet.cpp.
References GooFit::DataSet::getCurrentValues(), and GooFit::DataSet::observables.
Referenced by addEvent(), addWeightedEvent(), and getBinContent().
{
     std::vector<fptype> vals   = getCurrentValues();
     std::vector<size_t> locals = convertValuesToBins(vals);
     return localToGlobal(locals);
 }
getBinSize()
fptype GooFit::BinnedDataSet::getBinSize (size_t ivar) const
Definition at line 107 of file BinnedDataSet.cpp.
References GooFit::DataSet::observables.
Referenced by getBinCenter(), getBinContent(), getBinVolume(), and getNumWeightedEvents().
{
     return (observables.at(ivar).getUpperLimit() - observables[ivar].getLowerLimit()) / binsizes[ivar];
 }
getBinVolume()
fptype GooFit::BinnedDataSet::getBinVolume (size_t bin) const
Definition at line 111 of file BinnedDataSet.cpp.
References getBinSize(), and GooFit::DataSet::observables.
Referenced by getBinContent().
{
     fptype ret = 1;
     for(size_t i = 0; i < observables.size(); i++) {
         ret *= getBinSize(i);
     }
     return ret;
 }
getNumBins()
size_t GooFit::BinnedDataSet::getNumBins () const
Definition at line 135 of file BinnedDataSet.cpp.
Referenced by BinnedDataSet(), and getBinContent().
{
     return std::accumulate(std::begin(binsizes), std::end(binsizes), 1, std::multiplies<size_t>());
 }
getNumWeightedEvents()
fptype GooFit::BinnedDataSet::getNumWeightedEvents () const
This includes weights.
Definition at line 139 of file BinnedDataSet.cpp.
References getBinSize(), GooFit::DataSet::getName(), GOOFIT_INFO, and GooFit::DataSet::observables.
Referenced by getBinContent().
{
     return std::accumulate(std::begin(binvalues), std::end(binvalues), 0);
 }
setBinContent()
void GooFit::BinnedDataSet::setBinContent (unsigned int bin, fptype value) inline
Definition at line 39 of file BinnedDataSet.h.
References setBinError().
 { binvalues.at(bin) = value; }
setBinError()
void GooFit::BinnedDataSet::setBinError (unsigned int bin, fptype error)
Definition at line 128 of file BinnedDataSet.cpp.
Referenced by setBinContent().
{
     if(0 == binerrors.size())
         binerrors.resize(binvalues.size());
     binerrors.at(bin) = error;
 }
The documentation for this class was generated from the following files:
/home/travis/build/GooFit/GooFit/include/goofit/BinnedDataSet.h
/home/travis/build/GooFit/GooFit/src/goofit/BinnedDataSet.cpp