GooFit: GooFit::FCN Class Reference
GooFit::FCN Class Reference
#include <FCN.h>
Public Member Functions
FCN (Params &params)
Create an FCN given parameters (PDF reference is inside params)
double operator() (const std::vector< double > &pars) const override
Run the fit (used by Minuit2 class)
double operator() () const
produce the FCN value for the current values of the parameters
double Up () const override
This value is 0.5 for ll, 1 for chi2.
Params * GetParams ()
Get a pointer to the parameters.
Protected Attributes
Params * params_
Detailed Description
Definition at line 11 of file FCN.h.
Constructor & Destructor Documentation
FCN()
GooFit::FCN::FCN (Params & params)
Create an FCN given parameters (PDF reference is inside params)
Definition at line 9 of file FCN.cc.
References GooFit::host_callnumber, params_, GooFit::Variable::setChanged(), and GooFit::Params::vars_.
     : params_(&params) {
     host_callnumber = 0;
     // Verify that all varaibles need to be recached
     for(Variable *var : params_->vars_)
         var->setChanged(true);
 }
Member Function Documentation
GetParams()
Params * GooFit::FCN::GetParams ()
Get a pointer to the parameters.
Definition at line 44 of file FCN.cc.
References params_.
Referenced by Up().
 { return params_; }
operator()() [1/2]
double GooFit::FCN::operator() (const std::vector< double > & pars) const override
Run the fit (used by Minuit2 class)
Definition at line 18 of file FCN.cc.
References GooFit::PdfBase::calculateNLL(), GooFit::Params::from_minuit_vector(), GOOFIT_TRACE, GooFit::host_callnumber, params_, and GooFit::Params::pdf_.
{
     // Translate from Minuit indexing to GooFit indexing
     params_->from_minuit_vector(pars);
     GOOFIT_TRACE("Calculating NLL");
     double nll = params_->pdf_->calculateNLL();
     host_callnumber++;
     return nll;
 }
operator()() [2/2]
double GooFit::FCN::operator() () const
produce the FCN value for the current values of the parameters
Definition at line 30 of file FCN.cc.
References GooFit::PdfBase::calculateNLL(), GooFit::Params::from_minuit_vector(), GOOFIT_TRACE, GooFit::host_callnumber, GooFit::Params::make_minuit_vector(), params_, and GooFit::Params::pdf_.
{
     // Make a vector of current values, then force the recalculation step
     std::vector<double> pars = params_->make_minuit_vector();
     params_->from_minuit_vector(pars, true);
     GOOFIT_TRACE("Calculating NLL");
     double nll = params_->pdf_->calculateNLL();
     host_callnumber++;
     return nll;
 }
Up()
double GooFit::FCN::Up () const inline override
This value is 0.5 for ll, 1 for chi2.
Definition at line 26 of file FCN.h.
References GetParams().
 { return 0.5; }
Member Data Documentation
params_
Params* GooFit::FCN::params_ protected
Definition at line 13 of file FCN.h.
Referenced by FCN(), GetParams(), and operator()().
The documentation for this class was generated from the following files:
/home/travis/build/GooFit/GooFit/include/goofit/fitting/FCN.h
/home/travis/build/GooFit/GooFit/src/goofit/FCN.cc