GooFit: GooFit::Params Class Reference
GooFit::Params Class Reference
#include <Params.h>
Public Member Functions
Params (PdfBase &pdf)
void SetGooFitParams (const Minuit2::MnUserParameterState &input)
Read the values back into GooFit.
size_t size () const
Get the number of params in the fit.
std::vector< double > make_minuit_vector () const
Make a parameter array with the current variable values.
void from_minuit_vector (const std::vector< double > &values, bool force_changed=false)
Set from a minuit vector. Optional force_changed to force complete recalculation.
void set_record (bool do_record=true)
Set recording of Minuit parameter changes.
std::vector< std::vector< double > > get_recorded () const
Get recorded values array.
Protected Attributes
std::vector< Variable > vars_
PdfBase * pdf_
size_t num_
bool do_record_ {false}
std::vector< std::vector< double > > recorded_
Detailed Description
Definition at line 18 of file Params.h.
Constructor & Destructor Documentation
Params()
GooFit::Params::Params (PdfBase & pdf)
Definition at line 8 of file Params.cpp.
References GooFit::PdfBase::getParameters(), pdf_, and vars_.
     : pdf_(&pdf) {
     vars_ = pdf_->getParameters();
     for(Variable &var : vars_) {
         bool added;
         if(var.IsFixed()) {
             added = Add(var.getName(), var.getValue());
         } else if(var.getLowerLimit() == var.getUpperLimit()) {
             added = Add(var.getName(), var.getValue(), var.getError());
         } else {
             added = Add(var.getName(), var.getValue(), var.getError(), var.getLowerLimit(), var.getUpperLimit());
         }
         if(!added)
             throw std::runtime_error("The name " + var.getName() + " appears more than once!");
         var.setFitterIndex(Index(var.getName()));
     }
 }
Member Function Documentation
from_minuit_vector()
void GooFit::Params::from_minuit_vector (const std::vector< double > & values, bool force_changed = false)
Set from a minuit vector. Optional force_changed to force complete recalculation.
Definition at line 47 of file Params.cpp.
References GooFit::PdfBase::copyParams(), do_record_, GooFit::max_index(), pdf_, recorded_, and vars_.
Referenced by GooFit::FCN::operator()(), and size().
{
     std::vector<double> gooPars(max_index(vars_) + 1);
     for(Variable &var : vars_) {
         var.setChanged(force_changed ? true : var.getValue() != values.at(var.getFitterIndex()));
         gooPars.at(var.getIndex()) = values.at(var.getFitterIndex()) - var.getBlind(Variable::Key());
     }
     if(do_record_)
         recorded_.push_back(values);
     pdf_->copyParams(gooPars);
 }
get_recorded()
std::vector<std::vector<double> > GooFit::Params::get_recorded () const inline
Get recorded values array.
Definition at line 50 of file Params.h.
References recorded_.
 { return recorded_; }
make_minuit_vector()
std::vector< double > GooFit::Params::make_minuit_vector () const
Make a parameter array with the current variable values.
Definition at line 39 of file Params.cpp.
References GooFit::max_fitter_index(), and vars_.
Referenced by GooFit::FCN::operator()(), and size().
{
     std::vector<double> minuitPars(max_fitter_index(vars_) + 1);
     for(const Variable &var : vars_) {
         minuitPars.at(var.getFitterIndex()) = var.getValue();
     }
     return minuitPars;
 }
set_record()
void GooFit::Params::set_record (bool do_record = true) inline
Set recording of Minuit parameter changes.
Definition at line 47 of file Params.h.
References do_record_.
 { do_record_ = do_record; }
SetGooFitParams()
void GooFit::Params::SetGooFitParams (const Minuit2::MnUserParameterState & input)
Read the values back into GooFit.
Definition at line 29 of file Params.cpp.
References vars_.
{
     for(Variable &var : vars_) {
         int counter = var.getFitterIndex();
         var.setValue(input.Value(counter));
         var.setError(input.Error(counter));
         SetValue(counter, var.getValue());
         SetError(counter, var.getError());
     }
 }
size()
size_t GooFit::Params::size () const inline
Get the number of params in the fit.
Definition at line 38 of file Params.h.
References from_minuit_vector(), and make_minuit_vector().
 { return vars_.size(); };
Member Data Documentation
do_record_
bool GooFit::Params::do_record_ {false} protected
Definition at line 26 of file Params.h.
Referenced by from_minuit_vector(), and set_record().
num_
size_t GooFit::Params::num_ protected
Definition at line 24 of file Params.h.
pdf_
PdfBase* GooFit::Params::pdf_ protected
Definition at line 23 of file Params.h.
Referenced by from_minuit_vector(), GooFit::FCN::operator()(), and Params().
recorded_
std::vector<std::vector<double> > GooFit::Params::recorded_ protected
Definition at line 27 of file Params.h.
Referenced by from_minuit_vector(), and get_recorded().
vars_
std::vector<Variable> GooFit::Params::vars_ protected
Definition at line 22 of file Params.h.
Referenced by GooFit::FCN::FCN(), from_minuit_vector(), make_minuit_vector(), Params(), and SetGooFitParams().
The documentation for this class was generated from the following files:
/home/travis/build/GooFit/GooFit/include/goofit/fitting/Params.h
/home/travis/build/GooFit/GooFit/src/goofit/Params.cpp