GooFit: LorentzMatrix Class Reference
LorentzMatrix Class Reference
#include <SpinHelper.h>
Public Member Functions
EXEC_TARGET const gpuLVec & v (int i) const
EXEC_TARGET LorentzMatrix ()
EXEC_TARGET LorentzMatrix (const gpuLVec p[4])
EXEC_TARGET LorentzMatrix (const LorentzMatrix &other)
EXEC_TARGET const gpuLVec & X () const
EXEC_TARGET const gpuLVec & Y () const
EXEC_TARGET const gpuLVec & Z () const
EXEC_TARGET const gpuLVec & E () const
EXEC_TARGET gpuLVec & X ()
EXEC_TARGET gpuLVec & Y ()
EXEC_TARGET gpuLVec & Z ()
EXEC_TARGET gpuLVec & E ()
EXEC_TARGET const gpuLVec & operator[] (int i) const
EXEC_TARGET gpuLVec & operator[] (int i)
EXEC_TARGET LorentzMatrix & add (const LorentzMatrix &other)
EXEC_TARGET LorentzMatrix & subtract (const LorentzMatrix &other)
EXEC_TARGET LorentzMatrix & mult (fptype s)
EXEC_TARGET LorentzMatrix & div (fptype s)
EXEC_TARGET LorentzMatrix & operator+= (const LorentzMatrix &rhs)
EXEC_TARGET LorentzMatrix & operator*= (fptype rhs)
EXEC_TARGET LorentzMatrix & operator-= (const LorentzMatrix &rhs)
EXEC_TARGET LorentzMatrix & operator/= (fptype rhs)
EXEC_TARGET LorentzMatrix & operator= (const LorentzMatrix &other)
EXEC_TARGET LorentzMatrix operator+ (const LorentzMatrix &rhs) const
EXEC_TARGET LorentzMatrix operator- (const LorentzMatrix &rhs) const
EXEC_TARGET LorentzMatrix operator* (fptype rhs) const
EXEC_TARGET LorentzMatrix operator/ (fptype rhs) const
Protected Member Functions
EXEC_TARGET bool makeZero ()
Protected Attributes
gpuLVec _v [4]
Detailed Description
Definition at line 157 of file SpinHelper.h.
Constructor & Destructor Documentation
LorentzMatrix() [1/3]
EXEC_TARGET LorentzMatrix::LorentzMatrix () inline
Definition at line 173 of file SpinHelper.h.
 {};
LorentzMatrix() [2/3]
EXEC_TARGET LorentzMatrix::LorentzMatrix (const gpuLVec p[4]) inline
Definition at line 174 of file SpinHelper.h.
{
         for(int i=0; i<4; i++)
             _v[i] = p[i];
     }
LorentzMatrix() [3/3]
EXEC_TARGET LorentzMatrix::LorentzMatrix (const LorentzMatrix & other) inline
Definition at line 178 of file SpinHelper.h.
References _v.
{
         for(int i=0; i<4; i++)
             _v[i] = other._v[i];
     }
Member Function Documentation
add()
EXEC_TARGET LorentzMatrix& LorentzMatrix::add (const LorentzMatrix & other) inline
Definition at line 215 of file SpinHelper.h.
References _v.
{
         for(int i=0; i < 4; i++)
             _v[i] += other._v[i];
         return *this;
     }
div()
EXEC_TARGET LorentzMatrix& LorentzMatrix::div (fptype s) inline
Definition at line 233 of file SpinHelper.h.
{
         for(int i=0; i < 4; i++)
             _v[i] *= (1./s);
         return *this;
     }
E() [1/2]
EXEC_TARGET const gpuLVec& LorentzMatrix::E () const inline
Definition at line 191 of file SpinHelper.h.
Referenced by SymmLorentzMatrix::Contract_1(), and SymmLorentzMatrix::Contract_2().
{
         return _v[3];
     }
E() [2/2]
EXEC_TARGET gpuLVec& LorentzMatrix::E () inline
Definition at line 204 of file SpinHelper.h.
{
         return _v[3];
     }
makeZero()
EXEC_TARGET bool LorentzMatrix::makeZero () inline protected
Definition at line 161 of file SpinHelper.h.
{
         X().SetXYZE(0, 0, 0, 0);
         Y().SetXYZE(0, 0, 0, 0);
         Z().SetXYZE(0, 0, 0, 0);
         E().SetXYZE(0, 0, 0, 0);
         return true;
     }
mult()
EXEC_TARGET LorentzMatrix& LorentzMatrix::mult (fptype s) inline
Definition at line 227 of file SpinHelper.h.
{
         for(int i=0; i < 4; i++)
             _v[i] *= s;
         return *this;
     }
operator*()
EXEC_TARGET LorentzMatrix LorentzMatrix::operator* (fptype rhs) const inline
Definition at line 268 of file SpinHelper.h.
{
         LorentzMatrix returnVal(*this);
         returnVal *= rhs;
         return returnVal;
     }
operator*=()
EXEC_TARGET LorentzMatrix& LorentzMatrix::operator*= (fptype rhs) inline
Definition at line 243 of file SpinHelper.h.
{
         return mult(rhs);
     }
operator+()
EXEC_TARGET LorentzMatrix LorentzMatrix::operator+ (const LorentzMatrix & rhs) const inline
Definition at line 258 of file SpinHelper.h.
{
         LorentzMatrix returnVal(*this);
         returnVal += rhs;
         return returnVal;
     }
operator+=()
EXEC_TARGET LorentzMatrix& LorentzMatrix::operator+= (const LorentzMatrix & rhs) inline
Definition at line 240 of file SpinHelper.h.
{
         return add(rhs);
     }
operator-()
EXEC_TARGET LorentzMatrix LorentzMatrix::operator- (const LorentzMatrix & rhs) const inline
Definition at line 263 of file SpinHelper.h.
{
         LorentzMatrix returnVal(*this);
         returnVal -= rhs;
         return returnVal;
     }
operator-=()
EXEC_TARGET LorentzMatrix& LorentzMatrix::operator-= (const LorentzMatrix & rhs) inline
Definition at line 246 of file SpinHelper.h.
{
         return subtract(rhs);
     }
operator/()
EXEC_TARGET LorentzMatrix LorentzMatrix::operator/ (fptype rhs) const inline
Definition at line 273 of file SpinHelper.h.
{
         LorentzMatrix returnVal(*this);
         returnVal /= rhs;
         return returnVal;
     }
operator/=()
EXEC_TARGET LorentzMatrix& LorentzMatrix::operator/= (fptype rhs) inline
Definition at line 249 of file SpinHelper.h.
{
         return div(rhs);
     }
operator=()
EXEC_TARGET LorentzMatrix& LorentzMatrix::operator= (const LorentzMatrix & other) inline
Definition at line 252 of file SpinHelper.h.
References _v.
{
         for(int i=0; i<4; i++)
             _v[i] = other._v[i];
         return *this;
     }
operator[]() [1/2]
EXEC_TARGET const gpuLVec& LorentzMatrix::operator[] (int i) const inline
Definition at line 208 of file SpinHelper.h.
{
         return _v[i];
     }
operator[]() [2/2]
EXEC_TARGET gpuLVec& LorentzMatrix::operator[] (int i) inline
Definition at line 211 of file SpinHelper.h.
{
         return _v[i];
     }
subtract()
EXEC_TARGET LorentzMatrix& LorentzMatrix::subtract (const LorentzMatrix & other) inline
Definition at line 221 of file SpinHelper.h.
References _v.
{
         for(int i=0; i < 4; i++)
             _v[i] -= other._v[i];
         return *this;
     }
v()
EXEC_TARGET const gpuLVec& LorentzMatrix::v (int i) const inline
Definition at line 169 of file SpinHelper.h.
Referenced by ZTspin2::operator=().
{
         return _v[i];
     }
X() [1/2]
EXEC_TARGET const gpuLVec& LorentzMatrix::X () const inline
Definition at line 182 of file SpinHelper.h.
Referenced by SymmLorentzMatrix::Contract_1(), and SymmLorentzMatrix::Contract_2().
{
         return _v[0];
     }
X() [2/2]
EXEC_TARGET gpuLVec& LorentzMatrix::X () inline
Definition at line 195 of file SpinHelper.h.
{
         return _v[0];
     }
Y() [1/2]
EXEC_TARGET const gpuLVec& LorentzMatrix::Y () const inline
Definition at line 185 of file SpinHelper.h.
Referenced by SymmLorentzMatrix::Contract_1(), and SymmLorentzMatrix::Contract_2().
{
         return _v[1];
     }
Y() [2/2]
EXEC_TARGET gpuLVec& LorentzMatrix::Y () inline
Definition at line 198 of file SpinHelper.h.
{
         return _v[1];
     }
Z() [1/2]
EXEC_TARGET const gpuLVec& LorentzMatrix::Z () const inline
Definition at line 188 of file SpinHelper.h.
Referenced by SymmLorentzMatrix::Contract_1(), and SymmLorentzMatrix::Contract_2().
{
         return _v[2];
     }
Z() [2/2]
EXEC_TARGET gpuLVec& LorentzMatrix::Z () inline
Definition at line 201 of file SpinHelper.h.
{
         return _v[2];
     }
Member Data Documentation
_v
gpuLVec LorentzMatrix::_v[4] protected
Definition at line 159 of file SpinHelper.h.
Referenced by add(), SymmLorentzMatrix::add(), LorentzMatrix(), operator=(), SymmLorentzMatrix::operator=(), subtract(), and SymmLorentzMatrix::subtract().
The documentation for this class was generated from the following file:
/home/travis/build/GooFit/GooFit/include/goofit/PDFs/SpinHelper.h