GooFit: GooFit::FitManagerMinuit1 Class Reference
GooFit::FitManagerMinuit1 Class Reference
#include <FitManagerMinuit1.h>
Public Member Functions
FitManagerMinuit1 (PdfBase *dat)
~FitManagerMinuit1 ()
void setMaxCalls (double mxc)
void useHesseBefore (bool use=true)
void useHesse (bool use=true)
void useMinos (bool use=true)
void useImprove (bool use=true)
void setupMinuit ()
void runMigrad ()
void fit ()
TMinuit * getMinuitObject ()
void getMinuitValues () const
void getMinuitStatus (double &fmin, double &fedm, double &errdef, int &npari, int &nparx, int &istat) const
Public Attributes
TMinuit * minuit
Detailed Description
Definition at line 15 of file FitManagerMinuit1.h.
Constructor & Destructor Documentation
FitManagerMinuit1()
GooFit::FitManagerMinuit1::FitManagerMinuit1 (PdfBase * dat)
Definition at line 20 of file FitManagerMinuit1.cc.
     : minuit(0)
     , overrideCallLimit(-1)
     , _useHesseBefore(true)
     , _useHesse(true)
     , _useMinos(false)
     , _useImprove(false) {
     pdfPointer = dat;
     currGlue = this;
 }
~FitManagerMinuit1()
GooFit::FitManagerMinuit1::~FitManagerMinuit1 ()
Definition at line 31 of file FitManagerMinuit1.cc.
References minuit.
{
     if(minuit)
         delete minuit;
 }
Member Function Documentation
fit()
void GooFit::FitManagerMinuit1::fit ()
Definition at line 66 of file FitManagerMinuit1.cc.
References runMigrad(), and setupMinuit().
Referenced by useImprove().
{
     setupMinuit();
     runMigrad();
 }
getMinuitObject()
TMinuit* GooFit::FitManagerMinuit1::getMinuitObject () inline
Definition at line 37 of file FitManagerMinuit1.h.
References getMinuitStatus(), getMinuitValues(), and minuit.
{
         return minuit;
     }
getMinuitStatus()
void GooFit::FitManagerMinuit1::getMinuitStatus (double & fmin, double & fedm, double & errdef, int & npari, int & nparx, int & istat) const
Definition at line 106 of file FitManagerMinuit1.cc.
References minuit, and TMinuit::mnstat().
Referenced by getMinuitObject().
{
     minuit->mnstat(fmin, fedm, errdef, npari, nparx, istat);
     std::cout << "mnstat(fmin = " << fmin << ", fedm = " << fedm << ", errdef = " << errdef
               << ", npari = " << npari << ", nparx = " << nparx << ", istat = " << istat << ")" << std::endl;
 }
getMinuitValues()
void GooFit::FitManagerMinuit1::getMinuitValues () const
Definition at line 98 of file FitManagerMinuit1.cc.
References TMinuit::GetParameter(), minuit, and vars.
Referenced by FitFun(), and getMinuitObject().
{
     int counter = 0;
     for(std::vector<Variable*>::iterator i = vars.begin(); i != vars.end(); ++i) {
         minuit->GetParameter(counter++, (*i)->value, (*i)->error);
     }
 }
runMigrad()
void GooFit::FitManagerMinuit1::runMigrad ()
Definition at line 71 of file FitManagerMinuit1.cc.
References host_callnumber, TMinuit::Migrad(), minuit, and TMinuit::mnexcm().
Referenced by fit(), and useImprove().
{
     assert(minuit);
     host_callnumber = 0;
     if(0 < overrideCallLimit) {
         std::cout << "Calling MIGRAD with call limit " << overrideCallLimit << std::endl;
         double plist[1];
         plist[0] = overrideCallLimit;
         int err = 0;
         if(_useHesseBefore)
             minuit->mnexcm("HESSE", plist, 1, err);
         minuit->mnexcm("MIGRAD", plist, 1, err);
         if(_useHesse)
             minuit->mnexcm("HESSE", plist, 1, err);
         if(_useMinos)
             minuit->mnexcm("MINOS", plist, 1, err);
         if(_useImprove)
             minuit->mnexcm("IMPROVE", plist, 1, err);
     } else
         minuit->Migrad();
 }
setMaxCalls()
void GooFit::FitManagerMinuit1::setMaxCalls (double mxc) inline
Definition at line 19 of file FitManagerMinuit1.h.
{
         overrideCallLimit = mxc;
     }
setupMinuit()
void GooFit::FitManagerMinuit1::setupMinuit ()
Definition at line 36 of file FitManagerMinuit1.cc.
References PdfBase::copyParams(), TMinuit::DefineParameter(), FitFun(), TMinuit::FixParameter(), PdfBase::getParameters(), minuit, numPars, TMinuit::SetFCN(), and vars.
Referenced by fit(), and useImprove().
{
     vars.clear();
     pdfPointer->getParameters(vars);
     numPars = vars.size();
     if(minuit)
         delete minuit;
     minuit = new TMinuit(numPars);
     int maxIndex = 0;
     int counter = 0;
     for(std::vector<Variable*>::iterator i = vars.begin(); i != vars.end(); ++i) {
         minuit->DefineParameter(counter, (*i)->name.c_str(), (*i)->value, (*i)->error, (*i)->lowerlimit, (*i)->upperlimit);
         if((*i)->fixed)
             minuit->FixParameter(counter);
         counter++;
         if(maxIndex < (*i)->getIndex())
             maxIndex = (*i)->getIndex();
     }
     numPars = maxIndex+1;
     pdfPointer->copyParams();
     minuit->SetFCN(FitFun);
 }
useHesse()
void GooFit::FitManagerMinuit1::useHesse (bool use = true) inline
Definition at line 25 of file FitManagerMinuit1.h.
{
         _useHesse = use;
     }
useHesseBefore()
void GooFit::FitManagerMinuit1::useHesseBefore (bool use = true) inline
Definition at line 22 of file FitManagerMinuit1.h.
{
         _useHesseBefore = use;
     }
useImprove()
void GooFit::FitManagerMinuit1::useImprove (bool use = true) inline
Definition at line 31 of file FitManagerMinuit1.h.
References fit(), runMigrad(), and setupMinuit().
{
         _useImprove = use;
     }
useMinos()
void GooFit::FitManagerMinuit1::useMinos (bool use = true) inline
Definition at line 28 of file FitManagerMinuit1.h.
{
         _useMinos = use;
     }
Member Data Documentation
minuit
TMinuit* GooFit::FitManagerMinuit1::minuit
Definition at line 42 of file FitManagerMinuit1.h.
Referenced by getMinuitObject(), getMinuitStatus(), getMinuitValues(), runMigrad(), setupMinuit(), and ~FitManagerMinuit1().
The documentation for this class was generated from the following files:
/home/travis/build/GooFit/GooFit/include/goofit/FitManagerMinuit1.h
/home/travis/build/GooFit/GooFit/src/goofit/FitManagerMinuit1.cc