GooFit: GooFit::SymmLorentzMatrix Class Reference
GooFit::SymmLorentzMatrix Class Reference
#include <SpinHelper.h>
Public Member Functions
__device__ void makeGmunu ()
__device__ const SymmLorentzMatrix & gmunu ()
__device__ SymmLorentzMatrix ()
__device__ SymmLorentzMatrix (const gpuLVec p[4])
__device__ SymmLorentzMatrix (const gpuLVec p)
__device__ SymmLorentzMatrix (const SymmLorentzMatrix &other)=default
__device__ SymmLorentzMatrix & add (const SymmLorentzMatrix &other)
__device__ SymmLorentzMatrix & subtract (const SymmLorentzMatrix &other)
__device__ SymmLorentzMatrix & mult (fptype s)
__device__ SymmLorentzMatrix & div (fptype s)
__device__ gpuLVec Contract (const gpuLVec &vec)
__device__ LorentzMatrix Contract_1 (const SymmLorentzMatrix &M)
__device__ fptype Contract_2 (const SymmLorentzMatrix &M)
__device__ SymmLorentzMatrix & operator+= (const SymmLorentzMatrix &rhs)
__device__ SymmLorentzMatrix & operator*= (fptype rhs)
__device__ SymmLorentzMatrix & operator-= (const SymmLorentzMatrix &rhs)
__device__ SymmLorentzMatrix & operator/= (fptype rhs)
__device__ SymmLorentzMatrix & operator= (const SymmLorentzMatrix &other)
__device__ SymmLorentzMatrix operator+ (const SymmLorentzMatrix &rhs) const
__device__ SymmLorentzMatrix operator- (const SymmLorentzMatrix &rhs) const
__device__ SymmLorentzMatrix operator* (fptype rhs) const
__device__ SymmLorentzMatrix operator/ (fptype rhs) const
Public Member Functions inherited from GooFit::LorentzMatrix
__device__ const gpuLVec & v (int i) const
__device__ LorentzMatrix ()=default
__device__ LorentzMatrix (const gpuLVec p[4])
__device__ LorentzMatrix (const LorentzMatrix &other)
__device__ const gpuLVec & X () const
__device__ const gpuLVec & Y () const
__device__ const gpuLVec & Z () const
__device__ const gpuLVec & E () const
__device__ gpuLVec & X ()
__device__ gpuLVec & Y ()
__device__ gpuLVec & Z ()
__device__ gpuLVec & E ()
__device__ const gpuLVec & operator[] (int i) const
__device__ gpuLVec & operator[] (int i)
__device__ LorentzMatrix & add (const LorentzMatrix &other)
__device__ LorentzMatrix & subtract (const LorentzMatrix &other)
__device__ LorentzMatrix & mult (fptype s)
__device__ LorentzMatrix & div (fptype s)
__device__ LorentzMatrix & operator+= (const LorentzMatrix &rhs)
__device__ LorentzMatrix & operator*= (fptype rhs)
__device__ LorentzMatrix & operator-= (const LorentzMatrix &rhs)
__device__ LorentzMatrix & operator/= (fptype rhs)
__device__ LorentzMatrix & operator= (const LorentzMatrix &other)
__device__ LorentzMatrix operator+ (const LorentzMatrix &rhs) const
__device__ LorentzMatrix operator- (const LorentzMatrix &rhs) const
__device__ LorentzMatrix operator* (fptype rhs) const
__device__ LorentzMatrix operator/ (fptype rhs) const
Protected Member Functions
__device__ bool symmetrize ()
__device__ bool makeZero ()
Protected Member Functions inherited from GooFit::LorentzMatrix
__device__ bool makeZero ()
Additional Inherited Members
Protected Attributes inherited from GooFit::LorentzMatrix
gpuLVec _v [4]
Detailed Description
Definition at line 210 of file SpinHelper.h.
Constructor & Destructor Documentation
SymmLorentzMatrix() [1/4]
__device__ GooFit::SymmLorentzMatrix::SymmLorentzMatrix () inline
Definition at line 250 of file SpinHelper.h.
         : LorentzMatrix() {}
SymmLorentzMatrix() [2/4]
__device__ GooFit::SymmLorentzMatrix::SymmLorentzMatrix (const gpuLVec p[4]) inline
Definition at line 252 of file SpinHelper.h.
         : LorentzMatrix(p){};
SymmLorentzMatrix() [3/4]
__device__ GooFit::SymmLorentzMatrix::SymmLorentzMatrix (const gpuLVec p) inline
Definition at line 255 of file SpinHelper.h.
{
         X().SetX(p.GetX() * p.GetX());
         X().SetY(p.GetX() * p.GetY());
         X().SetZ(p.GetX() * p.GetZ());
         X().SetE(p.GetX() * p.GetE());
         Y().SetX(p.GetY() * p.GetX());
         Y().SetY(p.GetY() * p.GetY());
         Y().SetZ(p.GetY() * p.GetZ());
         Y().SetE(p.GetY() * p.GetE());
         Z().SetX(p.GetZ() * p.GetX());
         Z().SetY(p.GetZ() * p.GetY());
         Z().SetZ(p.GetZ() * p.GetZ());
         Z().SetE(p.GetZ() * p.GetE());
         E().SetX(p.GetE() * p.GetX());
         E().SetY(p.GetE() * p.GetY());
         E().SetZ(p.GetE() * p.GetZ());
         E().SetE(p.GetE() * p.GetE());
     }
SymmLorentzMatrix() [4/4]
__device__ GooFit::SymmLorentzMatrix::SymmLorentzMatrix (const SymmLorentzMatrix & other) default
Member Function Documentation
add()
__device__ SymmLorentzMatrix& GooFit::SymmLorentzMatrix::add (const SymmLorentzMatrix & other) inline
Definition at line 278 of file SpinHelper.h.
References GooFit::LorentzMatrix::_v.
{
         for(int i = 0; i < 4; i++)
             _v[i] += other._v[i];
         return *this;
     }
Contract()
__device__ gpuLVec GooFit::SymmLorentzMatrix::Contract (const gpuLVec & vec) inline
Definition at line 302 of file SpinHelper.h.
{
         // M^{mu nu} g_{nu alpha} v^{alpha}
         // M^{mu nu} v_{alpha}
         return vec.GetE() * E() - vec.GetX() * X() - vec.GetY() * Y() - vec.GetZ() * Z();
     }
Contract_1()
__device__ LorentzMatrix GooFit::SymmLorentzMatrix::Contract_1 (const SymmLorentzMatrix & M) inline
Definition at line 307 of file SpinHelper.h.
References GooFit::LorentzMatrix::E(), GooFit::LorentzMatrix::X(), GooFit::LorentzMatrix::Y(), and GooFit::LorentzMatrix::Z().
{
         // One pair of indices gets contracted. Since
         // both matrices are symmetric, it doesnt matter which.
         //
         // O^{mu alpha} g_{alpha beta} M^{beta nu} = R^{mu nu}
         // O^{mu alpha} M_{beta}^{nu}
         LorentzMatrix R;
         R.X() = this->Contract(M.X());
         R.Y() = this->Contract(M.Y());
         R.Z() = this->Contract(M.Z());
         R.E() = this->Contract(M.E()); // signs?
         return R;
     }
Contract_2()
__device__ fptype GooFit::SymmLorentzMatrix::Contract_2 (const SymmLorentzMatrix & M) inline
Definition at line 321 of file SpinHelper.h.
References GooFit::LorentzMatrix::E(), GooFit::LorentzMatrix::X(), GooFit::LorentzMatrix::Y(), and GooFit::LorentzMatrix::Z().
{
         // Both pairs of indices are contracted.
         // since the matrices are symmetric, it does
         // not matter which index from this with which form M.
         //
         // O^{mu alpha} g_{alpha beta} M^{beta nu} g_{mu nu}
         LorentzMatrix R(Contract_1(M));
         // R^{mu nu} R_{mu nu}
         fptype xx = R.X().GetX(); // Dot(R.X());
         fptype yy = R.Y().GetY(); // Dot(R.Y());
         fptype zz = R.Z().GetZ(); // Dot(R.Z());
         fptype tt = R.E().GetE(); // Dot(R.E());
         return tt - xx - yy - zz; // signs?
     }
div()
__device__ SymmLorentzMatrix& GooFit::SymmLorentzMatrix::div (fptype s) inline
Definition at line 296 of file SpinHelper.h.
{
         for(auto &i : _v)
             i *= (1. / s);
         return *this;
     }
gmunu()
__device__ const SymmLorentzMatrix& GooFit::SymmLorentzMatrix::gmunu ()
makeGmunu()
__device__ void GooFit::SymmLorentzMatrix::makeGmunu () inline
Definition at line 243 of file SpinHelper.h.
{
         X().SetXYZE(-1, 0, 0, 0);
         Y().SetXYZE(0, -1, 0, 0);
         Z().SetXYZE(0, 0, -1, 0);
         E().SetXYZE(0, 0, 0, 1);
     }
makeZero()
__device__ bool GooFit::SymmLorentzMatrix::makeZero () inline protected
Definition at line 234 of file SpinHelper.h.
{
         X().SetXYZE(0, 0, 0, 0);
         Y().SetXYZE(0, 0, 0, 0);
         Z().SetXYZE(0, 0, 0, 0);
         E().SetXYZE(0, 0, 0, 0);
         return true;
     }
mult()
__device__ SymmLorentzMatrix& GooFit::SymmLorentzMatrix::mult (fptype s) inline
Definition at line 290 of file SpinHelper.h.
{
         for(auto &i : _v)
             i *= s;
         return *this;
     }
operator*()
__device__ SymmLorentzMatrix GooFit::SymmLorentzMatrix::operator* (fptype rhs) const inline
Definition at line 357 of file SpinHelper.h.
{
         SymmLorentzMatrix returnVal(*this);
         returnVal *= rhs;
         return returnVal;
     }
operator*=()
__device__ SymmLorentzMatrix& GooFit::SymmLorentzMatrix::operator*= (fptype rhs) inline
Definition at line 338 of file SpinHelper.h.
 { return mult(rhs); }
operator+()
__device__ SymmLorentzMatrix GooFit::SymmLorentzMatrix::operator+ (const SymmLorentzMatrix & rhs) const inline
Definition at line 347 of file SpinHelper.h.
{
         SymmLorentzMatrix returnVal(*this);
         returnVal += rhs;
         return returnVal;
     }
operator+=()
__device__ SymmLorentzMatrix& GooFit::SymmLorentzMatrix::operator+= (const SymmLorentzMatrix & rhs) inline
Definition at line 337 of file SpinHelper.h.
 { return add(rhs); }
operator-()
__device__ SymmLorentzMatrix GooFit::SymmLorentzMatrix::operator- (const SymmLorentzMatrix & rhs) const inline
Definition at line 352 of file SpinHelper.h.
{
         SymmLorentzMatrix returnVal(*this);
         returnVal -= rhs;
         return returnVal;
     }
operator-=()
__device__ SymmLorentzMatrix& GooFit::SymmLorentzMatrix::operator-= (const SymmLorentzMatrix & rhs) inline
Definition at line 339 of file SpinHelper.h.
 { return subtract(rhs); }
operator/()
__device__ SymmLorentzMatrix GooFit::SymmLorentzMatrix::operator/ (fptype rhs) const inline
Definition at line 362 of file SpinHelper.h.
{
         SymmLorentzMatrix returnVal(*this);
         returnVal /= rhs;
         return returnVal;
     }
operator/=()
__device__ SymmLorentzMatrix& GooFit::SymmLorentzMatrix::operator/= (fptype rhs) inline
Definition at line 340 of file SpinHelper.h.
 { return div(rhs); }
operator=()
__device__ SymmLorentzMatrix& GooFit::SymmLorentzMatrix::operator= (const SymmLorentzMatrix & other) inline
Definition at line 341 of file SpinHelper.h.
References GooFit::LorentzMatrix::_v.
{
         for(int i = 0; i < 4; i++)
             _v[i] = other._v[i];
         return *this;
     }
subtract()
__device__ SymmLorentzMatrix& GooFit::SymmLorentzMatrix::subtract (const SymmLorentzMatrix & other) inline
Definition at line 284 of file SpinHelper.h.
References GooFit::LorentzMatrix::_v.
{
         for(int i = 0; i < 4; i++)
             _v[i] -= other._v[i];
         return *this;
     }
symmetrize()
__device__ bool GooFit::SymmLorentzMatrix::symmetrize () inline protected
Definition at line 215 of file SpinHelper.h.
{
         // clumsy but save
         X().SetY(Y().GetX());
         X().SetZ(Z().GetX());
         X().SetE(E().GetX());
         Y().SetX(X().GetY());
         Y().SetZ(Z().GetY());
         Y().SetE(E().GetY());
         Z().SetX(X().GetZ());
         Z().SetY(Y().GetZ());
         Z().SetE(E().GetZ());
         E().SetX(X().GetE());
         E().SetY(Y().GetE());
         E().SetZ(Z().GetE());
         return true;
     }
The documentation for this class was generated from the following file:
/home/travis/build/GooFit/GooFit/include/goofit/PDFs/physics/SpinHelper.h