GooFit: GooFit::Constant Class Reference
GooFit::Constant Class Reference
#include <Variable.h>
Public Member Functions
Constant (const Constant &)=delete
Constant & operator= (const Constant &)=delete
Constant (Constant &&)=default
void operator= (const fptype &val)
Support var = 3.
Constant (std::string n, fptype val)
~Constant () override=default
Public Member Functions inherited from GooFit::Indexable
Indexable (std::string n, fptype val=0)
Indexable (const Indexable &)=delete
Indexable & operator= (const Indexable &)=delete
Indexable (Indexable &&)=default
virtual ~Indexable ()=default
int getIndex () const
Get the GooFit index.
void setIndex (int value)
Set the GooFit index.
int getFitterIndex () const
Get the index from the fitter.
void setFitterIndex (int value)
Set the index (should be done by the fitter)
const std::string & getName () const
Get the name.
void setName (const std::string &val)
Set the name.
fptype getValue () const
Get the value.
void setValue (fptype val)
Set the value.
fptype operator= (const fptype &val)
Support var = 3.
operator fptype () const
Support fptype val = var.
Additional Inherited Members
Protected Attributes inherited from GooFit::Indexable
std::string name
Support for less than, etc.
fptype value
The value of the variable.
int index {-1}
The goofit index, -1 if unset.
int fitter_index {-1}
The fitter index, -1 if unset.
Detailed Description
This is similar to Variable, but the index points to functorConstants instead of cudaArray.
Definition at line 215 of file Variable.h.
Constructor & Destructor Documentation
Constant() [1/3]
GooFit::Constant::Constant (const Constant &) delete
Constant() [2/3]
GooFit::Constant::Constant (Constant &&) default
Constant() [3/3]
GooFit::Constant::Constant (std::string n, fptype val) inline
Definition at line 225 of file Variable.h.
References GooFit::max_fitter_index(), GooFit::max_index(), GooFit::operator<<(), and GooFit::operator>>().
         : Indexable(n, val) {}
~Constant()
GooFit::Constant::~Constant () override default
Member Function Documentation
operator=() [1/2]
Constant& GooFit::Constant::operator= (const Constant &) delete
operator=() [2/2]
void GooFit::Constant::operator= (const fptype & val) inline
Support var = 3.
Definition at line 223 of file Variable.h.
References GooFit::Indexable::setValue().
 { setValue(val); }
The documentation for this class was generated from the following file:
/home/travis/build/GooFit/GooFit/include/goofit/Variable.h