GooFit: GooFit::UnbinnedDataSet Class Reference
GooFit::UnbinnedDataSet Class Reference
#include <UnbinnedDataSet.h>
Public Member Functions
UnbinnedDataSet (const Observable &var, std::string n="")
UnbinnedDataSet (const std::vector< Observable > &vars, std::string n="")
UnbinnedDataSet (const std::set< Observable > &vars, std::string n="")
UnbinnedDataSet (std::initializer_list< Observable > vars, std::string n="")
~UnbinnedDataSet () override=default
void addEvent () override
void fillWithGrid ()
Replace the current dataset with a grid.
fptype getValue (const Observable &var, size_t idx) const
Get the value at a specific variable and event number.
void loadEvent (size_t idx)
Set all the variables to the current event values.
void setValueForAllEvents (const Observable &var)
Set all entries to a constant value (note: this is kind of ugly)
template<typename M >
void from_matrix (const M &input, bool filter=false)
Input an eigen matrix.
template<typename M >
M to_matrix () const
Produce an eigen Matrix.
Public Member Functions inherited from GooFit::DataSet
DataSet (const Observable &var, std::string n="")
DataSet (const std::vector< Observable > &vars, std::string n="")
DataSet (const std::set< Observable > &vars, std::string n="")
DataSet (std::initializer_list< Observable > vars, std::string n="")
virtual ~DataSet ()=default
virtual void addWeightedEvent (fptype weight)
template<typename... Args>
void addEvent (fptype value, Args... args)
This is a helper that allows multiple values to be passed in instead of relying on the content of the Variables.
const std::vector< Observable > & getObservables () const
size_t numVariables () const
size_t getNumEvents () const
std::string getName () const
Additional Inherited Members
Protected Member Functions inherited from GooFit::DataSet
std::vector< fptype > getCurrentValues () const
size_t indexOfVariable (const Observable &var) const
void checkAllVars () const
Throw an error if any variables are out of range, call in addEvent.
Protected Attributes inherited from GooFit::DataSet
size_t numEventsAdded {0}
std::vector< Observable > observables
Detailed Description
Definition at line 13 of file UnbinnedDataSet.h.
Constructor & Destructor Documentation
UnbinnedDataSet() [1/4]
GooFit::UnbinnedDataSet::UnbinnedDataSet (const Observable & var, std::string n = "")
Definition at line 11 of file UnbinnedDataSet.cpp.
     : DataSet(var, n) {
     data.resize(1);
 }
UnbinnedDataSet() [2/4]
GooFit::UnbinnedDataSet::UnbinnedDataSet (const std::vector< Observable > & vars, std::string n = "")
Definition at line 16 of file UnbinnedDataSet.cpp.
     : DataSet(vars, n) {
     data.resize(vars.size());
 }
UnbinnedDataSet() [3/4]
GooFit::UnbinnedDataSet::UnbinnedDataSet (const std::set< Observable > & vars, std::string n = "")
Definition at line 21 of file UnbinnedDataSet.cpp.
     : DataSet(vars, n) {
     data.resize(vars.size());
 }
UnbinnedDataSet() [4/4]
GooFit::UnbinnedDataSet::UnbinnedDataSet (std::initializer_list< Observable > vars, std::string n = "")
Definition at line 26 of file UnbinnedDataSet.cpp.
     : DataSet(vars, n) {
     data.resize(vars.size());
 }
~UnbinnedDataSet()
GooFit::UnbinnedDataSet::~UnbinnedDataSet () override default
Member Function Documentation
addEvent()
void GooFit::UnbinnedDataSet::addEvent () override virtual
Implements GooFit::DataSet.
Definition at line 58 of file UnbinnedDataSet.cpp.
References GooFit::DataSet::checkAllVars(), GooFit::DataSet::numEventsAdded, and GooFit::DataSet::observables.
Referenced by GooFit::DalitzPlotter::DalitzPlotter(), GooFit::DalitzPlotter::fillDataSetMC(), from_matrix(), and GooFit::make_a_grid().
{
     checkAllVars();
     size_t i = 0;
     for(const Observable &v : observables)
         data.at(i++).push_back(v.getValue());
     numEventsAdded++;
 }
fillWithGrid()
void GooFit::UnbinnedDataSet::fillWithGrid ()
Replace the current dataset with a grid.
Definition at line 91 of file UnbinnedDataSet.cpp.
References GooFit::DataSet::getObservables(), and GooFit::make_a_grid().
{
     for(const auto &dat : data)
         if(!dat.empty())
             throw GeneralError("The dataset must be empty to fill with grid!");
     std::vector<Observable> ret = getObservables();
     Observable *evt_num = nullptr;
     for(Observable &val : ret)
         if(val.isEventNumber())
             evt_num = &val;
     make_a_grid(ret, this, evt_num);
 }
from_matrix()
template<typename M > void GooFit::UnbinnedDataSet::from_matrix (const M & input, bool filter = false) inline
Input an eigen matrix.
Definition at line 42 of file UnbinnedDataSet.h.
References addEvent(), GooFit::DataSet::getNumEvents(), and GooFit::DataSet::observables.
{
         size_t optional_index = getNumEvents(); // Only used if index not included
         if(observables.size() != input.rows() && observables.size() != input.rows() + 1)
             throw GeneralError(
                 "The wrong number of rows, expected {}, but matrix had {}", observables.size(), input.rows());
         for(int i = 0; i < input.cols(); i++) {     // Loop over events
             for(int j = 0; j < input.rows(); j++) { // Loop over variables
                 observables.at(j).setValue(input(j, i));
             }
             // Special override for counting variables (final param)
             if(observables.size() == input.rows() + 1)
                 observables.at(input.rows()).setValue(optional_index++);
             if(!filter
                || std::all_of(std::begin(observables), std::end(observables), [](Observable var) { return bool(var); }))
                 addEvent();
         }
     }
getValue()
fptype GooFit::UnbinnedDataSet::getValue (const Observable & var, size_t idx) const
Get the value at a specific variable and event number.
Definition at line 31 of file UnbinnedDataSet.cpp.
References GooFit::Indexable::getName(), GooFit::DataSet::getNumEvents(), and GooFit::DataSet::indexOfVariable().
Referenced by GooFit::DalitzPlotter::fillDataSetMC(), GooFit::DalitzPlotter::getXval(), and GooFit::DalitzPlotter::getYval().
{
     if(idx >= getNumEvents()) {
         throw GooFit::GeneralError("UnbinnedDataSet: Attepted to find {} in event {} when only {} events exits",
                                    var.getName(),
                                    idx,
                                    getNumEvents());
     }
     size_t var_idx = indexOfVariable(var);
     return data[var_idx].at(idx);
 }
loadEvent()
void GooFit::UnbinnedDataSet::loadEvent (size_t idx)
Set all the variables to the current event values.
Definition at line 44 of file UnbinnedDataSet.cpp.
References GooFit::DataSet::observables.
{
     size_t i = 0;
     for(Observable &v : observables) {
         v.setValue(data.at(i++).at(idx));
     }
 }
setValueForAllEvents()
void GooFit::UnbinnedDataSet::setValueForAllEvents (const Observable & var)
Set all entries to a constant value (note: this is kind of ugly)
Definition at line 51 of file UnbinnedDataSet.cpp.
References GooFit::DataSet::getNumEvents(), GooFit::Indexable::getValue(), and GooFit::DataSet::indexOfVariable().
{
     size_t ivar = indexOfVariable(var);
     for(size_t i = 0; i < getNumEvents(); i++) {
         data[ivar][i] = var.getValue();
     }
 }
to_matrix()
template<typename M > M GooFit::UnbinnedDataSet::to_matrix () const inline
Produce an eigen Matrix.
Definition at line 66 of file UnbinnedDataSet.h.
{
         size_t rows = data.size();
         size_t cols = data.at(0).size();
         M mat(rows, cols);
         for(int i = 0; i < rows; i++) {
             for(int j = 0; j < cols; j++)
                 mat(i, j) = data[i].at(j);
         }
         return mat;
     }
The documentation for this class was generated from the following files:
/home/travis/build/GooFit/GooFit/include/goofit/UnbinnedDataSet.h
/home/travis/build/GooFit/GooFit/src/goofit/UnbinnedDataSet.cpp