GooFit: GooFit::LorentzMatrix Class Reference
GooFit::LorentzMatrix Class Reference
#include <SpinHelper.h>
Public Member Functions
__device__ const gpuLVec & v (int i) const
__device__ LorentzMatrix ()=default
__device__ LorentzMatrix (const gpuLVec p[4])
__device__ LorentzMatrix (const LorentzMatrix &other)
__device__ const gpuLVec & X () const
__device__ const gpuLVec & Y () const
__device__ const gpuLVec & Z () const
__device__ const gpuLVec & E () const
__device__ gpuLVec & X ()
__device__ gpuLVec & Y ()
__device__ gpuLVec & Z ()
__device__ gpuLVec & E ()
__device__ const gpuLVec & operator[] (int i) const
__device__ gpuLVec & operator[] (int i)
__device__ LorentzMatrix & add (const LorentzMatrix &other)
__device__ LorentzMatrix & subtract (const LorentzMatrix &other)
__device__ LorentzMatrix & mult (fptype s)
__device__ LorentzMatrix & div (fptype s)
__device__ LorentzMatrix & operator+= (const LorentzMatrix &rhs)
__device__ LorentzMatrix & operator*= (fptype rhs)
__device__ LorentzMatrix & operator-= (const LorentzMatrix &rhs)
__device__ LorentzMatrix & operator/= (fptype rhs)
__device__ LorentzMatrix & operator= (const LorentzMatrix &other)
__device__ LorentzMatrix operator+ (const LorentzMatrix &rhs) const
__device__ LorentzMatrix operator- (const LorentzMatrix &rhs) const
__device__ LorentzMatrix operator* (fptype rhs) const
__device__ LorentzMatrix operator/ (fptype rhs) const
Protected Member Functions
__device__ bool makeZero ()
Protected Attributes
gpuLVec _v [4]
Detailed Description
Definition at line 115 of file SpinHelper.h.
Constructor & Destructor Documentation
LorentzMatrix() [1/3]
__device__ GooFit::LorentzMatrix::LorentzMatrix () default
LorentzMatrix() [2/3]
__device__ GooFit::LorentzMatrix::LorentzMatrix (const gpuLVec p[4]) inline
Definition at line 132 of file SpinHelper.h.
{
         for(int i = 0; i < 4; i++)
             _v[i] = p[i];
     }
LorentzMatrix() [3/3]
__device__ GooFit::LorentzMatrix::LorentzMatrix (const LorentzMatrix & other) inline
Definition at line 136 of file SpinHelper.h.
References _v.
{
         for(int i = 0; i < 4; i++)
             _v[i] = other._v[i];
     }
Member Function Documentation
add()
__device__ LorentzMatrix& GooFit::LorentzMatrix::add (const LorentzMatrix & other) inline
Definition at line 153 of file SpinHelper.h.
References _v.
{
         for(int i = 0; i < 4; i++)
             _v[i] += other._v[i];
         return *this;
     }
div()
__device__ LorentzMatrix& GooFit::LorentzMatrix::div (fptype s) inline
Definition at line 171 of file SpinHelper.h.
{
         for(auto &i : _v)
             i *= (1. / s);
         return *this;
     }
E() [1/2]
__device__ const gpuLVec& GooFit::LorentzMatrix::E () const inline
Definition at line 143 of file SpinHelper.h.
Referenced by GooFit::SymmLorentzMatrix::Contract_1(), and GooFit::SymmLorentzMatrix::Contract_2().
 { return _v[3]; }
E() [2/2]
__device__ gpuLVec& GooFit::LorentzMatrix::E () inline
Definition at line 148 of file SpinHelper.h.
 { return _v[3]; }
makeZero()
__device__ bool GooFit::LorentzMatrix::makeZero () inline protected
Definition at line 119 of file SpinHelper.h.
{
         X().SetXYZE(0, 0, 0, 0);
         Y().SetXYZE(0, 0, 0, 0);
         Z().SetXYZE(0, 0, 0, 0);
         E().SetXYZE(0, 0, 0, 0);
         return true;
     }
mult()
__device__ LorentzMatrix& GooFit::LorentzMatrix::mult (fptype s) inline
Definition at line 165 of file SpinHelper.h.
{
         for(auto &i : _v)
             i *= s;
         return *this;
     }
operator*()
__device__ LorentzMatrix GooFit::LorentzMatrix::operator* (fptype rhs) const inline
Definition at line 198 of file SpinHelper.h.
{
         LorentzMatrix returnVal(*this);
         returnVal *= rhs;
         return returnVal;
     }
operator*=()
__device__ LorentzMatrix& GooFit::LorentzMatrix::operator*= (fptype rhs) inline
Definition at line 179 of file SpinHelper.h.
 { return mult(rhs); }
operator+()
__device__ LorentzMatrix GooFit::LorentzMatrix::operator+ (const LorentzMatrix & rhs) const inline
Definition at line 188 of file SpinHelper.h.
{
         LorentzMatrix returnVal(*this);
         returnVal += rhs;
         return returnVal;
     }
operator+=()
__device__ LorentzMatrix& GooFit::LorentzMatrix::operator+= (const LorentzMatrix & rhs) inline
Definition at line 178 of file SpinHelper.h.
 { return add(rhs); }
operator-()
__device__ LorentzMatrix GooFit::LorentzMatrix::operator- (const LorentzMatrix & rhs) const inline
Definition at line 193 of file SpinHelper.h.
{
         LorentzMatrix returnVal(*this);
         returnVal -= rhs;
         return returnVal;
     }
operator-=()
__device__ LorentzMatrix& GooFit::LorentzMatrix::operator-= (const LorentzMatrix & rhs) inline
Definition at line 180 of file SpinHelper.h.
 { return subtract(rhs); }
operator/()
__device__ LorentzMatrix GooFit::LorentzMatrix::operator/ (fptype rhs) const inline
Definition at line 203 of file SpinHelper.h.
{
         LorentzMatrix returnVal(*this);
         returnVal /= rhs;
         return returnVal;
     }
operator/=()
__device__ LorentzMatrix& GooFit::LorentzMatrix::operator/= (fptype rhs) inline
Definition at line 181 of file SpinHelper.h.
 { return div(rhs); }
operator=()
__device__ LorentzMatrix& GooFit::LorentzMatrix::operator= (const LorentzMatrix & other) inline
Definition at line 182 of file SpinHelper.h.
References _v.
{
         for(int i = 0; i < 4; i++)
             _v[i] = other._v[i];
         return *this;
     }
operator[]() [1/2]
__device__ const gpuLVec& GooFit::LorentzMatrix::operator[] (int i) const inline
Definition at line 150 of file SpinHelper.h.
 { return _v[i]; }
operator[]() [2/2]
__device__ gpuLVec& GooFit::LorentzMatrix::operator[] (int i) inline
Definition at line 151 of file SpinHelper.h.
 { return _v[i]; }
subtract()
__device__ LorentzMatrix& GooFit::LorentzMatrix::subtract (const LorentzMatrix & other) inline
Definition at line 159 of file SpinHelper.h.
References _v.
{
         for(int i = 0; i < 4; i++)
             _v[i] -= other._v[i];
         return *this;
     }
v()
__device__ const gpuLVec& GooFit::LorentzMatrix::v (int i) const inline
Definition at line 128 of file SpinHelper.h.
Referenced by GooFit::ZTspin2::operator=().
 { return _v[i]; }
X() [1/2]
__device__ const gpuLVec& GooFit::LorentzMatrix::X () const inline
Definition at line 140 of file SpinHelper.h.
Referenced by GooFit::SymmLorentzMatrix::Contract_1(), and GooFit::SymmLorentzMatrix::Contract_2().
 { return _v[0]; }
X() [2/2]
__device__ gpuLVec& GooFit::LorentzMatrix::X () inline
Definition at line 145 of file SpinHelper.h.
 { return _v[0]; }
Y() [1/2]
__device__ const gpuLVec& GooFit::LorentzMatrix::Y () const inline
Definition at line 141 of file SpinHelper.h.
Referenced by GooFit::SymmLorentzMatrix::Contract_1(), and GooFit::SymmLorentzMatrix::Contract_2().
 { return _v[1]; }
Y() [2/2]
__device__ gpuLVec& GooFit::LorentzMatrix::Y () inline
Definition at line 146 of file SpinHelper.h.
 { return _v[1]; }
Z() [1/2]
__device__ const gpuLVec& GooFit::LorentzMatrix::Z () const inline
Definition at line 142 of file SpinHelper.h.
Referenced by GooFit::SymmLorentzMatrix::Contract_1(), and GooFit::SymmLorentzMatrix::Contract_2().
 { return _v[2]; }
Z() [2/2]
__device__ gpuLVec& GooFit::LorentzMatrix::Z () inline
Definition at line 147 of file SpinHelper.h.
 { return _v[2]; }
Member Data Documentation
_v
gpuLVec GooFit::LorentzMatrix::_v[4] protected
Definition at line 117 of file SpinHelper.h.
Referenced by add(), GooFit::SymmLorentzMatrix::add(), LorentzMatrix(), operator=(), GooFit::SymmLorentzMatrix::operator=(), subtract(), and GooFit::SymmLorentzMatrix::subtract().
The documentation for this class was generated from the following file:
/home/travis/build/GooFit/GooFit/include/goofit/PDFs/physics/SpinHelper.h