GooFit: GooFit::DalitzPlotter Class Reference
GooFit::DalitzPlotter Class Reference
This class makes it easy to make plots over 3 body Dalitz PDFs. You can use ROOT style value access or bin numbers.
#include <DalitzPlotter.h>
Public Member Functions
DalitzPlotter (GooPdf *overallSignal, DalitzPlotPdf *signalDalitz)
void fillDataSetMC (UnbinnedDataSet &dataset, size_t nTotal)
Fill a dataset with MC events.
size_t getNumEvents () const
size_t getX (size_t event) const
size_t getY (size_t event) const
fptype getXval (size_t event) const
fptype getYval (size_t event) const
fptype getZval (size_t event) const
fptype getVal (size_t event, size_t num=0) const
UnbinnedDataSet * getDataSet ()
const Observable & getM12 () const
const Observable & getM13 () const
Detailed Description
This class makes it easy to make plots over 3 body Dalitz PDFs. You can use ROOT style value access or bin numbers.
Definition at line 19 of file DalitzPlotter.h.
Constructor & Destructor Documentation
DalitzPlotter()
GooFit::DalitzPlotter::DalitzPlotter (GooPdf * overallSignal, DalitzPlotPdf * signalDalitz) inline
Definition at line 30 of file DalitzPlotter.h.
References GooFit::UnbinnedDataSet::addEvent(), GooFit::Observable::getBinSize(), GooFit::Indexable::getLowerLimit(), GooFit::Observable::getNumBins(), GooFit::DataSet::getNumEvents(), GooFit::Indexable::getValue(), GooFit::inDalitz(), and GooFit::Indexable::setValue().
         : m12(signalDalitz->_m12)
         , m13(signalDalitz->_m13)
         , eventNumber(signalDalitz->_eventNumber)
         , data({m12, m13, eventNumber})
         , mother(signalDalitz->decayInfo.motherMass) {
         eventNumber.setValue(0);
         for(size_t i = 0; i < m12.getNumBins(); ++i) {
             m12.setValue(m12.getLowerLimit() + m12.getBinSize() * (i + 0.5));
             for(size_t j = 0; j < m13.getNumBins(); ++j) {
                 m13.setValue(m13.getLowerLimit() + m13.getBinSize() * (j + 0.5));
                 if(inDalitz(m12.getValue(),
                             m13.getValue(),
                             signalDalitz->decayInfo.motherMass,
                             signalDalitz->decayInfo.daug1Mass,
                             signalDalitz->decayInfo.daug2Mass,
                             signalDalitz->decayInfo.daug3Mass)) {
                     xbins.push_back(i);
                     ybins.push_back(j);
                     data.addEvent();
                     eventNumber.setValue(eventNumber.getValue() + 1);
                 }
             }
         }
         auto old = overallSignal->getData();
         overallSignal->setData(&data);
         signalDalitz->setDataSize(data.getNumEvents());
         pdfValues = overallSignal->getCompProbsAtDataPoints();
         overallSignal->setData(old);
     }
Member Function Documentation
fillDataSetMC()
void GooFit::DalitzPlotter::fillDataSetMC (UnbinnedDataSet & dataset, size_t nTotal) inline
Fill a dataset with MC events.
Definition at line 64 of file DalitzPlotter.h.
References GooFit::UnbinnedDataSet::addEvent(), GooFit::Observable::getBinSize(), GooFit::UnbinnedDataSet::getValue(), and GooFit::Indexable::setValue().
{
         // Setup random numbers
         std::random_device rd;
         std::mt19937 gen(rd());
         // Uniform distribution
         std::uniform_real_distribution<> unihalf(-.5, .5);
         std::uniform_real_distribution<> uniwhole(0.0, 1.0);
         // CumSum in other languages
         std::vector<double> integral(pdfValues[0].size());
         std::partial_sum(pdfValues[0].begin(), pdfValues[0].end(), integral.begin());
         // Make this a 0-1 fraction by dividing by the end value
         std::for_each(integral.begin(), integral.end(), [&integral](double &val) { val /= integral.back(); });
         for(size_t i = 0; i < nTotal; i++) {
             double r = uniwhole(gen);
             // Binary search for integral[cell-1] < r < integral[cell]
             size_t j = std::lower_bound(integral.begin(), integral.end(), r) - integral.begin();
             // Fill in the grid square randomly
             double currm12 = data.getValue(m12, j) + m12.getBinSize() * unihalf(gen);
             double currm13 = data.getValue(m13, j) + m13.getBinSize() * unihalf(gen);
             m12.setValue(currm12);
             m13.setValue(currm13);
             eventNumber.setValue(i);
             dataset.addEvent();
         }
     }
getDataSet()
UnbinnedDataSet* GooFit::DalitzPlotter::getDataSet () inline
Definition at line 111 of file DalitzPlotter.h.
 { return &data; }
getM12()
const Observable& GooFit::DalitzPlotter::getM12 () const inline
Definition at line 113 of file DalitzPlotter.h.
 { return m12; }
getM13()
const Observable& GooFit::DalitzPlotter::getM13 () const inline
Definition at line 114 of file DalitzPlotter.h.
References GooFit::Indexable::getLowerLimit(), GooFit::Observable::getNumBins(), getNumEvents(), GooFit::Indexable::getUpperLimit(), getVal(), getX(), and getY().
 { return m13; }
getNumEvents()
size_t GooFit::DalitzPlotter::getNumEvents () const inline
Definition at line 97 of file DalitzPlotter.h.
References GooFit::DataSet::getNumEvents().
Referenced by getM13().
 { return data.getNumEvents(); }
getVal()
fptype GooFit::DalitzPlotter::getVal (size_t event, size_t num = 0) const inline
Definition at line 109 of file DalitzPlotter.h.
Referenced by getM13().
 { return pdfValues.at(num).at(event); }
getX()
size_t GooFit::DalitzPlotter::getX (size_t event) const inline
Definition at line 99 of file DalitzPlotter.h.
Referenced by getM13().
 { return xbins.at(event); }
getXval()
fptype GooFit::DalitzPlotter::getXval (size_t event) const inline
Definition at line 103 of file DalitzPlotter.h.
References GooFit::UnbinnedDataSet::getValue().
Referenced by getZval().
 { return data.getValue(m12, event); }
getY()
size_t GooFit::DalitzPlotter::getY (size_t event) const inline
Definition at line 101 of file DalitzPlotter.h.
Referenced by getM13().
 { return ybins.at(event); }
getYval()
fptype GooFit::DalitzPlotter::getYval (size_t event) const inline
Definition at line 105 of file DalitzPlotter.h.
References GooFit::UnbinnedDataSet::getValue().
Referenced by getZval().
 { return data.getValue(m13, event); }
getZval()
fptype GooFit::DalitzPlotter::getZval (size_t event) const inline
Definition at line 107 of file DalitzPlotter.h.
References getXval(), getYval(), and POW2.
 { return POW2(mother) - POW2(getXval(event)) - POW2(getYval(event)); }
The documentation for this class was generated from the following file:
/home/travis/build/GooFit/GooFit/include/goofit/PDFs/physics/DalitzPlotter.h