GooFit: UnbinnedDataSet Class Reference
UnbinnedDataSet Class Reference
#include <UnbinnedDataSet.h>
Public Member Functions
UnbinnedDataSet (Variable *var, string n="")
UnbinnedDataSet (std::vector< Variable *> &vars, string n="")
UnbinnedDataSet (std::set< Variable *> &vars, string n="")
virtual ~UnbinnedDataSet ()
virtual void addEventVector (std::vector< fptype > &vals, fptype weight=1)
int getNumEvents () const
fptype getValue (Variable *var, int idx) const
void loadEvent (int idx)
void setValueForAllEvents (Variable *var)
Public Member Functions inherited from DataSet
DataSet (Variable *var, string n="")
DataSet (std::vector< Variable *> &vars, string n="")
DataSet (std::set< Variable *> &vars, string n="")
~DataSet ()
void addEvent ()
void addEvent (fptype val)
void addWeightedEvent (fptype weight)
varConstIt varsBegin () const
varConstIt varsEnd () const
void getVariables (std::vector< Variable *> &vars)
varConstRIt varsRBegin () const
varConstRIt varsREnd () const
int numVariables () const
int numEvents () const
string getName () const
Additional Inherited Members
Protected Member Functions inherited from DataSet
vector< fptype > getCurrentValues () const
unsigned int indexOfVariable (Variable *var) const
Protected Attributes inherited from DataSet
int numEventsAdded
Detailed Description
Definition at line 6 of file UnbinnedDataSet.h.
Constructor & Destructor Documentation
UnbinnedDataSet() [1/3]
UnbinnedDataSet::UnbinnedDataSet (Variable * var, string n = "")
Definition at line 4 of file UnbinnedDataSet.cc.
     : DataSet(var, n)
 {}
UnbinnedDataSet() [2/3]
UnbinnedDataSet::UnbinnedDataSet (std::vector< Variable *> & vars, string n = "")
Definition at line 8 of file UnbinnedDataSet.cc.
     : DataSet(vars, n)
 {}
UnbinnedDataSet() [3/3]
UnbinnedDataSet::UnbinnedDataSet (std::set< Variable *> & vars, string n = "")
Definition at line 12 of file UnbinnedDataSet.cc.
     : DataSet(vars, n)
 {}
~UnbinnedDataSet()
UnbinnedDataSet::~UnbinnedDataSet () virtual
Definition at line 16 of file UnbinnedDataSet.cc.
 {}
Member Function Documentation
addEventVector()
void UnbinnedDataSet::addEventVector (std::vector< fptype > & vals, fptype weight = 1) virtual
Implements DataSet.
Definition at line 61 of file UnbinnedDataSet.cc.
References DataSet::numEventsAdded, DataSet::varsBegin(), and DataSet::varsEnd().
{
     // NB, unbinned data set ignores weights.
     numEventsAdded++;
     varConstIt currVar = varsBegin();
     std::map<Variable*, fptype> currEvent;
     for(unsigned int i = 0; i < vals.size(); ++i) {
         assert(currVar != varsEnd());
         double currVal = vals[i];
         if(currVal < (*currVar)->lowerlimit) {
             std::cout << "Warning: Value "
                       << currVal
                       << " less than minimum "
                       << (*currVar)->lowerlimit
                       << " for "
                       << (*currVar)->name
                       << "; clamping to minimum.\n";
             currVal = (*currVar)->lowerlimit;
         }
         if(currVal > (*currVar)->upperlimit) {
             std::cout << "Warning: Value "
                       << currVal
                       << " more than maximum "
                       << (*currVar)->upperlimit
                       << " for "
                       << (*currVar)->name
                       << "; clamping to maximum.\n";
             currVal = (*currVar)->upperlimit;
         }
         currEvent[*currVar] = currVal;
         ++currVar;
     }
     assert(currVar == varsEnd());
     data.push_back(currEvent);
 }
getNumEvents()
int UnbinnedDataSet::getNumEvents () const inline
Definition at line 16 of file UnbinnedDataSet.h.
References getValue(), loadEvent(), and setValueForAllEvents().
Referenced by getValue(), and loadEvent().
{
         return data.size();
     }
getValue()
fptype UnbinnedDataSet::getValue (Variable * var, int idx) const
Definition at line 18 of file UnbinnedDataSet.cc.
References DataSet::getName(), getNumEvents(), and Indexable::name.
Referenced by getNumEvents().
{
     if(idx >= getNumEvents()) {
         std::cout << "UnbinnedDataSet error: Attempt to find "
                   << var->name
                   << " in event "
                   << idx
                   << " when only "
                   << getNumEvents()
                   << " events exist.\n";
         return -1;
     }
     if(0 > idx) {
         std::cout << "UnbinnedDataSet error: Cannot return value of "
                   << var->name
                   << " for index "
                   << idx
                   << std::endl;
         return -1;
     }
     std::map<Variable*, fptype>::const_iterator event = data[idx].find(var);
     if(event == data[idx].end()) {
         static map<string, bool> printed;
         if(!printed[var->name]) {
             std::cout << "UnbinnedDataSet error: Could not find variable "
                       << var->name
                       << " in event "
                       << idx
                       << " of data set "
                       << getName()
                       << ". Returning -1. This message will only be printed once.\n";
             printed[var->name] = true;
         }
         return -1;
     }
     return (*event).second;
 }
loadEvent()
void UnbinnedDataSet::loadEvent (int idx)
Definition at line 102 of file UnbinnedDataSet.cc.
References getNumEvents().
Referenced by getNumEvents().
{
     if(idx >= getNumEvents()) {
         std::cout << "UnbinnedDataSet error: Attempt to load event "
                   << idx
                   << " when only "
                   << getNumEvents()
                   << " events exist.\n";
         return;
     }
     if(0 > idx) {
         std::cout << "UnbinnedDataSet error: Cannot load event "
                   << idx
                   << std::endl;
         return;
     }
     for(std::map<Variable*, fptype>::iterator v = data[idx].begin(); v != data[idx].end(); ++v) {
         (*v).first->value = (*v).second;
     }
 }
setValueForAllEvents()
void UnbinnedDataSet::setValueForAllEvents (Variable * var)
Definition at line 124 of file UnbinnedDataSet.cc.
References Indexable::value.
Referenced by getNumEvents().
{
     for(std::vector<std::map<Variable*, fptype>>::iterator i = data.begin(); i != data.end(); ++i) {
         (*i)[var] = var->value;
     }
 }
The documentation for this class was generated from the following files:
/home/travis/build/GooFit/GooFit/include/goofit/UnbinnedDataSet.h
/home/travis/build/GooFit/GooFit/src/goofit/UnbinnedDataSet.cc