GooFit: DataSet Class Reference
DataSet Class Reference abstract
#include <DataSet.h>
Public Member Functions
DataSet (Variable *var, string n="")
DataSet (std::vector< Variable *> &vars, string n="")
DataSet (std::set< Variable *> &vars, string n="")
~DataSet ()
void addEvent ()
void addEvent (fptype val)
virtual void addEventVector (std::vector< fptype > &vals, fptype weight=1)=0
void addWeightedEvent (fptype weight)
varConstIt varsBegin () const
varConstIt varsEnd () const
void getVariables (std::vector< Variable *> &vars)
varConstRIt varsRBegin () const
varConstRIt varsREnd () const
int numVariables () const
int numEvents () const
string getName () const
Protected Member Functions
vector< fptype > getCurrentValues () const
unsigned int indexOfVariable (Variable *var) const
Protected Attributes
int numEventsAdded
Detailed Description
Definition at line 13 of file DataSet.h.
Constructor & Destructor Documentation
DataSet() [1/3]
DataSet::DataSet (Variable * var, string n = "")
Definition at line 5 of file DataSet.cc.
     : numEventsAdded(0)
     , name(n) {
     variables.push_back(var);
     if(n == "")
         generateName();
 }
DataSet() [2/3]
DataSet::DataSet (std::vector< Variable *> & vars, string n = "")
Definition at line 14 of file DataSet.cc.
     : numEventsAdded(0)
     , name(n) {
     for(std::vector<Variable*>::iterator v = vars.begin(); v != vars.end(); ++v) {
         variables.push_back(*v);
     }
     if(n == "")
         generateName();
 }
DataSet() [3/3]
DataSet::DataSet (std::set< Variable *> & vars, string n = "")
Definition at line 25 of file DataSet.cc.
     : numEventsAdded(0)
     , name(n) {
     variables.resize(vars.size());
     for(std::set<Variable*>::iterator v = vars.begin(); v != vars.end(); ++v) {
         variables[(*v)->index] = (*v);
     }
     if(n == "")
         generateName();
 }
~DataSet()
DataSet::~DataSet ()
Definition at line 38 of file DataSet.cc.
                   {
     variables.clear();
 }
Member Function Documentation
addEvent() [1/2]
void DataSet::addEvent ()
Definition at line 42 of file DataSet.cc.
References addEventVector(), and getCurrentValues().
{
     vector<fptype> vals = getCurrentValues();
     addEventVector(vals);
 }
addEvent() [2/2]
void DataSet::addEvent (fptype val)
Definition at line 52 of file DataSet.cc.
References addEventVector().
{
     // Helper method to avoid the user having to wrap
     // every one-dimensional event in a vector.
     assert(1 == variables.size());
     std::vector<fptype> helper;
     helper.push_back(val);
     addEventVector(helper);
 }
addEventVector()
virtual void DataSet::addEventVector (std::vector< fptype > & vals, fptype weight = 1) pure virtual
Implemented in BinnedDataSet, and UnbinnedDataSet.
Referenced by addEvent(), and addWeightedEvent().
addWeightedEvent()
void DataSet::addWeightedEvent (fptype weight)
Definition at line 47 of file DataSet.cc.
References addEventVector(), and getCurrentValues().
{
     vector<fptype> vals = getCurrentValues();
     addEventVector(vals, weight);
 }
getCurrentValues()
vector< fptype > DataSet::getCurrentValues () const protected
Definition at line 62 of file DataSet.cc.
References varsBegin(), and varsEnd().
Referenced by addEvent(), addWeightedEvent(), BinnedDataSet::getBinNumber(), and getName().
{
     vector<fptype> values;
     for(varConstIt v = varsBegin(); v != varsEnd(); ++v) {
         values.push_back((*v)->value);
     }
     return values;
 }
getName()
string DataSet::getName () const inline
Definition at line 46 of file DataSet.h.
References getCurrentValues(), and indexOfVariable().
Referenced by UnbinnedDataSet::getValue().
{
         return name;
     }
getVariables()
void DataSet::getVariables (std::vector< Variable *> & vars)
Definition at line 72 of file DataSet.cc.
Referenced by varsEnd().
{
     for(std::vector<Variable*>::iterator v = variables.begin(); v != variables.end(); ++v) {
         vars.push_back(*v);
     }
 }
indexOfVariable()
unsigned int DataSet::indexOfVariable (Variable * var) const protected
Definition at line 78 of file DataSet.cc.
References Indexable::name, varsBegin(), and varsEnd().
Referenced by BinnedDataSet::getBinCenter(), BinnedDataSet::getBinNumber(), and getName().
{
     for(unsigned int i = 0; i < variables.size(); ++i) {
         if(var != variables[i])
             continue;
         return i;
     }
     std::cout << "Error: Attempted to get index of variable "
               << var->name
               << " in DataSet of ";
     for(varConstIt v = varsBegin(); v != varsEnd(); ++v) {
         std::cout << "\n  " << (*v)->name << std::endl;
     }
     std::cout << "\nAborting." << std::endl;
     assert(false);
     abort();
     return 0;
 }
numEvents()
int DataSet::numEvents () const inline
Definition at line 42 of file DataSet.h.
References numEventsAdded.
{
         return numEventsAdded;
     }
numVariables()
int DataSet::numVariables () const inline
Definition at line 39 of file DataSet.h.
{
         return variables.size();
     }
varsBegin()
varConstIt DataSet::varsBegin () const inline
Definition at line 25 of file DataSet.h.
Referenced by BinnedDataSet::addEventVector(), UnbinnedDataSet::addEventVector(), BinnedDataSet::getBinNumber(), BinnedDataSet::getBinVolume(), getCurrentValues(), BinnedDataSet::getNumBins(), BinnedDataSet::getNumEvents(), and indexOfVariable().
{
         return variables.begin();
     }
varsEnd()
varConstIt DataSet::varsEnd () const inline
Definition at line 28 of file DataSet.h.
References getVariables().
Referenced by BinnedDataSet::addEventVector(), UnbinnedDataSet::addEventVector(), BinnedDataSet::getBinNumber(), BinnedDataSet::getBinVolume(), getCurrentValues(), BinnedDataSet::getNumBins(), BinnedDataSet::getNumEvents(), and indexOfVariable().
{
         return variables.end();
     }
varsRBegin()
varConstRIt DataSet::varsRBegin () const inline
Definition at line 33 of file DataSet.h.
{
         return variables.rbegin();
     }
varsREnd()
varConstRIt DataSet::varsREnd () const inline
Definition at line 36 of file DataSet.h.
{
         return variables.rend();
     }
Member Data Documentation
numEventsAdded
int DataSet::numEventsAdded protected
Definition at line 53 of file DataSet.h.
Referenced by BinnedDataSet::addEventVector(), UnbinnedDataSet::addEventVector(), and numEvents().
The documentation for this class was generated from the following files:
/home/travis/build/GooFit/GooFit/include/goofit/DataSet.h
/home/travis/build/GooFit/GooFit/src/goofit/DataSet.cc