GooFit: GooFit::FitManagerMinuit2 Class Reference
GooFit::FitManagerMinuit2 Class Reference
#include <FitManagerMinuit2.h>
Public Member Functions
FitManagerMinuit2 (PdfBase *dat)
virtual double Up () const
double operator() (const std::vector< double > &pars) const
ROOT::Minuit2::FunctionMinimum * fit ()
void getMinuitValues () const
Protected Attributes
PdfBase * pdfPointer
ROOT::Minuit2::MnUserParameters * params
ROOT::Minuit2::MnMigrad * migrad
std::vector< Variable * > vars
int numPars
Detailed Description
Definition at line 16 of file FitManagerMinuit2.h.
Constructor & Destructor Documentation
FitManagerMinuit2()
GooFit::FitManagerMinuit2::FitManagerMinuit2 (PdfBase * dat) inline
Definition at line 19 of file FitManagerMinuit2.h.
References pdfPointer.
{
         pdfPointer = dat;
     }
Member Function Documentation
fit()
ROOT::Minuit2::FunctionMinimum * GooFit::FitManagerMinuit2::fit ()
Definition at line 15 of file FitManagerMinuit2.cc.
References PdfBase::getParameters(), host_callnumber, migrad, numPars, params, pdfPointer, and vars.
Referenced by Up().
{
     host_callnumber = 0;
     params = new ROOT::Minuit2::MnUserParameters();
     vars.clear();
     pdfPointer->getParameters(vars);
     numPars = vars.size();
     int maxIndex = 0;
     for(std::vector<Variable*>::iterator i = vars.begin(); i != vars.end(); ++i) {
         if((*i)->lowerlimit == (*i)->upperlimit)
             params->Add((*i)->name, (*i)->value, (*i)->error);
         else
             params->Add((*i)->name, (*i)->value, (*i)->error, (*i)->lowerlimit, (*i)->upperlimit);
         if((*i)->fixed)
             params->Fix(params->Index((*i)->name));
         if(maxIndex < (*i)->getIndex())
             maxIndex = (*i)->getIndex();
     }
     numPars = maxIndex+1;
     migrad = new ROOT::Minuit2::MnMigrad(*this, *params);
     ROOT::Minuit2::FunctionMinimum* ret = new ROOT::Minuit2::FunctionMinimum((*migrad)());
     return ret;
 }
getMinuitValues()
void GooFit::FitManagerMinuit2::getMinuitValues () const
Referenced by Up().
operator()()
double GooFit::FitManagerMinuit2::operator() (const std::vector< double > & pars) const
Definition at line 44 of file FitManagerMinuit2.cc.
References PdfBase::calculateNLL(), PdfBase::copyParams(), PdfBase::getParameters(), host_callnumber, migrad, numPars, pdfPointer, and vars.
Referenced by Up().
{
     vector<double> gooPars; // Translates from Minuit indexing to GooFit indexing
     gooPars.resize(numPars);
     int counter = 0;
     for(std::vector<Variable*>::iterator i = vars.begin(); i != vars.end(); ++i) {
         gooPars[(*i)->index] = pars[counter++];
     }
     pdfPointer->copyParams(gooPars);
     double nll = pdfPointer->calculateNLL();
     host_callnumber++;
 #ifdef PRINTCALLS
     double edm = migrad->State().Edm();
     cout.precision(8);
     cout << "State at call "
          << host_callnumber << " : "
          << nll << " "
          << edm << " Pars: ";
     std::vector<Variable*> vars;
     pdfPointer->getParameters(vars);
     for(std::vector<Variable*>::iterator i = vars.begin(); i != vars.end(); ++i) {
         if(0 > (*i)->getIndex())
             continue;
         if((*i)->fixed)
             continue;
         cout << "(" << (*i)->name << " " << pars[(*i)->getIndex()] << ") "; // migrad->Value((*i)->getIndex()) << ") ";
     }
     cout << endl;
 #endif
     return nll;
 }
Up()
virtual double GooFit::FitManagerMinuit2::Up () const inline virtual
Definition at line 22 of file FitManagerMinuit2.h.
References fit(), getMinuitValues(), and operator()().
{
         return 1.0;
     }
Member Data Documentation
migrad
ROOT::Minuit2::MnMigrad* GooFit::FitManagerMinuit2::migrad protected
Definition at line 32 of file FitManagerMinuit2.h.
Referenced by fit(), and operator()().
numPars
int GooFit::FitManagerMinuit2::numPars protected
Definition at line 35 of file FitManagerMinuit2.h.
Referenced by fit(), and operator()().
params
ROOT::Minuit2::MnUserParameters* GooFit::FitManagerMinuit2::params protected
Definition at line 31 of file FitManagerMinuit2.h.
Referenced by fit().
pdfPointer
PdfBase* GooFit::FitManagerMinuit2::pdfPointer protected
Definition at line 30 of file FitManagerMinuit2.h.
Referenced by fit(), FitManagerMinuit2(), and operator()().
vars
std::vector<Variable*> GooFit::FitManagerMinuit2::vars protected
Definition at line 34 of file FitManagerMinuit2.h.
Referenced by fit(), and operator()().
The documentation for this class was generated from the following files:
/home/travis/build/GooFit/GooFit/include/goofit/FitManagerMinuit2.h
/home/travis/build/GooFit/GooFit/src/goofit/FitManagerMinuit2.cc