GooFit: cuPrintf.cu File Reference
cuPrintf.cu File Reference
#include "cuPrintf.cuh"
#include <stdio.h>
Macros
#define CUPRINTF_CU
#define CUPRINTF_SM10_MAGIC 0xC810
#define CUPRINTF_ALIGN_SIZE sizeof(long long)
#define CUPRINTF_SM11_MAGIC (unsigned short)0xC811
#define CUPRINTF_PREAMBLE
#define CUPRINTF_ARG(argname) bufptr = copyArg(bufptr, argname, end);
#define CUPRINTF_POSTAMBLE
Functions
struct __align__ (8)
struct __align__ (16)
__device__ int cuPrintf (const char *fmt)
template<typename T1 >
__device__ int cuPrintf (const char *fmt, T1 arg1)
template<typename T1 , typename T2 >
__device__ int cuPrintf (const char *fmt, T1 arg1, T2 arg2)
template<typename T1 , typename T2 , typename T3 >
__device__ int cuPrintf (const char *fmt, T1 arg1, T2 arg2, T3 arg3)
template<typename T1 , typename T2 , typename T3 , typename T4 >
__device__ int cuPrintf (const char *fmt, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
__device__ int cuPrintf (const char *fmt, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
__device__ int cuPrintf (const char *fmt, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 >
__device__ int cuPrintf (const char *fmt, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 >
__device__ int cuPrintf (const char *fmt, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 >
__device__ int cuPrintf (const char *fmt, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 >
__device__ int cuPrintf (const char *fmt, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10)
__device__ void cuPrintfRestrict (int threadid, int blockid)
cudaError_t cudaPrintfInit (size_t bufferLen)
void cudaPrintfEnd ()
cudaError_t cudaPrintfDisplay (void *outputFP, bool showThreadID)
Variables
cuPrintfRestriction
cuPrintfHeader
cuPrintfHeaderSM10
Macro Definition Documentation
#define CUPRINTF_ALIGN_SIZE sizeof(long long)
Definition at line 107 of file cuPrintf.cu.
#define CUPRINTF_ARG (argname) bufptr = copyArg(bufptr, argname, end);
Definition at line 343 of file cuPrintf.cu.
Referenced by cuPrintf().
#define CUPRINTF_CU
Definition at line 53 of file cuPrintf.cu.
#define CUPRINTF_POSTAMBLE
Value:
fmtstart = bufptr; \
    end = cuPrintfStrncpy(bufptr, fmt, CUPRINTF_MAX_LEN, end); \
    writePrintfHeader(start, end ? fmtstart : NULL); \
    return end ? (int)(end - start) : 0;
Definition at line 347 of file cuPrintf.cu.
Referenced by cuPrintf().
#define CUPRINTF_PREAMBLE
Value:
char *start, *end, *bufptr, *fmtstart; \
    if((start = getNextPrintfBufPtr()) == NULL) return 0; \
    end = start + CUPRINTF_MAX_LEN; \
    bufptr = start + sizeof(cuPrintfHeader);
Definition at line 336 of file cuPrintf.cu.
Referenced by cuPrintf().
#define CUPRINTF_SM10_MAGIC 0xC810
Definition at line 93 of file cuPrintf.cu.
Referenced by cudaPrintfDisplay().
#define CUPRINTF_SM11_MAGIC (unsigned short)0xC811
Definition at line 110 of file cuPrintf.cu.
Referenced by cudaPrintfDisplay().
Function Documentation
struct __align__ (8) read
Definition at line 65 of file cuPrintf.cu.
struct __align__ (16) read
Definition at line 94 of file cuPrintf.cu.
cudaError_t cudaPrintfDisplay (void * outputFP, bool showThreadID)
Definition at line 747 of file cuPrintf.cu.
References CUPRINTF_SM10_MAGIC, CUPRINTF_SM11_MAGIC, and cuPrintfHeaderSM10.
Referenced by abortWithCudaPrintFlush().
void cudaPrintfEnd ()
Definition at line 721 of file cuPrintf.cu.
Referenced by abortWithCudaPrintFlush().
cudaError_t cudaPrintfInit (size_t bufferLen)
Definition at line 688 of file cuPrintf.cu.
References cuPrintfRestriction.
__device__ int cuPrintf (const char * fmt)
Definition at line 353 of file cuPrintf.cu.
References CUPRINTF_POSTAMBLE, and CUPRINTF_PREAMBLE.
Referenced by device_Faddeeva_2(), and device_Voigtian().
template<typename T1 > __device__ int cuPrintf (const char * fmt, T1 arg1)
Definition at line 359 of file cuPrintf.cu.
References CUPRINTF_ARG, CUPRINTF_POSTAMBLE, and CUPRINTF_PREAMBLE.
template<typename T1 , typename T2 > __device__ int cuPrintf (const char * fmt, T1 arg1, T2 arg2)
Definition at line 367 of file cuPrintf.cu.
References CUPRINTF_ARG, CUPRINTF_POSTAMBLE, and CUPRINTF_PREAMBLE.
template<typename T1 , typename T2 , typename T3 > __device__ int cuPrintf (const char * fmt, T1 arg1, T2 arg2, T3 arg3)
Definition at line 376 of file cuPrintf.cu.
References CUPRINTF_ARG, CUPRINTF_POSTAMBLE, and CUPRINTF_PREAMBLE.
template<typename T1 , typename T2 , typename T3 , typename T4 > __device__ int cuPrintf (const char * fmt, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
Definition at line 386 of file cuPrintf.cu.
References CUPRINTF_ARG, CUPRINTF_POSTAMBLE, and CUPRINTF_PREAMBLE.
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > __device__ int cuPrintf (const char * fmt, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
Definition at line 397 of file cuPrintf.cu.
References CUPRINTF_ARG, CUPRINTF_POSTAMBLE, and CUPRINTF_PREAMBLE.
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > __device__ int cuPrintf (const char * fmt, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
Definition at line 409 of file cuPrintf.cu.
References CUPRINTF_ARG, CUPRINTF_POSTAMBLE, and CUPRINTF_PREAMBLE.
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 > __device__ int cuPrintf (const char * fmt, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
Definition at line 421 of file cuPrintf.cu.
References CUPRINTF_ARG, CUPRINTF_POSTAMBLE, and CUPRINTF_PREAMBLE.
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 > __device__ int cuPrintf (const char * fmt, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
Definition at line 435 of file cuPrintf.cu.
References CUPRINTF_ARG, CUPRINTF_POSTAMBLE, and CUPRINTF_PREAMBLE.
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > __device__ int cuPrintf (const char * fmt, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9)
Definition at line 450 of file cuPrintf.cu.
References CUPRINTF_ARG, CUPRINTF_POSTAMBLE, and CUPRINTF_PREAMBLE.
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 > __device__ int cuPrintf (const char * fmt, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10)
Definition at line 466 of file cuPrintf.cu.
References CUPRINTF_ARG, CUPRINTF_POSTAMBLE, and CUPRINTF_PREAMBLE.
__device__ void cuPrintfRestrict (int threadid, int blockid)
Definition at line 498 of file cuPrintf.cu.
Variable Documentation
cuPrintfHeader
Definition at line 90 of file cuPrintf.cu.
cuPrintfHeaderSM10
Definition at line 100 of file cuPrintf.cu.
Referenced by cudaPrintfDisplay().
cuPrintfRestriction
Definition at line 68 of file cuPrintf.cu.
Referenced by cudaPrintfInit().