GooFit: FPOINTER/devcomplex.hh File Reference
devcomplex.hh File Reference
Classes
struct devcomplex< T >
Functions
template<typename T >
__device__ devcomplex< T > operator+ (const devcomplex< T > &one, const devcomplex< T > &other)
template<typename T >
__device__ devcomplex< T > operator- (const devcomplex< T > &one, const devcomplex< T > &other)
template<typename T >
__device__ devcomplex< T > operator+ (const devcomplex< T > &one, T other)
template<typename T >
__device__ devcomplex< T > operator/ (const devcomplex< T > &one, const devcomplex< T > &other)
template<typename T >
__device__ devcomplex< T > operator* (const devcomplex< T > &one, const devcomplex< T > &other)
template<typename T >
__device__ devcomplex< T > operator* (const devcomplex< T > &one, const int &other)
template<typename T >
__device__ devcomplex< T > operator/ (const T &a, const devcomplex< T > &b)
template<typename T >
__device__ devcomplex< T > operator* (T a, const devcomplex< T > &b)
template<typename T >
__device__ T norm (const devcomplex< T > &z)
template<typename T >
__device__ T norm2 (const devcomplex< T > &z)
template<typename T >
__device__ devcomplex< T > exp (const devcomplex< T > &z)
template<typename T >
__device__ devcomplex< T > conj (const devcomplex< T > &z)
Function Documentation
template<typename T > __device__ devcomplex<T> conj (const devcomplex< T > & z)
Definition at line 106 of file devcomplex.hh.
References devcomplex< T >::imag, and devcomplex< T >::real.
Referenced by device_Tddp(), device_Tddp_calcIntegrals(), and getAmplitudeCoefficients().
template<typename T > __device__ devcomplex<T> exp (const devcomplex< T > & z)
Definition at line 101 of file devcomplex.hh.
References COS, EXP, devcomplex< T >::imag, devcomplex< T >::real, and SIN.
Referenced by cpuvoigtian(), dev_powi(), device_Faddeeva_2(), Faddeeva_2(), TRandom::Gaus(), gaussian(), CrystalBallThrustFunctor::integrate(), novosib(), TRandom::Poisson(), and TRandom::PoissonD().
template<typename T > __device__ T norm (const devcomplex< T > & z)
Definition at line 93 of file devcomplex.hh.
References devcomplex< T >::imag, devcomplex< T >::real, and SQRT.
Referenced by Faddeeva_2(), PolynomialThrustFunctor::getCoefficient(), ArgusThrustFunctor::integrate(), and FunctorBase::recursiveSetNormalisation().
template<typename T > __device__ T norm2 (const devcomplex< T > & z)
Definition at line 97 of file devcomplex.hh.
References devcomplex< T >::imag, and devcomplex< T >::real.
Referenced by device_Faddeeva_2(), and device_Tddp().
template<typename T > __device__ devcomplex<T> operator* (const devcomplex< T > & one, const devcomplex< T > & other)
Definition at line 75 of file devcomplex.hh.
References devcomplex< T >::imag, and devcomplex< T >::real.
template<typename T > __device__ devcomplex<T> operator* (const devcomplex< T > & one, const int & other)
Definition at line 79 of file devcomplex.hh.
References devcomplex< T >::imag, and devcomplex< T >::real.
template<typename T > __device__ devcomplex<T> operator* (T a, const devcomplex< T > & b)
Definition at line 89 of file devcomplex.hh.
References devcomplex< T >::imag, and devcomplex< T >::real.
template<typename T > __device__ devcomplex<T> operator+ (const devcomplex< T > & one, const devcomplex< T > & other)
Definition at line 57 of file devcomplex.hh.
References devcomplex< T >::imag, and devcomplex< T >::real.
template<typename T > __device__ devcomplex<T> operator+ (const devcomplex< T > & one, T other)
Definition at line 65 of file devcomplex.hh.
References devcomplex< T >::imag, and devcomplex< T >::real.
template<typename T > __device__ devcomplex<T> operator- (const devcomplex< T > & one, const devcomplex< T > & other)
Definition at line 61 of file devcomplex.hh.
References devcomplex< T >::imag, and devcomplex< T >::real.
template<typename T > __device__ devcomplex<T> operator/ (const devcomplex< T > & one, const devcomplex< T > & other)
Definition at line 69 of file devcomplex.hh.
References devcomplex< T >::imag, and devcomplex< T >::real.
template<typename T > __device__ devcomplex<T> operator/ (const T & a, const devcomplex< T > & b)
Definition at line 83 of file devcomplex.hh.
References devcomplex< T >::imag, and devcomplex< T >::real.