GooFit: Validators
Validators
Some validators that are provided.
Functions
bool CLI::ExistingFile (std::string filename)
Check for an existing file.
bool CLI::ExistingDirectory (std::string filename)
Check for an existing directory.
bool CLI::NonexistentPath (std::string filename)
Check for a non-existing path.
template<typename T >
std::function< bool(std::string)> CLI::Range (T min, T max)
Produce a range validator function.
template<typename T >
std::function< bool(std::string)> CLI::Range (T max)
Range of one value is 0 to value.
Detailed Description
Some validators that are provided.
These are simple bool(std::string) validators that are useful.
Function Documentation
ExistingDirectory()
bool CLI::ExistingDirectory (std::string filename)
Check for an existing directory.
Definition at line 735 of file CLI11.hpp.
{
     struct stat buffer;
     bool exist = stat(filename.c_str(), &buffer) == 0;
     bool is_dir = (buffer.st_mode & S_IFDIR) != 0;
     if(!exist) {
         std::cerr << "Directory does not exist: " << filename << std::endl;
         return false;
     } else if (is_dir) {
         return true;
     } else {
         std::cerr << "Directory is actually a file: " << filename << std::endl;
         return false;
     }
 }
ExistingFile()
bool CLI::ExistingFile (std::string filename)
Check for an existing file.
Definition at line 719 of file CLI11.hpp.
{
     struct stat buffer;
     bool exist = stat(filename.c_str(), &buffer) == 0;
     bool is_dir = (buffer.st_mode & S_IFDIR) != 0;
     if(!exist) {
         std::cerr << "File does not exist: " << filename << std::endl;
         return false;
     } else if (is_dir) {
         std::cerr << "File is actually a directory: " << filename << std::endl;
         return false;
     } else {
         return true;
     }
 }
NonexistentPath()
bool CLI::NonexistentPath (std::string filename)
Check for a non-existing path.
Definition at line 752 of file CLI11.hpp.
{
     struct stat buffer;
     bool exist = stat(filename.c_str(), &buffer) == 0;
     if(!exist) {
         return true;
     } else {
         std::cerr << "Path exists: " << filename << std::endl;
         return false;
     }
 }
Range() [1/2]
template<typename T > std::function<bool(std::string)> CLI::Range (T min, T max)
Produce a range validator function.
Definition at line 765 of file CLI11.hpp.
References CLI::detail::lexical_cast().
Referenced by CLI::Range().
{
     return [min, max](std::string input){
         T val;
         detail::lexical_cast(input, val);
         return val >= min && val <= max;
     };
 }
Range() [2/2]
template<typename T > std::function<bool(std::string)> CLI::Range (T max)
Range of one value is 0 to value.
Definition at line 775 of file CLI11.hpp.
References CLI::Range().
{
     return Range((T) 0, max);
 }