GooFit: CLI::detail Namespace Reference
CLI::detail Namespace Reference
Classes
struct AppFriend
This class is simply to allow tests access to App's protected functions.
struct ini_ret_t
Enumerations
enum enabler
Simple empty scoped class.
enum Classifer {
Classifer::NONE, Classifer::POSITIONAL_MARK, Classifer::SHORT, Classifer::LONG,
Classifer::SUBCOMMAND
}
Functions
template<typename T , enable_if_t< std::is_integral< T >::value &&std::is_signed< T >::value, detail::enabler > = detail::dummy>
constexpr const char * type_name ()
This one should not be used, since vector types print the internal type.
template<typename T , enable_if_t< std::is_integral< T >::value, detail::enabler > = detail::dummy>
bool lexical_cast (std::string input, T &output)
Integers.
std::vector< std::string > split (const std::string &s, char delim)
Split a string by a delim.
template<typename T >
std::string join (const T &v, std::string delim=",")
Simple function to join a string.
template<typename T >
std::string rjoin (const T &v, std::string delim=",")
Join a string in reverse order.
std::string & ltrim (std::string &str)
Trim whitespace from left of string.
std::string & ltrim (std::string &str, const std::string &filter)
Trim anything from left of string.
std::string & rtrim (std::string &str)
Trim whitespace from right of string.
std::string & rtrim (std::string &str, const std::string &filter)
Trim anything from right of string.
std::string & trim (std::string &str)
Trim whitespace from string.
std::string & trim (std::string &str, const std::string filter)
Trim anything from string.
std::string trim_copy (const std::string &str)
Make a copy of the string and then trim it.
std::string trim_copy (const std::string &str, const std::string &filter)
Make a copy of the string and then trim it, any filter string can be used (any char in string is filtered)
void format_help (std::stringstream &out, std::string name, std::string description, size_t wid)
Print a two part "help" string.
template<typename T >
bool valid_first_char (T c)
Verify the first character of an option.
template<typename T >
bool valid_later_char (T c)
Verify following characters of an option.
bool valid_name_string (const std::string &str)
Verify an option name.
std::string to_lower (std::string str)
Return a lower case version of a string.
std::vector< std::string > split_up (std::string str)
Split a string '"one two" "three"' into 'one two', 'three'.
std::string inijoin (std::vector< std::string > args)
std::vector< ini_ret_t > parse_ini (std::istream &input)
Internal parsing function.
std::vector< ini_ret_t > parse_ini (const std::string &name)
Parse an INI file, throw an error (ParseError:INIParseError or FileError) on failure.
bool split_short (const std::string &current, std::string &name, std::string &rest)
bool split_long (const std::string &current, std::string &name, std::string &value)
std::vector< std::string > split_names (std::string current)
std::tuple< std::vector< std::string >, std::vector< std::string >, std::string > get_names (const std::vector< std::string > &input)
Get a vector of short names, one of long names, and a single name.
Variables
constexpr enabler dummy = {}
An instance to use in EnableIf.
Enumeration Type Documentation
Classifer
enum CLI::detail::Classifer strong
Enumerator
NONE
POSITIONAL_MARK
SHORT
LONG
SUBCOMMAND
Definition at line 1269 of file CLI11.hpp.
 {NONE, POSITIONAL_MARK, SHORT, LONG, SUBCOMMAND};
enabler
enum CLI::detail::enabler strong
Simple empty scoped class.
Definition at line 232 of file CLI11.hpp.
 {};
Function Documentation
format_help()
void CLI::detail::format_help (std::stringstream & out, std::string name, std::string description, size_t wid)
Print a two part "help" string.
Definition at line 427 of file CLI11.hpp.
Referenced by CLI::App::help().
{
     name = "  " + name;
     out << std::setw(wid) << std::left << name;
     if(description != "") {
         if(name.length()>=wid)
             out << std::endl << std::setw(wid) << "";
         out << description;
     }
     out << std::endl;
 }
get_names()
std::tuple<std::vector<std::string>,std::vector<std::string>, std::string> CLI::detail::get_names (const std::vector< std::string > & input) inline
Get a vector of short names, one of long names, and a single name.
Definition at line 669 of file CLI11.hpp.
References CLI::BadNameString, valid_first_char(), and valid_name_string().
Referenced by CLI::Option::Option().
{
     std::vector<std::string> short_names;
     std::vector<std::string> long_names;
     std::string pos_name;
     for(std::string name : input) {
         if(name.length() == 0)
             continue;
         else if(name.length() > 1 && name[0] == '-' && name[1] != '-') {
             if(name.length()==2 && valid_first_char(name[1]))
                 short_names.push_back(std::string(1,name[1]));
             else
                 throw BadNameString("Invalid one char name: "+name);
         } else if(name.length() > 2 && name.substr(0,2) == "--") {
             name = name.substr(2);
             if(valid_name_string(name))
                 long_names.push_back(name);
             else
                 throw BadNameString("Bad long name: "+name);
         } else if(name == "-" || name == "--") {
             throw BadNameString("Must have a name, not just dashes");
         } else {
             if(pos_name.length() > 0)
                 throw BadNameString("Only one positional name allowed, remove: "+name);
             pos_name = name;
         }
     }
     return std::tuple<std::vector<std::string>,std::vector<std::string>, std::string>
         (short_names, long_names, pos_name);
 }
inijoin()
std::string CLI::detail::inijoin (std::vector< std::string > args) inline
Definition at line 521 of file CLI11.hpp.
Referenced by CLI::App::config_to_str().
{
     std::ostringstream s;
     size_t start = 0;
     for (const auto& arg : args) {
         if(start++ > 0)
             s << " ";
         auto it = std::find_if(arg.begin(), arg.end(), [](char ch){ return std::isspace<char>(ch , std::locale());});
         if(it == arg.end())
             s << arg;
         else if(arg.find("\"") == std::string::npos)
             s << "\"" << arg << "\"";
         else
             s << "\'" << arg << "\'";
     }
     return s.str();
 }
join()
template<typename T > std::string CLI::detail::join (const T & v, std::string delim = ",")
Simple function to join a string.
Definition at line 351 of file CLI11.hpp.
Referenced by CLI::App::add_option(), CLI::App::add_set(), CLI::App::add_set_ignore_case(), CLI::Option::get_name(), and CLI::Option::run_callback().
{
     std::ostringstream s;
     size_t start = 0;
     for (const auto& i : v) {
         if(start++ > 0)
             s << delim;
         s << i;
     }
     return s.str();
 }
lexical_cast()
template<typename T , enable_if_t< std::is_integral< T >::value, detail::enabler > = detail::dummy> bool CLI::detail::lexical_cast (std::string input, T & output)
Integers.
String and similar.
Floats.
Definition at line 286 of file CLI11.hpp.
References dummy.
Referenced by CLI::App::add_option(), CLI::App::add_set(), and CLI::Range().
{
         try{
             output = (T) std::stoll(input);
             return true;
         } catch (std::invalid_argument) {
             return false;
         } catch (std::out_of_range) {
             return false;
         }
     }
ltrim() [1/2]
std::string& CLI::detail::ltrim (std::string & str)
Trim whitespace from left of string.
Definition at line 377 of file CLI11.hpp.
{
     auto it = std::find_if(str.begin(), str.end(), [](char ch){ return !std::isspace<char>(ch , std::locale());});
     str.erase(str.begin(), it);
     return str;
 }
ltrim() [2/2]
std::string& CLI::detail::ltrim (std::string & str, const std::string & filter)
Trim anything from left of string.
Definition at line 384 of file CLI11.hpp.
Referenced by trim().
{
     auto it = std::find_if(str.begin(), str.end(), [&filter](char ch){return filter.find(ch) == std::string::npos;});
     str.erase(str.begin(), it);
     return str;
 }
parse_ini() [1/2]
std::vector<ini_ret_t> CLI::detail::parse_ini (std::istream & input)
Internal parsing function.
Definition at line 570 of file CLI11.hpp.
References CLI::detail::ini_ret_t::fullname, CLI::detail::ini_ret_t::inputs, split_up(), to_lower(), trim(), and trim_copy().
Referenced by CLI::App::_parse().
{
     std::string name, line;
     std::string section = "default";
     std::vector<ini_ret_t> output;
     while(getline(input, line)) {
         std::vector<std::string> items;
         detail::trim(line);
         size_t len = line.length();
         if(len > 1 && line[0] == '[' && line[len-1] == ']') {
             section = line.substr(1,len-2);
         } else if (len > 0 && line[0] != ';') {
             output.emplace_back();
             ini_ret_t& out = output.back();
             // Find = in string, split and recombine
             auto pos = line.find("=");
             if(pos != std::string::npos) {
                 name = detail::trim_copy(line.substr(0,pos));
                 std::string item = detail::trim_copy(line.substr(pos+1));
                 items = detail::split_up(item);
             } else {
                 name = detail::trim_copy(line);
                 items = {"ON"};
             }
             if(detail::to_lower(section) == "default")
                 out.fullname = name;
             else
                 out.fullname = section + "." + name;
             out.inputs.insert(std::end(out.inputs), std::begin(items), std::end(items));
         }
     }
     return output;
 }
parse_ini() [2/2]
std::vector<ini_ret_t> CLI::detail::parse_ini (const std::string & name)
Parse an INI file, throw an error (ParseError:INIParseError or FileError) on failure.
Definition at line 610 of file CLI11.hpp.
{
     std::ifstream input{name};
     if(!input.good())
         throw FileError(name);
     return parse_ini(input);
 }
rjoin()
template<typename T > std::string CLI::detail::rjoin (const T & v, std::string delim = ",")
Join a string in reverse order.
Definition at line 364 of file CLI11.hpp.
Referenced by CLI::App::_parse().
{
     std::ostringstream s;
     for(size_t start=0; start<v.size(); start++) {
         if(start > 0)
             s << delim;
         s << v[v.size() - start - 1];
     }
     return s.str();
 }
rtrim() [1/2]
std::string& CLI::detail::rtrim (std::string & str)
Trim whitespace from right of string.
Definition at line 392 of file CLI11.hpp.
{
     auto it = std::find_if(str.rbegin(), str.rend(), [](char ch){ return !std::isspace<char>(ch, std::locale());});
     str.erase(it.base() , str.end() );
     return str;
 }
rtrim() [2/2]
std::string& CLI::detail::rtrim (std::string & str, const std::string & filter)
Trim anything from right of string.
Definition at line 399 of file CLI11.hpp.
Referenced by trim().
{
     auto it = std::find_if(str.rbegin(), str.rend(), [&filter](char ch){return filter.find(ch) == std::string::npos;});
     str.erase(it.base(), str.end());
     return str;
 }
split()
std::vector<std::string> CLI::detail::split (const std::string & s, char delim)
Split a string by a delim.
Definition at line 332 of file CLI11.hpp.
Referenced by CLI::detail::ini_ret_t::name(), and CLI::detail::ini_ret_t::parent().
{
     std::vector<std::string> elems;
     // Check to see if emtpy string, give consistent result
     if(s=="")
         elems.push_back("");
     else {
         std::stringstream ss;
         ss.str(s);
         std::string item;
         while (std::getline(ss, item, delim)) {
             elems.push_back(item);
         }
     }
     return elems;
 }
split_long()
bool CLI::detail::split_long (const std::string & current, std::string & name, std::string & value) inline
Definition at line 639 of file CLI11.hpp.
References valid_first_char().
Referenced by CLI::App::_parse_long(), and CLI::App::_recognize().
{
     if(current.size()>2 && current.substr(0,2) == "--" && valid_first_char(current[2])) {
         auto loc = current.find("=");
         if(loc != std::string::npos) {
             name = current.substr(2,loc-2);
             value = current.substr(loc+1);
         } else {
             name = current.substr(2);
             value = "";
         }
         return true;
     } else
         return false;
 }
split_names()
std::vector<std::string> CLI::detail::split_names (std::string current) inline
Definition at line 655 of file CLI11.hpp.
Referenced by CLI::Option::Option().
{
     std::vector<std::string> output;
     size_t val;
     while((val = current.find(",")) != std::string::npos) {
         output.push_back(current.substr(0,val));
         current = current.substr(val+1);
     }
     output.push_back(current);
     return output;
 }
split_short()
bool CLI::detail::split_short (const std::string & current, std::string & name, std::string & rest) inline
Definition at line 629 of file CLI11.hpp.
References valid_first_char().
Referenced by CLI::App::_parse_short(), and CLI::App::_recognize().
{
     if(current.size()>1 && current[0] == '-' && valid_first_char(current[1])) {
         name = current.substr(1,1);
         rest = current.substr(2);
         return true;
     } else
         return false;
 }
split_up()
std::vector<std::string> CLI::detail::split_up (std::string str) inline
Split a string '"one two" "three"' into 'one two', 'three'.
Definition at line 468 of file CLI11.hpp.
References trim().
Referenced by parse_ini().
{
     std::vector<char> delims = {'\'', '\"'};
     auto find_ws = [](char ch){ return std::isspace<char>(ch , std::locale());};
     trim(str);
     std::vector<std::string> output;
     while(str.size() > 0) {
         if(str[0] == '\'') {
             auto end = str.find('\'', 1);
             if(end != std::string::npos) {
                 output.push_back(str.substr(1,end-1));
                 str = str.substr(end+1);
             } else {
                 output.push_back(str.substr(1));
                 str = "";
             }
         } else if(str[0] == '\"') {
             auto end = str.find('\"', 1);
             if(end != std::string::npos) {
                 output.push_back(str.substr(1,end-1));
                 str = str.substr(end+1);
             } else {
                 output.push_back(str.substr(1));
                 str = "";
             }
         } else {
             auto it = std::find_if(std::begin(str), std::end(str), find_ws);
             if(it != std::end(str)) {
                 std::string value = std::string(str.begin(),it);
                 output.push_back(value);
                 str = std::string(it, str.end());
             } else {
                 output.push_back(str);
                 str = "";
             }
         }
         trim(str);
     }
     return output;
 }
to_lower()
std::string CLI::detail::to_lower (std::string str) inline
Return a lower case version of a string.
Definition at line 461 of file CLI11.hpp.
Referenced by CLI::App::_parse_ini(), CLI::App::add_set_ignore_case(), CLI::Option::check_lname(), CLI::Option::check_name(), CLI::App::check_name(), CLI::Option::check_sname(), CLI::App::help(), and parse_ini().
{
     std::transform(std::begin(str), std::end(str), std::begin(str),
         [](const std::string::value_type &x){return std::tolower(x,std::locale());});
     return str;
 }
trim() [1/2]
std::string& CLI::detail::trim (std::string & str)
Trim whitespace from string.
Definition at line 406 of file CLI11.hpp.
References ltrim(), and rtrim().
Referenced by parse_ini().
{
     return ltrim(rtrim(str));
 }
trim() [2/2]
std::string& CLI::detail::trim (std::string & str, const std::string filter)
Trim anything from string.
Definition at line 411 of file CLI11.hpp.
References ltrim(), and rtrim().
Referenced by split_up(), and trim_copy().
{
     return ltrim(rtrim(str, filter), filter);
 }
trim_copy() [1/2]
std::string CLI::detail::trim_copy (const std::string & str)
Make a copy of the string and then trim it.
Definition at line 416 of file CLI11.hpp.
References trim().
Referenced by parse_ini().
{
     std::string s = str;
     return trim(s);
 }
trim_copy() [2/2]
std::string CLI::detail::trim_copy (const std::string & str, const std::string & filter)
Make a copy of the string and then trim it, any filter string can be used (any char in string is filtered)
Definition at line 422 of file CLI11.hpp.
References trim().
{
     std::string s = str;
     return trim(s, filter);
 }
type_name()
template<typename T , enable_if_t< std::is_integral< T >::value &&std::is_signed< T >::value, detail::enabler > = detail::dummy> constexpr const char * CLI::detail::type_name ()
This one should not be used, since vector types print the internal type.
Was going to be based on http://stackoverflow.com/questions/1055452/c-get-name-of-type-in-template But this is cleaner and works better in this case
Definition at line 246 of file CLI11.hpp.
References dummy.
{
         return "INT";
     }
valid_first_char()
template<typename T > bool CLI::detail::valid_first_char (T c)
Verify the first character of an option.
Definition at line 440 of file CLI11.hpp.
Referenced by get_names(), split_long(), split_short(), and valid_name_string().
{
     return std::isalpha(c, std::locale()) || c=='_';
 }
valid_later_char()
template<typename T > bool CLI::detail::valid_later_char (T c)
Verify following characters of an option.
Definition at line 446 of file CLI11.hpp.
Referenced by valid_name_string().
{
     return std::isalnum(c, std::locale()) || c=='_' || c=='.' || c=='-';
 }
valid_name_string()
bool CLI::detail::valid_name_string (const std::string & str) inline
Verify an option name.
Definition at line 451 of file CLI11.hpp.
References valid_first_char(), and valid_later_char().
Referenced by get_names().
{
     if(str.size()<1 || !valid_first_char(str[0]))
         return false;
     for(auto c : str.substr(1))
         if(!valid_later_char(c))
             return false;
     return true;
 }
Variable Documentation
dummy
constexpr enabler CLI::detail::dummy = {}
An instance to use in EnableIf.
Definition at line 235 of file CLI11.hpp.
Referenced by CLI::App::add_flag(), CLI::App::add_option(), CLI::App::add_subcommand(), lexical_cast(), and type_name().