GooFit: GooFit Namespace Reference
GooFit Namespace Reference
Namespaces
Lineshapes
literals
Resonances
Classes
class AddPdf
class AmpCalc
class AmpCalc_TD
class Amplitude
class Application
class ArgusPdf
class BifurGaussPdf
class BinnedChisqFit
class BinnedDataSet
class BinnedErrorFit
class BinnedNllFit
class BinTransformPdf
class BWPdf
class CompositePdf
class ConvolutionPdf
class CorrGaussianPdf
class CrystalBallPdf
class DalitzPlotPdf
class DalitzPlotter
This class makes it easy to make plots over 3 body Dalitz PDFs. You can use ROOT style value access or bin numbers.
class DalitzVetoPdf
class DataSet
struct DecayInfo3
struct DecayInfo3t
struct DecayInfo4
struct DecayInfo4t
struct Dim5
class DPPdf
class EventNumber
class EventWeightedAddPdf
class ExpGausPdf
class ExpPdf
class FCN
class FitControl
class FitManagerMinuit1
class FitManagerMinuit2
class FourDblTupleAdd
class GaussianPdf
struct GeneralError
Thrown when a general error is encountered.
class GooPdf
class IncoherentSumPdf
class Indexable
class InterHistPdf
class JohnsonSUPdf
class KinLimitBWPdf
class LandauPdf
class Lineshape
class LorentzMatrix
class LSCalculator
class LSCalculator_TD
class MappedPdf
class MetricTaker
class Minuit1
class MixingTimeResolution
class NormIntegrator
class NormIntegrator_TD
class NormLSCalculator
class NormLSCalculator_TD
class NormSpinCalculator
class NormSpinCalculator_TD
class NovosibirskPdf
class Observable
Special class for observables. Used in DataSets.
struct OutOfRange
class Params
class PdfBase
class PolynomialPdf
class ProdPdf
class ResonancePdf
class ScaledGaussianPdf
class SFCalculator
class SFCalculator_TD
class SmoothHistogramPdf
class SpecialComplexSum
class SpecialDalitzIntegrator
class SpecialIncoherentIntegrator
class SpecialIncoherentResonanceCalculator
class SpecialResonanceCalculator
class SpecialResonanceIntegrator
class SpecialWaveCalculator
class SpinFactor
class SpinSumT
class SpinSumV
class StepPdf
class strided_range
class SymmLorentzMatrix
class TDDP4
class TddpPdf
class ThreeGaussResolution
class TrigThresholdPdf
class TruthResolution
class UnbinnedDataSet
class UnbinnedNllFit
class Uncertain
class Variable
class VariableBinTransform1DPdf
struct VetoInfo
class VoigtianPdf
struct WaveHolder_s
class ZTspin1
class ZTspin2
Typedefs
using fpcomplex = thrust::complex< fptype >
using FitManager = GooFit::FitManagerMinuit2
using fptype = double
typedef fptype(* device_function_ptr) (fptype *, fptype *, unsigned int *)
Pass event, parameters, index into parameters.
typedef fptype(* device_metric_ptr) (fptype, fptype *, unsigned int)
typedef fptype(* device_resfunction_ptr) (fptype, fptype, fptype, fptype, fptype, fptype, fptype, fptype, fptype, fptype *, unsigned int *)
typedef fptype(* device_calc_tau_fcn_ptr) (fptype, fptype, fptype, fptype, fptype, fptype, fptype)
typedef fpcomplex(* resonance_function_ptr) (fptype, fptype, fptype, unsigned int *)
typedef fptype(* spin_function_ptr) (fptype *, unsigned int *)
typedef thrust::tuple< fptype, fptype, fptype, fptype > WaveHolder
typedef thrust::tuple< fptype, fptype, fptype, fptype, fptype, fptype > ThreeComplex
Enumerations
enum FitErrors : int { FitErrors::Valid = 0, FitErrors::NotRun = 50, FitErrors::InValid }
enum EvalFunc : size_t {
EvalFunc::Eval = 0, EvalFunc::NLL, EvalFunc::Prob, EvalFunc::BinAvg,
EvalFunc::BinWithError, EvalFunc::Chisq
}
enum DP4Pair {
M_12 = 0, M_34, M_13, M_14,
M_23, M_24, M_12_3, M_13_2,
M_23_1, M_12_4, M_14_2, M_24_1,
M_13_4, M_14_3, M_34_1, M_23_4,
M_24_3, M_34_2
}
enum DaughterPair { PAIR_12 = 0, PAIR_13, PAIR_23 }
enum FF : unsigned int { FF::One = 0, FF::BL, FF::BL_Prime, FF::BL2 }
enum SF_4Body {
SF_4Body::DtoPP1_PtoSP2_StoP3P4, SF_4Body::DtoPP1_PtoVP2_VtoP3P4, SF_4Body::DtoV1V2_V1toP1P2_V2toP3P4_S, SF_4Body::DtoV1V2_V1toP1P2_V2toP3P4_P,
SF_4Body::DtoV1V2_V1toP1P2_V2toP3P4_D, SF_4Body::DtoAP1_AtoVP2_VtoP3P4, SF_4Body::DtoAP1_AtoVP2Dwave_VtoP3P4, SF_4Body::DtoVS_VtoP1P2_StoP3P4,
SF_4Body::DtoV1P1_V1toV2P2_V2toP3P4, SF_4Body::DtoAP1_AtoSP2_StoP3P4, SF_4Body::DtoTP1_TtoVP2_VtoP3P4, SF_4Body::FF_12_34_L1,
SF_4Body::FF_12_34_L2, SF_4Body::FF_123_4_L1, SF_4Body::FF_123_4_L2, SF_4Body::ONE
}
Functions
void signal_handler (int s)
will call the correct exit func, no unwinding of the stack though
void print_splash ()
void print_goofit_info (int gpuDev_=0)
Print out information about GooFit.
void abort (std::string file, int line, std::string reason, const PdfBase *pdf=nullptr)
Smart abort that includes the file name and location, and prints a stack trace if possible.
template<int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int >
__device__ Eigen::Array< fpcomplex, 5, 5 > compute_inverse5 (const Eigen::Array< fpcomplex, 5, 5 > &m)
template<>
__device__ Eigen::Array< fpcomplex, 5, 5 > compute_inverse5<-1, -1, 0, -1, -1, -1, -1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 > (const Eigen::Array< fpcomplex, 5, 5 > &M)
void fillDataSetMC1D (GooPdf &pdf, Observable var, size_t nTotal, unsigned int seed=0)
Uncertain operator* (fptype other, const Uncertain &self)
Allow int and float multiplies.
std::ostream & operator<< (std::ostream &stream, Uncertain value)
Simple << output.
void format_arg (fmt::BasicFormatter< char > &f, const char *&format_str, const Uncertain &s)
fmt support
template<typename M >
M read_csv (std::string name, bool comma=true)
fptype cpuvoigtian (fptype x, fptype m, fptype w, fptype s)
void writeToFile (PdfBase *pdf, const char *fname)
void readFromFile (PdfBase *pdf, const char *fname)
void writeListOfNumbers (thrust::host_vector< fptype > &target, const char *fname)
void readListOfNumbers (thrust::host_vector< fptype > &target, const char *fname)
gooError gooMalloc (void **target, size_t bytes)
gooError gooFree (void *ptr)
template<typename T >
std::vector< T > flatten (const std::vector< thrust::complex< T >> &input)
Flatten a complex array into a standard one (1r, 1i, 2r, 2i, ...)
std::vector< fpcomplex > complex_derivative (const std::vector< fptype > &x, const std::vector< fpcomplex > &y)
constexpr const char * evalfunc_to_string (EvalFunc val)
__device__ int dev_powi (int base, int exp)
void * getMetricPointer (std::string name)
__device__ fptype callFunction (fptype *eventAddress, unsigned int functionIdx, unsigned int paramIdx)
template<typename E >
constexpr std::underlying_type< E >::type enum_to_underlying (E e)
__host__ __device__ bool inDalitz (const fptype &m12, const fptype &m13, const fptype &bigM, const fptype &dm1, const fptype &dm2, const fptype &dm3)
__device__ fpcomplex getResonanceAmplitude (fptype m12, fptype m13, fptype m23, unsigned int functionIdx, unsigned int pIndex)
__device__ void get4Vecs (fptype *Vecs, const unsigned int &constants, const fptype &m12, const fptype &m34, const fptype &cos12, const fptype &cos34, const fptype &phi)
__device__ fptype getmass (const unsigned int &pair, fptype &d1, fptype &d2, const fptype *vecs, const fptype &m1, const fptype &m2, const fptype &m3, const fptype &m4)
__device__ fptype twoBodyCMmom (double rMassSq, fptype d1m, fptype d2m)
__device__ fptype dampingFactorSquare (const fptype &cmmom, const int &spin, const fptype &mRadius)
__device__ fptype spinFactor (unsigned int spin, fptype motherMass, fptype daug1Mass, fptype daug2Mass, fptype daug3Mass, fptype m12, fptype m13, fptype m23, unsigned int cyclic_index)
class __align__ (16) gpuLVec
__device__ gpuLVec operator+ (gpuLVec lhs, const gpuLVec &rhs)
__device__ gpuLVec operator- (gpuLVec lhs, const gpuLVec &rhs)
__device__ gpuLVec operator* (gpuLVec lhs, fptype rhs)
__device__ gpuLVec operator* (fptype lhs, gpuLVec rhs)
__device__ SymmLorentzMatrix operator* (fptype lhs, const SymmLorentzMatrix &rhs)
__device__ SymmLorentzMatrix operator/ (fptype lhs, const SymmLorentzMatrix &rhs)
__device__ fptype LeviCivita (const gpuLVec &p1, const gpuLVec &p2, const gpuLVec &p3, const gpuLVec &p4)
__device__ gpuLVec LeviCivita (const gpuLVec &a, const gpuLVec &b, const gpuLVec &c)
Eigen::Matrix< fptype, 5, Eigen::Dynamic > to_5param (const Eigen::Matrix< fptype, 16, Eigen::Dynamic > &mat)
This is a helper to convert values. It copies back and forth, so is only to be used in scripts.
int max_index (const std::vector< Variable > &vars)
Get the max index of a variable from a list.
int max_index (const std::vector< Observable > &vars)
int max_fitter_index (const std::vector< Variable > &vars)
Get the max fitter index of a variable from a list.
std::ostream & operator<< (std::ostream &o, const GooFit::Variable &var)
Nice print of Variable.
std::ostream & operator<< (std::ostream &o, const GooFit::Observable &var)
Nice print of Observable.
std::istream & operator>> (std::istream &i, GooFit::Observable &var)
Allow Observable to be read in.
fpcomplex Faddeeva_2 (const fpcomplex &z)
void make_a_grid (std::vector< Observable > ret, UnbinnedDataSet *grid, Observable *eventNum)
Variables
constexpr rang::fg const black = rang::fg::black
constexpr rang::fg const red = rang::fg::red
constexpr rang::fg const green = rang::fg::green
constexpr rang::fg const yellow = rang::fg::yellow
constexpr rang::fg const blue = rang::fg::blue
constexpr rang::fg const magenta = rang::fg::magenta
constexpr rang::fg const cyan = rang::fg::cyan
constexpr rang::fg const gray = rang::fg::gray
constexpr rang::style const reset = rang::style::reset
constexpr rang::style const bold = rang::style::bold
constexpr rang::style const dim = rang::style::dim
constexpr rang::style const italic = rang::style::italic
int host_callnumber = 0
const int maxParams = GOOFIT_MAXPAR
fptype * dev_event_array
fptype host_normalisation [maxParams]
fptype host_params [maxParams]
unsigned int host_indices [maxParams]
int totalParams = 0
int totalConstants = 1
constexpr const char * evalfunc_vals [] = {"ptr_to_Eval", "ptr_to_NLL", "ptr_to_Prob", "ptr_to_BinAvg", "ptr_to_BinWithError", "ptr_to_Chisq"}
void * host_fcn_ptr
const int resonanceSize = 4
Typedef Documentation
device_calc_tau_fcn_ptr
typedef fptype(* GooFit::device_calc_tau_fcn_ptr) (fptype, fptype, fptype, fptype, fptype, fptype, fptype)
Definition at line 10 of file MixingTimeResolution_Aux.h.
device_function_ptr
typedef fptype(* GooFit::device_function_ptr) (fptype *, fptype *, unsigned int *)
Pass event, parameters, index into parameters.
Definition at line 46 of file GooPdf.h.
device_metric_ptr
typedef fptype(* GooFit::device_metric_ptr) (fptype, fptype *, unsigned int)
Definition at line 48 of file GooPdf.h.
device_resfunction_ptr
typedef fptype(* GooFit::device_resfunction_ptr) (fptype, fptype, fptype, fptype, fptype, fptype, fptype, fptype, fptype, fptype *, unsigned int *)
Definition at line 8 of file MixingTimeResolution_Aux.h.
FitManager
using GooFit::FitManager = typedef GooFit::FitManagerMinuit2
Definition at line 9 of file FitManager.h.
fpcomplex
using GooFit::fpcomplex = typedef thrust::complex<fptype>
Definition at line 8 of file Complex.h.
fptype
using GooFit::fptype = typedef double
Definition at line 96 of file GlobalCudaDefines.h.
resonance_function_ptr
typedef fpcomplex(* GooFit::resonance_function_ptr) (fptype, fptype, fptype, unsigned int *)
Definition at line 10 of file ResonancePdf.h.
spin_function_ptr
typedef fptype(* GooFit::spin_function_ptr) (fptype *, unsigned int *)
Definition at line 15 of file SpinFactors.h.
ThreeComplex
typedef thrust::tuple<fptype, fptype, fptype, fptype, fptype, fptype> GooFit::ThreeComplex
Definition at line 19 of file TddpPdf.h.
WaveHolder
typedef thrust::tuple<fptype, fptype, fptype, fptype> GooFit::WaveHolder
Definition at line 18 of file TddpPdf.h.
Enumeration Type Documentation
DaughterPair
enum GooFit::DaughterPair
Enumerator
PAIR_12
PAIR_13
PAIR_23
Definition at line 69 of file DalitzPlotHelpers.h.
 { PAIR_12 = 0, PAIR_13, PAIR_23 };
DP4Pair
enum GooFit::DP4Pair
Enumerator
M_12
M_34
M_13
M_14
M_23
M_24
M_12_3
M_13_2
M_23_1
M_12_4
M_14_2
M_24_1
M_13_4
M_14_3
M_34_1
M_23_4
M_24_3
M_34_2
Definition at line 49 of file DalitzPlotHelpers.h.
              {
     M_12 = 0,
     M_34,
     M_13,
     M_14,
     M_23,
     M_24,
     M_12_3,
     M_13_2,
     M_23_1,
     M_12_4,
     M_14_2,
     M_24_1,
     M_13_4,
     M_14_3,
     M_34_1,
     M_23_4,
     M_24_3,
     M_34_2
 };
EvalFunc
enum GooFit::EvalFunc : size_t strong
Enumerator
Eval
NLL
Prob
BinAvg
BinWithError
Chisq
Definition at line 15 of file GooPdf.h.
 : size_t { Eval = 0, NLL, Prob, BinAvg, BinWithError, Chisq };
FF
enum GooFit::FF : unsigned int strong
Enumerator
One
BL
BL_Prime
BL2
Definition at line 25 of file LineshapesPdf.h.
 : unsigned int { One = 0, BL, BL_Prime, BL2 };
FitErrors
enum GooFit::FitErrors : int strong
Enumerator
Valid
NotRun
InValid
Definition at line 14 of file FitManagerMinuit2.h.
 : int { Valid = 0, NotRun = 50, InValid };
SF_4Body
enum GooFit::SF_4Body strong
Enumerator
DtoPP1_PtoSP2_StoP3P4
DtoPP1_PtoVP2_VtoP3P4
DtoV1V2_V1toP1P2_V2toP3P4_S
DtoV1V2_V1toP1P2_V2toP3P4_P
DtoV1V2_V1toP1P2_V2toP3P4_D
DtoAP1_AtoVP2_VtoP3P4
DtoAP1_AtoVP2Dwave_VtoP3P4
DtoVS_VtoP1P2_StoP3P4
DtoV1P1_V1toV2P2_V2toP3P4
DtoAP1_AtoSP2_StoP3P4
DtoTP1_TtoVP2_VtoP3P4
FF_12_34_L1
FF_12_34_L2
FF_123_4_L1
FF_123_4_L2
ONE
Definition at line 17 of file SpinFactors.h.
                     {
     DtoPP1_PtoSP2_StoP3P4,
     DtoPP1_PtoVP2_VtoP3P4,
     DtoV1V2_V1toP1P2_V2toP3P4_S,
     DtoV1V2_V1toP1P2_V2toP3P4_P,
     DtoV1V2_V1toP1P2_V2toP3P4_D,
     DtoAP1_AtoVP2_VtoP3P4,
     DtoAP1_AtoVP2Dwave_VtoP3P4,
     DtoVS_VtoP1P2_StoP3P4,
     DtoV1P1_V1toV2P2_V2toP3P4,
     DtoAP1_AtoSP2_StoP3P4,
     DtoTP1_TtoVP2_VtoP3P4,
     FF_12_34_L1,
     FF_12_34_L2,
     FF_123_4_L1,
     FF_123_4_L2,
     ONE
 };
Function Documentation
__align__()
class GooFit::__align__ (16)
Definition at line 15 of file SpinHelper.h.
{
   private:
     fptype X;
     fptype Y;
     fptype Z;
     fptype E;
   public:
     __device__ gpuLVec() { X = Y = Z = E = 0; };
     __device__ gpuLVec(fptype x, fptype y, fptype z, fptype e)
         : X(x)
         , Y(y)
         , Z(z)
         , E(e){};
     __device__ void SetXYZE(fptype x, fptype y, fptype z, fptype e) {
         X = x;
         Y = y;
         Z = z;
         E = e;
     }
     __device__ fptype Dot(const gpuLVec &rhs) const { return E * rhs.E - X * rhs.X - Y * rhs.Y - Z * rhs.Z; }
     __device__ inline fptype GetX() const { return X; }
     __device__ inline fptype GetY() const { return Y; }
     __device__ inline fptype GetZ() const { return Z; }
     __device__ inline fptype GetE() const { return E; }
     __device__ inline fptype Mag2() const { return this->Dot(*this); }
     __device__ inline fptype M() const { return sqrt(this->Mag2()); }
     __device__ inline void SetX(fptype a) { X = a; }
     __device__ inline void SetY(fptype a) { Y = a; }
     __device__ inline void SetZ(fptype a) { Z = a; }
     __device__ inline void SetE(fptype a) { E = a; }
     __device__ gpuLVec &operator+=(const gpuLVec &rhs) {
         X += rhs.X;
         Y += rhs.Y;
         Z += rhs.Z;
         E += rhs.E;
         return *this;
     }
     __device__ gpuLVec &operator-=(const gpuLVec &rhs) {
         X -= rhs.X;
         Y -= rhs.Y;
         Z -= rhs.Z;
         E -= rhs.E;
         return *this;
     }
     __device__ gpuLVec &operator*=(const fptype rhs) {
         X *= rhs;
         Y *= rhs;
         Z *= rhs;
         E *= rhs;
         return *this;
     }
 };
abort()
void GooFit::abort (std::string file, int line, std::string reason, const PdfBase * pdf = nullptr)
Smart abort that includes the file name and location, and prints a stack trace if possible.
Definition at line 9 of file Abort.cpp.
References bold, GooFit::PdfBase::getName(), GooFit::PdfBase::getParameters(), host_params, red, reset, and totalParams.
{
     void *stackarray[20];
     std::cout << GooFit::reset << GooFit::red << "Abort called from " << file << " line " << line << " due to "
               << reason << std::endl;
     if(pdf) {
         std::vector<Variable> pars = pdf->getParameters();
         std::cout << "Parameters of " << pdf->getName() << " : \n";
         for(const Variable &v : pars) {
             if(0 > v.getIndex())
                 continue;
             std::cout << "  " << v.getName() << " (" << v.getIndex() << ") :\t" << host_params[v.getIndex()]
                       << std::endl;
         }
     }
     std::cout << "Parameters (" << totalParams << ") :\n";
     for(int i = 0; i < totalParams; ++i) {
         std::cout << host_params[i] << " ";
     }
 #if Backtrace_FOUND
     std::cout << GooFit::bold << std::endl;
     // get void* pointers for all entries on the stack
     int size = backtrace(stackarray, 20);
     // print out all the frames to stderr
     backtrace_symbols_fd(stackarray, size, 2);
 #endif
     std::cout << GooFit::reset << std::flush;
     throw GooFit::GeneralError(reason);
 }
callFunction()
__device__ fptype GooFit::callFunction (fptype * eventAddress, unsigned int functionIdx, unsigned int paramIdx)
complex_derivative()
std::vector<fpcomplex> GooFit::complex_derivative (const std::vector< fptype > & x, const std::vector< fpcomplex > & y)
Definition at line 20 of file ComplexUtils.h.
{
     if(x.size() != y.size()) // Must be a valid pointer
         throw GeneralError("x and y must have the same diminsions!");
     int i, k;
     unsigned int n = x.size();
     std::vector<fpcomplex> u(n);
     std::vector<fpcomplex> y2(n);
     fptype sig, p, qn, un;
     fpcomplex yp1 = 2. * (y[1] - y[0]) / (x[1] - x[0]);
     fpcomplex ypn = 2. * (y[n - 1] - y[n - 2]) / (x[n - 1] - x[n - 2]);
     /* The lower boundary condition is set either to be "natural" or else to have specified first derivative*/
     if(yp1.real() > 0.99e30) {
         y2[0].real(0.);
         u[0].real(0.);
     } else {
         y2[0].real(-0.5);
         u[0].real(3.0 / (x[1] - x[0]) * ((y[1].real() - y[0].real()) / (x[1] - x[0]) - yp1.real()));
     }
     if(yp1.imag() > 0.99e30) {
         y2[0].imag(0.);
         u[0].imag(0.);
     } else {
         y2[0].imag(-0.5);
         u[0].imag(3.0 / (x[1] - x[0]) * ((y[1].imag() - y[0].imag()) / (x[1] - x[0]) - yp1.imag()));
     }
     /* This is the decomposition loop of the tridiagonal algorithm. y2 and u are used for temporary storage of the
      * decomposed factors*/
     for(i = 1; i < n - 1; i++) {
         sig = (x[i] - x[i - 1]) / (x[i + 1] - x[i - 1]);
         p   = sig * y2[i - 1].real() + 2.0;
         y2[i].real((sig - 1.0) / p);
         u[i].real((y[i + 1].real() - y[i].real()) / (x[i + 1] - x[i])
                   - (y[i].real() - y[i - 1].real()) / (x[i] - x[i - 1]));
         u[i].real((6.0 * u[i].real() / (x[i + 1] - x[i - 1]) - sig * u[i - 1].real()) / p);
         p = sig * y2[i - 1].imag() + 2.0;
         y2[i].imag((sig - 1.0) / p);
         u[i].imag((y[i + 1].imag() - y[i].imag()) / (x[i + 1] - x[i])
                   - (y[i].imag() - y[i - 1].imag()) / (x[i] - x[i - 1]));
         u[i].imag((6.0 * u[i].imag() / (x[i + 1] - x[i - 1]) - sig * u[i - 1].imag()) / p);
     }
     /* The upper boundary condition is set either to be "natural" or else to have specified first derivative*/
     if(ypn.real() > 0.99e30) {
         qn = 0.;
         un = 0.;
     } else {
         qn = 0.5;
         un = (3.0 / (x[n - 1] - x[n - 2])) * (ypn.real() - (y[n - 1].real() - y[n - 2].real()) / (x[n - 1] - x[n - 2]));
     }
     y2[n - 1].real((un - qn * u[n - 2].real()) / (qn * y2[n - 2].real() + 1.0));
     if(ypn.imag() > 0.99e30) {
         qn = 0.;
         un = 0.;
     } else {
         qn = 0.5;
         un = (3.0 / (x[n - 1] - x[n - 2])) * (ypn.imag() - (y[n - 1].imag() - y[n - 2].imag()) / (x[n - 1] - x[n - 2]));
     }
     y2[n - 1].imag((un - qn * u[n - 2].imag()) / (qn * y2[n - 2].imag() + 1.0));
     /* This is the backsubstitution loop of the tridiagonal algorithm */
     for(k = n - 2; k >= 0; k--) {
         y2[k].real(y2[k].real() * y2[k + 1].real() + u[k].real());
         y2[k].imag(y2[k].imag() * y2[k + 1].imag() + u[k].imag());
     }
     return y2;
 }
compute_inverse5()
template<int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int , int > __device__ Eigen::Array<fpcomplex, 5, 5> GooFit::compute_inverse5 (const Eigen::Array< fpcomplex, 5, 5 > & m)
compute_inverse5<-1, -1, 0, -1, -1, -1, -1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 >()
template<> __device__ Eigen::Array<fpcomplex, 5, 5> GooFit::compute_inverse5<-1, -1, 0, -1, -1, -1, -1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 > (const Eigen::Array< fpcomplex, 5, 5 > & M) inline
Definition at line 36 of file compute_inverse5.h.
{
     Eigen::Array<fpcomplex, 5, 5> O;
     O(0, 0) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(0, 1) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(0, 2) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(0, 3) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(0, 4) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(1, 0) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(1, 1) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(1, 2) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(1, 3) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(1, 4) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(2, 0) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(2, 1) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(2, 2) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(2, 3) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(2, 4) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(3, 0) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(3, 1) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(3, 2) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(3, 3) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(3, 4) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(4, 0) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(4, 1) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(4, 2) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(4, 3) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     O(4, 4) = (M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                - M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                + M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                + M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                - M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                + M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                - M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                + M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                - M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1))
               / (M(0, 0) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 4) - M(0, 0) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 3)
                  - M(0, 0) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 4) + M(0, 0) * M(1, 1) * M(2, 3) * M(3, 4) * M(4, 2)
                  + M(0, 0) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 3) - M(0, 0) * M(1, 1) * M(2, 4) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 4) - M(0, 0) * M(1, 3) * M(2, 1) * M(3, 4) * M(4, 2)
                  - M(0, 0) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 4) + M(0, 0) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 1)
                  + M(0, 0) * M(1, 3) * M(2, 4) * M(3, 1) * M(4, 2) - M(0, 0) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 3) + M(0, 0) * M(1, 4) * M(2, 1) * M(3, 3) * M(4, 2)
                  + M(0, 0) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 3) - M(0, 0) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 1)
                  - M(0, 0) * M(1, 4) * M(2, 3) * M(3, 1) * M(4, 2) + M(0, 0) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 1) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 4) + M(0, 1) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 3)
                  + M(0, 1) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 4) - M(0, 1) * M(1, 0) * M(2, 3) * M(3, 4) * M(4, 2)
                  - M(0, 1) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 3) + M(0, 1) * M(1, 0) * M(2, 4) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 4) + M(0, 1) * M(1, 3) * M(2, 0) * M(3, 4) * M(4, 2)
                  + M(0, 1) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 4) - M(0, 1) * M(1, 3) * M(2, 2) * M(3, 4) * M(4, 0)
                  - M(0, 1) * M(1, 3) * M(2, 4) * M(3, 0) * M(4, 2) + M(0, 1) * M(1, 3) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 3) - M(0, 1) * M(1, 4) * M(2, 0) * M(3, 3) * M(4, 2)
                  - M(0, 1) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 3) + M(0, 1) * M(1, 4) * M(2, 2) * M(3, 3) * M(4, 0)
                  + M(0, 1) * M(1, 4) * M(2, 3) * M(3, 0) * M(4, 2) - M(0, 1) * M(1, 4) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 3) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 4) + M(0, 3) * M(1, 0) * M(2, 1) * M(3, 4) * M(4, 2)
                  + M(0, 3) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 4) - M(0, 3) * M(1, 0) * M(2, 2) * M(3, 4) * M(4, 1)
                  - M(0, 3) * M(1, 0) * M(2, 4) * M(3, 1) * M(4, 2) + M(0, 3) * M(1, 0) * M(2, 4) * M(3, 2) * M(4, 1)
                  + M(0, 3) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 4) - M(0, 3) * M(1, 1) * M(2, 0) * M(3, 4) * M(4, 2)
                  - M(0, 3) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 4) + M(0, 3) * M(1, 1) * M(2, 2) * M(3, 4) * M(4, 0)
                  + M(0, 3) * M(1, 1) * M(2, 4) * M(3, 0) * M(4, 2) - M(0, 3) * M(1, 1) * M(2, 4) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 0) * M(3, 1) * M(4, 2) - M(0, 3) * M(1, 4) * M(2, 0) * M(3, 2) * M(4, 1)
                  - M(0, 3) * M(1, 4) * M(2, 1) * M(3, 0) * M(4, 2) + M(0, 3) * M(1, 4) * M(2, 1) * M(3, 2) * M(4, 0)
                  + M(0, 3) * M(1, 4) * M(2, 2) * M(3, 0) * M(4, 1) - M(0, 3) * M(1, 4) * M(2, 2) * M(3, 1) * M(4, 0)
                  + M(0, 4) * M(1, 0) * M(2, 1) * M(3, 2) * M(4, 3) - M(0, 4) * M(1, 0) * M(2, 1) * M(3, 3) * M(4, 2)
                  - M(0, 4) * M(1, 0) * M(2, 2) * M(3, 1) * M(4, 3) + M(0, 4) * M(1, 0) * M(2, 2) * M(3, 3) * M(4, 1)
                  + M(0, 4) * M(1, 0) * M(2, 3) * M(3, 1) * M(4, 2) - M(0, 4) * M(1, 0) * M(2, 3) * M(3, 2) * M(4, 1)
                  - M(0, 4) * M(1, 1) * M(2, 0) * M(3, 2) * M(4, 3) + M(0, 4) * M(1, 1) * M(2, 0) * M(3, 3) * M(4, 2)
                  + M(0, 4) * M(1, 1) * M(2, 2) * M(3, 0) * M(4, 3) - M(0, 4) * M(1, 1) * M(2, 2) * M(3, 3) * M(4, 0)
                  - M(0, 4) * M(1, 1) * M(2, 3) * M(3, 0) * M(4, 2) + M(0, 4) * M(1, 1) * M(2, 3) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 0) * M(3, 1) * M(4, 2) + M(0, 4) * M(1, 3) * M(2, 0) * M(3, 2) * M(4, 1)
                  + M(0, 4) * M(1, 3) * M(2, 1) * M(3, 0) * M(4, 2) - M(0, 4) * M(1, 3) * M(2, 1) * M(3, 2) * M(4, 0)
                  - M(0, 4) * M(1, 3) * M(2, 2) * M(3, 0) * M(4, 1) + M(0, 4) * M(1, 3) * M(2, 2) * M(3, 1) * M(4, 0));
     return O;
 };
cpuvoigtian()
fptype GooFit::cpuvoigtian (fptype x, fptype m, fptype w, fptype s)
Definition at line 122 of file Faddeeva.cpp.
References Faddeeva_2().
{
     // This calculation includes the normalisation - integral
     // over the reals is equal to one.
     // return constant for zero width and sigma
     if((0 == s) && (0 == w))
         return 1;
     if(s <= 0 || w <= 0)
         throw GooFit::GeneralError("s {} and w {} must be larger than 0", s, w);
     fptype coef = -0.5 / (s * s);
     fptype arg  = x - m;
     // Breit-Wigner for zero sigma
     if(0 == s)
         return (1 / (arg * arg + 0.25 * w * w));
     // Gauss for zero width
     if(0 == w)
         return exp(coef * arg * arg);
     // actual Voigtian for non-trivial width and sigma
     fptype c = 1. / (sqrt(2) * s);
     fptype a = 0.5 * c * w;
     fptype u = c * arg;
     fpcomplex z(u, a);
     // printf("Calling Faddeeva %f %f %f %f %f %f %f\n", x, m, s, w, c, a, u);
     fpcomplex v = Faddeeva_2(z);
     static const fptype rsqrtPi = 0.5641895835477563;
     return c * rsqrtPi * v.real();
 }
dampingFactorSquare()
__device__ fptype GooFit::dampingFactorSquare (const fptype & cmmom, const int & spin, const fptype & mRadius)
dev_powi()
__device__ int GooFit::dev_powi (int base, int exp)
Referenced by evalfunc_to_string().
enum_to_underlying()
template<typename E > constexpr std::underlying_type<E>::type GooFit::enum_to_underlying (E e)
Definition at line 21 of file DalitzPlotHelpers.h.
References get4Vecs(), getmass(), getResonanceAmplitude(), inDalitz(), m12, and m13.
{
     return static_cast<typename std::underlying_type<E>::type>(e);
 }
evalfunc_to_string()
constexpr const char* GooFit::evalfunc_to_string (EvalFunc val)
Definition at line 20 of file GooPdf.h.
References dev_powi(), evalfunc_vals, getMetricPointer(), and maxParams.
 { return evalfunc_vals[static_cast<size_t>(val)]; }
Faddeeva_2()
fpcomplex GooFit::Faddeeva_2 (const fpcomplex & z)
Definition at line 46 of file Faddeeva.cpp.
References M_2PI.
Referenced by cpuvoigtian().
{
     fptype *n, *e, t, u, r, s, d, f, g, h;
     fpcomplex c, d2, v, w;
     int i;
     s = norm(z); // Actually the square of the norm. Don't ask me, I didn't name the function.
     if(s < 1e-7) {
         // use Pade approximation
         fpcomplex zz = z * z;
         v            = exp(zz);
         c            = C[0];
         d2           = D[0];
         for(i = 1; i <= 6; i++) {
             c  = c * zz + C[i];
             d2 = d2 * zz + D[i];
         }
         w = fptype(1.0) / v + fpcomplex(0.0, M_2_SQRTPI) * c / d2 * z * v;
         return w;
     }
     // use trapezoid rule
     // select default table 1
     n = n1;
     e = e1;
     r = M_1_PI * 0.5;
     // if z is too close to a pole select table 2
     if(fabs(z.imag()) < 0.01 && fabs(z.real()) < 6.01) {
         h = fabs(z.real()) * 2;
         // Equivalent to modf(h, &g). Do this way because nvcc only knows about double version of modf.
         g = floor(h);
         h -= g;
         if(h < 0.02 || h > 0.98) {
             n = n2;
             e = e2;
             r = M_1_PI * 0.53;
         }
     }
     d = (z.imag() - z.real()) * (z.imag() + z.real());
     f = 4 * z.real() * z.real() * z.imag() * z.imag();
     g = h = 0.0;
     for(i = 0; i < 12; i++) {
         t = d + n[i];
         u = e[i] / (t * t + f);
         g += (s + n[i]) * u;
         h += (s - n[i]) * u;
     }
     u = 1 / s;
     c = r * fpcomplex(z.imag() * (u + 2.0 * g), z.real() * (u + 2.0 * h));
     if(z.imag() < M_2PI) {
         s = 2.0 / r;
         t = s * z.real();
         u = s * z.imag();
         s = sin(t);
         h = cos(t);
         f = exp(-u) - h;
         g = 2.0 * exp(d - u) / (s * s + f * f);
         u = 2.0 * z.real() * z.imag();
         h = cos(u);
         t = sin(u);
         c += g * fpcomplex((h * f - t * s), -(h * s + t * f));
     }
     return c;
 }
fillDataSetMC1D()
void GooFit::fillDataSetMC1D (GooPdf & pdf, Observable var, size_t nTotal, unsigned int seed = 0) inline
Definition at line 13 of file MonteCarlo.h.
References data, GooFit::UnbinnedDataSet::fillWithGrid(), GooFit::Observable::getBinSize(), GooFit::GooPdf::getCompProbsAtDataPoints(), GooFit::PdfBase::getData(), GooFit::UnbinnedDataSet::getValue(), GooFit::PdfBase::setData(), and GooFit::Indexable::setValue().
{
     // Setup bins
     UnbinnedDataSet data{var};
     data.fillWithGrid();
     auto origdata = pdf.getData();
     if(origdata == nullptr)
         throw GeneralError("Can't run on a PDF with no DataSet to fill!");
     pdf.setData(&data);
     std::vector<double> pdfValues = pdf.getCompProbsAtDataPoints()[0];
     // Setup random numbers
     if(seed == 0) {
         std::random_device rd;
         seed = rd();
     }
     std::mt19937 gen(seed);
     // Poisson distribution
     std::poisson_distribution<> d(nTotal);
     size_t num_events = d(gen);
     // Uniform distribution
     std::uniform_real_distribution<> unihalf(-.5, .5);
     std::uniform_real_distribution<> uniwhole(0.0, 1.0);
     // CumSum in other languages
     std::vector<double> integral(pdfValues.size());
     std::partial_sum(pdfValues.begin(), pdfValues.end(), integral.begin());
     // Make this a 0-1 fraction by dividing by the end value
     std::for_each(integral.begin(), integral.end(), [&integral](double &val) { val /= integral.back(); });
     for(size_t i = 0; i < num_events; i++) {
         double r = uniwhole(gen);
         // Binary search for integral[cell-1] < r < integral[cell]
         size_t j = std::lower_bound(integral.begin(), integral.end(), r) - integral.begin();
         // Fill in the grid randomly
         double varValue = data.getValue(var, j) + var.getBinSize() * unihalf(gen);
         var.setValue(varValue);
         origdata->addEvent();
     }
     pdf.setData(origdata);
 }
flatten()
template<typename T > std::vector<T> GooFit::flatten (const std::vector< thrust::complex< T >> & input)
Flatten a complex array into a standard one (1r, 1i, 2r, 2i, ...)
Definition at line 11 of file ComplexUtils.h.
{
     std::vector<T> output;
     for(auto val : input) {
         output.push_back(val.real());
         output.push_back(val.imag());
     }
     return output;
 }
format_arg()
void GooFit::format_arg (fmt::BasicFormatter< char > & f, const char *& format_str, const Uncertain & s) inline
fmt support
Definition at line 101 of file Uncertain.h.
References GooFit::Uncertain::get_uncertainty(), and GooFit::Uncertain::get_value().
{
     std::string value{format_str};
     auto end        = value.find('}');
     std::string val = std::string{"{" + value.substr(0, end) + "}"};
     f.writer().write(val.c_str(), s.get_value());
     f.writer().write("  ");
     f.writer().write(val.c_str(), s.get_uncertainty());
     format_str += end + 1; // Remove :xxx}
 }
get4Vecs()
__device__ void GooFit::get4Vecs (fptype * Vecs, const unsigned int & constants, const fptype & m12, const fptype & m34, const fptype & cos12, const fptype & cos34, const fptype & phi)
Referenced by enum_to_underlying().
getmass()
__device__ fptype GooFit::getmass (const unsigned int & pair, fptype & d1, fptype & d2, const fptype * vecs, const fptype & m1, const fptype & m2, const fptype & m3, const fptype & m4)
Referenced by enum_to_underlying().
getMetricPointer()
void* GooFit::getMetricPointer (std::string name)
Referenced by evalfunc_to_string().
getResonanceAmplitude()
__device__ fpcomplex GooFit::getResonanceAmplitude (fptype m12, fptype m13, fptype m23, unsigned int functionIdx, unsigned int pIndex)
Referenced by enum_to_underlying().
gooFree()
gooError GooFit::gooFree (void * ptr)
gooMalloc()
gooError GooFit::gooMalloc (void ** target, size_t bytes)
inDalitz()
__host__ __device__ bool GooFit::inDalitz (const fptype & m12, const fptype & m13, const fptype & bigM, const fptype & dm1, const fptype & dm2, const fptype & dm3)
Referenced by GooFit::DalitzPlotter::DalitzPlotter(), and enum_to_underlying().
LeviCivita() [1/2]
__device__ fptype GooFit::LeviCivita (const gpuLVec & p1, const gpuLVec & p2, const gpuLVec & p3, const gpuLVec & p4)
Definition at line 406 of file SpinHelper.h.
{
     // this calculates the determinant of the 4x4 matrix build out of p1,p2,p3,p4
     return p1.GetZ() * p2.GetY() * p3.GetX() * p4.GetE() - p1.GetY() * p2.GetZ() * p3.GetX() * p4.GetE()
            - p1.GetZ() * p2.GetX() * p3.GetY() * p4.GetE() + p1.GetX() * p2.GetZ() * p3.GetY() * p4.GetE()
            + p1.GetY() * p2.GetX() * p3.GetZ() * p4.GetE() - p1.GetX() * p2.GetY() * p3.GetZ() * p4.GetE()
            - p1.GetZ() * p2.GetY() * p3.GetE() * p4.GetX() + p1.GetY() * p2.GetZ() * p3.GetE() * p4.GetX()
            + p1.GetZ() * p2.GetE() * p3.GetY() * p4.GetX() - p1.GetE() * p2.GetZ() * p3.GetY() * p4.GetX()
            - p1.GetY() * p2.GetE() * p3.GetZ() * p4.GetX() + p1.GetE() * p2.GetY() * p3.GetZ() * p4.GetX()
            + p1.GetZ() * p2.GetX() * p3.GetE() * p4.GetY() - p1.GetX() * p2.GetZ() * p3.GetE() * p4.GetY()
            - p1.GetZ() * p2.GetE() * p3.GetX() * p4.GetY() + p1.GetE() * p2.GetZ() * p3.GetX() * p4.GetY()
            + p1.GetX() * p2.GetE() * p3.GetZ() * p4.GetY() - p1.GetE() * p2.GetX() * p3.GetZ() * p4.GetY()
            - p1.GetY() * p2.GetX() * p3.GetE() * p4.GetZ() + p1.GetX() * p2.GetY() * p3.GetE() * p4.GetZ()
            + p1.GetY() * p2.GetE() * p3.GetX() * p4.GetZ() - p1.GetE() * p2.GetY() * p3.GetX() * p4.GetZ()
            - p1.GetX() * p2.GetE() * p3.GetY() * p4.GetZ() + p1.GetE() * p2.GetX() * p3.GetY() * p4.GetZ();
 }
LeviCivita() [2/2]
__device__ gpuLVec GooFit::LeviCivita (const gpuLVec & a, const gpuLVec & b, const gpuLVec & c) inline
Definition at line 422 of file SpinHelper.h.
{
     gpuLVec v;
     v.SetE(-1. * a.GetX() * (b.GetY() * c.GetZ() - b.GetZ() * c.GetY())
            - a.GetY() * (b.GetZ() * c.GetX() - b.GetX() * c.GetZ())
            - a.GetZ() * (b.GetX() * c.GetY() - b.GetY() * c.GetX()));
     v.SetZ(a.GetX() * (b.GetE() * c.GetY() - b.GetY() * c.GetE())
            + a.GetY() * (b.GetX() * c.GetE() - b.GetE() * c.GetX())
            + a.GetE() * (b.GetY() * c.GetX() - b.GetX() * c.GetY()));
     v.SetY(a.GetX() * (b.GetZ() * c.GetE() - b.GetE() * c.GetZ())
            + a.GetZ() * (b.GetE() * c.GetX() - b.GetX() * c.GetE())
            + a.GetE() * (b.GetX() * c.GetZ() - b.GetZ() * c.GetX()));
     v.SetX(a.GetY() * (b.GetE() * c.GetZ() - b.GetZ() * c.GetE())
            + a.GetZ() * (b.GetY() * c.GetE() - b.GetE() * c.GetY())
            + a.GetE() * (b.GetZ() * c.GetY() - b.GetY() * c.GetZ()));
     return v;
 }
make_a_grid()
void GooFit::make_a_grid (std::vector< Observable > ret, UnbinnedDataSet * grid, Observable * eventNum)
Definition at line 67 of file UnbinnedDataSet.cpp.
References GooFit::UnbinnedDataSet::addEvent(), GooFit::Indexable::getLowerLimit(), GooFit::Observable::getNumBins(), GooFit::Indexable::getUpperLimit(), GooFit::Indexable::getValue(), GooFit::Observable::isEventNumber(), and GooFit::Indexable::setValue().
Referenced by GooFit::UnbinnedDataSet::fillWithGrid().
{
     if(ret.empty()) {
         grid->addEvent();
         if(eventNum != nullptr)
             eventNum->setValue(eventNum->getValue() + 1);
         return;
     }
     Observable var = ret.back();
     ret.pop_back(); // safe because this is a copy
     if(var.isEventNumber()) { // Skip
         make_a_grid(ret, grid, eventNum);
     } else {
         for(int i = 0; i < var.getNumBins(); ++i) {
             double step = (var.getUpperLimit() - var.getLowerLimit()) / var.getNumBins();
             var.setValue(var.getLowerLimit() + (i + 0.5) * step);
             make_a_grid(ret, grid, eventNum);
         }
     }
 }
max_fitter_index()
int GooFit::max_fitter_index (const std::vector< Variable > & vars)
Get the max fitter index of a variable from a list.
Definition at line 28 of file Variable.cpp.
References GooFit::Variable::getFitterIndex().
Referenced by GooFit::Params::make_minuit_vector(), and GooFit::EventNumber::operator=().
{
     const Variable max_ind_ptr
         = *std::max_element(std::begin(vars), std::end(vars), [](const Variable &a, const Variable &b) {
               return a.getFitterIndex() < b.getFitterIndex();
           });
     return max_ind_ptr.getFitterIndex();
 }
max_index() [1/2]
int GooFit::max_index (const std::vector< Variable > & vars)
Get the max index of a variable from a list.
Definition at line 8 of file Variable.cpp.
References GooFit::Indexable::getIndex().
Referenced by GooFit::Minuit1::Eval(), GooFit::Params::from_minuit_vector(), and GooFit::EventNumber::operator=().
{
     if(vars.empty())
         return -1;
     const Variable &max_ind_ptr
         = *std::max_element(std::begin(vars), std::end(vars), [](const Variable &a, const Variable &b) {
               return a.getIndex() < b.getIndex();
           });
     return max_ind_ptr.getIndex();
 }
max_index() [2/2]
int GooFit::max_index (const std::vector< Observable > & vars)
Definition at line 18 of file Variable.cpp.
References GooFit::Indexable::getIndex().
{
     if(vars.empty())
         return -1;
     const Observable &max_ind_ptr
         = *std::max_element(std::begin(vars), std::end(vars), [](const Observable &a, const Observable &b) {
               return a.getIndex() < b.getIndex();
           });
     return max_ind_ptr.getIndex();
 }
operator*() [1/4]
__device__ gpuLVec GooFit::operator* (gpuLVec lhs, fptype rhs)
Definition at line 74 of file SpinHelper.h.
 { return lhs *= rhs; }
operator*() [2/4]
__device__ gpuLVec GooFit::operator* (fptype lhs, gpuLVec rhs)
Definition at line 75 of file SpinHelper.h.
 { return rhs *= lhs; }
operator*() [3/4]
Uncertain GooFit::operator* (fptype other, const Uncertain & self) inline
Allow int and float multiplies.
Definition at line 91 of file Uncertain.h.
References GooFit::Uncertain::get_uncertainty(), GooFit::Uncertain::get_value(), and GooFit::Uncertain::Uncertain().
{
     return Uncertain(self.get_value() * other, self.get_uncertainty() * other);
 }
operator*() [4/4]
__device__ SymmLorentzMatrix GooFit::operator* (fptype lhs, const SymmLorentzMatrix & rhs)
Definition at line 372 of file SpinHelper.h.
{
     SymmLorentzMatrix returnVal(rhs);
     returnVal *= lhs;
     return returnVal;
 }
operator+()
__device__ gpuLVec GooFit::operator+ (gpuLVec lhs, const gpuLVec & rhs)
Definition at line 72 of file SpinHelper.h.
 { return lhs += rhs; }
operator-()
__device__ gpuLVec GooFit::operator- (gpuLVec lhs, const gpuLVec & rhs)
Definition at line 73 of file SpinHelper.h.
 { return lhs -= rhs; }
operator/()
__device__ SymmLorentzMatrix GooFit::operator/ (fptype lhs, const SymmLorentzMatrix & rhs)
Definition at line 377 of file SpinHelper.h.
{
     SymmLorentzMatrix returnVal(rhs);
     returnVal /= lhs;
     return returnVal;
 }
operator<<() [1/3]
std::ostream& GooFit::operator<< (std::ostream & stream, Uncertain value) inline
Simple << output.
Definition at line 96 of file Uncertain.h.
References GooFit::Uncertain::get_uncertainty(), and GooFit::Uncertain::get_value().
Referenced by GooFit::EventNumber::operator=().
{
     return stream << value.get_value() << "  " << value.get_uncertainty();
 }
operator<<() [2/3]
std::ostream & GooFit::operator<< (std::ostream & o, const GooFit::Variable & var)
Nice print of Variable.
Definition at line 36 of file Variable.cpp.
References GooFit::Variable::blind, GooFit::Variable::getError(), GooFit::Variable::getFitterIndex(), GooFit::Indexable::getIndex(), GooFit::Indexable::getLowerLimit(), GooFit::Indexable::getName(), GooFit::Indexable::getUpperLimit(), GooFit::Indexable::getValue(), and GooFit::Variable::IsFixed().
{
     o << var.getName() << ": " << var.getValue() << " +/- " << var.getError();
     if(!var.IsFixed())
         o << " [" << var.getLowerLimit() << ", " << var.getUpperLimit() << "]";
     if(var.getIndex() >= 0)
         o << " GooFit index: " << var.getIndex();
     if(var.getFitterIndex() >= 0)
         o << " Fitter index: " << var.getFitterIndex();
     if(*var.blind != 0)
         o << " Blinded";
     return o;
 }
operator<<() [3/3]
std::ostream & GooFit::operator<< (std::ostream & o, const GooFit::Observable & var)
Nice print of Observable.
Definition at line 50 of file Variable.cpp.
References GooFit::Indexable::getIndex(), GooFit::Indexable::getLowerLimit(), GooFit::Indexable::getName(), GooFit::Observable::getNumBins(), GooFit::Indexable::getUpperLimit(), and GooFit::Indexable::getValue().
{
     o << var.getName() << ": " << var.getValue() << " (" << var.getNumBins() << " bins)";
     o << " [" << var.getLowerLimit() << ", " << var.getUpperLimit() << "]";
     if(var.getIndex() >= 0)
         o << " GooFit index: " << var.getIndex();
     return o;
 }
operator>>()
std::istream & GooFit::operator>> (std::istream & i, GooFit::Observable & var)
Allow Observable to be read in.
Definition at line 59 of file Variable.cpp.
References GooFit::Indexable::value.
Referenced by GooFit::EventNumber::operator=().
 { return i >> *var.value; }
print_goofit_info()
void GooFit::print_goofit_info (int gpuDev_ = 0)
Print out information about GooFit.
print_splash()
void GooFit::print_splash ()
Optional print for splash Orignal: Slant Relief from http://patorjk.com/software/taag/#p=testall&f=Wavy&t=GooFit (tightened a bit) New: Block letters
read_csv()
template<typename M > M GooFit::read_csv (std::string name, bool comma = true)
Definition at line 10 of file Eigen.h.
{
     using namespace Eigen;
     std::ifstream input(name);
     std::string line;
     std::vector<typename M::Scalar> values;
     size_t rows = 0;
     while(std::getline(input, line)) {
         std::stringstream lineStream(line);
         std::string cell;
         typename M::Scalar value;
         if(comma)
             while(std::getline<char>(lineStream, cell, ','))
                 values.push_back(std::stod(cell));
         else
             while(lineStream >> value)
                 values.push_back(value);
         ++rows;
     }
     return Map<const Matrix<typename M::Scalar, M::RowsAtCompileTime, M::ColsAtCompileTime, ColMajor>>(
         values.data(), values.size() / rows, rows);
 };
readFromFile()
void GooFit::readFromFile (PdfBase * pdf, const char * fname)
Definition at line 23 of file FunctorWriter.cpp.
References GooFit::PdfBase::getParameters(), GooFit::Variable::setError(), GooFit::Indexable::setLowerLimit(), GooFit::Indexable::setUpperLimit(), and GooFit::Indexable::setValue().
Referenced by makeOverallSignal(), and runCanonicalFit().
{
     std::vector<Variable> params = pdf->getParameters();
     std::map<std::string, Variable *> tempMap;
     for(Variable &p : params) {
         tempMap[p.getName()] = &p;
     }
     std::ifstream reader;
     reader.open(fname);
     std::string buffer;
     char discard[1000];
     int numSet = 0;
     while(true) {
         reader >> buffer;
         if(reader.eof())
             break;
         Variable *var = tempMap[buffer];
         fptype value, error, lowerlimit, upperlimit;
         size_t numbins;
         if(var) {
             reader >> value >> error >> numbins >> lowerlimit >> upperlimit;
             var->setValue(value);
             var->setError(error);
             var->setLowerLimit(lowerlimit);
             var->setUpperLimit(upperlimit);
             if(++numSet == tempMap.size())
                 break;
         } else {
             reader.getline(discard, 1000);
         }
     }
     reader.close();
 }
readListOfNumbers()
void GooFit::readListOfNumbers (thrust::host_vector< fptype > & target, const char * fname)
Definition at line 67 of file FunctorWriter.cpp.
{
     std::ifstream reader;
     reader.open(fname);
     fptype buffer = 0;
     while(true) {
         reader >> buffer;
         if(reader.eof())
             break;
         target.push_back(buffer);
     }
     reader.close();
 }
signal_handler()
void GooFit::signal_handler (int s)
will call the correct exit func, no unwinding of the stack though
spinFactor()
__device__ fptype GooFit::spinFactor (unsigned int spin, fptype motherMass, fptype daug1Mass, fptype daug2Mass, fptype daug3Mass, fptype m12, fptype m13, fptype m23, unsigned int cyclic_index)
to_5param()
Eigen::Matrix<fptype, 5, Eigen::Dynamic> GooFit::to_5param (const Eigen::Matrix< fptype, 16, Eigen::Dynamic > & mat)
This is a helper to convert values. It copies back and forth, so is only to be used in scripts.
Definition at line 11 of file UserUtils.h.
{
     mcbooster::Particles_h h_p0(mat.cols());
     mcbooster::Particles_h h_p1(mat.cols());
     mcbooster::Particles_h h_p2(mat.cols());
     mcbooster::Particles_h h_p3(mat.cols());
     for(int i = 0; i < mat.cols(); i++) {
         h_p0[i].set(mat(3, i), mat(0, i), mat(1, i), mat(2, i));
         h_p1[i].set(mat(7, i), mat(4, i), mat(5, i), mat(6, i));
         h_p2[i].set(mat(11, i), mat(8, i), mat(9, i), mat(10, i));
         h_p3[i].set(mat(15, i), mat(12, i), mat(13, i), mat(14, i));
     }
     mcbooster::Particles_d d_p0(h_p0.begin(), h_p0.end());
     mcbooster::Particles_d d_p1(h_p1.begin(), h_p1.end());
     mcbooster::Particles_d d_p2(h_p2.begin(), h_p2.end());
     mcbooster::Particles_d d_p3(h_p3.begin(), h_p3.end());
     mcbooster::RealVector_d d_m12(mat.cols());
     mcbooster::RealVector_d d_m34(mat.cols());
     mcbooster::RealVector_d d_cos12(mat.cols());
     mcbooster::RealVector_d d_cos34(mat.cols());
     mcbooster::RealVector_d d_phi(mat.cols());
     mcbooster::ParticlesSet_d particles = {&d_p0, &d_p1, &d_p2, &d_p3};
     mcbooster::VariableSet_d variables  = {&d_m12, &d_m34, &d_cos12, &d_cos34, &d_phi};
     Dim5 eval = Dim5();
     mcbooster::EvaluateArray<Dim5>(eval, particles, variables);
     mcbooster::RealVector_h h_m12(d_m12.begin(), d_m12.end());
     mcbooster::RealVector_h h_m34(d_m34.begin(), d_m34.end());
     mcbooster::RealVector_h h_cos12(d_cos12.begin(), d_cos12.end());
     mcbooster::RealVector_h h_cos34(d_cos34.begin(), d_cos34.end());
     mcbooster::RealVector_h h_phi(d_phi.begin(), d_phi.end());
     Eigen::Matrix<fptype, 5, Eigen::Dynamic> output(5, mat.cols());
     for(int i = 0; i < mat.cols(); i++) {
         output(0, i) = h_m12[i];
         output(1, i) = h_m34[i];
         output(2, i) = h_cos12[i];
         output(3, i) = h_cos34[i];
         output(4, i) = h_phi[i];
     }
     return output;
 }
twoBodyCMmom()
__device__ fptype GooFit::twoBodyCMmom (double rMassSq, fptype d1m, fptype d2m)
writeListOfNumbers()
void GooFit::writeListOfNumbers (thrust::host_vector< fptype > & target, const char * fname)
Definition at line 84 of file FunctorWriter.cpp.
Referenced by writeBackgroundHistograms().
{
     std::ofstream writer;
     writer.open(fname);
     for(fptype t : target) {
         writer << t << " ";
     }
     writer.close();
 }
writeToFile()
void GooFit::writeToFile (PdfBase * pdf, const char * fname)
Definition at line 9 of file FunctorWriter.cpp.
References GooFit::PdfBase::getParameters().
Referenced by runBackgroundDalitzFit(), and runSigmaFit().
{
     std::vector<Variable> params = pdf->getParameters();
     std::ofstream writer;
     writer.open(fname);
     for(const Variable &p : params) {
         writer << p.getName() << " " << p.getValue() << " " << p.getError() << " " << p.getLowerLimit() << " "
                << p.getUpperLimit() << std::endl;
     }
     writer.close();
 }
Variable Documentation
black
constexpr rang::fg const GooFit::black = rang::fg::black
Definition at line 8 of file Color.h.
blue
constexpr rang::fg const GooFit::blue = rang::fg::blue
Definition at line 12 of file Color.h.
bold
constexpr rang::style const GooFit::bold = rang::style::bold
Definition at line 17 of file Color.h.
Referenced by abort(), GooFit::FitManagerMinuit2::fit(), and GooFit::FitManagerMinuit1::fit().
cyan
constexpr rang::fg const GooFit::cyan = rang::fg::cyan
Definition at line 14 of file Color.h.
dev_event_array
fptype * GooFit::dev_event_array
Definition at line 28 of file PdfBase.cpp.
dim
constexpr rang::style const GooFit::dim = rang::style::dim
Definition at line 18 of file Color.h.
Referenced by GooFit::Dim5::Dim5().
evalfunc_vals
constexpr const char* GooFit::evalfunc_vals[] = {"ptr_to_Eval", "ptr_to_NLL", "ptr_to_Prob", "ptr_to_BinAvg", "ptr_to_BinWithError", "ptr_to_Chisq"}
Definition at line 18 of file GooPdf.h.
Referenced by evalfunc_to_string().
gray
constexpr rang::fg const GooFit::gray = rang::fg::gray
Definition at line 15 of file Color.h.
Referenced by GooFit::FitManagerMinuit2::fit(), and GooFit::FitManagerMinuit1::fit().
green
constexpr rang::fg const GooFit::green = rang::fg::green
Definition at line 10 of file Color.h.
Referenced by GooFit::FitManagerMinuit2::fit().
host_callnumber
int GooFit::host_callnumber = 0
Definition at line 33 of file PdfBase.cpp.
Referenced by GooFit::Minuit1::Eval(), GooFit::FCN::FCN(), GooFit::FitManagerMinuit2::fit(), GooFit::FitManagerMinuit1::fit(), and GooFit::FCN::operator()().
host_fcn_ptr
void* GooFit::host_fcn_ptr
host_indices
unsigned int GooFit::host_indices
Definition at line 31 of file PdfBase.cpp.
Referenced by GooFit::ExpPdf::hasAnalyticIntegral(), GooFit::Lineshape::setConstantIndex(), GooFit::SpinFactor::setConstantIndex(), and GooFit::ResonancePdf::setConstantIndex().
host_normalisation
fptype GooFit::host_normalisation
Definition at line 29 of file PdfBase.cpp.
host_params
fptype GooFit::host_params
Definition at line 30 of file PdfBase.cpp.
Referenced by abort().
italic
constexpr rang::style const GooFit::italic = rang::style::italic
Definition at line 19 of file Color.h.
magenta
constexpr rang::fg const GooFit::magenta = rang::fg::magenta
Definition at line 13 of file Color.h.
Referenced by GooFit::FitManagerMinuit2::fit(), and main().
maxParams
const int GooFit::maxParams = GOOFIT_MAXPAR
Definition at line 38 of file PdfBase.h.
Referenced by evalfunc_to_string(), and GooFit::PdfBase::registerConstants().
red
constexpr rang::fg const GooFit::red = rang::fg::red
Definition at line 9 of file Color.h.
Referenced by abort(), and GooFit::FitManagerMinuit2::fit().
reset
constexpr rang::style const GooFit::reset = rang::style::reset
Definition at line 16 of file Color.h.
Referenced by abort(), GooFit::FitManagerMinuit2::fit(), GooFit::FitManagerMinuit1::fit(), and main().
resonanceSize
const int GooFit::resonanceSize = 4
Definition at line 71 of file DalitzPlotHelpers.h.
totalConstants
int GooFit::totalConstants = 1
Definition at line 35 of file PdfBase.cpp.
Referenced by GooFit::PdfBase::registerConstants().
totalParams
int GooFit::totalParams = 0
Definition at line 34 of file PdfBase.cpp.
Referenced by abort().
yellow
constexpr rang::fg const GooFit::yellow = rang::fg::yellow
Definition at line 11 of file Color.h.