GooFit: rang::rang_implementation Namespace Reference
rang::rang_implementation Namespace Reference
Typedefs
template<typename T >
using enableStd = typename std::enable_if< std::is_same< T, rang::style >::value||std::is_same< T, rang::fg >::value||std::is_same< T, rang::bg >::value||std::is_same< T, rang::fgB >::value||std::is_same< T, rang::bgB >::value, std::ostream & >::type
template<typename T >
using enableControl = typename std::enable_if< std::is_same< T, rang::control >::value, std::ostream & >::type
Functions
std::streambuf const *& RANG_coutbuf ()
std::streambuf const *& RANG_cerrbuf ()
std::streambuf const *& RANG_clogbuf ()
int getIword ()
bool supportsColor ()
bool isTerminal (const std::streambuf *osbuf)
template<typename T >
enableStd< T > setColor (std::ostream &os, T const value)
Typedef Documentation
enableControl
template<typename T > using rang::rang_implementation::enableControl = typedef typename std::enable_if<std::is_same<T, rang::control>::value, std::ostream &>::type
Definition at line 256 of file rang.hpp.
enableStd
template<typename T > using rang::rang_implementation::enableStd = typedef typename std::enable_if<std::is_same<T, rang::style>::value || std::is_same<T, rang::fg>::value || std::is_same<T, rang::bg>::value || std::is_same<T, rang::fgB>::value || std::is_same<T, rang::bgB>::value, std::ostream &>::type
Definition at line 174 of file rang.hpp.
Function Documentation
getIword()
int rang::rang_implementation::getIword () inline
Definition at line 114 of file rang.hpp.
Referenced by rang::operator<<().
     {
         static int i = std::ios_base::xalloc();
         return i;
     }
isTerminal()
bool rang::rang_implementation::isTerminal (const std::streambuf * osbuf) inline
Definition at line 146 of file rang.hpp.
References RANG_cerrbuf(), RANG_clogbuf(), and RANG_coutbuf().
Referenced by rang::operator<<().
     {
         if (osbuf == RANG_coutbuf()) {
 #if defined(OS_LINUX) || defined(OS_MAC)
             return isatty(fileno(stdout)) ? true : false;
 #elif defined(OS_WIN)
             return _isatty(_fileno(stdout)) ? true : false;
 #endif
         }
         if (osbuf == RANG_cerrbuf() || osbuf == RANG_clogbuf()) {
 #if defined(OS_LINUX) || defined(OS_MAC)
             return isatty(fileno(stderr)) ? true : false;
 #elif defined(OS_WIN)
             return _isatty(_fileno(stderr)) ? true : false;
 #endif
         }
         return false;
     }
RANG_cerrbuf()
std::streambuf const*& rang::rang_implementation::RANG_cerrbuf () inline
Definition at line 102 of file rang.hpp.
Referenced by rang::init(), and isTerminal().
     {
         static std::streambuf const *pErrbuff = std::cerr.rdbuf();
         return pErrbuff;
     }
RANG_clogbuf()
std::streambuf const*& rang::rang_implementation::RANG_clogbuf () inline
Definition at line 108 of file rang.hpp.
Referenced by rang::init(), and isTerminal().
     {
         static std::streambuf const *pLogbuff = std::clog.rdbuf();
         return pLogbuff;
     }
RANG_coutbuf()
std::streambuf const*& rang::rang_implementation::RANG_coutbuf () inline
Definition at line 96 of file rang.hpp.
Referenced by rang::init(), and isTerminal().
     {
         static std::streambuf const *pOutbuff = std::cout.rdbuf();
         return pOutbuff;
     }
setColor()
template<typename T > enableStd<T> rang::rang_implementation::setColor (std::ostream & os, T const value) inline
Definition at line 247 of file rang.hpp.
Referenced by rang::operator<<().
     {
         return os << "\033[" << static_cast<int>(value) << "m";
     }
supportsColor()
bool rang::rang_implementation::supportsColor () inline
Definition at line 121 of file rang.hpp.
Referenced by rang::operator<<().
     {
 #if defined(OS_LINUX) || defined(OS_MAC)
         static constexpr const char* Terms[] = {
             "ansi", "color", "console", "cygwin", "gnome", "konsole", "kterm",
             "linux", "msys", "putty", "rxvt", "screen", "vt100", "xterm"
         };
         const char *env_p = std::getenv("TERM");
         if (env_p == nullptr) {
             return false;
         }
         static const bool result = std::any_of(
           std::begin(Terms), std::end(Terms), [&](const char* term) {
               return std::strstr(env_p, term) != nullptr;
           });
 #elif defined(OS_WIN)
         static constexpr bool result = true;
 #endif
         return result;
     }