GooFit: rang Namespace Reference
rang Namespace Reference
Namespaces
rang_implementation
Enumerations
enum style {
style::reset = 0, style::bold = 1, style::dim = 2, style::italic = 3,
style::underline = 4, style::blink = 5, style::rblink = 6, style::reversed = 7,
style::conceal = 8, style::crossed = 9
}
enum fg {
fg::black = 30, fg::red = 31, fg::green = 32, fg::yellow = 33,
fg::blue = 34, fg::magenta = 35, fg::cyan = 36, fg::gray = 37,
fg::reset = 39
}
enum bg {
bg::black = 40, bg::red = 41, bg::green = 42, bg::yellow = 43,
bg::blue = 44, bg::magenta = 45, bg::cyan = 46, bg::gray = 47,
bg::reset = 49
}
enum fgB {
fgB::black = 90, fgB::red = 91, fgB::green = 92, fgB::yellow = 93,
fgB::blue = 94, fgB::magenta = 95, fgB::cyan = 96, fgB::gray = 97
}
enum bgB {
bgB::black = 100, bgB::red = 101, bgB::green = 102, bgB::yellow = 103,
bgB::blue = 104, bgB::magenta = 105, bgB::cyan = 106, bgB::gray = 107
}
enum control { control::autoColor = 0, control::forceColor = 1 }
Functions
void init ()
template<typename T >
rang_implementation::enableStd< T > operator<< (std::ostream &os, T const value)
template<typename T >
rang_implementation::enableControl< T > operator<< (std::ostream &os, T const value)
Enumeration Type Documentation
bg
enum rang::bg strong
Enumerator
black
red
green
yellow
blue
magenta
cyan
gray
reset
Definition at line 57 of file rang.hpp.
               {
     black   = 40,
     red     = 41,
     green   = 42,
     yellow  = 43,
     blue    = 44,
     magenta = 45,
     cyan    = 46,
     gray    = 47,
     reset   = 49
 };
bgB
enum rang::bgB strong
Enumerator
black
red
green
yellow
blue
magenta
cyan
gray
Definition at line 80 of file rang.hpp.
                {
     black   = 100,
     red     = 101,
     green   = 102,
     yellow  = 103,
     blue    = 104,
     magenta = 105,
     cyan    = 106,
     gray    = 107
 };
control
enum rang::control strong
Enumerator
autoColor
forceColor
Definition at line 91 of file rang.hpp.
 { autoColor = 0, forceColor = 1 };
fg
enum rang::fg strong
Enumerator
black
red
green
yellow
blue
magenta
cyan
gray
reset
Definition at line 45 of file rang.hpp.
               {
     black   = 30,
     red     = 31,
     green   = 32,
     yellow  = 33,
     blue    = 34,
     magenta = 35,
     cyan    = 36,
     gray    = 37,
     reset   = 39
 };
fgB
enum rang::fgB strong
Enumerator
black
red
green
yellow
blue
magenta
cyan
gray
Definition at line 69 of file rang.hpp.
                {
     black   = 90,
     red     = 91,
     green   = 92,
     yellow  = 93,
     blue    = 94,
     magenta = 95,
     cyan    = 96,
     gray    = 97
 };
style
enum rang::style strong
Enumerator
reset
bold
dim
italic
underline
blink
rblink
reversed
conceal
crossed
Definition at line 32 of file rang.hpp.
                  {
     reset     = 0,
     bold      = 1,
     dim       = 2,
     italic    = 3,
     underline = 4,
     blink     = 5,
     rblink    = 6,
     reversed  = 7,
     conceal   = 8,
     crossed   = 9
 };
Function Documentation
init()
void rang::init () inline
Definition at line 259 of file rang.hpp.
References rang::rang_implementation::RANG_cerrbuf(), rang::rang_implementation::RANG_clogbuf(), and rang::rang_implementation::RANG_coutbuf().
Referenced by reduce().
 {
     rang_implementation::RANG_coutbuf();
     rang_implementation::RANG_cerrbuf();
     rang_implementation::RANG_clogbuf();
 }
operator<<() [1/2]
template<typename T > rang_implementation::enableControl<T> rang::operator<< (std::ostream & os, T const value) inline
Definition at line 279 of file rang.hpp.
References autoColor, forceColor, and rang::rang_implementation::getIword().
 {
     if (value == rang::control::forceColor) {
         os.iword(rang_implementation::getIword()) = 1;
     } else if (value == rang::control::autoColor) {
         os.iword(rang_implementation::getIword()) = 0;
     }
     return os;
 }
operator<<() [2/2]
template<typename T > rang_implementation::enableStd<T> rang::operator<< (std::ostream & os, T const value) inline
Definition at line 267 of file rang.hpp.
References rang::rang_implementation::getIword(), rang::rang_implementation::isTerminal(), rang::rang_implementation::setColor(), and rang::rang_implementation::supportsColor().
 {
     std::streambuf const *osbuf = os.rdbuf();
     return (os.iword(rang_implementation::getIword())
              || ((rang_implementation::supportsColor())
              && (rang_implementation::isTerminal(osbuf))))
       ? rang_implementation::setColor(os, value)
       : os;
 }