GooFit: examples/simpleFitExample.cu File Reference
simpleFitExample.cu File Reference
#include "Variable.hh"
#include "PdfBuilder.hh"
#include "UnbinnedDataSet.hh"
#include "LandauThrustFunctor.hh"
#include "NovosibirskThrustFunctor.hh"
#include "BifurGaussThrustFunctor.hh"
#include "TRandom.hh"
#include "TH1F.h"
#include "TH2F.h"
#include "TStyle.h"
#include "TCanvas.h"
#include <sys/time.h>
#include <sys/times.h>
#include <iostream>
Functions
double novosib (double x, double peak, double width, double tail)
void fitAndPlot (ThrustPdfFunctor *total, UnbinnedDataSet *data, TH1F &dataHist, Variable *xvar, const char *fname)
int main (int argc, char **argv)
Variables
TCanvas * foo = 0
Function Documentation
void fitAndPlot (ThrustPdfFunctor * total, UnbinnedDataSet * data, TH1F & dataHist, Variable * xvar, const char * fname)
Definition at line 47 of file simpleFitExample.cu.
References DataSet::addEvent(), PdfFunctor::fit(), foo, ThrustPdfFunctor::getCompProbsAtDataPoints(), PdfFunctor::getMinuitValues(), UnbinnedDataSet::getNumEvents(), UnbinnedDataSet::loadEvent(), Variable::lowerlimit, Variable::numbins, FunctorBase::setData(), Variable::upperlimit, and Variable::value.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 90 of file simpleFitExample.cu.
References DataSet::addEvent(), fitAndPlot(), foo, TRandom::Gaus(), TRandom::Landau(), Variable::lowerlimit, novosib(), Variable::numbins, TRandom::Uniform(), Variable::upperlimit, and Variable::value.
double novosib (double x, double peak, double width, double tail)
Definition at line 21 of file simpleFitExample.cu.
References exp().
Referenced by main().
Variable Documentation
TCanvas* foo = 0
Definition at line 45 of file simpleFitExample.cu.
Referenced by fitAndPlot(), and main().