GooFit: CLI::detail::ini_ret_t Struct Reference
CLI::detail::ini_ret_t Struct Reference
#include <CLI11.hpp>
Public Member Functions
std::string parent () const
std::string name () const
Return name.
Public Attributes
std::string fullname
This is the full name with dots.
std::vector< std::string > inputs
Listing of inputs.
size_t level = 0
Current parent level.
Detailed Description
Definition at line 540 of file CLI11.hpp.
Member Function Documentation
name()
std::string CLI::detail::ini_ret_t::name () const inline
Return name.
Definition at line 563 of file CLI11.hpp.
References CLI::detail::split().
Referenced by CLI::App::_parse_ini().
parent()
std::string CLI::detail::ini_ret_t::parent () const inline
Return parent or empty string, based on level
Level 0, a.b.c would return a Level 1, a.b.c could return b
Definition at line 554 of file CLI11.hpp.
References CLI::detail::split().
Referenced by CLI::App::_parse_ini().
Member Data Documentation
fullname
std::string CLI::detail::ini_ret_t::fullname
This is the full name with dots.
Definition at line 542 of file CLI11.hpp.
Referenced by CLI::App::_parse_ini(), and CLI::detail::parse_ini().
inputs
std::vector<std::string> CLI::detail::ini_ret_t::inputs
Listing of inputs.
Definition at line 545 of file CLI11.hpp.
Referenced by CLI::App::_parse_ini(), and CLI::detail::parse_ini().
level
size_t CLI::detail::ini_ret_t::level = 0
Current parent level.
Definition at line 548 of file CLI11.hpp.
Referenced by CLI::App::_parse_ini().
The documentation for this struct was generated from the following file:
/home/travis/build/GooFit/GooFit/include/goofit/detail/CLI11.hpp