.PHONY: all clean

all: 2d_plot/2d_plot addition/addition chisquare/chisquare convolution/convolution dalitz/dalitz DP4/DP4 exponential/exponential pipipi0DPFit/pipipi0DPFit product/product SigGen/SigGen simpleFit/simpleFit TDDP4/TDDP4 zachFit/zachFit

2d_plot/2d_plot:
	cd 2d_plot && $(MAKE)

addition/addition:
	cd addition && $(MAKE)	

chisquare/chisquare:
	cd chisquare && $(MAKE)

convolution/convolution:
	cd convolution && $(MAKE)

dalitz/dalitz:
	cd dalitz && $(MAKE)

DP4/DP4:
	cd DP4 && $(MAKE)

exponential/exponential:
	cd exponential && $(MAKE)

pipipi0DPFit/pipipi0DPFit:
	cd pipipi0DPFit && $(MAKE)

product/product:
	cd product && $(MAKE)

SigGen/SigGen:
	cd SigGen && $(MAKE)

simpleFit/simpleFit:
	cd simpleFit && $(MAKE)

TDDP4/TDDP4:
	cd TDDP4 && $(MAKE)

zachFit/zachFit:
	cd zachFit && $(MAKE)

clean:
	cd 2d_plot && $(MAKE) clean
	cd addition && $(MAKE) clean
	cd chisquare && $(MAKE) clean
	cd convolution && $(MAKE) clean
	cd dalitz && $(MAKE) clean
	cd DP4 && $(MAKE) clean
	cd exponential && $(MAKE) clean
	cd pipipi0DPFit && $(MAKE) clean
	cd product && $(MAKE) clean
	cd SigGen && $(MAKE) clean
	cd simpleFit && $(MAKE) clean
	cd TDDP4 && $(MAKE) clean
	cd zachFit && $(MAKE) clean
