#!/bin/sh
trapCmd=""
cmd="g++"

pwd=$(/bin/pwd)
verbose=""
while [ X$1 != X"" ]; do
    case $1 in
	*.cu)
	    ccFile=$(echo $1 | sed -e 's/\.cu$/.cc/')
	    if [ ! -z $verbose ]; then
		echo ln -fs $pwd/$1 $ccFile
	    fi
	    ln -fs $pwd/$1 $ccFile
	    ccFiles="$ccFiles $ccFile"
	    cmd="$cmd \"$ccFile\""
	    ;;
	-arch=sm_20)
	    ;;				# skip
	-v|--verbose)
	    verbose=1;;
	*)
	    cmd="$cmd \"$1\"";;
    esac
    shift
done

if [ X"$ccFiles" != X"" ]; then
    trap "echo $ccFiles; rm $ccFiles" 0
fi

if [ ! -z $verbose ]; then
    eval echo $cmd
fi

eval $cmd


